### ISSUE TITLE
review DiGeorge, velocardiofacial syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1006]
MONDO_0008564 and MONDO_0018923 give velocardiofacial syndrome as an exact synonym yet 
MONDO_0008644 is defined as velocardiofacial syndrome

What is necessary for clinical practice?
Should velocardiofacial syndrome  be removed as exact synonyms of DiGeorge and 22q11.2 deletion syndrome

**Comment by nicolevasilevsky** [comment]
@pnrobinson, @ahamosh, @ana-rath-orphanet - do any of you have any feedback/could you offer your clinical expertise?

**Comment by ahamosh** [comment]
22q11 deletion is a synonym for both velocardiofacial and DiGeorge syndrome (as both are caused by the deletion).  The difference between VCF (later recognition, not severe heart disease, not neonatal immunodeficiency) and DiGeorge is severity and age of recognition.  So both are 22q11 deletion, but the 2 syndromic names are not clinically identical.

**Comment by cmungall** [comment]
Thanks! @ahamosh 

Based on this I recommend @maglott's suggestion of removing the exact synonym (or demoting to RELATED) of VCF from MONDO:0008564 and MONDO:0018923. The first came from NCIT, we may want to pass this along to them. @ana-rath-orphanet I don't know if you want to do the same thing for https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_567

**Comment by nicolevasilevsky** [comment]
I made the VCF synonyms related synonyms.

The following synonyms were related synonyms for DiGeorge syndrome, but I made them exact (because that seemed incorrect - let me know if I wrong and I can change them back to related):
DGS
Di-George syndrome
DiGeorge syndrome; DGS
