### ISSUE TITLE
[Revise subclass] pseudoxanthoma elasticum (inherited or acquired)

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#1015]
**Mondo term (ID and Label)**
pseudoxanthoma elasticum (inherited or acquired) (MONDO:0024308)

**Suggested revision and reasons**
During EFO disease clean up, it was suggested that this should be a child of genetic disorder rather than integumentary system disease (or at least child of both). See: https://ghr.nlm.nih.gov/condition/pseudoxanthoma-elasticum and https://rarediseases.info.nih.gov/diseases/9643/pseudoxanthoma-elasticum.

EFO ticket: https://github.com/EBISPOT/efo/issues/606

**Comment by nicolevasilevsky** [comment]
@zoependlington I added the superclass 'inherited genetic disease' (which is the term that replaced 'genetic disorder' but this caused unsatisfiable classes in the ontology, so I removed it.

Because the term is labeled 'inherited or acquired', I don't think it can be a child of 'inherited genetic disease'.

**Comment by cmungall** [comment]
I agree with @nicolevasilevsky.

See also #1046 and #1047
