### ISSUE TITLE
PXE and mode of inheritance

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1046]
we currently place https://omim.org/entry/177850 (AD form of PXE) as a subclass of the AR form (https://omim.org/entry/264800).

This isn't right, it seems verbose but I think the hierarchy should be

 * PXE
    * inherited PXE
        * AR
        * AD
    * acquired PXE

**Comment by nicolevasilevsky** [comment]
I agree that it does not make sense to have the AD form of the disease be a subclass of the AR form.

This is confusing, because the AR form OMIM:264800 is labeled 'inherited pseudoxanthoma elasticum' (MONDO_0009925). From my understanding, it sounds like we need a new subclass of MONDO_0009925 'inherited pseudoxanthoma elasticum' that is equivalent to OMIM:264800 that is the AR form, with the hierarchy you describe above.

There is currently not a generic PXE class in Mondo, do you want me to create one?

**Comment by cmungall** [comment]
the generic form exists, it just has an awkward name.

This is current:

 * **PXE** MONDO:0024308
    * inherited PXE (MONDO_0009925) _-this is the AR form_
        * AD (MONDO_0008333)
    * acquired PXE (MONDO_0016441)

I think it should be:

* **PXE** MONDO:0024308
    * inherited PXE (MONDO_NEW)
        * AD (MONDO_0008333)
        * AR (MONDO_0009925) **rename this to be explicitly AR**
    * acquired PXE (MONDO_0016441)

**Comment by nicolevasilevsky** [comment]
thanks for the clarification!
