### ISSUE TITLE
Two terms with same exact match

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/mondo#1145]
**Mondo term (ID Label)**
http://purl.obolibrary.org/obo/MONDO_0008891 riboflavin transporter deficiency
http://purl.obolibrary.org/obo/MONDO_0000406 Brown-Vialetto-van Laere syndrome

**Bug/Typo/Error description**
Both of the above terms have skos#exactMatch links to  http://identifiers.org/mesh/C537111

I wonder if adding a check for this kind of thing to the acceptance testing for a version would be helpful?

**Comment by cbizon** [comment]
There are 127 cases of this (attached)
[mondo_bugs.txt](https://github.com/monarch-initiative/mondo/files/4206523/mondo_bugs.txt)

**Comment by nicolevasilevsky** [comment]
Thank you @cbizon, I will take a look at this

**Comment by nicolevasilevsky** [comment]
Regarding 
http://purl.obolibrary.org/obo/MONDO_0008891 riboflavin transporter deficiency
http://purl.obolibrary.org/obo/MONDO_0000406 Brown-Vialetto-van Laere syndrome

Orphanet has Brown-Vialetto-van Laere syndrome as a synonym for Riboflavin transporter deficiency, hence they both xref the MeSH term

https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=12856&Disease_Disease_Search_diseaseGroup=97229&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Riboflavin-transporter-deficiency&title=Riboflavin%20transporter%20deficiency&search=Disease_Search_Simple

**Comment by nicolevasilevsky** [comment]
Do you think these synonyms are incorrect? I can remove the xref from 'riboflavin transporter deficiency' and report this to Orphanet.

**Comment by nicolevasilevsky** [comment]
I created a [spreadsheet])https://docs.google.com/spreadsheets/d/10vJr5zLouJr6VRG9VQMh46yWAotRHZZcUtVCprPMOKM/edit#gid=0)

**Comment by cbizon** [comment]
I'm not enough of an expert in the diseases to have a valid opinion about which of the exactmatch terms is correct, unfortunately.  But it has to be one of them, unless the mondo classes are also equivalent!

**Comment by nicolevasilevsky** [comment]
Thanks @cbizon. I'll look into it further. 

Also cc'ing @ana-rath-orphanet and @annieolry from Orphanet.

**Comment by cmungall** [comment]
@nicolevasilevsky can you add a ticket for the proposed check, thx

**Comment by nicolevasilevsky** [comment]
@cbizon 
In the example above, ' Brown-Vialetto-van Laere syndrome' has now been obsoleted.

I looked through 6 examples in the [spreadsheet](https://docs.google.com/spreadsheets/d/10vJr5zLouJr6VRG9VQMh46yWAotRHZZcUtVCprPMOKM/edit#gid=0) and noted that in all of the cases, the two Mondo terms do have xrefs to the same source ID, but the xrefs are not equivalentTo, so that does not mean that the two records should be identical.

We apply semantics to the xrefs, if there is the tag MONDO:equivalentTo, that means the Mondo class is equivalent to the source term (such as OMIM). If it doesn't have a MONDO:equivalentTo annotation, then it could be there because another terminology xref'd that source and we just included it to preserve the provenance. 

Does this help clarify?

I didn't review every term in your list but I suspect that is the case for at least the majority of terms, if not all.

**Comment by cmungall** [comment]
Good summary but I'll explain in more detail later. We want to avoid proxy
internal mergers even with weaker skos

**Comment by joeflack4** [comment]
I've been assigned similar issue #2630. I have a loose understanding of what might be happening based on what Nicole said a couple comments up. But if anyone has a recommendation as to where to look in the codebase to fix this, thta would be helpful.

**Comment by nicolevasilevsky** [comment]
@matentzn said he is pretty sure this is fixed. We should check it after the next release in November (in mid-November when OLS picks up the newest release). I'll set myself a reminder.
