### ISSUE TITLE
X-linked Ehlers-Danlos syndrome (MONDO_0010586 )

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1167]
**Mondo term (ID and Label)**
X-linked Ehlers-Danlos syndrome   (MONDO_0010586 )

**Reason for deprecation**
OMIM reports: Malfait et al. (2017) stated that the condition designated EDS5 is no longer included in the EDS spectrum.  (https://www.omim.org/entry/314400#history)
Orphanet (ORPHA:75497) cites Ehlers-Danlos syndrome type 5 as a synonym for X-linked Ehlers-Danlos syndrome

**comment**
If the term needs to be retained, please remove exactMatch http://identifiers.org/omim/305200 given that OMIM  305200 is no longer primary

**Comment by nicolevasilevsky** [comment]
Hi @maglott 
Which term do you want to obsolete?
It looks like 'Ehlers-Danlos syndrome type 5' is already a synonym for X-linked Ehlers-Danlos syndrome (MONDO_0010586).

As you said - I will update the xref to OMIM, which is currently OMIM:305200. I will update it to OMIM:314400

Thanks!

**Comment by maglott** [comment]
I likely applied the wrong label to the issue.  If policy is to report former names as synonyms, then EDS5 can likely remain with MONDO_0010586

**Comment by nicolevasilevsky** [comment]
Actually, I think we do need to obsolete X-linked Ehlers-Danlos syndrome (MONDO_0010586), if we want to follow OMIM. I'll send an email out to the list, to make sure there aren't any objections.
Thanks Donna!

**Comment by nicolevasilevsky** [comment]
cc @annieolry @ana-rath-orphanet @NCIEVS

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky We retired all the subtypes that are not included in the current classification back in 2017. We currently only list Cardiac-Valvular Ehlers-Danlos syndrome and not X-linked EDS or EDS type V. 

Thanks!

**Comment by annieolry** [comment]
Please consider to keep this entity according to expert's advice. See beelow:

X-linked Ehlers-Danlos syndrome was indeed excluded from the EDS spectrum in the 2017 consensus classification (Malfait et al, PMID: 28306229). This EDS variant was described (among other rare cases in the literature) by DiFerrante et al, 1975 (PMID: 240645) in an Italian family, and some authors later commented that this family more likely belonged to an X-linked cardiovascular disease type (cardiac valvular dysplasia) and questioned the existence of "EDS V" as a separate entity.
However, Ritelli et al., 2017 (PMID: 27739212) provided a clinical and molecular update of the same Italian family, in whom they identified a novel mutation in the FLNA gene. Authors commented that future observations could support the existence of a novel EDS subtype with X-linked recessive inheritance, features of classical EDS, and co-existence of severe cardiac valvular dysplasia. This paper was not cited in the new EDS classification since both papers were published approximately at the same time.

We contacted Pr Fransiska Malfait to share these observations, and received the following reply:

    Dear Dr. Ali,

    Thank you very much for your email.
    Indeed, the publication of Ritelli et al was only published online after we finalized the classification paper (I remember that the time  we discussed this with Marco Castori, last author of the FLNA paper).
    I would recommend to keep it in the classification for now, since, indeed, based on further descriptions, there is a possibility that in future this could be included again in the EDS classification.
    I hope this is of help, and please do not hesitate to contact me in case of further questions,

    Sincerely,

    Fransiska Malfait

Our decision was therefore to keep X-linked EDS in the Orphanet nomenclature. Pr Marina Colombi (co-author of the 2017 classification update), and Dr Marco Ritelli (author of the FLNA paper reassessing the Italian family) were informed of the decision and they concurred with Pr Malfait's recommendation.

Pr Malfait also validated the updated Orphanet classification of Ehlers-Danlos syndromes, which includes a new EDS variant described after the 2017 classification: ORPHA:536532 Classical-like Ehlers-Danlos syndrome type 2, caused by AEBP1 mutations.

I hope this helps.

**Comment by nicolevasilevsky** [comment]
@annieolry I think we should keep this term, per your suggestion.

I added an annotation to the OMIM xref to note the OMIM term is obsolete (I think this is the correct approach for Mondo.)
