### ISSUE TITLE
ORPHA vs Orphanet

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#118]
MONDO uses "Orphanet" as a prefix for orphanet items, but Orphanet uses "ORPHA". Should we also switch to "ORPHA" for consistency's sake?

**Comment by cmungall** [comment]
See https://github.com/monarch-initiative/dipper/issues/469#issuecomment-373194246

The official ORDO purls have a URI fragment `Orphanet_NNNN`, so following OBO conventions the CURIE would be `Orphanet:NNN`, but this is convention rather than rule, so we could in theory use anything

coordinate with @simonjupp

**Comment by simonjupp** [comment]
For ORDO we use Orphanet:NNN and this is the preferred prefix in OLS and OxO. We have Orpha as an alternative prefix from identifiers.org.

**Comment by nicolevasilevsky** [comment]
I think this can be closed. Please reopen if necessary
