### ISSUE TITLE
Cancer vs tumor x-ref

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#1200]
**Mondo term (ID and Label):**
MONDO:0003120 (mixed testicular germ cell cancer)

**Xref that should be fixed (ID and label):**
NCIT:C6347 (Testicular Mixed Germ Cell Tumor)

**Other comments:**
This is an exact match x-ref to a tumor term, not a cancer term so I believe that this is incorrect somewhere - the synonyms and definition also refer to tumor. Is this term supposed to be mixed testicular germ cell tumor instead of mixed testicular germ cell cancer?

Thanks!

Related to: https://github.com/EBISPOT/efo/issues/683

**Comment by nicolevasilevsky** [comment]
This one is a bit tricky, because the NCIt definition is what we'd describe as a cancer, not a tumor. I made all of the tumor synonyms related instead of exact, but I think we should keep the equiv xref to NCIT, because the def of this term describes a cancer.

@paolaroncaglia and @cmungall let me know if you disagree or you would prefer I do something else.
Thanks!

**Comment by paolaroncaglia** [comment]
Pinging @zoependlington as she opened this ticket, just so this doesn't get lost (I know Zoe's busy with another task atm).
