### ISSUE TITLE
add synonym to '2019 novel coronavirus infection'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1216]
**Mondo term (ID and Label)**
'2019 novel coronavirus infection'

**Synonym to be added**
SARS-CoV-2
dbxref:doi:10.1038/s41564-020-0695-z

**Synonym subtype: ie, broad/exact/narrow/related**
exact

- [x] fix typo in other doi

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

Would you please consider adding the following synonyms too, to MONDO_0100096 '2019 novel coronavirus infection', to aid in text searches (e.g., OpenTargets monitor these terms to investigate the available data):

SARS-coronavirus 2
2019 novel coronavirus
2019-nCoV

Also (see https://en.wikipedia.org/wiki/Betacoronavirus):
β-coronavirus
betacoronavirus
β-CoV
β-CoVs
beta-CoV
beta-CoVs

I realize that some of these refer to the viral species rathjer than the infection, so they wouldn't be exact synonyms. Many thanks in advance.

(Note for self: stemming from https://github.com/ebispot/efo/issues/736.)

**Comment by nicolevasilevsky** [comment]
yes, will do!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
We've been asked to include SnomedCT and NHS digital codes for Covid19. As we'll be importing MONDO_0100096 '2019 novel coronavirus infection', could you please add those as cross-references? Details for the Snomed codes are here: http://www.snomed.org/news-and-events/articles/march-2020-interim-snomedct-release-COVID-19
We're still on the hunt for the exact NHS digital terminology, will update soon!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Quick update: looks like the NHS digital code is not public yet; could you please prioritize addition of the SnomedCT xref above for the coming Mondo release? That'd be really helpful. Thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia - nice, feel free to use the 'high priority' tag all that you want. :)

I added this xref and synonyms. Thanks for your help with this!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks so much for your prompt help with this!
May I please bother you again with a couple more related requests.

- [ ] I'm afraid I can't see a commit linked here showing addition of SnomedCT codes to MONDO_0100096 '2019 novel coronavirus infection' (https://github.com/monarch-initiative/mondo/issues/1216#issuecomment-603138551). I'm probably missing something, but double-checking just in case, please bear with me!

- [ ] Also - the COVID-19 Phenomics UK project just released a list of codes used to record COVID-19 related events in electronic health records. Many of these may not be in scope for Mondo, but based on http://covid19-phenomics.org/#section-ehr-terms, could you please  add the following xrefs to MONDO_0100096 '2019 novel coronavirus infection':
ICD-10 codes:
U07.1 | Diagnosis of COVID-19 confirmed by laboratory testing
U07.2 | Diagnosis of COVID-19 suspected or probable
ICD-10 codes, 10th revision (ICD-11):
RA01.0 | Diagnosis of COVID-19 confirmed by laboratory testing
RA01.2 | Diagnosis of COVID-19 suspected or probable

- [ ] Finally, would you please consider if addition of the following xrefs to MONDO_0100096 '2019 novel coronavirus infection' would be feasible/acceptable for Mondo:
UK SNOMED-CT
Type | ConceptID | DescriptionID
Clinical finding | 1240581000000104 | 2019-nCoV (novel coronavirus) detected
Clinical finding | 1240751000000100 | Disease caused by 2019-nCoV (novel coronavirus)
Clinical finding | 1240551000000105 | Pneumonia caused by 2019-nCoV (novel coronavirus)
Clinical finding | 1240541000000107 | Upper respiratory tract infection caused by 2019-nCoV (novel coronavirus)

To be continued very shortly!

**Comment by nicolevasilevsky** [comment]
Done! These suggestions are great, please let me know if there are any other xrefs you come across. Thank you @paolaroncaglia

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky thank you for incorporating our requests so promptly. We don't have any others at the moment :-)

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Apologies for re-opening this ticket again... I'm not sure if this is in the most recent Mondo editors version: should there be a link between '2019 novel coronavirus infection' (or perhaps best its child 'pneumonia caused by 2019 novel coronavirus') and 'severe acute respiratory syndrome'? ("A viral respiratory infection caused by the SARS coronavirus. ...") The infection per se doesn't always come with severe acute respiratory symptoms, but 
'pneumonia caused by 2019 novel coronavirus' subclass of 'severe acute respiratory syndrome'
would seem correct. Or not?
Keeping the high priority on this please. Million thanks.
Paola

**Comment by nicolevasilevsky** [comment]
I will make 'severe acute respiratory syndrome' a child of MONDO_0005719 'coronavinae infectious disease'.

I don't think we want to add  'pneumonia caused by 2019 novel coronavirus' as a new term in Mondo after all.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
I think this ticket may be closed, correct? Thanks.

**Comment by nicolevasilevsky** [comment]
Yes!
