### ISSUE TITLE
Incorrect definition property for "extranodal nasal NK/T cell lymphoma"

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#1243]
**Mondo term (ID Label)**
extranodal nasal NK/T cell lymphoma -- http://purl.obolibrary.org/obo/MONDO_0019472

**Bug/Typo/Error description**
This term does not use the definition property IAO_0000115, but appears to be using  http://purl.obolibrary.org/obo/def  instead.

**Comment by nicolevasilevsky** [comment]
<img width="1680" alt="Screen Shot 2020-03-10 at 3 44 36 PM" src="https://user-images.githubusercontent.com/6722114/76366058-23bfe480-62e6-11ea-8a72-ea19f07c92db.png">

It looks like it is using the correct definition annotation to me.

**Comment by twhetzel** [comment]
@zoependlington can you point out where you saw the other definition property used?

**Comment by zoependlington** [comment]
The OLS entry (https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019472) has the definition (on the right) under http://purl.obolibrary.org/obo/def rather than IAO_0000115. I do see that it is annotated with IAO_0000115 in the owl version I have open in Protege. Very strange... All definitions displayed on the OLS version of Mondo seem to be this way. May be the way OLS is pulling in the obo file or something to do with owl vs obo - @henrietteharmse?

**Comment by nicolevasilevsky** [comment]
@zoependlington is this still an issue or can this be closed?

**Comment by nicolevasilevsky** [comment]
closing, please reopen if this is still an issue
