### ISSUE TITLE
pulmonary valve stenosis vs. valvular pulmonary stenosis

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1260]
valvular pulmonary stenosis does not have a definition.  Is this stenosis of the pulmonary valve?  It is defined as a subtype of Congenital pulmonary valve stenosis by Orphanet, so it seems we have some duplication of concepts and need to review relationships.

MONDO_0020395 'valvular pulmonary stenosis'
MONDO_0006936 'pulmonary valve stenosis'

orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=3189 (Congenital pulmonary valve stenosis) 

https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=14071&Disease_Disease_Search_diseaseGroup=Orphanet_99054&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Valvular-pulmonary-stenosis&title=Valvular%20pulmonary%20stenosis&search=Disease_Search_Simple

**Comment by nicolevasilevsky** [comment]
Good question @maglott 

@ana-rath-orphanet could you comment on this?

**Comment by nicolevasilevsky** [comment]
The text def of 'pulmonary valve stenosis' is:
The pathologic narrowing of the orifice of the pulmonary valve. This lesion restricts blood outflow from the right ventricle to the pulmonary artery. When the trileaflet valve is fused into an imperforate membrane, the blockage is complete.

**Comment by nicolevasilevsky** [comment]
My brief google search suggests these two terms are equivalent.

**Comment by ana-rath-orphanet** [comment]
Hello
Both concepts are not the same, but hierarchically dependent. see the classification, based on IPCCC:
 Congenital pulmonary valve stenosis ORPHA:3189 
       Subpulmonary stenosis ORPHA:3190
       Supravalvular pulmonary stenosis ORPHA:3192
       Valvular pulmonary stenosis ORPHA:99054

We need to correct the latter to "valvar" instead of "valvular" and that will make things much more clear, always according to IPCCC (ticket open in Orphanet)
Definitions can be found also in IPCCC source (FYI they revised ICD11)
http://ipccc.net/ipccc-download-form/

Thank you keeping both concepts
Ana

**Comment by ana-rath-orphanet** [comment]
the classification format in my comment disappeared : ORPHA:3189 is the parent of the other three ;)

**Comment by nicolevasilevsky** [comment]
Thanks @ana-rath-orphanet!
