### ISSUE TITLE
[Obsolete]continuous muscle fiber activity hereditary, MONDO_0022857

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1269]
**Mondo term (ID and Label)**
continuous muscle fiber activity hereditary, MONDO_0022857

**Reason for deprecation**
duplicate

**Suggested replacement or term to consider**
hereditary continuous muscle fiber activity,  MONDO_0019943

**Comment by pnrobinson** [comment]
This is coming from Orphanet, however, the name at OMIM seems to be more accurate
Orphanet:972
https://omim.org/entry/160120 (I think that the disease being refered to by the Orphanet entry is Isolated Myokymia 1, which is "included" In this OMIM entry, which also includes episodic ataxia).
The latter is this MONDO entry
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008047&viewMode=All&siblings=false
 
See also this for Myokymia https://en.wikipedia.org/wiki/Myokymia

I am not sure how best to model this in Mondo @cmungall @mellybelly @nicolevasilevsky  ??

**Comment by nicolevasilevsky** [comment]
It looks like this term: continuous muscle fiber activity hereditary, MONDO_0022857
is coming from GARD and the webpage is down, so maybe this has been obsoleted in GARD?
@GARDinfocenter

**Comment by nicolevasilevsky** [comment]
@pnrobinson are you suggesting that MONDO_0019943 'hereditary continuous muscle fiber activity' should be renamed to Myokymia 1
and we should remove the related synonyms on MONDO_0008047 'episodic ataxia type 1'?

cc @ana-rath-orphanet

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky That is correct. We had replaced continuous muscle fiber activity hereditary with “hereditary continuous muscle fiber activity” (as per Orphanet) and had also added the synonym “Episodic ataxia type 1. We'll research Peter's suggestion and get back to you.

**Comment by nicolevasilevsky** [comment]
From Gioconda:
Hi!  This one is very confusing because of the different names and terms used in all the sources.   I think that I will use the GeneReview as our main source which states that other names for episodic ataxia type 1 are:
Acetazolamide-responsive periodic ataxia
Continuous muscle fiber activity
Episodic ataxia with myokymia
Familial paroxysmal kinesigenic ataxia and continuous myokymia
Isaacs-Mertens syndrome
Hereditary paroxysmal ataxia with neuromyotonia
 
The only one that uses hereditary continuous muscle fiber activity is Orphanet, a page that was reviewed in 2013.  The condition, I believe, originated from an article published back in 1984 where some members of the same family presented with continuous muscle fiber activity https://onlinelibrary.wiley.com/doi/abs/10.1002/ana.410150104 which is known as “Isaacs syndrome” (GARD: https://rarediseases.info.nih.gov/diseases/6793/isaacs-syndrome   NINDS:  https://www.ninds.nih.gov/Disorders/All-Disorders/Isaacs-Syndrome-Information-Page   synonyms:  neuromyotonia, Isaacs-Mertens syndrome, continuous muscle fiber activity syndrome, and quantal squander syndrome, Peripheral nerve hyperexcitability). 
 
For now, this is what I propose:
 
Retire hereditary continuous muscle activity syndrome
Add the term “episodic ataxia type 1” with the synonyms from GeneReviews (which basically are the same stated in OMIM)
Keep Isaac’s syndrome for now (I think that the cases that are being included in episodic ataxia 1 are the hereditary cases but not the acquired cases)
Contact Orphanet and ask for them to review this terms
 
Please let me know if you agree with this and we can make the same changes.
