### ISSUE TITLE
review of OMIMPS PS256040 and its children

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1271]
MONDO_0009726  has children of CANDLE syndrome, JMP syndrome,Nakajo-Nishimura syndrome

The text of OMIM 256040 states 
This disorder encompasses Nakajo-Nishimura syndrome (NKJO); joint contractures, muscular atrophy, microcytic anemia, and panniculitis-induced lipodystrophy (JMP syndrome); and chronic atypical neutrophilic dermatosis with lipodystrophy and elevated temperature syndrome (CANDLE). Among Japanese patients, this disorder is best described as Nakajo-Nishimura syndrome, since both Nakajo (1939) and Nishimura et al. (1950) contributed to the original phenotypic descriptions.

Looking for experts to clarify whether Nakajo-Nishimura syndrome, JMP syndrome, and CANDLE are alternate terms for proteosome-associated autoinflammatory syndrome.

**Comment by nicolevasilevsky** [comment]
@ahamosh @ana-rath-orphanet @GARDinfocenter

**Comment by ahamosh** [comment]
Hi All,
Per OMIM these are synonymous or alternate title for the same thing.
thanks,
Ada

**Comment by GARDInfoCenter** [comment]
The proteasome-associated autoinflammatory syndrome include all of these,  Nakajo-Nishimura syndrome (NNS), JMP syndrome and CANDLE syndrome and all are caused by mutations in the PSMB8 gene (and all have lipodystrophy and skin problems).  

Please see: 
Orphanet - https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=324977 and the Article - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3690515/  

However, the disorders are listed separately.  So, these disorders are not really synonyms or alternate terms; they are subtypes.

**Comment by ahamosh** [comment]
All of these conditions in 256040 are considered by OMIM to be the same disorder (Proteasome-associated autoinflammatory disorder 1 with alternate names and caused by mutations in PSMB8.  The Phenotypic series (PS256040) includes three other disorders (Proteasome-associated autoinflammatory disorder-2, -3, and -4, caused by 3 other genes. Two have been reported only in one family each.

**Comment by ana-rath-orphanet** [comment]
Decision of the Orphanet team:
- ORPHA:324977 Proteasome disability syndrome was renamed "Proteasome-associated autoinflammatory syndrome"
- As advised by the experts, the 3 clinical subtypes were deprecated to Proteasome-associated autoinflammatory syndrome (ORPHA:324977)

Experts Dr Abhimanyu Garg (who originally reported JMP syndrome), Dr Nobuo Kanazawa (prominently involved in research related to Nakajo-Nishimura syndrome), and Dr Antonio Torrelo (who originally reported CANDLE syndrome) were contacted to enquire whether the clinical, pathophysiological and genetic characteristics described so far in the literature provide enough justification to maintain the subdivision of PRAAS (ORPHA:324977) into Nakajo-Nishimura syndrome (ORPHA:2615), CANDLE syndrome (ORPHA:325004) and JMP syndrome (ORPHA:324999) as clinical subtypes, or if all patients should be coded with one unique ORPHAcode (ORPHA:324977), as part of a unique disease spectrum.

Replies received:
- Dr Garg: "I will agree with collating these three syndromes together as I believe that they represent different severity or phase of illness related to PSMB8 dysfunction."
- Dr Kanazawa: "I have discussed with some Japanese colleagues and basically agree to your proposal that original ID of JMP/NNS/CANDLE will be replaced to a single new ID of PRAAS.
Actually, in the IJD paper by Dr, McDermott, he not only proposed the umbrella name of PRAAS but also described the difference of three diseases as attached.
But recently-identified cases with novel mutations in various proteasomal genes have already been diagnosed as PRAAS, no longer as any of JMP/NNS/CANDLE.
I now believe that we should go forward with an understanding of the nomenclature history of this unique disease spectrum."

**Comment by ana-rath-orphanet** [comment]
Orphanet has deprecated these to Proteasome-associated auto inflammatory syndrome, so merging makes sense. However, the terms are not perfect synonyms.

Thank you for asking

Ana
