### ISSUE TITLE
[Obsolete] MONDO_0006060 nasopharyngeal squamous cell carcinoma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1276]
MONDO_0015459 'nasopharyngeal carcinoma'

replace with:
MONDO_0006060	nasopharyngeal squamous cell carcinoma'

Reason:
This term no longer exists in EFO and MESH and has a duplicate def with MONDO:0006060

**Comment by cmungall** [comment]
This should *not* be a merge on the basis of the names

nasopharyngeal carcinoma is a broader concept. See

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1559589/

_Three subtypes of NPC are recognized in the World Health Organization (WHO) classification: 1) squamous cell carcinoma, typically found in the older adult population; 2) non-keratinizing carcinoma; 3) undifferentiated carcinoma. _

You have identified a problem: the definition for MONDO:0006060 is clearly broader than the name:

```
id: MONDO:0006060
name: nasopharyngeal squamous cell carcinoma
def: "A carcinoma arising from the nasopharyngeal epithelium. It includes the following types: keratinizing squamous cell carcinoma, nonkeratinizing carcinoma (differentiated and undifferentiated), basaloid squamous cell carcinoma, and papillary adenocarcinoma." [NCIT:P378]
xref: EFO:1000058 {source="MONDO:equivalentTo"}
xref: MESH:C538339 {source="MONDO:relatedTo", source="EFO:1000058"}
xref: NCIT:C3871 {source="MONDO:relatedTo", source="EFO:1000058"}
xref: SCTID:449248000 {source="EFO:1000058"}
is_a: MONDO:0010150 {source="EFO:1000058"} ! head and neck squamous cell carcinoma
```

the correct approach here is not to merge. merging should only be done if we are clear the concepts are equivalent.

One option is to fix the def to be the narrower concept, since this is what is clearly intended by the name.

However, fixing defs to change their meaning is dubious. It is often better to obsolete an unclear concept and replace with clearer ones. Here I would obsolete MONDO:0006060. But I would not to a replaced-by to the broader concept. I would do replaced-by to a new concept meant to represent SCC of the nasopharynx. I would also ensure this has a logical def.

This is assuming PMC1559589 is correct in its statement. This should be coordinated with NCIT we should have the same hierarchy here.

**Comment by nicolevasilevsky** [comment]
@cmungall I did the edits you suggested above and created a PR, but need to contact NCIT before it is ready to merge.

**Comment by nicolevasilevsky** [comment]
@fragosog
Could you (or someone from NCIT) review our course of action here? Here is a summary:

We obsoleted the term:
```
id: MONDO:0006060
name: nasopharyngeal squamous cell carcinoma
def: "A carcinoma arising from the nasopharyngeal epithelium. It includes the following types: keratinizing squamous cell carcinoma, nonkeratinizing carcinoma (differentiated and undifferentiated), basaloid squamous cell carcinoma, and papillary adenocarcinoma." [NCIT:P378]
xref: EFO:1000058 {source="MONDO:equivalentTo"}
xref: MESH:C538339 {source="MONDO:relatedTo", source="EFO:1000058"}
xref: NCIT:C3871 {source="MONDO:relatedTo", source="EFO:1000058"}
xref: SCTID:449248000 {source="EFO:1000058"}
is_a: MONDO:0010150 {source="EFO:1000058"} ! head and neck squamous cell carcinoma
```
and created the new term and replaced the term above with this new term:

```
id: MONDO:0100117
name: nasopharyngeal squamous cell carcinoma
def: "A squamous cell carcinoma that involves the nasopharynx." [MONDO:patterns/squamous_cell_carcinoma, PMID:16800883]
synonym: "nasopharyngeal squamous cell carcinoma" EXACT [MONDO:0006060]
synonym: "SCC of the nasopharynx" EXACT ABBREVIATION [MONDO:cjm]
synonym: "squamous cell carcinoma of the nasopharynx" EXACT [MONDO:cjm]
xref: NCIT:C3871 {source="MONDO:relatedTo", source="EFO:1000058"}
xref: SCTID:449248000 {source="EFO:1000058"}
is_a: MONDO:0010150 {source="EFO:1000058"} ! head and neck squamous cell carcinoma
intersection_of: MONDO:0005096 ! squamous cell carcinoma
intersection_of: disease_has_location UBERON:0001728 ! nasopharynx
created_by: http://orcid.org/0000-0001-5208-3432
```
I see that NCIT does not have such a term and we'd like to coordinate with you to ensure we have the same hierarchy.

**Comment by cmungall** [comment]
this is the SCC concept in NCIT: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C54360

**Comment by nicolevasilevsky** [comment]
Thanks Chris, I'll work on this

**Comment by nicolevasilevsky** [comment]
- [ ] do not obsolete. Create new PR with new definition
