### ISSUE TITLE
[Obsolete]MONDO_0007796/hypoparathyroidism, familial isolated

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1305]
**Mondo term (ID and Label)**
MONDO_0007796/hypoparathyroidism, familial isolated

**Reason for deprecation**
matches, with word order changed, its parent
familial isolated hypoparathyroidism/MONDO_0016390

**Suggested replacement or term to consider**
remove MONDO_0007796/hypoparathyroidism, familial isolated and make its children children of MONDO_0016390

**Comment by nicolevasilevsky** [comment]
these look equivalent to me too.

@ana-rath-orphanet @ahamosh

**Comment by ahamosh** [comment]
Agree.

**Comment by cmungall** [comment]
OK, but I think something is not quite right here in the ontology.

The intent was (rightly or wrongly) to group:

 - https://omim.org/entry/307700 HYPOPARATHYROIDISM, X-LINKED; HYPX (Orphanet:2239 - Familial isolated hypoparathyroidism due to agenesis of parathyroid gland)
 - https://omim.org/entry/146200 HYPOPARATHYROIDISM, FAMILIAL ISOLATED; FIH (GCM2 or PTH). In orphanet the GCM2 form is Orphanet:2239 and the PTH form is 

See how Orphanet does this in this figure:

![image](https://user-images.githubusercontent.com/50745/80294285-edff7f80-871c-11ea-8403-a87375329122.png)

I think we should proceed carefully here. Some obsoletions may be in order, but this is not a merge based on the current structure.

Let's start with what we think the best ontology structure is, with clear definitions for the leaf nodes

(Sorry for the delayed response... I'm trying to get the kboom graphs up and running again which makes deugging this easier, there are some other oddities in the omim-ordo mappings here)

**Comment by ahamosh** [comment]
Hi All,
Hope you are staying safe.  I am a bit confused.  It looks like OMIM still has a lumped entry for Familial Isolated Hypoparathyroidims (146200), which includes this phenotype due to PTH or GCM2.  We probably need to split this into 2 entries.  The X-linked recessive phenotype (307700), does not have a clear molecular etiology and is an older entry.  We won't get rid of it, but its etiology and existence aren't certain.
Does that help at all?
Thanks,
Ada

**Comment by nicolevasilevsky** [comment]
I'm not sure I understand what the best way forward is. @cmungall could you outline the action items needed? Thanks!

**Comment by nicolevasilevsky** [comment]
As it stands now on the pull request, the hierarchy would be:
MONDO_0016390 'familial isolated hypoparathyroidism' (OMIM:146200)
-MONDO_0010618 'familial isolated hypoparathyroidism due to agenesis of parathyroid gland' (OMIM:307700)

These two terms weren't merged.

**Comment by nicolevasilevsky** [comment]
@cmungall how do you know that  in orphanet the GCM2 form is Orphanet:2239? I don't see that noted on their [website](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=2112&Disease_Disease_Search_diseaseGroup=2239-&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Familial-isolated-hypoparathyroidism-due-to-agenesis-of-parathyroid-gland&title=Familial%20isolated%20hypoparathyroidism%20due%20to%20agenesis%20of%20parathyroid%20gland&search=Disease_Search_Simple)

**Comment by ana-rath-orphanet** [comment]
Yes, it is, in the webpage you link, if you scroll down you click on the gene link to access GCM2.

Ana

**Comment by cmungall** [comment]
@nicolevasilevsky regarding your Q "how do you know that in orphanet the GCM2 form is Orphanet:2239? I don't see that noted on their website" you can also see this in ORDO in OLS, lower right box. Although ORDO may up to be 6 months behind, the OLS display can help with these complicated issues where looking at the hierarchy and mappings simultaneously can help

**Comment by cmungall** [comment]
@ahamosh - yes, this helps.

@nicolevasilevsky - I think it may be simplest if we just wait for OMIM to create the separate entry. If the label clash is causing problems then perhaps give the child MONDO_0007796 an artificial name, e.g. list both genes..?

**Comment by cmungall** [comment]
I see OMIM has now split the FIH entry, there a PS with the generic name, and 1 and 2 subtypes: https://www.omim.org/phenotypicSeries/PS146200 thanks @ahamosh !

This should now be straightforward to resolve, one more Q for @ana-rath-orphanet -

Autosomal dominant hypocalcemia
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_428

which you have as equivalent to https://omim.org/entry/601198 HYPOCALCEMIA, AUTOSOMAL DOMINANT 1; HYPOC1 is classified as a FIH

I can see how this fits the def of FIH, but it conflicts with the OMIM PS - how do we resolve this?
