### ISSUE TITLE
Merge MYH-9 related disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1376]
id: MONDO:0007954
name: May-Hegglin anomaly
def: "An autosomal dominant disorder characterized by the triad of thrombocytopenia, giant platelets, and characteristic inclusions in peripheral blood leukocytes. It is characterized by varying degrees of thrombocytopenia that may be associated with purpura and bleeding; it is associated with mutation of the MYH9 gene." [NCIT:C131646]

_This was obsoleted in Orphanet and replaced by MYH-9 related disease_

id: MONDO:0015912
name: MYH-9 related disease
def: "MYH9-related disease (MYH9-RD) is an inherited giant platelet disorder with a complex phenotype characterized by congenital thrombocytopenia and possible subsequent manifestations of sensorineural hearing loss, presenile cataracts, elevation of liver enzymes, and/or progressive nephropathy often leading to end-stage renal disease (ESRD). Epstein syndrome, Fechtner syndrome, May-Hegglin anomaly and Sebastian syndrome, previously described as distinct disorders, represent some of the different clinical presentations of MYH9-RD." [Orphanet:182050]

**Comment by ahamosh** [comment]
In OMIM, we folded all the MYH9-related disorders into # 155100. MACROTHROMBOCYTOPENIA AND GRANULOCYTE INCLUSIONS WITH OR WITHOUT NEPHRITIS OR SENSORINEURAL HEARING LOSS; MATINS.  We don't call them MYH9-related disorders.  There is a separate isolated autosomal dominant deafness (DFNA17, MIM:603622) due to MYH9.  

This is the description in OMIM:
Macrothrombocytopenia with or without granulocyte inclusions, nephritis, or sensorineural hearing loss was previously thought to comprise 4 distinct entities with overlapping features: Fechtner syndrome, May-Hegglin anomaly, Epstein syndrome, and Sebastian syndrome. Fechtner syndrome was characterized by the triad of thrombocytopenia, giant platelets, and Dohle body-like inclusions in peripheral blood leukocytes, with the additional Alport syndrome (301050)-like features of nephritis, hearing loss, and eye abnormalities, predominantly cataracts (Peterson et al., 1985). May-Hegglin anomaly was characterized by the triad of thrombocytopenia, giant platelets, and Dohle body-like inclusions in peripheral blood leukocytes. Epstein syndrome was characterized by thrombocytopenia, deafness, and nephritis, and lacked leukocyte inclusion bodies on classic staining of peripheral blood smears. Sebastian syndrome was similar to May-Hegglin anomaly, but had a different ultrastructural appearance of the leukocyte inclusions. Seri et al. (2003) suggested that these 4 disorders were not distinct entities, but rather represented a single disorder with a continuous clinical spectrum because variable phenotypic expression is observed not only between families but also within families having the same MYH9 mutation. In addition, Balduini et al. (2011) noted that all patients present leukocyte inclusion bodies, although of variable size. Seri et al. (2003) proposed the term 'MYH9-related disease' for the disorder; however, an isolated form of nonsyndromic deafness (DFNA17; 603622) is also caused by mutation in the MYH9 gene.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh! I just reversed the order above, ie MONDO:0007954 May-Hegglin anomaly should be obsoleted and replaced by MONDO:0015912 MYH-9 related disease, and I believe this is consistent with what you noted above.

**Comment by ahamosh** [comment]
But please don’t call it MYH9-related disease. Call it the long OMIM name, please.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolevasilevsky** [comment]
Sure thing, will do!
