### ISSUE TITLE
osteoarthritis susceptibility exact matching osteoarthritis

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/mondo#1395]
Action item:
- [x] make these xrefs related to on MONDO:0008143 osteoarthritis susceptibility 1:
http://linkedlifedata.com/resource/umls/id/C0029408;  Degenerative Polyarthritis
http://identifiers.org/snomedct/396275006; osteoarthritis

- [x] add them as equivalentTo on MONDO:0005178 (osteoarthritis)

_updated 10/21/21 NV_

---

**Mondo term (ID and Label):**
MONDO:0008143 osteoarthritis susceptibility 1

**Xref that should be fixed (ID and label):**
 http://linkedlifedata.com/resource/umls/id/C0029408;  Degenerative Polyarthritis
http://identifiers.org/snomedct/396275006; osteoarthritis

**Other comments:**
These are both SKOS exactMatches.  But I think that they should instead be exactMatches with MONDO:0002758 (osteoarthritis).

**Comment by maglott** [comment]
This is an example of a larger question, namely is susceptibility to disease to be treated as equivalent to the disease itself?  Seems to be they should be distinct entities and not synonyms.  Another example is 
visceral leishmaniasis MONDO:0005445 
which is a parent of 
susceptibility to visceral leishmaniasis, 1 MONDO:0021012.  
That makes the genetic predisposition (susceptibility) represented as an infectious
 disease, which seems wrong.

**Comment by nicolevasilevsky** [comment]
Update - we have a meeting scheduled later this month to address issues with susceptibility, so I'm hoping we can get this resolved soon. Thanks for your patience. :)

**Comment by kallia-p** [comment]
A comment on susceptibility for common complex disorders using osteoarthritis as an example (which I worked with for many years as a GWAS geneticist). It's not correct currently to assign one gene for susceptibility to osteoarthritis, which is a common complex disease caused by the complex interplay between hundreds of genetic variants and environmental risk factors. I think that all three MONDO osteoarthritis susceptibility terms must have been created during the era of candidate gene studies (>15 years ago) where researchers where choosing a priori variants in one gene to study and would associate this one gene with the disease, sometimes using liberal statistical thresholds for declaring association that weren't replicated in independent studies. Over the past 15 years with GWAS studies we recognise that for each of the variants that have been associated with the disease, the risk or effect size is small to modest e.g. an individual with the GDF5 risk allele may have a 15% higher chance of developing osteoarthritis than an individual that doesn't have this risk allele. Unlike rare diseases penetrance is very low. Furthermore the associated variants are often regulatory and it requires a lot of downstream work and functional studies to pinpoint the gene that they may be effecting . So in my opinion the osteoarthritis susceptibility 1, 3 and 5 entries in MONDO should be deleted.

**Comment by kallia-p** [comment]
see also #3121. For the time being we are assigning osteoarthritis superclass to osteoarthritis susceptibility terms until a decision has been reached from the wider discussion on addressing susceptibility types for complex diseases.
