### ISSUE TITLE
question about MONDO_0022460 anophthalmia cleft lip palate hypothalamic disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#140]
@GARDInfoCenter
Is this an appropriate reference for this term:
[PMID: 8160751 ](https://www.ncbi.nlm.nih.gov/pubmed/8160751)
MONDO_0022460 anophthalmia cleft lip palate hypothalamic disorder'

**Comment by cmungall** [comment]
The MONDO ID corresponds to https://rarediseases.info.nih.gov/diseases/714/anophthalmia-cleft-lip-palate-hypothalamic-disorder

**Comment by GARDInfoCenter** [comment]
We believe that "anophthalmia cleft lip palate hypothalamic disorder" was included on the GARD list based on the reference you mentioned. However, because we have been unable to find another case or article and because we feel that this case was probably a case of "Anophthalmia plus syndrome", we have retired the term "anophthalmia cleft lip palate hypothalamic disorder" and kept the term "anophthalmia plus syndrome".

**Comment by nicolevasilevsky** [comment]
@cmungall should we obsolete MONDO_0022460 anophthalmia cleft lip palate hypothalamic disorder', since it has been retired from GARD?

I see instructions for obsoleting/merging in the MONDO editors guide using owltools, but I have never done it before. Would you like me to try or would you like to do it?

CURIE of class to be obsoleted: mondo:0022460
CURIE of replacement class: mondo:0010930
