### ISSUE TITLE
Need help with GARD definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#141]
@GARDInfoCenter - could you please help with the definitions for the following terms? I have not been able to find any information online.

- [ ] [anophthalmia microcephaly hypogonadism](https://rarediseases.info.nih.gov/diseases/718/anophthalmia-microcephaly-hypogonadism)
- [ ] [antihypertensive drugs antenatal exposure syndrome](https://rarediseases.info.nih.gov/diseases/733/antihypertensive-drugs-antenatal-exposure)
- [ ] [aortic arches defect](https://rarediseases.info.nih.gov/diseases/741/aortic-arches-defect)
- [ ] [apolipoprotein C 2i deficiency](https://rarediseases.info.nih.gov/diseases/759/apolipoprotein-c-2i-deficiency) - I can't find anything about c 2i, but can find c II
- [ ] [aplasia cutis congenita recessive](https://rarediseases.info.nih.gov/diseases/755/aplasia-cutis-congenita-recessive) - is this different from autosomal recessive? Both classes exist in GARD and in MONDO, I can't find anything about just the recessive version online though.
- [ ] [arthritis short stature deafness](https://rarediseases.info.nih.gov/diseases/775/arthritis-short-stature-deafness)

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky - Please see below. We were unable to locate information on some of the terms; therefore, we retired them from our list. 

- Anophthalmia  microcephaly hypogonadism – Retired

- Antihypertensive drugs antenatal exposure syndrome – Retired

- Aortic arches defect – Kept. This one is also listed in Orphanet and is a rare malformation.  See [http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3428&Disease_Disease_Search_diseaseGroup=aortic-arch&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group of diseases=Aortic-arch-defects&title=Aortic-arch-defects&search=Disease_Search_Simple]

- Apolipoprotein C 2i deficiency:  Was a typo, so changed name to "Apolipoprotein C-II deficiency" and  added some synonyms

-Aplasia cutis congenita recessive: Retired because covered under the existing term "Aplasia cutis congenita"

- Arthritis short stature deafness: Retired

**Comment by cmungall** [comment]
@nicolevasilevsky can you obsolete these? You can cite this ticket as a reason for obsolescence, and add a comment "This term was found in the globalgenes.org rare disease list, but no information could be found about it"

For ACCR and AAD add a replaced_by to the correct class

**Comment by nicolevasilevsky** [comment]
@cmungall I obsoleted the class 'apolipoprotein C 2i deficiency' - I just did it manually, hopefully you can review my PR and let me know if there are any issues. I'll wait for you to okay that before obsoleting the other classes.

@GARDInfoCenter and @cmungall - the Orphanet record for 'Aortic arches defect' does not have a definition either and I was not able to find anything online. I could write my own definition? It does seem like more of a phenotype though? Or a grouping class?

**Comment by GARDInfoCenter** [comment]
We found the following articles that might be helpful in creating a definition for Aortic arches defects:
https://www.orpha.net/data/patho/GB/uk-aortic-arch.pdf and the following:
https://pubs.rsna.org/doi/full/10.1148/rg.2017160033 
https://www.ncbi.nlm.nih.gov/pubmed/28683906

**Comment by nicolevasilevsky** [comment]
note to self, to do:

- [ ] obsolet Anophthalmia microcephaly hypogonadism 
- [ ] obsolete Antihypertensive drugs antenatal exposure syndrome 
- [ ]  add def to Aortic arches defect, see comments above for def
- [ ] obsolete Aplasia cutis congenita recessive, replaced by existing term "Aplasia cutis congenita"
- [ ] obsolete Arthritis short stature deafness

cite this ticket as a reason for obsolescence, and add a comment "This term was found in the globalgenes.org rare disease list, but no information could be found about it"
