### ISSUE TITLE
axiomatize chromosomal diseases with monochrom ontology 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1440]
Related to https://github.com/monarch-initiative/mondo/issues/387

http://obofoundry.org/ontology/monochrom

**Comment by nicolevasilevsky** [comment]
Per the Monarch huddle on 04/23/20- Nico will look into ‘pushing the button’ on the Monochrom ontology to make this live/usable. He will coordinate with Kent and Dipper group.

Would the next step would be to import it into Mondo? Or would we just bring in the classes we need for the axioms?

**Comment by nicolevasilevsky** [comment]
- [ ] Should we create a design pattern for these axioms too?

**Comment by cmungall** [comment]
yes, we will need various DPs

**Comment by cmungall** [comment]
First pass of classes amenable to axiomatization based on crude grep/perl based NER:

|name|
|---|
|X-linked disease|
|Sotos syndrome 1|
|Charcot-Marie-Tooth disease type 1A|
|chromosome 16p12.1 deletion syndrome, 520kb|
|alpha thalassemia-intellectual disability syndrome type 1|
|chromosome 18p deletion syndrome|
|chromosome 5q deletion syndrome|
|chromosome 9p deletion syndrome|
|recombinant 8 syndrome|
|syndactyly type 1|
|split hand-foot malformation 3|
|mosaic variegated aneuploidy syndrome 1|
|X-linked myotubular myopathy-abnormal genitalia syndrome|
|syndromic X-linked intellectual disability Lubs type|
|X-linked intellectual disability-retinitis pigmentosa syndrome|
|fragile X syndrome|
|chromosome Xp21 deletion syndrome|
|chromosome Xp11.23-p11.22 duplication syndrome|
|chromosome Xq28 duplication syndrome|
|Xq27.3q28 duplication syndrome|
|X-linked acrogigantism due to Xq26 microduplication|
|Xq25 microduplication syndrome|
|X-linked diffuse leiomyomatosis-Alport syndrome|
|X-linked centronuclear myopathy|
|premature ovarian failure 1|
|Russell-silver syndrome, X-linked|
|spermatogenic failure, Y-linked, 1|
|spermatogenic failure, Y-linked, 2|
|chromosome 8Q12.1-q21.2 deletion syndrome|
|autosomal dominant polycystic kidney disease type 1 with tuberous sclerosis|
|2q37 microdeletion syndrome|
|distal monosomy 10p|
|tetrasomy 12p|
|chromosome 18q deletion syndrome|
|distal monosomy 13q|
|homozygous 11P15-p14 deletion syndrome|
|chromosome 1p36 deletion syndrome|
|paternal uniparental disomy of chromosome 14|
|8q22.1 microdeletion syndrome|
|chromosome 22q11.2 microduplication syndrome|
|15q11q13 microduplication syndrome|
|chromosome 3q29 microdeletion syndrome|
|distal 10q deletion syndrome|
|14q22q23 microdeletion syndrome|
|7q11.23 microduplication syndrome|
|zygodactyly type 1|
|Rubinstein-Taybi syndrome due to 16p13.3 microdeletion|
|chromosome 22q11.2 deletion syndrome, distal|
|proximal 16p11.2 microdeletion syndrome|
|chromosome 3q29 microduplication syndrome|
|chromosome 15q13.3 microdeletion syndrome|
|chromosome 10q23 deletion syndrome|
|chromosome 2q32-q33 deletion syndrome|
|chromosome 2q31.2 deletion syndrome|
|chromosome 1q21.1 deletion syndrome|
|chromosome 1q21.1 duplication syndrome|
|chromosome 2p16.1-p15 deletion syndrome|
|chromosome 1q41-q42 deletion syndrome|
|chromosome 6pter-p24 deletion syndrome|
|chromosome 15q26-qter deletion syndrome|
|chromosome 6q24-q25 deletion syndrome|
|chromosome 19q13.11 deletion syndrome|
|chromosome 5p13 duplication syndrome|
|chromosome 17p13.3 duplication syndrome|
|chromosome 17q23.1-q23.2 deletion syndrome|
|chromosome 15q24 deletion syndrome|
|distal 16p11.2 microdeletion syndrome|
|chromosome 14q11-q22 deletion syndrome|
|chromosome 16p13.3 duplication syndrome|
|chromosome 4q21 deletion syndrome|
|chromosome 17q21.31 duplication syndrome|
|chromosome 6q11-q14 deletion syndrome|
|chromosome 2p12-p11.2 deletion syndrome|
|chromosome 16p12.2-p11.2 deletion syndrome|
|familial clubfoot due to 17q23.1q23.2 microduplication|
|chromosome 19p13.13 deletion syndrome|
|chromosome 17q11.2 deletion syndrome, 1.4Mb|
|chromosome 2q31.1 duplication syndrome|
|distal 7q11.23 microdeletion syndrome|
|chromosome 1p32-p31 deletion syndrome|
|chromosome 17p13.1 deletion syndrome|
|3p- syndrome|
|chromosome 13q14 deletion syndrome|
|mosaic variegated aneuploidy syndrome 2|
|chromosome 8q21.11 deletion syndrome|
|tetrasomy 18p|
|chromosome 15q25 deletion syndrome|
|chromosome 2P16.3 deletion syndrome|
|chromosome 17q12 duplication syndrome|
|chromosome 17q12 deletion syndrome|
|chromosome 16q22 deletion syndrome|
|chromosome 16p11.2 duplication syndrome|
|distal tetrasomy 15q|
|chromosome 3q13.31 deletion syndrome|
|chromosome 22q13 duplication syndrome|
|8q24.3 microdeletion syndrome|
|chromosome 15q11.2 deletion syndrome|
|chromosome 5q12 deletion syndrome|
|motor developmental delay due to 14q32.2 paternally expressed gene defect|
|14q32 duplication syndrome|
|ring chromosome 14|
|16p13.2 microdeletion syndrome|
|15q14 microdeletion syndrome|
|chromosome 11p13 deletion syndrome, distal|
|Sotos syndrome 3|
|chromosome 19q13.11 deletion syndrome, proximal|
|48,XXYY syndrome|
|mosaic trisomy 3|
|pentasomy X|
|17q11.2 microduplication syndrome|
|ring chromosome 1|
|ring chromosome 10|
|ring chromosome 12|
|ring chromosome 17|
|ring chromosome 18|
|ring chromosome 19|
|ring chromosome 20|
|ring chromosome 21|
|ring chromosome 22|
|ring chromosome 4|
|ring chromosome 6|
|ring chromosome 7|
|chromosome 8-derived supernumerary ring/marker|
|non-distal monosomy 10q|
|distal monosomy 17q|
|2q24 microdeletion syndrome|
|deletion 5q35|
|distal monosomy 7q36|
|2p21 microdeletion syndrome|
|distal monosomy 9p|
|Xp22.3 microdeletion syndrome|
|partial chromosome Y deletion|
|mosaic trisomy 1|
|non-distal trisomy 10q|
|mosaic trisomy 12|
|trisomy 12p|
|non-distal trisomy 13q|
|mosaic trisomy 14|
|distal trisomy 14q|
|mosaic trisomy 15|
|distal trisomy 15q|
|mosaic trisomy 16|
|mosaic trisomy 17|
|trisomy 18p|
|distal trisomy 18q|
|distal trisomy 19q|
|6q16 deletion syndrome|
|trisomy 10p|
|mosaic trisomy 2|
|mosaic trisomy 20|
|trisomy 4p|
|trisomy 5p|
|distal trisomy 6p|
|mosaic trisomy 7|
|trisomy 8q|
|45,X/46,XY mixed gonadal dysgenesis|
|Prader-Willi syndrome due to paternal deletion of 15q11q13 type 1|
|Prader-Willi syndrome due to paternal deletion of 15q11q13 type 2|
|5q14.3 microdeletion syndrome|
|8q12 microduplication syndrome|
|2q23.1 microdeletion syndrome|
|5q35 microduplication syndrome|
|Beckwith-Wiedemann syndrome due to 11p15 microdeletion|
|Beckwith-Wiedemann syndrome due to 11p15 translocation/inversion|
|silver-Russell syndrome due to 7p11.2p13 microduplication|
|silver-Russell syndrome due to an imprinting defect of 11p15|
|silver-Russell syndrome due to 11p15 microduplication|
|silver-Russell syndrome due to maternal uniparental disomy of chromosome 11|
|trisomy 9p|
|hypotonia-cystinuria syndrome type 1|
|1q44 microdeletion syndrome|
|paternal uniparental disomy of chromosome 1|
|maternal uniparental disomy of chromosome 1|
|2q31.1 microdeletion syndrome|
|2q33.1 microdeletion syndrome|
|ring chromosome 5|
|6p22 microdeletion syndrome|
|7q31 microdeletion syndrome|
|8p11.2 deletion syndrome|
|8p23.1 microdeletion syndrome|
|8p23.1 duplication syndrome|
|19p13.12 microdeletion syndrome|
|multiple congenital anomalies due to 14q32.2 maternally expressed gene defect|
|paternal 14q32.2 microdeletion syndrome|
|distal 7q11.23 microduplication syndrome|
|14q12 microdeletion syndrome|
|16p11.2p12.2 microduplication syndrome|
|14q11.2 microduplication syndrome|
|16p13.11 microdeletion syndrome|
|16p13.11 microduplication syndrome|
|16q24.3 microdeletion syndrome|
|distal 17p13.3 microdeletion syndrome|
|trisomy 17p|
|20p12.3 microdeletion syndrome|
|paternal 20q13.2q13.3 microdeletion syndrome|
|20q13.33 microdeletion syndrome|
|trisomy 20p|
|21q22.11q22.12 microdeletion syndrome|
|distal 22q11.2 microduplication syndrome|
|trisomy 1q|
|atypical Norrie disease due to monosomy Xp11.3|
|maternal uniparental disomy of chromosome X|
|paternal uniparental disomy of chromosome X|
|ring chromosome Y|
|49,XXXYY syndrome|
|Mowat-Wilson syndrome due to monosomy 2q22|
|blepharophimosis-epicanthus inversus-ptosis due to 3q23 rearrangement syndrome|
|familial adenomatous polyposis due to 5q22.2 microdeletion|
|Alagille syndrome due to 20p12 microdeletion|
|Okihiro syndrome due to 20q13 microdeletion|
|partial deletion of chromosome 1|
|partial deletion of chromosome 2|
|partial deletion of chromosome 3|
|partial deletion of chromosome 4|
|partial deletion of chromosome 5|
|partial deletion of chromosome 6|
|partial deletion of chromosome 7|
|partial deletion of chromosome 8|
|partial deletion of chromosome 9|
|partial deletion of chromosome 10|
|partial deletion of chromosome 11|
|partial deletion of the long arm of chromosome 12|
|partial deletion of chromosome 16|
|partial deletion of chromosome 17|
|partial deletion of chromosome 18|
|partial deletion of chromosome 19|
|partial deletion of chromosome 20|
|partial deletion of the short arm of chromosome 1|
|partial deletion of the short arm of chromosome 2|
|partial deletion of the short arm of chromosome 3|
|partial deletion of the short arm of chromosome 4|
|partial deletion of the short arm of chromosome 5|
|partial deletion of the short arm of chromosome 6|
|partial deletion of the short arm of chromosome 7|
|partial deletion of the short arm of chromosome 8|
|partial deletion of the short arm of chromosome 9|
|partial deletion of the short arm of chromosome 10|
|partial deletion of the short arm of chromosome 11|
|partial deletion of the short arm of chromosome 16|
|partial monosomy of the short arm of chromosome 17|
|partial deletion of the short arm of chromosome 18|
|partial deletion of the short arm of chromosome 19|
|partial monosomy of the short arm of chromosome 20|
|partial deletion of the long arm of chromosome 1|
|partial deletion of the long arm of chromosome 2|
|partial deletion of the long arm of chromosome 3|
|partial deletion of the long arm of chromosome 4|
|partial deletion of the long arm of chromosome 5|
|partial deletion of the long arm of chromosome 6|
|partial deletion of the long arm of chromosome 7|
|partial deletion of the long arm of chromosome 8|
|partial monosomy of the long arm of chromosome 9|
|partial monosomy of the long arm of chromosome 10|
|partial deletion of the long arm of chromosome 11|
|partial deletion of the long arm of chromosome 13|
|partial deletion of the long arm of chromosome 14|
|partial deletion of the long arm of chromosome 15|
|partial deletion of the long arm of chromosome 16|
|partial deletion of the long arm of chromosome 17|
|partial deletion of the long arm of chromosome 18|
|partial deletion of the long arm of chromosome 19|
|partial deletion of the long arm of chromosome 20|
|partial deletion of the long arm of chromosome 21|
|partial deletion of the long arm of chromosome 22|
|partial duplication of chromosome 1|
|partial duplication of chromosome 2|
|partial duplication of chromosome 3|
|partial duplication of chromosome 4|
|partial trisomy/tetrasomy of chromosome 5|
|partial duplication of chromosome 6|
|partial duplication of chromosome 7|
|partial duplication of chromosome 8|
|partial trisomy/tetrasomy of chromosome 9|
|partial duplication of chromosome 10|
|partial duplication of chromosome 11|
|partial trisomy/tetrasomy of the short arm of chromosome 12|
|partial duplication of chromosome 16|
|partial duplication of chromosome 17|
|partial trisomy/tetrasomy of chromosome 18|
|partial duplication of chromosome 19|
|partial trisomy of chromosome 20|
|partial duplication of the short arm of chromosome 2|
|partial duplication of the short arm of chromosome 3|
|partial duplication of the short arm of chromosome 4|
|partial trisomy/tetrasomy of the short arm of chromosome 5|
|partial duplication of the short arm of chromosome 6|
|partial duplication of the short arm of chromosome 7|
|partial duplication of the short arm of chromosome 8|
|partial trisomy of the short arm of chromosome 9|
|partial duplication of the short arm of chromosome 10|
|partial duplication of the short arm of chromosome 11|
|partial duplication of the short arm of chromosome 16|
|partial duplication of the short arm of chromosome 17|
|partial trisomy/tetrasomy of the short arm of chromosome 18|
|partial duplication of the long arm of chromosome 1|
|partial duplication of the long arm of chromosome 2|
|partial duplication of the long arm of chromosome 3|
|partial duplication of the long arm of chromosome 4|
|partial trisomy of the long arm of chromosome 5|
|partial duplication of the long arm of chromosome 6|
|partial duplication of the long arm of chromosome 7|
|partial duplication of the long arm of chromosome 8|
|partial trisomy of the long arm of chromosome 9|
|partial duplication of the long arm of chromosome 10|
|partial duplication of the long arm of chromosome 11|
|partial duplication of the long arm of chromosome 13|
|partial duplication of the long arm of chromosome 14|
|partial duplication of the long arm of chromosome 15|
|partial trisomy of the long arm of chromosome 16|
|partial duplication of the long arm of chromosome 17|
|partial trisomy of the long arm of chromosome 18|
|partial duplication of the long arm of chromosome 19|
|partial trisomy of the long arm of chromosome 20|
|partial duplication of the long arm of chromosome 22|
|X chromosome number anomaly|
|X chromosome number anomaly with female phenotype|
|X chromosome number anomaly with male phenotype|
|polysomy of X chromosome|
|partial deletion of chromosome X|
|partial monosomy of the short arm of chromosome X|
|Y chromosome number anomaly|
|X and Y chromosomal anomaly|
|partial deletion of the long arm of chromosome X|
|partial duplication of chromosome X|
|partial duplication of the short arm of chromosome X|
|partial duplication of the long arm of chromosome X|
|uniparental disomy of chromosome X|
|partial duplication of the short arm of chromosome 1|
|trisomy 8p|
|DYRK1A-related intellectual disability syndrome due to 21q22.13q22.2 microdeletion|
|10q22.3q23.3 microduplication syndrome|
|distal monosomy 12p|
|partial deletion of chromosome 12|
|facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to 10p11.21p12.31 microdeletion|
|Xp22.13p22.2 duplication syndrome|
|12q15q21.1 microdeletion syndrome|
|microtriplication 11q24.1|
|distal Xq28 microduplication syndrome|
|1p21.3 microdeletion syndrome|
|2q31.1 microduplication syndrome|
|zygodactyly type 2|
|zygodactyly type 3|
|zygodactyly type 4|
|11p15.4 microduplication syndrome|
|20p13 microdeletion syndrome|
|12p12.1 microdeletion syndrome|
|2q23.1 microduplication syndrome|
|7p22.1 microduplication syndrome|
|Xq12-q13.3 duplication syndrome|
|15q overgrowth syndrome|
|severe neonatal hypotonia-seizures-encephalopathy syndrome due to 5q31.3 microdeletion|
|partial deletion of the short arm of chromosome 12|
|distal 17p13.1 microdeletion syndrome|
|9p13 microdeletion syndrome|
|duplication/inversion 15q11|
|tetrasomy 5p|
|tetrasomy 9p|
|trisomy X|
|trisomy 13|
|distal trisomy 17q|
|trisomy 18|
|16q24.1 microdeletion syndrome|
|neurodevelopmental disorder-craniofacial dysmorphism-cardiac defect-hip dysplasia syndrome due to 9q21 microdeletion|
|3q26q27 microdeletion syndrome|
|20q11.2 microduplication syndrome|
|distal monosomy 1q|
|2p13.2 microdeletion syndrome|
|17q21.31 microdeletion syndrome|
|2p21 microdeletion syndrome without cystinuria|
|homozygous 2p21 microdeletion syndrome|
|3q27.3 microdeletion syndrome|
|9q31.1q31.3 microdeletion syndrome|
|14q24.1q24.3 microdeletion syndrome|
|Angelman syndrome due to imprinting defect in 15q11-q13|
|13q12.3 microdeletion syndrome|
|3p25.3 microdeletion syndrome|
|11q22.2q22.3 microdeletion syndrome|
|20q11.2 microdeletion syndrome|
|19p13.3 microduplication syndrome|
|partial duplication of the short arm of chromosome 19|
|symptomatic form of fragile X syndrome in female carrier|
|1p35.2 microdeletion syndrome|
|22q11.2 deletion syndrome|
|monosomy 21|
|neurofibromatosis type 1|
|Charcot-Marie-Tooth disease type 1|
|6q terminal deletion syndrome|
|monosomy 9q22.3|
|47,XYY syndrome|
|tetrasomy X|
|12q14 microdeletion syndrome|
|tetrasomy 21|
|mosaic trisomy 4|
|mosaic trisomy 5|
|mosaic trisomy 8|
|mosaic trisomy 10|
|mosaic trisomy 22|
|distal trisomy 1p36|
|distal trisomy 2p|
|distal trisomy 3p|
|4p16.3 microduplication syndrome|
|distal trisomy 7p|
|Beckwith-Wiedemann syndrome due to 11p15 microduplication|
|8p inverted duplication/deletion syndrome|
|distal trisomy 2q|
|3q26 microduplication syndrome|
|distal trisomy 4q|
|distal trisomy 5q|
|distal trisomy 6q|
|distal trisomy 8q|
|distal trisomy 9q|
|distal trisomy 10q|
|distal trisomy 11q|
|distal trisomy 13q|
|distal trisomy 16q|
|distal trisomy 20q|
|distal trisomy 22q|
|non-distal trisomy 9q|
|monosomy 22|
|distal monosomy 7p|
|distal monosomy 19p13.3|
|non-distal monosomy 7p|
|distal monosomy 4q|
|Kleefstra syndrome due to 9q34 microdeletion|
|distal monosomy 12q|
|distal monosomy 14q|
|distal monosomy 20q|
|non-distal monosomy 12q|
|non-distal monosomy 20q|
|monosomy 13q34|
|ring chromosome 2|
|ring chromosome 3|
|ring chromosome 9|
|ring chromosome 11|
|ring chromosome 13|
|ring chromosome 15|
|ring chromosome 16|
|maternal uniparental disomy of chromosome 2|
|maternal uniparental disomy of chromosome 4|
|maternal uniparental disomy of chromosome 6|
|silver-Russell syndrome due to maternal uniparental disomy of chromosome 7|
|maternal uniparental disomy of chromosome 9|
|maternal uniparental disomy of chromosome 14|
|maternal uniparental disomy of chromosome 16|
|maternal uniparental disomy of chromosome 20|
|maternal uniparental disomy of chromosome 21|
|maternal uniparental disomy of chromosome 22|
|paternal uniparental disomy of chromosome 5|
|paternal uniparental disomy of chromosome 6|
|paternal uniparental disomy of chromosome 7|
|Beckwith-Wiedemann syndrome due to paternal uniparental disomy of chromosome 11|
|paternal uniparental disomy of chromosome 20|
|paternal uniparental disomy of chromosome 21|
|X small rings|
|48,XXXY syndrome|
|49,XXXXY syndrome|
|isochromosome Y|
|maternal uniparental disomy of chromosome 13|
|46,XY disorder of sex development|
|syndrome with 46,XY disorder of sex development|
|chromosome Y structural anomaly|
|chromosome X structural anomaly|
|X-linked syndromic intellectual disability|
|Prader-Willi syndrome due to maternal uniparental disomy of chromosome 15|
|Prader-Willi syndrome due to paternal 15q11q13 deletion|
|Angelman syndrome due to maternal 15q11q13 deletion|
|Angelman syndrome due to paternal uniparental disomy of chromosome 15|
|isochromosomy Yp|
|isochromosomy Yq|
|monosomy X|
|mosaic monosomy X|
|paternal uniparental disomy of chromosome 13|
|48,XYYY syndrome|
|49,XYYYY syndrome|
|Turner syndrome due to structural X chromosome anomalies|
|mosaic trisomy 9|
|chromosome 17 abnormality|
|chromosome 11q trisomy|
|chromosome 12p deletion|
|chromosome 13q trisomy|
|chromosome 13q-mosaicism|
|chromosome 16 trisomy|
|chromosome 13p duplication|
|chromosome 16p13.3 deletion syndrome|
|chromosome 17p deletion|
|chromosome 18 mosaic monosomy|
|chromosome 1q deletion|
|chromosome 20 trisomy|
|chromosome 22, monosome mosaic|
|trisomy 22|
|chromosome 22q deletion|
|chromosome 3 duplication syndrome|
|chromosome 4 short arm deletion|
|chromosome 8 deletion|
|fragile X syndrome type 1|
|fragile X syndrome type 2|
|fragile X syndrome type 3|
|Kleefstra syndrome 1|
|partial duplication of chromosome 12|
|partial duplication of the long arm of chromosome 12|
|chromosome 1, uniparental disomy 1q12 q21|
|mosaic trisomy 6|
|chromosome 8, trisomy|
|16p12.1p12.3 triplication syndrome|
|9q33.3q34.11 microdeletion syndrome|
|4q25 proximal deletion syndrome|
|mosaic variegated aneuploidy syndrome 3|
|chromosome 1p35 deletion syndrome|

**Comment by sabrinatoro** [comment]
Except for 2 terms which will be obsoleted in the June release, this project is done. Closing this issue.
