### ISSUE TITLE
MONDO:0020184 parentage

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1501]
MONDO:0020184 rare eyebrow/eyelashes anomaly
--
is_a eyelid disease

is_a 
eye disease

Looks incorrect?

**Comment by nicolevasilevsky** [comment]
There is a comment on this term:
Editor note: does not align with anatomy

and an annotation on the subclass Of assertion: MONDO:disputed

it seems like we should exclude this parent and add the superclass 'eye adnexa disease' instead.

**Comment by cmungall** [comment]
Thanks Nicole, the fix is correct, although we lose the fact that this affects the hair

I'm going to go ahead and merge this but I'll keep this open. Note we have an 'obsoletion candidate' on this one, and a link to #254 - we don't like groupings like "rare X". The reason this wasn't changed to just "X" was precisely because we don't have an anatomic grouping for eyelib/eyebrow

I really think some obsoletion is in order here. This falls in the category of dubious ordo-derived groupings that you and @paolaroncaglia have been looking at. Let's take a look:

![image](https://user-images.githubusercontent.com/50745/82518018-3e2af100-9ad3-11ea-8e40-ea43fc563770.png)

What we have here are some phenotypes, with diseases classified under them.

It's not even clear why all the diseases are here. Most of them are syndromic with multiple manifestations, of which hair anomalies in the ocular adnexa seem a relatively minor feature.

For example, for the highlighted 'follicular atrophoderma-basal cell carcinoma'
https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=1009&Disease_Disease_Search_diseaseType=ORPHA&Disease_Disease_Search_diseaseGroup=113&Disease(s)/group%20of%20diseases=Follicular-atrophoderma-and-basal-cell-carcinomas&title=Follicular-atrophoderma-and-basal-cell-carcinomas&search=Disease_Search_Simple

_The disease manifests during the neonatal period or during infancy. It is characterized by hypotrichosis, hypohidrosis, milia and basal cell carcinomas of early onset. Follicular atrophoderma is frequent and most common on the dorsum of the hands and feet, the extensor surfaces of the elbows and knees, and the face. Hypotrichosis affects the scalp and **sometimes the eyebrows**. The milia papules and basal cell carcinomas are located predominantly on the face. Basal cell carcinomas develop in 40% of patients, usually during the 2nd or 3rd decade of life. Additional common features include basal cell hamartomas, trichoepitheliomas and, in very rare cases, atopy, keratosis pilaris, ichthyosis, arachnodactyly with joint hyperlaxity, osteochondritis, deafness and learning difficulties._

It just doesn't make any sense to have this classification. The phenotype should be captured in an association between  'follicular atrophoderma-basal cell carcinoma' and HPO terms for Hypotrichosis of the eyebrow, with an 'infrequent' qualifier, rather than trying to bake infrequent associations to vague groupings into the hierarchy!

Your PR definitely improves things, as we were previously classifying this one under eyelid which it doesn't even seem to affect. At least the eyebrow thing is true occasionally.

But we really need to get moving on obsoleting a lot these classes!
