### ISSUE TITLE
genetic hair anomaly (MONDO:0021027) parentage

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1502]
genetic hair anomaly (MONDO:0021027)

is_a genetic epidermal appendage anomaly

which is a "skin disease"

Looks incorrect?

**Comment by nicolevasilevsky** [comment]
cc @Orphanet @ana-rath-orphanet @annieolry

**Comment by nicolevasilevsky** [comment]
This comes from Orphanet, and the term is not defined, but this def from [medscape](https://emedicine.medscape.com/article/1294744-overview) says:
Hair follicles, sebaceous glands, sweat glands, apocrine glands, and mammary glands are considered epidermal glands or epidermal appendages, because they develop as downgrowths or diverticula of the epidermis into the dermis.

So I think this is okay.

Please reopen if you disagree, thanks!
