### ISSUE TITLE
NTR: idiopathic anaphylaxis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#157]
For new term requests, please provide the following information:

## Preferred term label
 idiopathic anaphylaxis

## Parent
MONDO_0000605 'hypersensitivity reaction disease'

## def
Idiopathic anaphylaxis is a rare form of anaphylaxis for which triggers cannot be identified despite a detailed history and careful diagnostic assessment.

## Source
PMID:28890861

See: HP_0410148 'Idiopathic anaphylaxis'
This term was added to HPO, but Peter thought it may be better in MONDO. See https://github.com/obophenotype/human-phenotype-ontology/issues/3440

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall do we like this term for MONDO? Would we want to add anaphylaxis as a parent term for this class as well?

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall is it okay to add this term to MONDO?

**Comment by cmungall** [comment]
It seems odd to have an idiopathic form of X in the ontology yet not X.

NCIT includes anaphylaxis as a disease rather than finding.

```
 / NCIT:C7057 ! Disease, Disorder or Finding
  is_a NCIT:C2991 ! Disease or Disorder
   is_a NCIT:C27551 ! Disorder by Site
    is_a NCIT:C27351 ! Immune System and Related Disorders
     is_a NCIT:C3507 ! Immune System Disorder
      is_a NCIT:C3114 ! Hypersensitivity
       is_a NCIT:C107101 ! Anaphylaxis ***
       is_a NCIT:C114345 ! Type II Hypersensitivity
       is_a NCIT:C114346 ! Type III Hypersensitivity
       is_a NCIT:C114476 ! Allergic Reaction
       is_a NCIT:C3115 ! Type IV Hypersensitivity
       is_a NCIT:C3116 ! Type I Hypersensitivity
       is_a NCIT:C3432 ! Urticaria
       is_a NCIT:C3668 ! Contact Hypersensitivity
```

I think I am tending towards the inclusion of anaphylaxis (as well as children like idiopathic and systemic). Formally this would be the disposition to realizing anaphylactic shocks under certain triggers.

note IA should have an equiv xref (see MONDO manual) to SCTID:241954008

**Comment by cmungall** [comment]
What about exercise-induced? GARD treats as a disorder: https://rarediseases.info.nih.gov/diseases/6392/exercise-induced-anaphylaxis

(but we also have this in HPO)

**Comment by pnrobinson** [comment]
This is an item that can be conceptualized both as a disease and as a feature. There are other diseases that characteristically feature certain types of analphylaxis and this can be used as a differential diagnostic criteria, and this is the reason for inclusion in the HPO. However, if we consider the etiology, features, time course of the various types of anaphylaxis, then they can be conceptualized as diseases.
In the future, we will probably annotate to the MONDO term instead of the HPO term. This will require a decent amount of software engineering that we will develop in the common disease annotation project but that will probably become part of the rare disease annotations with time.
