### ISSUE TITLE
urea cycle related

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1572]
follow on from

https://github.com/monarch-initiative/mondo/issues/1553

Is there really a difference between

MONDO:0019217  inborn disorder of urea cycle metabolism and ammonia detoxification 
MONDO:0004739 | urea cycle disorder

Isn't  all urea cycle about ammonia detoxification ?

I ask because 
MONDO:0019217  inborn disorder of urea cycle metabolism and ammonia detoxification
was made a child which means it's narrower so the logic seems  a bit strange

if MONDO:0019217 is urea cycle plus ammonia detoxification

**Comment by nicolevasilevsky** [comment]
I don't know the biology well enough here to comment.

@pnrobinson could you help?

**Comment by pnrobinson** [comment]
Well yes the urea cycle performs ammonia detoxification, and so there is no need to write "and ammonia detoxification". 
These are inborn errors and so "urea cycle disorder' implies that they are genetic diseases. There are very rare exceptions to this rule, though, for instance, there have been reports of liver transplantation leading to a urea cycle disorder because the donor had the disease (https://pubmed.ncbi.nlm.nih.gov/18044746/). I think that we do not need to worry about this for now, though. So I would suggest that for now we merge these terms and retain

primary label "urea cycle disorder"
synonyms "inborn error of urea cycle metabolism", urea cycle defect, Inborn Error of Metabolism with Hyperammonemia

**Comment by nicolevasilevsky** [comment]
Perfect, thank you, @pnrobinson!
