### ISSUE TITLE
review subclasses of disease by subcellular system affected

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1578]
look for terms in branch 'disease by subcellular system affected' and flag any terms where this is the only parent 

this was discussed at the 05/22 Mondo mtg.

**Comment by paolaroncaglia** [comment]
Other than the terms whose label starts with "disease by", here's a start:
- [ ] MONDO:0021017 synaptopathy -> has only 1 child, that has another parent too;
...
TBC

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I don't remember what the specific action item here was, what are we meant to do with these terms? Do we want to reclassify them? Or consider obsoleting them?
Thanks!

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

> @paolaroncaglia I don't remember what the specific action item here was, what are we meant to do with these terms? Do we want to reclassify them? Or consider obsoleting them?

Some of the terms in that branch may be useful but it's up to Mondo if you'd like to keep the broader grouping classes or not... I tried to help with this, but I progress slowly because I look at terms in OLS (old laptop may not agree with memory settings necessary to display Mondo in Protege). This work is less priority for EFO than the Orphanet-related issue, so I'm ok with leaving it aside, if keeping the ticket open is ok with you please. Thanks!

**Comment by nicolevasilevsky** [comment]
disease by subcellular system affected has been obsoleted, so I think this is no longer needed. Closing.
