### ISSUE TITLE
hydatiform mole,  missing parent

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1611]
hydatiform mole is a descendant of
MONDO_0016784  gestational trophoblastic disease

but should that move  down to 
gestational trophoblastic neoplasm MONDO_0018944 
def
A diverse group of pregnancy-related tumors characterized by excessive proliferation of trophoblasts. Representative examples include hydatidiform mole, gestational choriocarcinoma, and placental site trophoblastic tumor.

**Comment by cmungall** [comment]
OK, I think this is a bit complicated

On the one hand, it seems we may want to go one step further and merge GTT and GTN, based on synonyms in NCIT:

```
id: NCIT:C4699
name: Gestational Trophoblastic Tumor
def: "A diverse group of pregnancy-related tumors characterized by excessive proliferation of trophoblasts. Representative examples include hydatidiform mole, gestational choriocarcinoma, and placental site trophoblastic tumor." []
synonym: "GTT" EXACT  []
synonym: "Gestational Trophoblastic Disease" EXACT  []
synonym: "Gestational Trophoblastic Tumor" EXACT  []
synonym: "Gestational trophoblastic disease" EXACT  []
synonym: "gestational trophoblastic disease" EXACT  []
synonym: "gestational trophoblastic neoplasia" EXACT  []
synonym: "gestational trophoblastic tumor" EXACT  []
is_a: NCIT:C3053 ! Female Reproductive System Neoplasm
is_a: NCIT:C3422 ! Trophoblastic Tumor
is_a: NCIT:C35169 ! Pregnancy Disorder
relationship: NCIT:R101 NCIT:C12402 ! Disease_Has_Primary_Anatomic_Site Female Reproductive System
intersection_of: NCIT:C3053 ! Female Reproductive System Neoplasm
intersection_of: NCIT:R101 NCIT:C12402 ! Disease_Has_Primary_Anatomic_Site Female Reproductive System
intersection_of: NCIT:C3422 ! Trophoblastic Tumor
intersection_of: NCIT:R101 NCIT:C12402 ! Disease_Has_Primary_Anatomic_Site Female Reproductive System
intersection_of: NCIT:C35169 ! Pregnancy Disorder
intersection_of: NCIT:R101 NCIT:C12402 ! Disease_Has_Primary_Anatomic_Site Female Reproductive System
```

However, the NCIT graph is not very consistent with their textual description:

![image](https://user-images.githubusercontent.com/50745/84101654-4fc13380-a9c3-11ea-9839-7e5959ccd7f5.png)

NCIT are our go-to source for anything cell proliferation, @nicolevasilevsky can you coordinate with them to resolve this?

My assumption is that there is a reluctance to classify HM under neoplasm due to questions of whether it fit the definition of "uncontrolled cell proliferation". This can be seen if we look deeper in NCIT:

![image](https://user-images.githubusercontent.com/50745/84102542-9d3ea000-a9c5-11ea-8e0e-3d12127d130e.png)

here we can see the 3 subtypes.. ideally the ordering of the siblings would be partial, complete, and invasive. Only the invasive is placed under neoplasm. I have chosen to highlight also the two major subtypes of neoplasm in NCIT (Recall that in NCIT, plain "neoplasm" is malignancy-neutral)

This classification seems quite unusual to me. I would have placed the invasive form under the stronger 'malignant' neoplasm. And my understanding is that HMs in general are usually considered benign, with a potential to become malignant, so placing PHM under benign neoplasm seems justified... but this is based on very cursory reading.

It would certainly make things easier to consider all HMs to be neoplasms (in the broad sense, i.e malignancy-neutral, as per NCIT), which would induce an equivalence between GTT and GTD, which we would address by merging.

I'd be hesitant to do this without consulting the experts here.

The current situation in mondo is a bit of a fudge: GTD = GTT OR HM.

**Comment by nicolevasilevsky** [comment]
emailed NCIt on 06/10/20

**Comment by nicolevasilevsky** [comment]
NCIt said (06/11/20):
Our opinion is that Hydatidiform mole is not a neoplasm. It is a degenerative disorder that occurs during pregnancy. It should stay under trophoblastic disease and not moved under trophoblastic neoplasm.

@ValWood I am going to close this ticket, but please reopen if you'd like to discuss further.

**Comment by ValWood** [comment]
in that case,should the definition of

gestational trophoblastic neoplasm MONDO_0018944
A diverse group of pregnancy-related tumors characterized by excessive proliferation of trophoblasts. Representative examples include hydatidiform mole, gestational choriocarcinoma, and placental site trophoblastic tumor.

be revised?

**Comment by nicolevasilevsky** [comment]
I am unclear why you want to revise the def of gestational trophoblastic neoplasm MONDO_0018944. It is a sibling of 'hydatidiform mole'.

Could you please clarify? Thanks!

**Comment by ValWood** [comment]
Taken literally, this part of the definition MONDO_0018944 asserts  hydatiform moles are also neoplasms

"Representative examples include hydatidiform mole"

Is it "some forms of hydatiform mole" (if so which specifically?)

another logic issue is that the term "hydatiform mole"
has the parent "placenta neoplasm"???

Logically presumably  if it is_a "placental neoplasm", and is_a "gestational trophoblastic disease"
it MUST also be is_a "gestational trophoblastic neoplasm "

so there are further issues to resolve?

**Comment by ValWood** [comment]
"It should stay under trophoblastic disease and not moved under trophoblastic neoplasm"
Implies that the experts are not aware of the possibility of multiple inheritance? 

Note that I have no idea what is correct clinically,  my tickets  are based on the logic of what already exists in Mondo  (do you have logical definitions?)

**Comment by cmungall** [comment]
@ValWood these are exactly the right questions, we talked briefly about this on our call but didn't have time to start unravelling

**Comment by nicolevasilevsky** [comment]
@pnrobinson - if you have time, your input on this would be appreciated! Thanks!

**Comment by nicolevasilevsky** [comment]
Emailed NCIT 02/04/2022 to get further clarification

**Comment by nicolevasilevsky** [comment]
Followed up via email on 04/20/22
subject: Question about MONDO_0018944 'gestational trophoblastic neoplasm'

**Comment by nicolevasilevsky** [comment]
From NCIT EVS:
According to WHO, hydatidiform mole has been removed from trophoblastic neoplasms, so it should not be a subclass. We will modify the existing NCIt definition for this concept.

**Comment by pnrobinson** [comment]
AFAIK hydatidiform mole is considered a type of trophoblastic neoplasm. See for instance here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4853053/

**Comment by nicolevasilevsky** [comment]
to do:

- [ ] add as a subclass of neoplasm
- [ ] create ticket on NCIT tracker
