### ISSUE TITLE
[Merge] MONDO_0006248 'hydatidiform mole' with MONDO:0018944 'gestational trophoblastic neoplasm'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1614]
**Mondo term (ID and Label)**
MONDO_0006248 'hydatidiform mole'

**Reason for deprecation**
There is a comment on the class: TODO - merge with MONDO:0018944

**Term to be merged with**
MONDO:0018944 'gestational trophoblastic neoplasm'

**Comment by ValWood** [comment]
This is presumably  OK if the  the other things listed here:

gestational trophoblastic neoplasm MONDO_0018944
def
A diverse group of pregnancy-related tumors characterized by excessive proliferation of trophoblasts. Representative examples include hydatidiform mole, gestational choriocarcinoma, and placental site trophoblastic tumor.

i.e.
gestational choriocarcinoma, and placental site trophoblastic tumor.
are equivalent to the hydatiform mole.

Otherwise, the hydatiform mole  term seems a rather useful grouping term for the 
"hydatiform mole-form neoplasms"
e.g

hydatiform mole, recurrent, 1
hydatiform mole recurrent, 2
etc

(Do you know the rationale for the merge comment?)

**Comment by ValWood** [comment]
see also
https://github.com/monarch-initiative/mondo/issues/1611

**Comment by nicolevasilevsky** [comment]
I don't know the rationale - but it is not definitive, we are meant to investigate further. Sounds like you prefer to keep these terms separate. I can remove the comment. Thanks for your input. :)

Note to self:
- [ ] remove comment

**Comment by ValWood** [comment]
The correct superclass  https://github.com/monarch-initiative/mondo/issues/1611
 will help (I wonder if the merge was suggested in part to address this ommission?)

A merge might be appropriate (I don't know enough about whether gestational choriocarcinoma, and placental site trophoblastic tumor are other names for hydaitform mole. If they are, a merge may be appropriate.

I would say only merge if hydatiform mole is exact, but keep if narrow, because you have a 
slew of more specific hydatiform mole terms.

**Comment by galyea-gard** [comment]
Hi!  The hydatiform mole is  not a synonym for gestational throphoblastic neoplasm but may be considered a subtype (benign, except for the invasive type).  The gestational throphoblastic neoplasm or tumor, include several tumors such as the  gestational choriocarcinoma, and the hydatiform mole.
