### ISSUE TITLE
Missing Parent: MONDO:0010799	 mitochondrial non-syndromic sensorineural deafness with susceptibility to aminoglycoside exposure

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1652]
from 
https://github.com/monarch-initiative/mondo/issues/1587

I do have one more query though:

mitochondrial non-syndromic sensorineural deafness with susceptibility to aminoglycoside exposure

is not a descendant of 

 mitochondrial non-syndromic sensorineural deafness

**Comment by cmungall** [comment]
Yes, this omission is odd. This is a definite anti-pattern (lexical pattern implies subclass when in fact they are siblings).

Scratching a bit deeper it's a bit more complex

These two terms are equivalenced to two different OMIMs:

 * https://omim.org/entry/500008 DEAFNESS, NONSYNDROMIC SENSORINEURAL, MITOCHONDRIAL 
        * _mitochondrially inherited nonsyndromic sensorineural deafness can be caused by mutation in any 1 of several mitochondrial genes, including MTRNR1 (561000), MTTS1 (590080), MTCO1 (516030), MTTH (590040), MTND1 (516000), and MTTI (590045)._
 * https://omim.org/entry/580000 DEAFNESS, AMINOGLYCOSIDE-INDUCED
      * aminoglycoside-induced deafness is associated with mutations in at least 2 mitochondrial-encoded genes, including MTRNR1 (561000) and MTCO1 (516030).
       * = MONDO:0010799 mitochondrial non-syndromic sensorineural deafness with susceptibility to aminoglycoside exposure

The superclass-suggesting name in mondo for MONDO:0010799 comes from ORDO (https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_168609) (note ORDO doesn't xref the OMIM but we made the call that they are equivalent)

Now, most cases we would not have one OMIM subsume another, because usually this is an error since OMIM entities are usually distinct representing gene-specific etiologies, but perhaps mt diseases are handled differently. In fact we should have a check set up to detect these.

Now it may be the case that in this case one of these OMIMs subsumes the other but I would be inclined to be conservative here and keep them siblings. I would however use the OMIM name rather than the ORDO name, which will resolve the apparent contradiction in there being no superclass relationship.

(We can ask Ada if there are plans to split the Mt diseases into gene-specific entries, but I just want to check we haven't asked this in another ticket before bothering her).

**Comment by nicolevasilevsky** [comment]
>  I would however use the OMIM name rather than the ORDO name, which will resolve the apparent contradiction in there being no superclass relationship.

I will revise the name of MONDO_0010799 to aminoglycoside-induced deafness
