### ISSUE TITLE
erythropoietic protoporphyria

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1737]
Not sure how this relates to other tickets, so I am creating a new one.  Sorry for any duplication.
**erythropoietic protoporphyria** (http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0001676) hss the definition of being caused by ferrochetalase, which make it appear to be the same as https://www.omim.org/entry/177000 (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=121784.  https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=11304&MISSING%20CONTENT=Autosomal-erythropoietic-protoporphyria&search=Disease_Search_Simple&title=Autosomal%20erythropoietic%20protoporphyria)

Would this work?
**erythropoietic protoporphyria** 
MONDO_0001676
alter the definition to remove the mention of FECH
A rare congenital metabolic disorder characterized by an inborn error of porphyrin-heme biosynthesis. Signs and symptoms include painful cutaneous photosensitivity leading to blistering and scarring of the exposed skin areas, erythrodontia, red discoloration of urine, hemolytic anemia, and splenomegaly.

Indent **EPP1** and **EPP2** under **EPP/autosomal erythropoietic protoporphyria**

**Comment by nicolevasilevsky** [comment]
@maglott 
Let me know if this is incorrect:
![image](https://user-images.githubusercontent.com/6722114/89939124-5db25100-dbcc-11ea-87a6-5431e266c90b.png)

**Comment by maglott** [comment]
I don't know if it is correct, but that is what I was suggesting.

**Comment by nicolevasilevsky** [comment]
@ahamosh @ana-rath-orphanet @galyea-gard @pnrobinson, could any of you review and comment? thank you!

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Hi!  I commented directly in the GitHub ticket. Thank you! Gioconda

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by galyea-gard** [comment]
Erythropoietic protoporphyria may be classified in autosomal erythropoietic protoporphyria (inherited as AR ) and (only in about 2%)  X-linked EPP (which some authors refer as a separate form of protoporphyria that has very similar features to the autosomal EPP).  GARD term is listed only for erythropoietic protoporphyria (please notice that OMIM EPP1 is only for the AR type),  EPP was initially thought to be inherited in an autosomal dominant manner but AR inheritance is now established. Orphanet page for autosomal EPP comments about AD and AR (I think that they need to update it).  but notice that OMIM has a page for AD EPP (EPP2:  https://www.omim.org/entry/618015) where they comment that this form was reported in only one family and it is caused by mutations in the CLPX gene. We do not have " X-linked erythropoietic protoporphyria listed in the website yet.

**Comment by pnrobinson** [comment]
I am not sure if we gain much by the grouping term "autosomal erythropoietic protoporphyria" as opposed to just having the two grandchildren be children of "erythropoietic protoporphyria"?

**Comment by ahamosh** [comment]
Hi All,  The form of EPP (EPP1) due to ferrochelatase is AR. EPP, X-linked is due to ALAS2 defiency.  EPP2 is autosomal dominant and has been reported in one family as due to a pathogenic variant in CLPX.  OMIM needs to add EPP2 to the Phenotypic Series. I think that Donna's system works.  It could also be EPP with children by gene and not by inheritance.  I defer to your structure.

**Comment by galyea-gard** [comment]
I think that the classification can be the one suggested: 
EPP classified in Autosomal EPP (subclassified in EPP1 and EPP2) and X-linked EPP.  Please see my former comment. Thanks!

**Comment by galyea-gard** [comment]
I think that the classification can be the one suggested: 
EPP classified in Autosomal EPP (subclassified in EPP1 and EPP2) and X-linked EPP.  Please see my former comment. Thanks!
