### ISSUE TITLE
[Revise text def] classic phenylketonuria MONDO:0019259 vs phenylketonuria MONDO:0009861

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1738]
**Mondo term (ID and Label)**

What is the intended distinction between classic phenylketonuria and phenylketonuria?

phenylketonuria MONDO:0009861 has  exact synonyms which appear to overlap with the disease caused by P
AH deficiency and termed classic by others.

Should  phenylketonuria MONDO:0009861 correspond to  [C0031485]  Phenylketonurias
 and classic phenylketonuria MONDO:0019259 correspond to [C0751434]  Classical phenylketonuria
 with the exact synonyms of FOELLING SYNDROME, etc?

**Comment by nicolevasilevsky** [comment]
In Mondo, we have two terms:
phenylketonuria and classic phenylketonuria

Folling's disease is a synonym for phenylketonuria in Mondo, OMIM and DO

Folling's disease is a synonym for Classical phenylketonuria in UMLS

Looks like Folling discovered PKU, hence the synonym, Folling's disease:
https://pubmed.ncbi.nlm.nih.gov/12785112/

@pnrobinson @ahamosh Do you have any thoughts on this?

I propose that we:
- [ ] remove classical phenylketonuria as a synonym from phenylketonuria (there is no xref, not sure where this came from)
- [ ] Make Folling's disease a related synonym for both PKU and classical PKU

and I believe that will address the issue.

Thanks @maglott!

**Comment by pnrobinson** [comment]
I think that by default if you just say phenylketonuria you mean classical PKU.
Here is an article by some ex colleagues of mine:
https://www.sciencedirect.com/science/article/abs/pii/S1096719211002836
Here is a consensus statement that we could cite
https://www.nichd.nih.gov/publications/pubs/pku/sub3
I have never heard PKU being called Folling's disease  -- according to Wikipedia this is the name used in Norway after its discoverer, but I think that the community is moving away from names like this (see Ada's recent article), and so maybe it should be listed as an obsolete synonym?

**Comment by ahamosh** [comment]
I had never heard of PKU called Folling disease, but he did describe it.  In OMIM, the PKU entry includes classical and "mild" PKU, so all forms of hyperphenylalaninemia due to complete or partial deficiency of PAH, but not those from of elevated phenylalanine associated with other causes.  So PKU is not necessarily a synonym for classical PKU (diagnostic Phe level above 1200).  Most clinicians in the US use PKU for classical, hyperphenylalaninemia for non-classical requiring treatment (Phe 400-1199), and benign hyperphenylalaninemia for levels <400 requiring no treatment (except possibly in pregnancy to prevent maternal PKU.  But everyone will join the PKU Alliance...  Even things that are easy aren't simple.

**Comment by nicolevasilevsky** [comment]
Based on the comments above, I made the following edits:
1. excluded synonyms that mentioned Folling
2. added dbxref to this article (https://www.nichd.nih.gov/publications/pubs/pku/sub3) on classic phenylketonuria
