### ISSUE TITLE
review equivalent exact and related synonyms in the same record

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1794]
**Mondo term (ID Label)**
isolated sulfite oxidase deficiency/MONDO:0010089  is one example

**Bug/Typo/Error description**

  "hasExactSynonym" : [ "Sulfocysteinuria", "ISOD" ],
  "hasRelatedSynonym" : [ "sulfite oxidase deficiency, isolated", "sulfite oxidase deficiency, isolated; ISOD", "sulfite oxidase deficiency", "SULFOCYSTEINURIA" ],

Except for sulfite oxidase deficiency,  all the terms in the category of    "hasRelatedSynonym" are case or word-order transforms of the title or its exact synomyms  (after splitting on the semi-colon )

How many other examples of this are there? Isn't `related` to be used  then the labels represent a slightly different concept?

**Comment by nicolevasilevsky** [comment]
@maglott thanks for the feedback!

I fixed this case. I agree, I see this a lot too.

@matentzn could we develop a pipeline to review/fix these?

**Comment by matentzn** [comment]
I guess we could generate a report to that end, yes. I know how to do it, but I first want @cmungall permission because this redundancy may be by design.

**Comment by nicolevasilevsky** [comment]
On Mondo call - Chris said we should do a mass search and replace for some of these. We'll discuss this further when @matentzn is on the call.

too dangerous to do a global search and replace, but would be too much work to do it manually.

**Comment by nicolevasilevsky** [comment]
Action items:
- [ ] All OMIM synonyms should be exact (not related) 
- [ ] OMIM synonyms should be broken into synonyms - main term and abbreviation, for example [add]
- [ ] Any synonym that is exact and related, make it exact (need to move the source annotations to the exact synonym)

**Comment by maglott** [comment]
I am a bit skeptical about 'All OMIM synonyms should be exact (not related)'
* there are cases like https://www.omim.org/entry/602429 and https://www.omim.org/entry/603383 where the same alternate name is used on multiple records.  
* there are cases like the records for gene-specific name 1 where one of the alternate name is likely synonymous with the phenotypic series,  not the gene-specific entity.

Are these cases being detected?

**Comment by nicolevasilevsky** [comment]
good point @maglott, we'll look into this. Thank you!

**Comment by nicolevasilevsky** [comment]
I think we could do this:
1) change all OMIM synonyms from related to exact, 
2) then check where there are duplicate synonyms coming from OMIM and manually review these, and then make them related synonyms, if applicable (or maybe broad, in the example from Donna above). (it would probably be good to do this for all synonyms).

**Comment by maglott** [comment]
Sounds good.  With, perhaps, a special review of alternate names for 'disease name 1' because it may be that some of the alternate names are more correctly synonyms for 'disease name'

**Comment by matentzn** [comment]
Wait a moment; I am not anymore sure that all this is needed..

Check this [query](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aprefix%20oboInOwl%3A%20%3Chttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23%3E%0Aprefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT%20%3Fterm%20%3Fterm_label%20%3Frelated%20%3Fxref1%20%3Fxref2%0AWHERE%20%0A%7B%20%0A%20%20%7B%20%0A%20%20%20%20%3Fterm%20oboInOwl%3AhasRelatedSynonym%20%3Frelated%20%3B%0A%20%20%20%20%20%20rdfs%3Alabel%20%3Fterm_label%20%3B%0A%20%20%20%20%20%20oboInOwl%3AhasExactSynonym%20%3Fexact%20%3B%0A%20%20%20%20%20%20a%20owl%3AClass%20.%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20a%20owl%3AAxiom%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedProperty%20oboInOwl%3AhasExactSynonym%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedTarget%20%3Fexact%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20oboInOwl%3AhasDbXref%20%3Fxref1%20%0A%20%20%20%20%20%20%5D%20.%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20a%20owl%3AAxiom%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedProperty%20oboInOwl%3AhasRelatedSynonym%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedTarget%20%3Frelated%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20oboInOwl%3AhasDbXref%20%3Fxref2%20%0A%20%20%20%20%20%20%5D%20.%0A%20%20%20%20%0A%20%20%20%20FILTER%20(str(%3Frelated)%3Dstr(%3Fexact))%0A%20%20%20%20FILTER%20(regex(str(%3Fxref1)%2C%20%22%5EOMI%22))%0A%20%20%20%20FILTER%20(regex(str(%3Fxref2)%2C%20%22%5EOMI%22))%0A%20%20%20%20FILTER%20(isIRI(%3Fterm)%20%26%26%20regex(str(%3Fterm)%2C%20%22%5Ehttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_%22))%0A%20%20%7D%0A%20%20%23UNION%20%0A%20%20%23%20%7B%20%0A%20%20%23%20ASK%20CHRIS%3A%20IS%20THIS%20REDUNDANT%3F%20-%3E%20REDUNDANT..%0A%20%20%23%20%20%3Fx%20owl%3AannotatedProperty%20oboInOwl%3AhasRelatedSynonym%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedTarget%20%3Frelated%20.%0A%20%20%23%20%20%20%20%0A%20%20%23%20%3Fy%20owl%3AannotatedProperty%20oboInOwl%3AhasExactSynonym%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedTarget%20%3Fexact%20.%0A%20%20%23%20%20%20%20%0A%20%20%23%20%3Fterm%20rdfs%3Alabel%20%3Fterm_label%20.%0A%20%20%23%0A%20%20%23%20FILTER%20(str(%3Frelated)%3Dstr(%3Fexact))%0A%20%20%23%20FILTER%20(isIRI(%3Fterm)%20%26%26%20regex(str(%3Fterm)%2C%20%22%5Ehttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_%22))%0A%20%20%23%20%7D%0A%7D%0A&endpoint=https%3A%2F%2Fstars-app.renci.org%2Fubergraph%2Fsparql&requestMethod=POST&tabTitle=Query%201&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table&outputSettings=%7B%22pageSize%22%3A1000%7D).

It seems like there are only five cases that are caused by OMIM itself for the exact/related confusion! The other ones are [mostly from our automated approaches](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aprefix%20oboInOwl%3A%20%3Chttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23%3E%0Aprefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT%20%3Fterm%20%3Fterm_label%20%3Frelated%20%3Fxref1%20%3Fxref2%0AWHERE%20%0A%7B%20%0A%20%20%7B%20%0A%20%20%20%20%3Fterm%20oboInOwl%3AhasRelatedSynonym%20%3Frelated%20%3B%0A%20%20%20%20%20%20rdfs%3Alabel%20%3Fterm_label%20%3B%0A%20%20%20%20%20%20oboInOwl%3AhasExactSynonym%20%3Fexact%20%3B%0A%20%20%20%20%20%20a%20owl%3AClass%20.%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20a%20owl%3AAxiom%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedProperty%20oboInOwl%3AhasExactSynonym%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedTarget%20%3Fexact%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20oboInOwl%3AhasDbXref%20%3Fxref1%20%0A%20%20%20%20%20%20%5D%20.%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20a%20owl%3AAxiom%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedProperty%20oboInOwl%3AhasRelatedSynonym%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20owl%3AannotatedTarget%20%3Frelated%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20oboInOwl%3AhasDbXref%20%3Fxref2%20%0A%20%20%20%20%20%20%5D%20.%0A%20%20%20%20%0A%20%20%20%20FILTER%20(str(%3Frelated)%3Dstr(%3Fexact))%0A%20%20%20%20FILTER%20(isIRI(%3Fterm)%20%26%26%20regex(str(%3Fterm)%2C%20%22%5Ehttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_%22))%0A%20%20%7D%0A%20%20%23UNION%20%0A%20%20%23%20%7B%20%0A%20%20%23%20ASK%20CHRIS%3A%20IS%20THIS%20REDUNDANT%3F%20-%3E%20REDUNDANT..%0A%20%20%23%20%20%3Fx%20owl%3AannotatedProperty%20oboInOwl%3AhasRelatedSynonym%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedTarget%20%3Frelated%20.%0A%20%20%23%20%20%20%20%0A%20%20%23%20%3Fy%20owl%3AannotatedProperty%20oboInOwl%3AhasExactSynonym%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedSource%20%3Fterm%20%3B%0A%20%20%23%20%20%20%20owl%3AannotatedTarget%20%3Fexact%20.%0A%20%20%23%20%20%20%20%0A%20%20%23%20%3Fterm%20rdfs%3Alabel%20%3Fterm_label%20.%0A%20%20%23%0A%20%20%23%20FILTER%20(str(%3Frelated)%3Dstr(%3Fexact))%0A%20%20%23%20FILTER%20(isIRI(%3Fterm)%20%26%26%20regex(str(%3Fterm)%2C%20%22%5Ehttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_%22))%0A%20%20%23%20%7D%0A%7D%0A&endpoint=https%3A%2F%2Fstars-app.renci.org%2Fubergraph%2Fsparql&requestMethod=POST&tabTitle=Query%201&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table&outputSettings=%7B%22pageSize%22%3A1000%7D)..

I don't think we should alter OMIM records after all!

**Comment by matentzn** [comment]
@cmungall for the second query above, I notice a lot of this:

![image](https://user-images.githubusercontent.com/7070631/102125180-2afdbb00-3e41-11eb-9520-b0f259bba117.png)

Can we maybe just fix these quickly those seems to contribute most of about 1000 cases.. The rest could even be done manually!

**Comment by matentzn** [comment]
Sorry this ticket needs to me reconciled with #2386 #1145 #2255 we need a unified strategy..

**Comment by nicolevasilevsky** [comment]
I had a question about the location top pattern:
https://github.com/monarch-initiative/mondo/issues/2156

What does location_top mean?

**Comment by matentzn** [comment]
There are now only 39 cases left @nicolevasilevsky: I would suggest you do them manually
I am saying that, because I can see that some of them (see the first) are better classified as related, and not as exact. Hope you agree :)

- [ ] MONDO:0002967	"dermatophytosis of scalp or beard"	"dermatophytosis of scalp"
- [ ] MONDO:0003816	"articular cartilage disease"	"articular cartilage of joint disease"
- [ ] MONDO:0017173	"non-syndromic male infertility due to sperm motility disorder"	"isolated male infertility due to sperm motility disorder"
- [ ] MONDO:0002404	"liver hemangioma"	"hemangioma of liver"
- [ ] MONDO:0015221	"non-syndromic respiratory or mediastinal malformation"	"isolated respiratory or mediastinal malformation"
- [ ] MONDO:0006921	"Actinomycetales infectious disease"	"actinomycetales infection"
- [ ] MONDO:0015207	"non-syndromic esophageal malformation"	"isolated esophageal malformation"
- [ ] MONDO:0020710	"amnionitis"	"amnionitis"
- [ ] MONDO:0015215	"non-syndromic diaphragmatic or abdominal wall malformation"	"isolated diaphragmatic or abdominal wall malformation"
- [ ] MONDO:0020959	"Mansonella ozzardi infection"	"mansonella ozzardi infection"
- [ ] MONDO:0020679	"conductive hearing loss disorder"	"conductive deafness"
- [ ] MONDO:0006375	"placental hemangioma"	"hemangioma of placenta"
- [ ] MONDO:0021932	"infection by Trypanosoma gambiense"	"gambian trypanosomiasis"
- [ ] MONDO:0015217	"non-syndromic developmental defect of the eye"	"isolated developmental defect of the eye"
- [ ] MONDO:0020779	"cartilage development disorder"	"chondrodystrophy"
- [ ] MONDO:0043969	"nocturnal paroxysmal dystonia"	"sleep-related dystonia"
- [ ] MONDO:0022220	"Parinaud syndrome"	"dorsal midbrain syndrome"
- [ ] MONDO:0008494	"cryohydrocytosis"	"cryohydrocytosis"
- [ ] MONDO:0021348	"neoplasm of testis"	"testis neoplasm"
- [ ] MONDO:0015619	"non-syndromic urogenital tract malformation"	"isolated urogenital tract malformation"
- [ ] MONDO:0020843	"pseudomembranous diphtheritic conjunctivitis"	"pseudomembranous diphtheritic conjunctivitis"
- [ ] MONDO:0020980	"hair nevus"	"nevoid hypertrichosis"
- [ ] MONDO:0015219	"non-syndromic central nervous system malformation"	"isolated central nervous system malformation"
- [ ] MONDO:0021353	"tumor of uterus"	"uterus neoplasm"
- [ ] MONDO:0022220	"Parinaud syndrome"	"parinaud syndrome"
- [ ] MONDO:0022435	"Mauriac syndrome"	"mauriac syndrome"
- [ ] MONDO:0019181	"non-syndromic X-linked intellectual disability"	"X-linked non-syndromic intellectual disability"
- [ ] MONDO:0021941	"infection by Trypanosoma rhodesiense"	"rhodesian trypanosomiasis"
- [ ] MONDO:0015829	"non-syndromic uterovaginal malformation"	"isolated uterovaginal malformation"
- [ ] MONDO:0005722	"croup"	"acute laryngotracheobronchitis"
- [ ] MONDO:0019471	"adult T-cell leukemia/lymphoma"	"adult T-cell leukemia"
- [ ] MONDO:0020683	"acute disease"	"acute disease"
- [ ] MONDO:0003124	"testicular Leydig cell tumor"	"Leydig cell tumor of testis"
- [ ] MONDO:0024633	"hypertensive renal disease"	"hypertensive nephropathy"
- [ ] MONDO:0015211	"non-syndromic intestinal malformation"	"isolated intestinal malformation"
- [ ] MONDO:0023642	"Weber syndrome"	"Weber-Gubler syndrome"
- [ ] MONDO:0010584	"dyskeratosis congenita, X-linked"	"X-linked dyskeratosis congenita"
- [ ] MONDO:0021053	"carotid body paraganglioma"	"paraganglioma of carotid body"
- [ ] MONDO:0015209	"non-syndromic gastroduodenal malformation"	"isolated gastroduodenal malformation"

**Comment by matentzn** [comment]
I started here:
https://github.com/monarch-initiative/mondo/pull/2620

If you find the time, you can just finish the rest. I have also added the hard test, so when its done, the issue should be solved for good.

**Comment by nicolevasilevsky** [comment]
This ticket has two issues on it- the issue in the title is fixed. I'm moving the other issue to a new ticket
