### ISSUE TITLE
Consolidating documentation of MONDO-Orphanet classification

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#184]
_From @siiraa on April 27, 2017 13:3_

There are a few standing questions and the activities of reclassifying hanging ORDO terms that need to be documented. There has been an on-going conversation on the combined effort of this re-classification. https://docs.google.com/document/d/1ePEudnqb4w0yxM0whi5TPJWf54SyaRznj2Qy_mi4f9A/edit?usp=sharing is where all the documentation from all involved parties should go @cmungall @mellybelly @drseb 

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#244_

**Comment by nicolevasilevsky** [comment]
@siiraa - is this still an issue or can I close this?

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky,
@siiraa no longer works in the EFO team, so please direct any question stemming from her past tickets (and any EFO-related question in general) to myself @paolaroncaglia, @zoependlington or @simonjupp and one of us will pick it up, thanks. In this particular case, the issue here might be superseded when we implement future plans for EFO3 and disease integration - we’re working on them already. So I think you may close this ticket. 
Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
Thanks for the update @paolaroncaglia! I'll close this ticket and assign other tickets to you or your team members.
