### ISSUE TITLE
Place OMIM traits into distinct file

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#194]
_From @cmungall on September 16, 2015 2:58_

For original discussion see: https://github.com/monarch-initiative/monarch-app/issues/955

Various IDs such as "Skin/Hair/Eye Pigmentation, Variation In, 9" OMIM:611742 are in the omimexclude file maintained by @sbello - this is good, as these are not diseases.

However, we have some data associated with this OMIM ID, treating it as a trait. We should find a way to include these in a separate trait ontology.

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#53_

**Comment by nicolevasilevsky** [comment]
_From @cmungall on September 16, 2015 3:2_

I'm not even 100% sure how to interpret the omim term

http://www.omim.org/entry/611742

it says "dark/light" hair. Does the omim term represent the trait (attribute) or the phenotype (value)?

**Comment by nicolevasilevsky** [comment]
_From @pnrobinson on September 16, 2015 4:35_

OMIM provides incomplete coverage of a number of traits that have been studied by GWAS. Especially, but not only, eQTL data from model organisms data can probably be mapped to this, but we will need to find a way to ingest data from GWAS Catalog and or GWAS Central and also to disambiguate traits and diseases (neither OMIM nor the GWAS databases reliably distinguish between disease and trait data!). Something to discuss at the upcoming strategy meeting!

**Comment by nicolevasilevsky** [comment]
_From @mellybelly on September 16, 2015 4:42_

Ontology of Biological Attributes !!
Also needed to support clinical measures such as in PhenX.

**Comment by nicolevasilevsky** [comment]
_From @mellybelly on September 16, 2015 4:46_

P.S. we should relate this set back to OMIM, has anyone done that? @sbello?

**Comment by nicolevasilevsky** [comment]
_From @jmcmurry on October 15, 2015 19:42_

This is a blocker for https://github.com/monarch-initiative/monarch-disease-ontology/issues/53

**Comment by pnrobinson** [comment]
We are going to put this into the ``omit-list.txt`` file in the rare-diseases/annotated repo!

**Comment by nicolevasilevsky** [comment]
Great - can we close this ticket?

**Comment by sbello** [comment]
@nicolevasilevsky Yes we have related these back to OMIM but you have to keep in mind that OMIM is not exclusively disease and includes a number of "phenotypes" that are clearly not disease. So, OMIM is not going to change these.
In this case I would agree that the OMIM record reads more like a "trait" as it just talks about variation in skin and eye pigment. I don't see an appropriate term in the VTO but we could easily add something under surface structure morphology trait.
Also note, that since MGI has switched to the DO I've stopped updating of OMIM exclude list. I just don't report this to DO for addition when I come across them.

**Comment by nicolevasilevsky** [comment]
I think this can be closed
