### ISSUE TITLE
[NTR] Rare genetic intellectual disability or genetic intellectual disability

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2042]
Open question:
Should we add a new term Mendelian intellectual disability?

_updated 10/21/21 by NV_

---

**Preferred term label:**
genetic intellectual disability (not sure of standards for word order)

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Intellectual disability with a genetic basis

**XREFS**
ORPHA:183757
* comment*  
ClinVar has received submissions based on ORPHA:183757, and we cannot connect to a MONDO id.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0001071, MONDO:0019117

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
MONDO:0015802 and its siblings ( I don't see that either MONDO:0000509 or MONDO:0000508 is defined as genetic)

**Your nano-attribution (ORCID)**

**Comment by nicolevasilevsky** [comment]
@maglott it looks like this term was obsoleted in Mondo and replaced with
MONDO_0001071 'intellectual disability'

**Comment by nicolevasilevsky** [comment]
It was obsoleted because we wanted to obsolete the rare X terms (see https://github.com/monarch-initiative/mondo/issues/254).

Do you think we need a specific class for genetic intellectual disability? I suspect that @cmungall may say it would be hard to keep the children up to date. Hopefully he can weigh in.

**Comment by maglott** [comment]
I agree this is a policy question:  does MONDO want to make explicit distinctions, by assigning distinct ids and managing trees,  between terms for a disorder, without qualifications,  and the specific subset that is genetic?   I concur with the decision to remove 'rare' from preferred terms, but wonder if there is a case to be made for making a distinction between 'intellectual disability' and 'intellectual disability with a genetic basis'.

**Comment by pnrobinson** [comment]
Might be good to ask Ada.
I do not think that "rare genetic" is good, but "Mendelian ID" might be reasonable. We should also look at the Delta in Mondo, i.e., what entries do we have that are not Mendelian?

**Comment by nicolevasilevsky** [comment]
Per Ada:
add term monogenic intellectual disability

**Comment by nicolevasilevsky** [comment]
See pending PR
I added this new term with the logical axiom 
`'intellectual disability'`
` and ('has modifier' some inherited)`

(this is the same axiom as monogenic obesity)

A lot of children are inferred, where intellectual disability is just a feature of the disease. In my cases, this is because they are classified as a children of 'syndromic ID' (se list [here](https://docs.google.com/spreadsheets/d/1kZT-Nv6UELLaqeyaBi_dSW8Gu9ZFKCXQ0jYI8M1RBwU/edit#gid=0)).

I am wondering if these inferences are correct. Or maybe the logical axiom is too broad?

**Comment by nicolevasilevsky** [comment]
Hi @maglott 
Upon discussion and based on previous discussion (#1758, #1495, #722) we decided that it's not a good idea for us to add a new class called 'monogenic intellectual disability;. It will be too hard for us to properly maintain classes that are monogenic (or polygenic). (If we did add this term, we'd want to add modifiers that would allow for automatic classification, and that would require us to add modifiers to every term that is monogenic (or polygenic) and that would be too difficult to maintain.

I will close this. Thanks @maglott!
