### ISSUE TITLE
[Revise hierarchy] 'ichthyosis (disease)'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2114]
**Mondo term (ID and Label)**
'ichthyosis (disease)'

**Suggested revision and reasons**
Per @pnrobinson: Probably use this article to develop the hierarchy: https://pubmed.ncbi.nlm.nih.gov/20643494/

related to https://github.com/monarch-initiative/mondo/pull/2110

**Comment by maglott** [comment]
I found this issue when trying to review discordancies between MONDO id/MIM number relationships in MONDO and those we have at NCBI.  We have MIM 146700 as a XRef to MONDO:0024304 because of the term match; likely we should have it as an XRef to MONDO:0015947, given that OMIM's records are for heritable disorders.  That said, i don't think MIM 146700 should be an XRef to the AD form, given that https://omim.org/entry/146700 reports MIM 146700  includes both dominant and recessive forms.   Is there any rule to make certain the mode of inheritance cited any resource is valided in its classification?

**Comment by nicolevasilevsky** [comment]
[1-s2.0-S019096220901487X-main.pdf](https://github.com/monarch-initiative/mondo/files/7456595/1-s2.0-S019096220901487X-main.pdf)

**Comment by nicolevasilevsky** [comment]
OMIM:146700 is an equiv xref to MONDO_0007810 'autosomal dominant ichthyosis vulgaris'. @maglott I agree this is incorrect.

I wonder if we should create a new class that is equivalent to [OMIM:146799](https://omim.org/entry/146700).

I will work on this with Sabrina.

**Comment by nicolevasilevsky** [comment]
Here are some notes I took:
https://docs.google.com/document/d/1JL4jPmRg3EeJxGDGBDRTEf3cyRfHqJm-bhHGZ6NnXPY/edit#

This got really messy and confusing, I need to come back to it later.
