### ISSUE TITLE
Add a tag `latest` with the version of the last built

### ISSUE THREAD

**Issue by aholovenko** [monarch-initiative/mondo#2121]
We want to be able to download a specific file from latest build without the need to specify the name of the tag: 
```
https://github.com/monarch-initiative/mondo/releases/download/v2020-10-03/mondo-with-equivalents.owl
```
```
https://github.com/monarch-initiative/mondo/releases/download/latest/mondo-with-equivalents.owl
```
Is it possible to maintain such a tag?

**Comment by balhoff** [comment]
@aholovenko I think what you want is "current" instead of "latest":

`https://github.com/monarch-initiative/mondo/releases/download/current/mondo-with-equivalents.owl`

However I wouldn't rely on this URL, since it could be changed to a different storage solution in the future. There are permanent URLs for accessing Mondo and other OBO ontologies, e.g.:

`http://purl.obolibrary.org/obo/mondo/mondo-with-equivalents.owl`

**Comment by aholovenko** [comment]
@balhoff Thanks! Closing the issue.
