### ISSUE TITLE
[Merge] 'catecholamine-producing tumor'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2199]
**Mondo term (ID and Label)**
MONDO:0019116 'catecholamine-producing tumor'

**Reason for deprecation**
Orphanet obsoleted this and merged it with Orphanet:100091 Adrenal/paraganglial tumor

**Term to be merged with**
MONDO:0015077 'adrenal/paraganglial tumor'

cc @drseb

**Comment by drseb** [comment]
thanks for putting it here

**Comment by galyea-gard** [comment]
Catecholamine-producing tumors may arise in the adrenal medulla (pheochromocytomas) or in extraadrenal chromaffin cells (secreting paragangliomas - paragangliomas (PGLs) are  tumors arising from the paraganglia (neural crest-derived paraxial autonomic ganglia). Does this help?  Thanks!  Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea-gard from what you're saying, it sounds like these two classes should not be merged?

**Comment by galyea-gard** [comment]
Hi!  The  pheochromocytoma-paraganglioma ORPHA:573163 is classified under Adrenal/paraganglial tumors (so, pheochromocytoma and paraganglioma (which Orphanet group together) are subtypes of the Adrenal/paraganglial tumors).  Because they have several common characteristics (they both come from the same type of tissue, (pheo form in the adrenal gland and paraganglioma form outside the adrenal gland), both have same factor risks, same clinical features and similar treatment) it may sense to group the pheochromocytoma and the paraganglioma together.

**Comment by nicolevasilevsky** [comment]
Per Dr. Sioutos the EVS pathologist (NCIt):
 
Tumors that secrete catecholamines are called sympathetic paragangliomas. They are located along sympathetic nerves and include extraadrenal sympathetic paragangliomas and pheochromocytromas. So, if you don’t have the term sympathetic paraganglioma, it is ok to merge the term catecholamine-producing tumor to the wider category adrenal/paraganglial tumor.

**Comment by galyea-gard** [comment]
So you will merge these under "sympathetic paragangliomas"? We don't have this term (we probably won't add it because it is a parent term - we won't also add the wider category adrenal/paraganglial tumor).  Of note, the catecholamine-producing tumors include both the pheochromocytoma and extraadrenal paraganglioma and also the ganglioneuroma.    Adrenal/paraganglial tumors is much broader and it includes several other conditions as wel). This was interesting. Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea-gard 
I think rather than merging it, maybe it is best to just obsolete this term and add annotations to consider sympathetic paraganglioma and MONDO:0015077 'adrenal/paraganglial tumor'.
