### ISSUE TITLE
[Merge] 'Goldenhar syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2358]
**Mondo term (ID and Label)**
'Goldenhar syndrome'

**Reason for deprecation**
@ahamosh and @ana-rath-orphanet - is 'Goldenhar syndrome' the same as MONDO_0015398 'hemifacial microsomia'?

OMIM uses 'hemifacial microsomia' as the primary label and Orphanet obsoleted Orphanet:374 'Goldenhar syndrome'.

Thanks!

**Comment by ahamosh** [comment]
Hi Nicole, yes, Goldenhar syndrome and hemifacial microsomia are the same things.

**Comment by nicolevasilevsky** [comment]
cc @galyea-gard

**Comment by galyea-gard** [comment]
Hi Nicole!  This is one that is in my list for terms to be reviewed.  This is indeed a tough one because the nomenclature is not clear.  OMIM and Orphanet used different names and so does GHR.  Goldenhar syndrome is a birth defect of the first and second branchial arch derivative and so is microfacial microsomia.   I think that this is a good candidate of a term to ask  Orphanet about the nomenclature, asking to clarify if the page that they have for Oculo-auriculo-vertebral spectrum includes Goldenhar syndrome and also the criteria the preferred term because the term craniofacial microsomia is also widely used and includes GS, HM, OAVS and other. Thank you!  Gioconda

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet @Anne-Pariser @Orphanet

**Comment by nicolevasilevsky** [comment]
Emailed Ana on 12/02/20

**Comment by nicolevasilevsky** [comment]
@galyea-gard any objections to following OMIM and merging these terms? It's been over 2 months and I haven't heard back from Orphanet.
thanks!

**Comment by galyea-gard** [comment]
As per my review, and agreeing with Orphanet,  hemifacial microsomia and Goldenhar syndrome are considered variants under  "oculoauriculovertebral spectrum (OAVS)" . I think the confusion is with OMIM.  Classically, the term "Craniofacial microsomia" is the parent term that include HM, GS and other diseases embryologically similar.  It makes the more sense to actually merge GS with OAVS. Thanks!

**Comment by nicolevasilevsky** [comment]
Thanks @galyea-gard. I will do that (I see that is what Orphanet did too).

**Comment by nicolevasilevsky** [comment]
Note to self- To do:
merge:
MONDO:0008112 'Goldenhar syndrome'

with
MONDO:0015397 'oculo-auriculo-vertebral spectrum'

owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0008112 MONDO:0015397 -o -f obo mondo-edit.obo
