### ISSUE TITLE
Review susceptibility terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2373]
Prior to our call with Ada in January 2021, @matentzn could please gather the following info:

1. which classes are tagged with the susceptibility pattern by logical def - _nico to teach nicole yasgui+SPARQL for susceptibility_
2. which classes lexically indicate they should be susceptibility - _nico to teach nicole yasgui+SPARQL for susceptibility_
3. how are we treating susc. phenotypic series (for example, see #2326 MONDO_0024462 'familial cutaneous melanoma') -  _Nicole to do_
4. Note we have a predisposition subset that should be replaced with pattern tags - _lower priority_
5. also check whether susceptibility terms have hpo annotations - _Nicole to do_

**Comment by cmungall** [comment]
@nicolevasilevsky can you fix the yaml first; then we can use dosdp tools

inherited_susceptibility.yaml:

 - migraine example is wrong
 - has incorrect pattern name
 - add more synonym patterns (`%s, susceptibility`, `%s, susceptibility to`)
 - def is wrong

susceptibility_by_gene.yaml

 - def prob needs improved to mention genus
 - add a name/syn pattern `%s susceptibility caused by %s`

**Comment by nicolevasilevsky** [comment]
I believe all of this is done.
