### ISSUE TITLE
Clarification request- Sudden cardiac arrest/death

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2419]
I am wondering about MONDO:0007264, "sudden cardiac arrest."

The cross references map to multiple things: "sudden cardiac death" (SCTID:95281009), "cardiac conduction disorder" or defect NCIT: C78245 & OMIM 115080. 

Should this term be renamed to "sudden cardiac death" to reflect the SNOMED and OMIM names? I think it would also map to UMLS C0085298, based on current cross references in UMLS. 
For reference, there is a separate MSH/UMLS concept for "sudden cardiac arrest" (C1720824). "Sudden suspension of cardiac activity that is usually due to ARRHYTHMIA, in contrast to heart attack (MYOCARDIAL INFARCTION) which occurs due to blockage. The sudden suspension of cardiac activity generally requires RESUSCITATION. ... (MSH)"

 I think there should be a clear distinction between sudden cardiac arrest (potentially reversible by resuscitation) and sudden cardiac death (by HPO, MSH definitions, this is not reversible).

**Comment by nicolevasilevsky** [comment]
Question for Ada:
is the gene associated for a susceptibility?
Should we create a class: Cardiac conduction defect, susceptibility to

**Comment by nicolevasilevsky** [comment]
to do:
need further info, but for now, remove AKAP10 from the Mondo class 'sudden cardiac arrest'

**Comment by nicolevasilevsky** [comment]
> remove AKAP10 from the Mondo class 'sudden cardiac arrest'
this is done

Action item is to look into this further.

**Comment by kanems** [comment]
Hello. MedGen is still awaiting a decision on this ticket. Thanks :-)

**Comment by nicolevasilevsky** [comment]
Hi @kanems thanks for your patience with this. 

I think this class should be split out, as the OMIM record has 'included' entries and we've now decided to split out 'included' entries as separate classes.

I propose the following terms:

[Term]
id: MONDO:NEW
name: sudden cardiac arrest
def: The sudden loss of all heart activity due to an irregular heart rhythm. [https://www.mayoclinic.org/diseases-conditions/sudden-cardiac-arrest/symptoms-causes/syc-20350634]
comment: Change to current cardiac arrthymia parent requested and confirmed as a correct use of is-a by James Ware, cardiac expert. {source="EFO:0004278"}
xref: EFO:0004278 {source="MONDO:equivalentTo"}
xref: MESH:C1720824 {source="MONDO:equivalentTo"}
is_a: MONDO:0007263 {source="https://orcid.org/0000-0001-5208-3432"} ! cardiac rhythm disease
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/2419 xsd:anyURI

[Term]
id: MONDO:0007264
name: sudden cardiac death (_**Note, this is the existing term and I agree with your proposal to relabel it, the existing label does not match the definition**_)
def: "An unexpected natural death from a cardiac cause within a short time period from the onset of symptoms." [NCIT:C50911]
synonym: "sudden cardiac death" EXACT [OMIM:115080]
xref: NCIT:C50911 {source="EFO:0004278", source="MONDO:otherHierarchy"}
xref: OMIM:115080 {source="EFO:0004278", source="MONDO:includedEntryInOMIM"}
xref: MESH:D016757 {source="EFO:0004278"}
xref: SCTID:95281009 {source="EFO:0004278", source="MONDO:equivalentTo"}
xref: UMLS:C0085298 {source="MONDO:notFoundInDiseaseSubset", source="OMIM:115080"}
is_a: MONDO:0007263 {source="EFO:0004278"} ! cardiac rhythm disease
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/4521 xsd:anyURI
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/2419 xsd:anyURI

[Term]
id: MONDO:NEW
name: cardiac conduction defect
xref: OMIM:115080 {source="EFO:0004278", source="MONDO:equivalentTo"}
synonym: "cardiac conduction disorder" BROAD [NCIT:C78245]
synonym: "conduction disorder" BROAD [NCIT:C78245]
synonym: "disorder of cardiac conduction" BROAD [NCIT:C78245]
synonym: "heart conduction disorder" BROAD [NCIT:C78245]
xref: NCIT:C78245 {source="MONDO:mondoIsBroaderThanSource"}
xref: Orphanet:871 {source="MONDO:relatedTo", source="OMIM:115080"}
xref: UMLS:C0264886 {source="MONDO:ncbi_mim2gene_medline", source="MONDO:notFoundInDiseaseSubset", source="OMIM:115080"}
is_a: MONDO:0007263 {source="https://orcid.org/0000-0001-5208-3432"} ! cardiac rhythm disease
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/2419 xsd:anyURI

[Term]
id: MONDO:NEW
name: familial sudden death
xref: OMIM:115080 {source="MONDO:equivalentTo"}
xref: UMLS:C1861884 {source="MONDO:notFoundInDiseaseSubset", source="OMIM:115080"}
is_a: MONDO:0007263 {source="https://orcid.org/0000-0001-5208-3432"} ! cardiac rhythm disease
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/2419 xsd:anyURI

**Comment by nicolevasilevsky** [comment]
Let me know if you agree and I will proceed with this plan.

**Comment by kanems** [comment]
Hi Nicole, looking back over my original post and comments, I think your proposal covers the different facets of the original request (and clarifies the different presentations of rapid onset heart defects that I am aware of). Thanks!

**Comment by nicolevasilevsky** [comment]
@kanems - @sabrinatoro pointed out that sudden cardiac death does not sound like a disease. This term exists in HPO, I suggest that we obsolete it in Mondo and point to HPO

I think we should obsolete 'familial sudden death' as well

Please let me know if you have any objections

**Comment by kanems** [comment]
@nicolevasilevsky MedGen will continue to support the OMIM and HPO terms. Thus, even if these aren't in scope for Mondo, MedGen can and will still represent these terms from our other sources. It should not be a problem for Mondo to obsolete these terms.
