### ISSUE TITLE
[Revise subclass] HP:0002140 Ischemic stroke move within stroke disorder, add definition

### ISSUE THREAD

**Issue by mshadbolt** [monarch-initiative/mondo#2497]
**Mondo term (ID and Label)**
HP:0002140 Ischemic stroke

**Suggested revision and reasons**
The term above appears to have been imported into MONDO from HP but it doesn't appear linked to other MONDO terms in a meaningful way within the hierarchy. I believe it would make sense for it to appear as a subclass of `MONDO:0005098 stroke disorder`
https://en.wikipedia.org/wiki/Stroke#Ischemic

The term also does not have any definition, a potential definition could be:

A stroke where blood supply to the brain is reduced or ceased.

synonyms: ischaemic stroke

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

@paolaroncaglia 

This isn't urgent or related to a particular dataset, just a weird quirk I noticed

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,

> **Mondo term (ID and Label)**
> HP:0002140 Ischemic stroke
> 
> **Suggested revision and reasons**
> The term above appears to have been imported into MONDO from HP but it doesn't appear linked to other MONDO terms in a meaningful way within the hierarchy. I believe it would make sense for it to appear as a subclass of `MONDO:0005098 stroke disorder`
> https://en.wikipedia.org/wiki/Stroke#Ischemic

Mondo imports HP terms and uses them to axiomatise diseases. This is clearer when looking at [the Ontobee entry for 'ischemic stroke'](http://www.ontobee.org/ontology/MONDO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0002140), but for some reason visualization of HP terms in Mondo via OLS is currently impaired. Tagging @matentzn and @nicolevasilevsky to look into this. More in general, it's not straightforfard to fit phenotype terms in disease-specific branches because some phenotypes occur in multiple diseases (e.g. headache, fever...). Mondo often addresses this by specifying in the label that they're referring to a disease (e.g. compare 'dementia' and 'dementia (disease').  

> The term also does not have any definition, a potential definition could be:
> 
> A stroke where blood supply to the brain is reduced or ceased.
> 
> synonyms: ischaemic stroke

This is a valid suggestion and it should be taken to the source ontology (HP). That way, the information content of the definition would percolate to any ontology that imports from (or cross-references) HP. Tagging @pnrobinson please.

Thanks for flagging this Marion, and happy new year!

**Comment by nicolevasilevsky** [comment]
thanks @paolaroncaglia.

What do you mean by the visualization of HP terms in Mondo via OLS is currently impaired - what do you see that looks wrong? I am not sure if this is something we could fix on the Mondo side.

@mshadbolt could you please report the definition suggestion in the HPO tracker, as @paolaroncaglia suggested? thank you!

https://github.com/obophenotype/human-phenotype-ontology

**Comment by mshadbolt** [comment]
created issue here: https://github.com/obophenotype/human-phenotype-ontology/issues/6558

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 

> What do you mean by the visualization of HP terms in Mondo via OLS is currently impaired - what do you see that looks wrong? I am not sure if this is something we could fix on the Mondo side.

No, don't worry, it's not a real issue, rather a choice (on OLS' part) of how to visualize terms. No action item for Mondo. If you're curious, see discussion here: https://github.com/EBISPOT/OLS/issues/311

All the best,
Paola

**Comment by nicolevasilevsky** [comment]
Thanks @paolaroncaglia!

I'll close this ticket.
