### ISSUE TITLE
acute adenoiditis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#2512]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020686

**Bug/Typo/Error description**
The adenoids  are the superior-most of the tonsils. Therefore, tonsillitis and adenoiditis are not exact synoynyms. I am not sure if it is a good idea to subclass according to each tonsil because typical acute bouts of tonsillitis affect multiple tonsils. We should consult the ENT literature for classifications.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @pnrobinson I'll take a look into this asap

**Comment by nicolevasilevsky** [comment]
@pnrobinson I am not sure where the label acute adenoiditis came from, the term is equiv to NCIT:C97142 acute tonsillitis, so I made that the primary label.

I revised the logical def to use tonsillitis instead of adenoiditis, so the inferred parent is now tonsillitis.

The logical def is now:
`tonsillitis
 and ('has modifier' some acute)`

**Comment by nicolevasilevsky** [comment]
I made `acute adenoiditis` a narrow synonym

**Comment by pnrobinson** [comment]
This seems reasonable. Perhaps it would also be good to make acute tonsillitis the 1. label?

**Comment by nicolevasilevsky** [comment]
yes, I did make acute tonsilitis the primary label :)
