### ISSUE TITLE
Creation of a new Nervous system class: Complex Neurodevelopmental Disorder

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#255]
For new term requests, please provide the following information:

## Preferred term label: 

complex neurodevelopmental disorder

## Textual definition

**Either**

An instance of nervous system disease that manifests with multiple associated nervous system phenotypes, including but not limited to intellectual disability, autism, and epilepsy (seizures), that currently have a genetic etiology.

OR

A disorder that involves more than one phenotype associated with the central nervous system, including but not limited to intellectual disability, autism, and seizures (epilepsy). 

## Suggested parent term
genetic nervous system disorder MONDO:0019117

## Suggested subclasses
Under this new class we would like to include 
Rare genetic epilepsy MONDO:0015955
Rare genetic intellectual disability MONDO:0015982
Rare pervasive developmental disorder MONDO:0015680
Prader Willi syndrome MONDO:0008300

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/tbn)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id
https://orcid.org/0000-0002-6733-369X

[Neurodevelopmental ontology ideas_pitch_6-14-18.docx](https://github.com/monarch-initiative/mondo/files/2138638/Neurodevelopmental.ontology.ideas_pitch_6-14-18.docx)

Other biocurators contributing to work  @ErinRiggs

**Comment by nicolevasilevsky** [comment]
@courtneythaxton do you think this class that we created is equivalent to Orphanet: Orphanet:528084 Non-specific syndromic intellectual disability

synonym: Complex neurodevelopmental disorder
def: A rare genetic intellectual disability characterized by the association of intellectual disability with variable other anomalies in the absence of a well-characterized syndrome. Associated abnormalities may include facial dysmorphism, neurological signs and symptoms, behavioral problems, and abnormalities of various other organ systems.

**Comment by nicolevasilevsky** [comment]
Note to self, if yes:
- [ ] add orphanet xref to MONDO:0100038 'complex neurodevelopmental disorder'
- [ ] change xref on MONDO:0060596 'neurodevelopmental disorder with dysmorphic facies and distal limb anomalies' to MONDO:relatedTo
- [ ] remove editor note (address https://github.com/monarch-initiative/mondo/issues/3811)

**Comment by ErinRiggs** [comment]
Hi Nicole.  I see you tagged Courtney in this, but I got the notification since I was previously on this ticket.  No, complex neurodevelopmental disorder is not always equivalent to non-specific syndromic intellectual disability.  We frequently use this term to describe presentations in which not all affected individuals have intellectual disability (e.g. some may have autism, some may have seizures, and some may have varying combinations of all of the above).  We can discuss further next week with the neurodevelopmental experts.  We utilize the terms with "intellectual disability" in the names (syndromic, non-syndromic, etc.) when all reported affected individuals have intellectual disability.

**Comment by nicolevasilevsky** [comment]
Thanks @ErinRiggs, good thing I asked! I will not add the Orphanet xref to this term. I'll close this ticket, thank you. :)
