### ISSUE TITLE
Noonan-like syndrome(s)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2554]
I am looking for clarification/verification for the cross-reference mapping of the concept(s) for "Noonan-like syndrome" 
MONDO:0020297 "noonan-related and noonan syndrome" should have a syn of "noonan-like" based on MESH:C537846 X-ref., however based on ticket #623 https://github.com/monarch-initiative/mondo/issues/623, Noonan-like syndrome is treated as a synonym for CBL-disorder (MONDO:0013308) 

UMLS has two concepts that seem to sort of fit or mix/match with the MESH:C537846 and CBL-disorder concept(s) and I'm not sure if they are distinct or overlapping/redundant:
  - C4016301 "Noonan syndrome-like disorder with juvenile myelomonocytic leukemia[JML]" maps to a phenotype associated OMIM 165360 (CBL protooncogene) and SNOMED_CT ID 783143001
  - C1834120  "NOONAN-LIKE/MULTIPLE GIANT CELL LESION SYNDROME (disorder)" maps to MSH C537846 "Noonan like syndrome" aka "Noonan Syndrome With Pigmented Villonodular Synovitis" aka "Noonan-like-multiple giant cell lesion syndrome" And this term UMLS organizes as a child of Noonan syndrome (C0028326) which, per the NCI definition is related to PTPN11, SOS1, RAF1 or KRAS mutations. 

So, given that different groups seem to use "Noonan-like syndrome" (or minor variations thereof), I am having trouble figuring how the MONDO concepts and UMLS terms map out. 
Is Noonan-like with JML (associated with CBL variants) C4016301 equivalent to CBL-disorder (MONDO:0013308) ?
And then, based on the MSH overlap, C1834120 is equivalent to MONDO:0020297 "noonan-related" ? Even though the MeSH term ends up as a specific sub-type under Noonan in UMLS?

**Comment by nicolevasilevsky** [comment]
> Is Noonan-like with JML (associated with CBL variants) C4016301 equivalent to CBL-disorder (MONDO:0013308) ?

Good question. This term was requested by the ClinGen RASopathy Expert Panel (https://www.clinicalgenome.org/affiliation/40021/), maybe we should ask them? I'll email them and cc you.

**Comment by nicolevasilevsky** [comment]
> And then, based on the MSH overlap, C1834120 is equivalent to MONDO:0020297 "noonan-related" ? Even though the MeSH term ends up as a specific sub-type under Noonan in UMLS?

Looks like UMLS:C1834120 was equiv to MONDO_0023873 Noonan-like/multiple giant cell lesion syndrome, which has been obsoleted, and it recommends considering:
MONDO:0008104 Noonan Syndrome 1
or
MONDO:0012547 Noonan Syndrome 4

It looks like this was obsoleted in OMIM and OMIM moved that term to the terms above (see https://omim.org/entry/163955).

@kanems should C1834120 be an equiv xref for one of those terms?

**Comment by kanems** [comment]
If MONDO no longer has a concept for Noonan-like/multiple giant cell lesion syndrome, then there may not be a good map for the UMLS C1834120 term... UMLS's cross-references on this CUI are the MSH term- C537846 (which MONDO maps to MONDO:0020297). 
From MedGen's perspective, we need to have this CUI/term to support submissions from our users, but it can exist without a MONDO ID if MONDO does not support the concept. 

For MONDO:0008104 Noonan Synd. 1: I think it maps best to Noonan Syndrome 1; UMLS CUI: C4551602 (The NCI and OMIM numbers are shared between the MONDO and UMLS concepts)

C1853120 is the UMLS term for Noonan synd 4, which is already in MONDO based on the OMIM x-ref. (the MSH term is also shared between UMLS and MONDO). 

Thanks for the email to ClinGen, I'll see what we can do without our database to clarify their CBL-related Noonan-like term from the UMLS CUI.

**Comment by nicolevasilevsky** [comment]
Emma from ClinGen will get back to us

**Comment by sabrinatoro** [comment]
Hello @kanems 

I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
Response from Emma:
Our RASopathy EP discussed this question yesterday. Their key reasoning for creating the CBL-related disorder MONDO term instead of using an existing term was that only a small proportion of probands (less than 20-30%) with variants in CBL and Noonan-like syndrome go on to develop JMML. The "Noonan syndrome-like disorder with juvenile myelomonocytic leukemia" reflects the fact that probands with CBL variants were originally ascertained because of the JMML phenotype, so this term is a historical artifact caused by ascertainment bias and is not a helpful diagnosis to give to a patient who does not have JMML. In addition, our group wanted to highlight that CBL variants cause phenotypes such as vascular malformations that are distinct from the Noonan presentation caused by variants in other genes. For example, PTPN11 can also cause Noonan syndrome with JMML, but I believe the UMLS term you are referring to is specific to CBL. For this reason, our experts suggested archiving the term "Noonan syndrome-like disorder with juvenile myelomonocytic leukemia" and replacing it with CBL-related disorder. 

Note - our curation team needs to review this response and will address this asap.

**Comment by nicolevasilevsky** [comment]
Hi @kanems sorry for the delay in revisiting this ticket. Based on your comment above (_For MONDO:0008104 Noonan Synd. 1: I think it maps best to Noonan Syndrome 1; UMLS CUI: C4551602 (The NCI and OMIM numbers are shared between the MONDO and UMLS concepts)_) - sounds like the action item it to:

- [ ] add UMLS:C4551602 as a dbxref (source: MONDO:equivalentTo) to MONDO_0008104 'Noonan syndrome 1'

I'll take care of this now.

Is anything else needed?

**Comment by kanems** [comment]
I think we can close this ticket now, thanks Nicole!
