### ISSUE TITLE
split term: MONDO_0016643 'frontonasal dysplasia'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2578]
**Mondo term (ID and Label)**
MONDO_0016643 'frontonasal dysplasia'

**Suggested revision and reasons**
This term has many children but the text def is:
Frontonasal dysplasia caused by mutations in the ALX3 gene, encoding homeobox protein aristaless-like 3. It is inherited in an autosomal recessive fashion.

I think the def should be revised to the Orphanet def:

A group of rare bone development disorders characterized by an array of abnormalities affecting the eyes, forehead, and nose, and linked to midfacial dysraphia. The clinical picture is highly variable, but the major findings include hypertelorism, a broad nasal root, a large and bifid nasal tip, and widow's peak. Occasionally, abnormalities can include accessory nasal tags, cleft lip, ocular abnormalities (coloboma, cataract, microphthalmia), conductive hearing loss, basal encephalocele and/or agenesis of the corpus callosum. Intellectual deficit is rare and more likely to occur in cases where hypertelorism is severe or where there is extra-cranial involvement.
Orphanet:250

And the NCIT term should be split into a new subclass.

**Comment by sabrinatoro** [comment]
Also: OMIM:136760 = FRONTONASAL DYSPLASIA 1 (mutation in ALX3 gene)

**Comment by sabrinatoro** [comment]
After review, there is already a MONDO term for the 'frontonasal dysplasia' due to ALX3 gene : 'frontorhiny' (MONDO:0007636)

**To do:** 
update 'frontonasal dysplasia' (MONDO:0016643):
- [ ] update definition (use the definition from Orphanet:250)
- [ ] dbxref - NCIT:C129028 should not be "MONDO:equivalent", it should be "MONDO:superClassOf"
- [ ] make synonym 'frontonasal dysplasia 1' (dbxref NCIT:C129028) a "narrow" synonym.

- [ ] Add NCIT:C129028 as "MONDO:equivalentTo" dbxref for 'frontorhiny' (MONDO:0007636)
