### ISSUE TITLE
[Revise subclass] Revise subclasses of peroxisomal disease (MONDO:0019053) (ClinGen request)

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2632]
The ClinGen Peroxisomal disorders expert recommends renaming and reclassification of many Mondo terms in the peroxisomal disease (MONDO:0019053) hierarchy.

This will affect naming of some OMIM terms (cc @ahamosh).

We welcome community feedback on these proposed changes. Please feel free to comment here or on the google doc.

See proposed changes [here (clean version)](https://docs.google.com/document/d/1fL23rNXAfZOqdn1n41ISUgUVtLN-CKRGLGR5V64tAgk/edit)

Nicole's version is [here](https://docs.google.com/document/d/1e_To1QzbxxhWrUI0_ABJtxYP5cVrPRA_LEKaXcc0toM/edit)

cc @cmungall @pnrobinson

**Comment by maglott** [comment]
For my own reference: https://github.com/monarch-initiative/mondo/issues/1490

**Comment by ahamosh** [comment]
Hi All,  We (OMIM) went to the google doc and we are confused because almost everything has a strike through it.  Also, we are concerned about eliminating the distinction between Zellweger (lethal) and less severe.  OMIM tends to divide by severity.  Peter Robinson suggested that that be done for everything.  Finally, I am not sure that clinicians will be able to follow this.  Also what is CADDS?

**Comment by nicolevasilevsky** [comment]
CADDS is:
- contiguous ABCD1 DXS1357E deletion syndrome
- Zellweger-like contiguous gene deletion syndrome

(see [Orphanet:369942](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_369942) and GARD:[12472](https://rarediseases.info.nih.gov/diseases/12472/deafness-dystonia-and-cerebral-hypomyelination))

**Comment by nicolevasilevsky** [comment]
@ahamosh I'm not sure I understand the concern about eliminating the distinction between Zellweger (lethal) and less severe - is that what is happening with these proposed changes?

@Mohan-Shruthi can you help address these concerns?

Would it make sense to have a call @ahamosh and @mohan-shruthi?

**Comment by ahamosh** [comment]
Hi Nicole,
Yes, if PBD #A and PBD#B are consolidated, it eliminates the A group which is lethal Zellweger vs. the B which already aggregates others, but leaves alone the infantile lethal form.  Just making sure that everyone is on board with that.
Thanks,
Ada

Ada Hamosh, MD, MPH
Dr. Frank V. Sutland Professor
McKusick-Nathans
Department of Genetic Medicine (DGM)
Clinical Director, DGM
Scientific Director, OMIM
Johns Hopkins University
Blalock 1007
600 N. Wolfe St
Baltimore, MD 21287-4922
Phone:  410-614-3313
Fax: 410-367-3231 (Please Note new FAX number)
ahamosh@jhmi.edu

Assistant:  Heather Dozier
phone:  410-955-6641
e-mail:  hdozier1@jhmi.edu

________________________________

**Comment by Mohan-Shruthi** [comment]
@nicolevasilevsky @ahamosh 

Hi Nicole and Ada, 

Apologies for the delay in response from our group!  

We are outlining the rationale for lumping all the entities under the "PEX# gene defect": (1) the disease entity is a spectrum, with overlap among the phenotypes. However, we acknowledge that the severe form is clinically recognizable; (2) the nomenclature currently used with A and B subtypes are confusing since it does not correspond to the gene, but the complementation group to which it belonged at the time of discovery; (3) While the severe cases are clinically distinguishable, the intermediate and milder phenotypes are not. But, several milder phenotypes are being further classified into distinct disease entities, which adds to the confusion and does not help the community. 
Upon reconsideration, we think that in order to preserve the distinction between severe vs milder phenotypes, perhaps we can modify the proposed classification as in the example below: 
----peroxisome biogenesis disorder 
--------Zellweger spectrum disorders 
------------peroxisome biogenesis disorder due to PEX1 defect (severe)
------------peroxisome biogenesis disorder due to PEX1 defect (intermediate/mild)

Please let us know your thoughts.

Thanks,
Shruthi

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi this is fine with me, I'd like to hear @ahamosh's thoughts before we implement these changes.

**Comment by ahamosh** [comment]
I have a couple more questions and suggestions:  I am confused as to why you want to put peroxisome biogenesis disorder under Zellweger spectrum.  The severe are Zellweger and the intermediate/mild aren't. One other point, don't call the non-infantile lethal mild.  No one with a disease thinks its mild. Call it attenuated or distinguish by age of onset. Finally, are you really going to get rid of the RCDPs?  Aren't they phenotypically distinct?    Maybe we should have a call...

**Comment by Mohan-Shruthi** [comment]
The term "Zellweger spectrum disorder" is being used in the community to refer to all severity classes, with the "severe", "intermediate" and "mild" being used to refer to the clinical phenotypes. This was adopted due to the overlap in the clinical spectrum (although we agree one could recognize the severe patients amongst this group due to their extensive polymicrogyria). The fact that each child may not fit a specific category, the disease changes over time, and new phenotypes are being recognized. PMID: 26750748 & 26627182 provide the guidelines for this classification. 

We can use the terms "intermediate/mild" or "intermediated/attenuated"; this may be difficult for the community to distinguish. What about "non-classic" and "classic/severe"?

We have updated the Google doc with RCDP and adult Refsum disease as a separate classes under PBDs:
--------rhizomelic chondrodysplasia punctata
------------peroxisome biogenesis disorder due to PEX7 defect (added as MONDO_0100272)
----------------rhizomelic chondrodysplasia punctata type 1 (MONDO:0008972)
------------peroxisome biogenesis disorder due to PEX5 defect in the PEX7-binding domain (added as MONDO:0100265)
----------------rhizomelic chondrodysplasia punctata type 5 (MONDO:0014743)
--------adult refsum disease (MONDO:0009958)
------------peroxisome biogenesis disorder due to PEX7 defect (added as MONDO_0100272)

If we need to discuss this further, we can set up a call.

**Comment by nicolevasilevsky** [comment]
This is what is proposed above:
![image](https://user-images.githubusercontent.com/6722114/112537958-8b6b9500-8d6c-11eb-85d7-2d7d75276956.png)

and we'd add the subClassOf axiom to the classic form:
'has modifier' some Severe

and the subClassOf axiom to the non-classic form:
'has modifier' some Moderate

**Comment by nicolevasilevsky** [comment]
The current edits are viewable here:
https://ols.monarchinitiative.org/ontologies/mondo_issue2632/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019234&viewMode=All&siblings=false

**Comment by nicolevasilevsky** [comment]
To do:
- [ ] ClinGen would like the Heimler syndrome removed, as the two Heimler syndrome subtypes have been incorporated under peroxisome biogenesis disorder (PBD) due PEX1 defect and PBD due to PEX6 defect.

- [ ] Regarding the neonatal adrenoleukodystrophy, this is only due to ABCD1 deficiency, which we now have under single enzyme/protein defects. You are right and our experts are aligned that the PBD subtypes should not be listed under neonatal adrenoleukodystrophy, but only under the Zellweger spectrum disorders. But I will double check with the group that it can be removed all together from here.

**Comment by nicolevasilevsky** [comment]
From Shruthi's notes in the google doc:

D-glyceric aciduria will potentially be a child of primary hyperoxaluria type 2. It is not a child of AGXT deficiency and can be removed from under disorder of glyoxylate metabolism within the peroxisomal disease tree.
