### ISSUE TITLE
[Merge] MONDO:0006772 'glycogen storage disease VIII'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2648]
**Mondo term (ID and Label)**
MONDO:0006772 'glycogen storage disease VIII'

**Reason for deprecation**
Obsoleted in OMIM

**Suggested term to be merged with**
MONDO:0010598 'glycogen storage disease IXa'
https://www.omim.org/entry/306000

This term still exists in DO, MeSH and GARD:

https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_2751
https://rarediseases.info.nih.gov/diseases/6538/glycogen-storage-disease-8
https://meshb.nlm.nih.gov/record/ui?ui=D006015

cc @galyea-gard, @ahamosh 

related to #2128

**Comment by galyea-gard** [comment]
Hi!  The GSD 8 was added a while ago and the term is not in use anymore.  We will fix this when our review process is over. I would suggest to use the Orphanet term "Glycogen storage disease due to liver phosphorylase kinase deficiency" because it is more descriptive and all the correspondent synonyms including the term from OMIM. Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
Thanks @galyea-gard!

**Comment by kanems** [comment]
I agree with this merge.
