### ISSUE TITLE
[Revise subclass] SIDS ! MONDO:0010086  subclass of Mendelian disorder

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#2759]
**Mondo term (ID and Label)**
MONDO:0010086, sudden infant death syndrome

**Suggested revision and reasons**
https://www.ncbi.nlm.nih.gov/books/NBK513378/

"Evidence suggests likely genomic complexity and a degree of overlap amongst sudden cardiac death, SIDS, and SUDEP. The advent of next-generation sequencing will improve our understanding of the genetics of SIDS, and will result in more answers for families with a family history of sudden or unexplained deaths. However, a Mendelian approach is not likely to explain all cases."

**Comment by nicolevasilevsky** [comment]
I'm not sure if I can add a superclass assertion unless SIDS was always Mendelian.

cc @pnrobinson

**Comment by kshefchek** [comment]
To clarify, I was wondering if the subclass of assertion should be removed

**Comment by nicolevasilevsky** [comment]
Yes, I agree with you that it should. thanks for clarifying.

**Comment by pnrobinson** [comment]
In general, SIDS is not a Mendelian disease. This entry (https://omim.org/entry/272120) implies that there are genetic variants that confer increased susceptibility to SIDS in some cases, and thatbut it does not imply that all or even most cases of SIDS are Mendelian. 
The entry states that some Mendelian arrhythmia genes can cause long QT (and other analogous examples), which can cause a potentially deadly arrhtyhmia and lead to SIDS. In this case, I would say that the infant had the disease long QT with the phenotypic feature of sudden infant death (the latter is an HPO term). The disease SID syndrome implies that the cause is unknown. 

@ahamosh thoughts?

**Comment by ahamosh** [comment]
SIDS is in OMIM because of the way people use OMIM.  I agree with Peter.  SIDS should not be in Mondo as a Mendelian phenotype.

**Comment by nicolevasilevsky** [comment]
I excluded the superclass of Mendelian disease, but I wonder if we should create a subclass of SIDS that is equiv to the OMIM term, and has the syn 'sudden infant death syndrome, susceptibility to' and conforms to the susceptibility pattern?

https://omim.org/entry/272120

Right now, the current class has the subclass axiom
'disease has basis in dysfunction of' some SCN5A

which is probably not true in every case.

**Comment by ahamosh** [comment]
There are lots of genes to which this can be linked and mostly to no genes at all.  Can we talk?  This is too complicated to type out.

**Comment by nicolevasilevsky** [comment]
Absolutely! Are you by chance free right now?
Or we have our Mondo call tomorrow at 12pm ET

**Comment by ahamosh** [comment]
Yes, happy to talk now: 410-961-0065
Ada

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolevasilevsky** [comment]
Per discussion with Ada, the recommendation is to obsolete this term, as it is not really a disease, and it is really an outcome of a variety of potential reasons, some which could be genetic, or environmental or maybe entirely unknown.
