### ISSUE TITLE
 MONDO:0019313 "hereditary lymphedema" Clean up request

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2768]
**Mondo term (ID and Label):**
hereditary lymphedema ;  MONDO:0019313

I started off questioning some X-refs and it seems like this term and its children need a bit of attention overall... please see comments.

**Xref that should be fixed (ID and label):**
OMIMPS:153100 Which OMIM states is "Phenotypic Series - PS153100; _Lymphatic malformation_ - PS153100" does not match the concept of generic "hereditary lymphedema"

Also not sure if Orphanet:79452 belongs here, either. As it is called "Milroy disease" (syns: Hereditary lymphedema type I; Nonne-Milroy lymphedema) 
and SCTID: 399889006 should go wherever this Orpha term goes (it is for "hereditary lymphedema type I")

**Other comments:**
Suggestions to clean up this term:
I.  Create a child term for Milroy disease (with the Orpha 79452 and SNOMED refs above)  with Syn "lymphatic malformation" and the OMIM [PS153100](https://www.omim.org/phenotypicSeries/PS153100).
  --> Children for this new term include the various specific MIM numbers referenced by Orpha79452  and the PS153100 
     -153100 (Lymphatic malformation 1)
     - 611944 (Lymphatic malformation 2)
     - 613480 (Lymphatic malform. 3)
     - 615907 (Lymphatic malform. 4)
     - 153200 (Lymphatic malform. 5)
     - 616843 (Lymphatic malform. 6)
     - 617300 (Lymphatic malform. 7)
     - 618773 (Lymphatic malform. 8 (Although OMIM has a "?" here in some places, but not others)
Ia .__Note: many of these above OMIM-linked terms need to be updated in MONDO, as the MONDO-assigned names are now "formerly" names from OMIM. This includes hereditary lymphedema types 1A, 1B, 1C, 1D, Meige disease...__

II. Should we maintain MONDO:0009535 "lymphedema, congenital recessive?"  The MIM # referenced by this term has been split (247440 MOVED TO 153100 AND 616843).  The MeSH and UMLS x-refs are still active terms, but at a minimum the OMIM Xref this term should be deleted.  

@ana-rath-orphanet @ahamosh : Do you think these suggestions accurately reflect the terms from OrphaNet and OMIM? Please advise if I am not understanding these properly.

**Comment by nicolevasilevsky** [comment]
From Joanna (OMIM):

It is a bit complicated.  The original lymphedema entries were
numbered 1, 2, 3 and were designated for the age of onset.  When
families were described with mutations, there were variable ages of
onset.  Then there were clinical entities described that had lymphatic
dysplasia (and lymphedema).  More recent families studied had
lymphoscintigraphy which highlighted malformations/anomalies of the
lymph system.  Authors would then call those lymphatic dysplasia or
some such terms.  We corralled them all under a lymphatic malformation
series PS153100.  The description here is "Primary lymphedema is
caused by anatomic or functional defects in the lymphatic system,
resulting in chronic swelling of body parts."  We used this reference
in some of our decision process:
Liu, N. F.; Yan, Z. X.; Wu, X. F. : Classification of
lymphatic-system malformations in primary lymphoedema based on MR
lymphangiography. Europ. J. Vasc. Endovasc. Surg. 44: 345-349, 2012.

Some people in lymphedema families had lymphatic malformations without
lymphedema.  This is why we chose the LMPHM* umbrella.

See the NOMENCLATURE heading in 153100 for some explanation.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@kanems I think ORPHA:79452 Milroy disease is equivalent to https://omim.org/entry/153100 LYMPHATIC MALFORMATION 1; LMPHM1 (MONDO_0007919 'lymphedema, hereditary, 1A'). I will move this xref.

I'll clean up these labels too to match OMIM.

 I agree 'lymphedema, congenital recessive' should be obsoleted and I created a separate ticket.
