### ISSUE TITLE
Obsolete parent terms

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#278]
Hello! During our build of our EFO 3 beta, we have come across a couple of terms that are subclasses of obsolete terms in MONDO:

- MONDO:0006280 is a subclass of an obsolete term MONDO:0003221
- MONDO:0016612 is a subclass of obsolete term MONDO:0000559
- MONDO:0016982 is a subclass of obsolete term MONDO:0005329

**Comment by cmungall** [comment]
oh dear, sorry, I thought we were checking these. My recollection is that we had our own SPARQL check on release for this, while we were waiting for this functionality in report - it seems not.

But in any case, this is now bundled into the report option in the latest robot, we'll configure the workflow so report is always executed which should prevent this in future.

For now, these have all been fixed in the edit version and will be reflected in next release

**Comment by paolaroncaglia** [comment]
@cmungall @nicolevasilevsky 
FYI, I see that all 3 errors reported by Zoe are fixed now, so this ticket could be closed (I won't do that myself now as I'm not sure what your preferred policy/procedure is re closing tickets).
