### ISSUE TITLE
MONDO:0012324, 14q22q23 microdeletion syndrome

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2847]
**Mondo term (ID and Label):**
MONDO:0012324, 14q22q23 microdeletion syndrome

**Xref that should be fixed (ID and label):**
OMIM:609640 (Orphanet:264200) ??
The OMIM entry is for FRIAS SYNDROME
Alternative titles; symbols : CHROMOSOME 14q22 DELETION SYNDROME
GROWTH DEFICIENCY, FACIAL ANOMALIES, AND BRACHYDACTYLY
Cytogenetic location: _14q22.1-q22.3_ 

 It seems like maybe this should not be equivalent to the 14q22q23 microdeletion syndrome?? The SNOMED definition for 14q22q23 microdeletion specifically mentions smaller 14q22 microdeletions may have variable expression.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
UMLS concept for the OMIM term: Frias syndrome, UMLS CUI: C1864825, maps MESH C535639
14q22q23 microdeletion syndrome,  UMLS CUI: C4749903 maps SNOMED ID 771439009

If these are indeed equivalent concepts, can we add the MIM preferred name to the OMIM entry? Someone should probably also alert UMLS to merge their two CUIs.

cc @ahamosh , @ana-rath-orphanet  Thank you for looking into this and providing any additional insight!

**Comment by nicolevasilevsky** [comment]
@kanems I'm not sure which is correct. Seems like GARD groups these together too: https://rarediseases.info.nih.gov/diseases/2384/frias-syndrome

We tend to follow OMIM, Orphanet and GARD as our primary sources, so I think since they all xref each other and combine these, we'll keep them combined.

I'll use 'Frias syndrome' as the primary label.

Let me know if that doesn't adequately address this ticket.

Thanks!
