### ISSUE TITLE
Clarification Inquiry: Relationship Between MONDO and HPO (Human Phenotype Ontology)

### ISSUE THREAD

**Issue by eloisevalasek** [monarch-initiative/mondo#3086]
Hello,

When reviewing terms in MONDO, I realized HPO (Human Phenotype Ontology) is not listed as a cross-referenced ontology. I would think MONDO cross-references with HPO since MONDO is developed with HPO (according to MONDO's website). I would appreciate clarification on whether there is any link between MONDO and HPO, and if so, what's the connection?

Thank you

**Comment by eloisevalasek** [comment]
Interesting, thank you. So, how should one go about cross-referencing between MONDO and HPO? For example, can SNOMED be used?

**Comment by matentzn** [comment]
I am probably not the authority on the matter, but I would cautiously say that this depends on the use case. Cross-reference, all by itself, does not mean much. If you are looking for the "kinda equal HP term" I would probably caution against it because in our world view, a phenotype is not the same as a disease. If you are looking for cross references in the sense of "phenotype that is somehow related with this disease" I would go for the annotations. If you absolutely want to bridge the "kind of equal" terms, then I would look in EBIs OxO: https://www.ebi.ac.uk/spot/oxo/

Can I ask, what is your use case? Maybe if I knew, I could think of something else as well.

**Comment by nicolevasilevsky** [comment]
Can this be closed? Thanks!
