### ISSUE TITLE
nonepidermolytic palmoplantar keratoderma [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3108]
**Mondo term (ID and Label)**
MONDO:0006588  nonepidermolytic palmoplantar keratoderma

**Suggested revision and reasons**
I am having a hard time making heads or tails of this class... but something seems off when we've got nonepidermolytic _focal_ types of a disorder as children/(great-)grandchildren of a _diffuse_ type of the same disorder. (See screenshot below)
I think also some of the MIM numbers may be mismatched in here as cross-references, but again, I am so confused at this point. I don't want to make suggestions that are incorrect. 

As OMIM describes these disorders, they can be divided into Diffuse, focal or punctate types AND further divided into epidermolytic or non-epidermolytic types.  I am attaching a doc with my notes on where I think the MIM numbers might be organized in a hierarchy, but I cannot tell which Mondo concepts or OrphaNet terms might be direct matches to these MIM disorders. And this is ONLY considering the genetic, isolated forms of the disorder, not ones where PPK is one feature of a broader syndrome that are elsewhere in the Mondo tree that includes (NEPPK) MONDO:0006588; I think it is very useful to have this "Isolated" PPK term, but maybe we need to make it less specific to "diffuse" PPK so we can reasonably have the focal, punctate and striate forms all grouped together meaningfully.
[PalmoplantarKeratoderma_Notes.docx](https://github.com/monarch-initiative/mondo/files/6541771/PalmoplantarKeratoderma_Notes.docx)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

![image](https://user-images.githubusercontent.com/71083858/119552814-f2a3c680-bd68-11eb-8533-1481e8bc8343.png)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@kanems thanks for the proposed hierarchy. I couldn't implement that as you outline because there were a lot of OMIM classes that were children of other OMIM classes, which wouldn't work because the OMIM classes had specific gene mutations (and the children inherit all the properties of the parent - so if the disease1 has a mutation in geneX, the child would also have a mutation in geneX , which is not the case with these classes).

To address this issue, I did the following revisions:

- exclude subclass ('nonepidermolytic palmoplantar keratoderma') from 'isolated focal non-epidermolytic palmoplantar keratoderma'
- exclude subclass ('nonepidermolytic palmoplantar keratoderma') from 'autosomal dominant focal non-epidermolytic palmoplantar keratoderma with plantar blistering'
- reclassified 'palmoplantar keratoderma, nonepidermolytic, focal 1' - now a subclass of 'isolated focal palmoplantar keratoderma'
- reclassified 'palmoplantar keratoderma, nonepidermolytic, focal or diffuse' as a child of 'hereditary palmoplantar keratoderma'
- reclassified 'palmoplantar keratoderma i, striate, focal, or diffuse' as a child of 'hereditary palmoplantar keratoderma'
