### ISSUE TITLE
disorder of GPI anchor biosynthesis (MONDO:0024321)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3116]
Previously these 3 genes were annotated to the same term,
can't load annotation for SPBC1604.15 (gpi16), line 965 - MONDO:0018641 not found in database
can't load annotation for SPBC3D6.07 (gpi3), line 1172 - MONDO:0018641 not found in database
can't load annotation for SPCC11E10.02c (gpi8), line 1300 - MONDO:0018641 not found in database

This seems to be a phenotype and was obsoleted. However, I would still expect all 3 genes to slim together, at least by some axis. However,

https://www.pombase.org/slim:pombe_mondo_slim/from/id/27487cd4-cbff-43b6-99ad-4b78b8472ce5

These should all be
disorder of GPI anchor biosynthesis (MONDO:0024321)
synonym Glycosylphosphatidylinositol Biosynthesis Defect

**Comment by ValWood** [comment]
These, being

MONDO:0030037
neurodevelopmental disorder with hypotonia and cerebellar atrophy, with or without seizures

MONDO:0010438 | paroxysmal nocturnal hemoglobinuria 1
MONDO:0010466 | multiple congenital anomalies-hypotonia-seizures syndrome 2
MONDO:0014166 | paroxysmal nocturnal hemoglobinuria 2
MONDO:0014165 | multiple congenital anomalies-hypotonia-seizures syndrome 3

**Comment by sabrinatoro** [comment]
Hello @ValWood 
I recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by ValWood** [comment]
Thank you  @sabrinatoro ;)

This particular one would be nice, because the GPI stuff might make a nice example when I talk about PomBase interacting with external resources in a departmental talk in the next few months. However, none of my tickets are super-urgent.

But ping me if you have any questions on my shoddy tickets!

Good to work with you again!

**Comment by sabrinatoro** [comment]
@ValWood 
I looked at the ontology. It looks like MONDO:0018641 was obsoleted because this term referred to the "acquired" version of the disease. Therefore this term was replaced by 'acquired paroxysmal nocturnal hemoglobinuria' (MONDO:0100245), and a new grouping term was created: "paroxysmal nocturnal hemoglobinuria" (MONDO:0100244)
Therefore the ontology looks like this:
<img width="362" alt="Screen Shot 2021-07-13 at 3 20 37 PM" src="https://user-images.githubusercontent.com/12737987/125534188-f8c7f39c-844d-4461-9153-bcd53e0856f0.png">

Looking at the inferred view, these terms are grouped under 'disorder of GPI anchor biosynthesis' (MONDO:0024321)
<img width="630" alt="Screen Shot 2021-07-13 at 3 31 55 PM" src="https://user-images.githubusercontent.com/12737987/125534304-abf4a870-1c05-4417-b304-1c8a11701c8c.png">

I see that the human genes are associated with the different types of 'disorder of GPI anchor biosynthesis' . 
Therefore I would expect these genes to be associated with this term (or a children term). 
I do not know when MONDO:0018641 was split ; is it possible that the source where you get the human gene-Mondo association hasn't been updated yet? 

Please let me know if this is answering your original issue, or if there is something else we should investigate in Mondo. 
Thanks!

**Comment by ValWood** [comment]
Hi Sabrina,

2/3 are fixed. This one is still outstanding:
Pig-K (Gpi8)  neurodevelopmental disorder with hypotonia and cerebellar atrophy, with or without seizures (Glycosylphosphatidylinositol Biosynthesis Defect 22, )

Should be is_a disorder of GPI anchor biosynthesis (MONDO:0024321)

and also these are missing parent disorder of GPI anchor biosynthesis (MONDO:0024321)
pig-B developmental and epileptic encephalopathy, 80
Pig-P developmental and epileptic encephalopathy, 55
Pig-Q developmental and epileptic encephalopathy, 77 (MONDO:0032808)


and this one
GPAA1 glycosylphosphatidylinositol biosynthesis defect 15 MONDO:0060627
congenital muscular dystrophy with intellectual disability and severe epilepsy
is_  congenital disorder of glycosylation type I
But this is missing "disorder of glycosylation (MONDO:0024322)" parent


cheers!

Val

**Comment by sabrinatoro** [comment]
@ValWood 
Do you think these terms should be children of 'GPI anchor biosynthesis' (MONDO:0024321) based on the affected gene's BP annotation? i.e. since pig-B/P/Q are associated to these diseases, these diseases should have the parent 'GPI anchor biosynthesis'.

(similar question for your other example)

**Comment by ValWood** [comment]
1.
neurodevelopmental disorder with hypotonia and cerebellar atrophy, with or without seizures (Glycosylphosphatidylinositol Biosynthesis Defect 22, )

should be is_a
disorder of GPI anchor biosynthesis (MONDO:0024321)

(in fact, the synonym is Glycosylphosphatidylinositol Biosynthesis Defect 22!)

**Comment by ValWood** [comment]
2. I think these and also these are missing parent disorder of GPI anchor biosynthesis (MONDO:0024321)

pig-B developmental and epileptic encephalopathy, 80
Pig-P developmental and epileptic encephalopathy, 55
Pig-Q developmental and epileptic encephalopathy, 77 (MONDO:0032808)

This is because  GPI anchor biosynthesis is a linear pathway and doesn't do anything except make the GPI anchor, so logically all disorders resulting from errors in the see genes must be 

disorder of GPI anchor biosynthesis (MONDO:0024321)?

**Comment by ValWood** [comment]
3. GPAA1 glycosylphosphatidylinositol biosynthesis defect 15 MONDO:0060627
congenital muscular dystrophy with intellectual disability and severe epilepsy
is_ congenital disorder of glycosylation type I

But this is missing  the parent "disorder of glycosylation (MONDO:0024322)" parent

logically  
disorder of glycosylation type I
seems that it must be a  "disorder of glycosylation"

**Comment by ValWood** [comment]
Note also that these are all single gene disorders.

Does that help?

**Comment by sabrinatoro** [comment]
Yes, thank you.
I will need to talk with @nicolevasilevsky to make sure that add the correct references in the ontology.

**Comment by sabrinatoro** [comment]
About the last point: 
congenital muscular dystrophy with intellectual disability and severe epilepsy (MONDO:0014023)
     is_ congenital disorder of glycosylation type I (MONDO:0005500)
          is_ congenital disorder of glycosylation-
               is_ disorder of glycosylation (MONDO:0024322)

Therefore MONDO:0014023 should have the inferred parent 'disorder of glycosylation' shouldn't it? 
would it be displayed though? (how high in the hierarchy does the reasoner go ?)
@nicolevasilevsky

**Comment by ValWood** [comment]
Actually @sabrinatoro  I _am_ picking up that inference for MONDO:0014023, so ignore that one.
v
