### ISSUE TITLE
neurofibromatosis type 1 MONDO v MONARCH

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3125]
http://purl.obolibrary.org/obo/MONDO_0018975
neurofibromatosis type 1

http://purl.obolibrary.org/obo/MONDO_0008078
neurofibromatosis, familial spinal

https://monarchinitiative.org/disease/MONDO:0008078
neurofibromatosis, familial spinal MONDO:0008078 (**Redirected from MONDO:0018975**) 

I don't understand why MONDO:0018975 is redirected to the the child term MONDO:0008078 in Monarch, what have they been merged? is this correct/what you would expect to see?

**Comment by matentzn** [comment]
Thank you @lcdaugherty 

From a quick look it seems this is not a problem with Mondo, but with Monarch - I have asked the Monarch UI team (@monicacecilia, @kshefchek) to take a look.

**Comment by lcdaugherty** [comment]
Thank you @matentzn - I knew it wasn't a MONDO thing but was confident you could solve it bu knowing the right people! :)

**Comment by kshefchek** [comment]
It looks like there are some incorrect equivalences in http://purl.obolibrary.org/obo/mondo/releases/2021-03-03/mondo.owl

http://purl.obolibrary.org/obo/DOID_0111253 is an exact match to MONDO:0018208, and MONDO:0008078, and MONDO:0018975

looks like this has since been fixed so this should be fixed for the next monarch data load

**Comment by lcdaugherty** [comment]
@kshefchek great thank you!

**Comment by nicolevasilevsky** [comment]
thanks all, I will close this
