### ISSUE TITLE
COVID definitions are inconsistent

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3133]
![image](https://user-images.githubusercontent.com/4943420/120895596-b6375c80-c5eb-11eb-965e-c17ac026d824.png)

Here, MICS-C is a type of COVID but MICS-A is a sequella.

Multisystem inflammatory syndrome in children (MIS-C) is a rare but severe condition that has been reported approximately 2–4 weeks after the onset of COVID-19 in children and adolescents.
https://www.cdc.gov/mmwr/volumes/69/wr/mm6932e2.htm

**Comment by lcdaugherty** [comment]
@nicolevasilevsky
MONDO:0100096 COVID-19 obsoleted exactmatch MeSH ID C000657245 
#2766

**Comment by nicolevasilevsky** [comment]
thanks @lcdaugherty!

@sabrinatoro we can work on this together.

**Comment by nicolevasilevsky** [comment]
@cmungall 
'COVID-19–associated multisystem inflammatory syndrome in children' is inferred to be a child of COVID-19 because of the subclassOf axiom:
`'disease has infectious agent' some 'Severe acute respiratory syndrome coronavirus 2'`

![image](https://user-images.githubusercontent.com/6722114/122846552-ef91ec80-d2ba-11eb-8ff7-ead0188e2cf5.png)

should we remove this subclassOf axiom?

**Comment by nicolevasilevsky** [comment]
@sabrinatoro and @pnrobinson Chris and I are working on revising the infectious disease modeling, and this will be resolved once that is done.

See PR https://github.com/monarch-initiative/mondo/pull/3118

![image](https://user-images.githubusercontent.com/6722114/122846975-cfaef880-d2bb-11eb-833c-f9a90984f06f.png)

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] add axiom to 'COVID-19–associated multisystem inflammatory syndrome in adults' (but after PR #3118 is merged.

**Comment by nicolevasilevsky** [comment]
I think this has been resolved, closing
