### ISSUE TITLE
[NTR] restrictive pulmonary disease

### ISSUE THREAD

**Issue by Vineyardintern** [monarch-initiative/mondo#3165]
**Preferred term label:**
restrictive pulmonary disease

**Synonyms**
restrictive lung disease 
NCIT:C91762 (exact synonym)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Decreased lung volume and inadequate ventilation due to parenchymal lung disorders (e.g., interstitial pulmonary fibrosis) or extrapulmonary disorders (e.g., scoliosis). Patients present with shortness of breath and cough. NCIT:C91762

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
lung disease MONDO:0005275

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @Vineyardintern 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by kallia-p** [comment]
@nicolevasilevsky 

I added the NCIT term as definition dbxref, as an an exact synonym and also as a dbxref
In terms of synonyms and dbxrefs there are a few more to add please see below and the diff and let me know if this is the correct way to do it

- NCIT:C91762
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C91762
Added NCIT:C91762 to the definition as a dbxref, to the exact synonym term as a dbxref and also as a separate annotation dbxref with source MONDO:equivalentTo

- In the OLS link above there is an NCIT dbxref to UMLS:C0085581. 
Added UMLS:C0085581 as an annotation dbxref with source MONDO:equivalentTo. I was a bit uncertain if in this instance I should also add source NCIT:C91762 but I did because that's where I found the cross reference to UMLS. 

- SNOMED SCTID:36485005 
https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F36485005&viewMode=All&siblings=false
Added SCTID:36485005 to the exact synonym term as a dbxref and also as a separate annotation dbxref with source MONDO:equivalentTo

- In OLS the SNOMED term above has a dbxref to ICD10CM:J98.4 Other disorders of lung. 
https://www.icd10data.com/ICD10CM/Codes/J00-J99/J96-J99/J98-/J98.4#:~:text=2021%20ICD%2D10%2DCM%20Diagnosis,4%3A%20Other%20disorders%20of%20lung
Restrictive lung disease is shown under Approximate Synonyms
I am not really sure how to represent this given that it is not an exact synonym but it falls under an ICD grouping term that contains this disease. For now I 've added ICD10CM:J98.4 as a separate annotation dbxref with source SCTID:36485005

**Comment by kallia-p** [comment]
@nicolevasilevsky @matentzn 
The PR failed QC https://github.com/monarch-initiative/mondo/pull/3721/checks?check_run_id=3732031973
