### ISSUE TITLE
DNA repair defect other than combined T-cell and B-cell immunodeficiencies [Obsolete]

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3191]
**Mondo term (ID and Label)**
DNA repair defect other than combined T-cell and B-cell immunodeficiencies

**Reason for deprecation**
This is a strange term. If it is required the descendants are very incomplete because there are many DNA repair defects that do not fit this classification (I can provide examples if required)

**Comment by nicolevasilevsky** [comment]
Thanks @ValWood. We'll look into this, we can probably obsolete this term, I just need to email the list and make sure no one has any objections.

@sabrinatoro @kallia-p - assigning both of you, if either of you would like to work on this. The documentation on how to obsolete a term is here: https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#manual-mergeobsolete

Note, there are a two classes that will become 'orphaned' (they will no longer have a parent class) after we obsolete this term, so we need to assign new parents for them. The terms are:
- 'combined immunodeficiency due to GINS1 deficiency' - _this should be a child of MONDO_0018035 'syndrome with combined immunodeficiency'_
- 'microcephaly, growth restriction and increased sister chromatid exchange' - _this should also be a child of MONDO_0018035 'syndrome with combined immunodeficiency'_

**Comment by sabrinatoro** [comment]
Hello @ValWood 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
