### ISSUE TITLE
[Merge] coxsackievirus infectious disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3205]
**Mondo term (ID and Label)**
MONDO_0005721 coxsackievirus infectious disease

**Reason for deprecation**
duplicate
'Keshan disease' is a single child of coxsackievirus infectious disease and I can't find any other evidence of other coxsackievirus infectious disease infections.

**Term to be merged with**
MONDO_0000241 'Keshan disease'

related to https://github.com/monarch-initiative/mondo/pull/3118

**Comment by kanems** [comment]
Hi Nicole! I was just looking at cleaning up this merge in MedGen's data but I think it may have been done in error. There are a host of other Coxsackievirus-based infectious diseases in UMLS:
Coxsackievirus Infections UMLS CUI: C0010246 is a broader term to:
[Acute coxsackievirus bronchitis - https://uts.nlm.nih.gov/uts/umls/concept/C0555994)
[Congenital coxsackie infection -https://uts.nlm.nih.gov/uts/umls/concept/C0456099)
[Conjunctivitis, Acute Hemorrhagic -https://uts.nlm.nih.gov/uts/umls/concept/C0009765)
[Coxsackie bronchitis -https://uts.nlm.nih.gov/uts/umls/concept/C5442600)
[Coxsackie endocarditis -https://uts.nlm.nih.gov/uts/umls/concept/C0153105)
[coxsackie group B virus infections -https://uts.nlm.nih.gov/uts/umls/concept/C2062443)
[Coxsackie meningitis-https://uts.nlm.nih.gov/uts/umls/concept/C0276431)
[Coxsackie muscle infection -https://uts.nlm.nih.gov/uts/umls/concept/C0343656)
[Coxsackie myocarditis -https://uts.nlm.nih.gov/uts/umls/concept/C0153106)
[Coxsackie pericarditis -https://uts.nlm.nih.gov/uts/umls/concept/C0153104)
[Coxsackie viral disease of the newborn -https://uts.nlm.nih.gov/uts/umls/concept/C0858002)
[Coxsackie virus exanthem -https://uts.nlm.nih.gov/uts/umls/concept/C0343654)
[Coxsackie virus hepatitis -https://uts.nlm.nih.gov/uts/umls/concept/C0400908)
[Coxsackie virus infection of oral cavity -https://uts.nlm.nih.gov/uts/umls/concept/C3697897)
[Coxsackievirus infection of the central nervous system -https://uts.nlm.nih.gov/uts/umls/concept/C1320177)
[Coxsackievirus virus as cause of disease classified elsewhere -https://uts.nlm.nih.gov/uts/umls/concept/C3509719)
[Eczema coxsackium -https://uts.nlm.nih.gov/uts/umls/concept/C4761277)
[Enteritis due to Human coxsackievirus -https://uts.nlm.nih.gov/uts/umls/concept/C2959679)
[Enteroviral lymphonodular pharyngitis -https://uts.nlm.nih.gov/uts/umls/concept/C0276424)
[Enterovirus heart infection -https://uts.nlm.nih.gov/uts/umls/concept/C0153103)
[group A coxsackie virus infections -https://uts.nlm.nih.gov/uts/umls/concept/C2012615)
[Hand, Foot and Mouth Disease -https://uts.nlm.nih.gov/uts/umls/concept/C0018572)
[Hepatitis in coxsackie viral disease -https://uts.nlm.nih.gov/uts/umls/concept/C0276433)
[Herpangina -https://uts.nlm.nih.gov/uts/umls/concept/C0019338)
[Lymphonodular coxsackie pharyngitis -https://uts.nlm.nih.gov/uts/umls/concept/C0343655)
[Neonatal coxsackie virus syndrome -https://uts.nlm.nih.gov/uts/umls/concept/C0343659)
[Other specified diseases due to Coxsackie virus -https://uts.nlm.nih.gov/uts/umls/concept/C0343653)
[Pleurodynia, Epidemic -https://uts.nlm.nih.gov/uts/umls/concept/C0032238)

MeSH has fewer children for this concept:  https://www.ncbi.nlm.nih.gov/mesh/?term=D003384  At a minimum Hand Foot and Mouth (MONDO:0005779) is a pretty common Coxsackievirus infectious disease, so I think it may be appropriate to revive this Mondo term and give it a few more children concepts; I am not sure if Keshan disease is really the best example of a Coxsackievirus infectious disease, either, but I also don't know enough to say if this should *not* be a child term either.; this article reports on the correlation but seems like the jury is still out regarding causation between the viral infection and KD. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7901819/
