### ISSUE TITLE
Make "dehydratase deficiency" more specific

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#3215]
**Mondo term (ID and Label):** dehydratase deficiency (MONDO:0009908)

**Suggested new label:** PCBD1 deficiency, PCD deficiency

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
This request is made on behalf of the ClinGen Aminoacidopathy EP (https://clinicalgenome.org/affiliation/40011/). Based on expert reccomendations, the term "dehydratase deficiency" is inappropriate for this entity as it is not unique. PCBD1 encodes a dehydratase, however the current label could cause confusion over which dehydratase is deficient in the proband.

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Thanks @RedRiver1816, we'll make this change.

@kallia-p:
- [ ] change label of dehydratase deficiency (MONDO:0009908) to PCBD1 deficiency
- [ ] make dehydratase deficiency an exact synonym with database cross-reference Orphanet:1578 and https://clinicalgenome.org/affiliation/40011/
- [ ] Add exact synonym PCD deficiency with database cross-reference https://clinicalgenome.org/affiliation/40011/
- [ ] add rdfs:comment:  Based on expert recommendations, the label "dehydratase deficiency" is inappropriate for this entity as it is not unique. PCBD1 encodes a dehydratase, however, the current label could cause confusion over which dehydratase is deficient in the proband.
- [ ] Add seeAlso: https://github.com/monarch-initiative/mondo/issues/3215

Thanks!

**Comment by kallia-p** [comment]
@nicolevasilevsky 

Box 1 - rdfs:label did you mean to add pterin-4 alpha-carbinolamine dehydratase 1 deficiency instead of PCBD1 deficiency? 
The latter has been added as an exact synonym as per box 4 instructions.

For consistency I also changed the definition
from 
Dehydratase deficiency or pterin-4 alpha-carbinolamine dehydratase (PCD) is considered ... PCD is inherited in an autosomal recessive manner.
to
Pterin-4 alpha-carbinolamine dehydratase 1 (PCBD1) deficiency is considered ... PCBD1 is inherited in an autosomal recessive manner.

**Comment by nicolevasilevsky** [comment]
Box 1 - yes

Thanks for revising the definition. Just FYI, Orphanet likes to start the definitions with the class name, Chris doesn't recommend this though. Please see his blog post: https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/
