### ISSUE TITLE
[NTR] emergency medicine conditions

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3234]
From [April 2021 Mondo Workshop](https://docs.google.com/document/d/1KXqGAZgZUbK-VnzcomnMbfAEq7WEeGxDaQ-EK8UUQZI/edit?usp=sharing)

Classes: ‘Injury’ , 'radiation or chemically induced disorder' , 'acute disease' 
These are “emergency medicine  conditions” 
(though these are not necessarily disease or disorder) 

Related to #2741

**Comment by sabrinatoro** [comment]
Also see: #922

**Comment by sabrinatoro** [comment]
Some terms do not seem like an ‘emergency medicine condition’ to me, but I am not an expert; therefore, I want to confirm that we indeed want to group the 3 classes  ‘Injury’ , 'radiation or chemically induced disorder,' and 'acute disease' under a new term ‘emergency medicine condition’. 
Should ‘acute disease’ be included in this new class? Should “acute myeloid leukemia” (MONDO:0018874), child of ‘acute disease’, be a grandchild of ‘emergency medicine conditions’?
Would all the terms under ‘radiation or chemically induced disorder’ make sense under ‘emergency medicine conditions’? For example Cushing syndrome (MONDO:0018912)

Maybe we can go ahead with the creation of the superclass ‘emergency medicine condition’ and clean up later? 
Please advice. Thank you! 
@pnrobinson @cmungall @nicolevasilevsky

**Comment by pnrobinson** [comment]
I would argue that EM condition is not a good way to categorize diseases because it is a matter of opinion whether somebody comes to the emergency room with any given disease (some are obvious, many are not). So numerous other conditions in MONDO could be Emergency conditions under certain circumstances. Acute disease is also not good, because many diseases start acutely and become chronic.

Why not just have injury as a top level term?
Can we discuss the need for -- radiation or chemically induced disorder, what are these exactly? Many diseases are "sometimes" radiation induced (say cancer, although this is debatable) and sometimes not.

So the problem is that these categories are roles rather than "essences" of the diseases!

**Comment by sabrinatoro** [comment]
This case will be taken care of with these 2 issues 
- #3414 
- #3415
