### ISSUE TITLE
[NTR] COVID-19-related coagulopathy

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#3246]
**Suggested term label:**
COVID-19-related coagulopathy

**Synonyms**
Thrombotic complications of COVID-19
COVID-19 hypercoagulability
**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
https://www.thelancet.com/journals/lanhae/article/PIIS2352-3026(21)00105-8/fulltext
https://www.uptodate.com/contents/covid-19-hypercoagulability
**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Comment**
A submitter to ClinVar provided "Susceptibility to severe coronavirus disease (COVID-19) due to an impaired coagulation process".  We could not find an appropriate term in Mondo.  Not sure whether this is to be captured as a disorder or a finding (i.e. in HPO), but it seems worth capturing explicitly

**Comment by pnrobinson** [comment]
I do not think this is a separate disease. This is a feature of COVID-19, i.e., an HPO term rather than a MONDO term.
Criteria for regarding a feature like this as a disease would include that there is a characteristic clinical course that is solely (or at least mainly) characterized by features such as Disseminated intravascular coagulation (HP:0005521). However, it is clear from the Lancet article that this is a feature that is seen as one of many in people with COVID-19

**Comment by maglott** [comment]
If others agree, I am fine with removing this request from Mondo. I have no knowledge whether the coagulopathy from COVID-19 has distinctive characteristics.

**Comment by nicolevasilevsky** [comment]
Sure thing, I will close. Thanks @maglott!
