### ISSUE TITLE
(hyper)homocystinemia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3247]
I am looking for clarification on mapping OMIM:603175- "Hyperhomocystinemia." Currently Mondo maps this MIM# to MONDO:0011293 (homocystinemia), but the OMIM preferred name is hyperhomocystinema, which might otherwise match to MONDO:0004743 . 
UMLS maps this MIM number to C3495426 (Homocysteinemia), as it is shown in Mondo.  
For MedGen, we'll follow Mondo's mapping and use MONDO:0011293 for this concept for now. But given the potential multiple match based on the name(s), I wanted to make sure this is how the community wants this to be represented.
@ahamosh @nicolevasilevsky

**Comment by ahamosh** [comment]
We, at OMIM, had a long discussion about this.   In the old days, we couldn't measure total homocysteine (free and bound).  Free homocysteine was measured on plasma amino acids where it should not be seen.  Now, most people follow total homocysteine which has a normal range up to 12 or 14.  So the correct term now should be hyperhomocysteinemia, since homocysteinemia can be normal.

**Comment by sabrinatoro** [comment]
After reviewing the terms and their cross-references, I am wondering whether we could merge 'homocysteinemia' (MONDO:0011293) to 'hyperhomocysteinemia' (MONDO:0004743) since OMIM:603174 refers to 'hyperhomocysteinemia' (as per previous comment from ahamosh).

Open question: 
Currently, GARD:0008230 is equivalent to 'homocysteinemia' (MONDO:0011293). 
Does this ID actually refers to 'hyperhomocysteinemia', or does it refers to a different concept/disease? 
I couldn't find much information about this GARD record.  @galyea-gard, could you please help? Thank you in advance! 

Note to self: still investigating UMLS:C3495426

**Comment by sabrinatoro** [comment]
MONDO:0011293 (homocystinemia) will be obsoleted and merged into 'hyperhomocysteinemia' (MONDO:0004743)
