### ISSUE TITLE
[Merge] type 1 and type 2 diabetes nephropathy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3277]
**Mondo term (ID and Label)**
MONDO:0005442 'type 1 diabetes nephropathy'
MONDO:0005443 MONDO_0005443

**Reason for deprecation**
redundant and this term is not used by clinicians.
@zoependlington @paolaroncaglia can you comment on why these classes were created (they come from EFO). Upon a discussion with kidney experts, it was decided these terms should be merged with MONDO:0005016 'diabetic nephropathy'

**Term to be merged with**
MONDO:0005016 'diabetic nephropathy'

**Comment by nicolevasilevsky** [comment]
@sabrinatoro this needs to be added to our spreadsheet and we should email the list when we have a longer list of terms to be merged/obsoleted

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

> **Mondo term (ID and Label)**
> MONDO:0005442 'type 1 diabetes nephropathy'
> MONDO:0005443 MONDO_0005443
> 
> **Reason for deprecation**
> redundant and this term is not used by clinicians.
> @zoependlington @paolaroncaglia can you comment on why these classes were created (they come from EFO). Upon a discussion with kidney experts, it was decided these terms should be merged with MONDO:0005016 'diabetic nephropathy'
> 
> **Term to be merged with**
> MONDO:0005016 'diabetic nephropathy'

Those are old EFO terms (created by James Malone) and they both have the EFO annotation property 'gwas trait' = true, meaning that they are in use by the GWAS catalog. They both have this definition citation in case it helps to discriminate:
Ruggenenti P and Remuzzi G (2000) Nephropathy of type 1 and type 2 diabetes: diverse pathophysiology, same treatment? Nephrology Dialysis Transplantation Volume 15, Issue 12Pp. 1900-1902.
I think that EFO should notify GWAS curators before obsoleting, and replace both terms with the new Mondo one you plan to create, if GWAS is ok with having one lump term rather than 2. @kallia-p (cc @zoependlington ) could you look into this, please?

Thanks,
Paola

**Comment by kallia-p** [comment]
@nicolevasilevsky @paolaroncaglia Paola thanks for checking this you are right and I will relay this message to the GWAS catalog curator. It looks like they have annotated several GWAS hits from various publications of diabetic nephropathy to either type 1 or type 2 diabetes depending on the diabetes type patients of the cohorts that were used for the GWAS studies. But there is a way round this for the GWAS catalog curators because they are thinking of moving into a model where they will have the tested trait (here diabetic nephropathy) from the population attribute studied (type 1 or type 2 diabetes).

**Comment by nicolevasilevsky** [comment]
Thanks @paolaroncaglia and @kallia-p.

@kallia-p could you let me know if it's okay to proceed? No rush. :)

**Comment by kallia-p** [comment]
@nicolevasilevsky Sure. I've relayed the message to the GWAS catalog team and they will come back to me with their answer.

**Comment by nicolevasilevsky** [comment]
speaking to @kallia-p, she said it is okay to go ahead and merge.
