### ISSUE TITLE
Questions re: Peroxisome Biogenesis Disorders reclassification

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3306]
@Mohan-Shruthi - I am done with reclassifying the peroxisome disorder per #2632. The changes will be available in the next release at the beginning of August. I have a few outstanding questions.

Our google docs are here:
- [Nicole's version](https://docs.google.com/document/d/1e_To1QzbxxhWrUI0_ABJtxYP5cVrPRA_LEKaXcc0toM/edit?pli=1)
- [Clean version](https://docs.google.com/document/d/1fL23rNXAfZOqdn1n41ISUgUVtLN-CKRGLGR5V64tAgk/edit)

**Questions re: Peroxisome Biogenesis Disorders reclassification:**

1. should MONDO_0008972 'rhizomelic chondrodysplasia punctata type 1' be merged with MONDO_0100272 'peroxisome biogenesis disorder due to PEX7 defect'? Is MONDO_0100307 'adult Refsum disease due to PEX7 defect' a child of MONDO_0008972 'rhizomelic chondrodysplasia punctata type 1'? Currently, they are siblings.
![image](https://user-images.githubusercontent.com/6722114/126056509-7295ab7b-ffe1-4593-8a12-bdbc2ceebeac.png)

2. Should MONDO_0100307 'adult Refsum disease due to PEX7 defect' be a child of MONDO_0009958 'adult Refsum disease'?

3. Regarding adult refum disease: could I please ask you to review this class further, it has several parent classes. Do you think some of these should be excluded (ie removed)?

4. MONDO_0031446 'hypercholanemia, familial 1' is not a single enzyme defect according to [OMIM](https://omim.org/entry/607748) and [Orphanet](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_238475) (per the doc, it was requested that 'hypercholanemia, familial 1' be a child of 'bile acid CoA:amino acid N-acyltransferaseSE (BAAT) deficiency', which is a descendent of 'peroxisomal single enzyme/protein defect'

5. Should MONDO_0013939 'peroxisome biogenesis disorder 7B' be a child of 'Zellweger spectrum disorders' or 'non-Zellweger spectrum disorder'? Currently it is a child of 'peroxisome biogenesis disorder'

6. Could you provide a definition for 'non-Zellweger spectrum disorder'?

---
**FYI:**
1.  I added 'ABCD3 congenital bile acid synthesis defect' as a synonym of 'congenital bile acid synthesis defect 5' and gave it a 'clingen preferred' tag.
2. I created a ticket (https://github.com/monarch-initiative/mondo/issues/3316) to obsolete MONDO:0017753 disorder of peroxisomal alpha-, beta- and omega-oxidation
Thanks!

**Comment by Mohan-Shruthi** [comment]
Hi Nicole,

Thank you for the updates and questions. Here are the responses from the Peroxisomal Disorders GCEP:

1. should MONDO_0008972 'rhizomelic chondrodysplasia punctata type 1' be merged with MONDO_0100272 'peroxisome biogenesis disorder due to PEX7 defect'? Is MONDO_0100307 'adult Refsum disease due to PEX7 defect' a child of MONDO_0008972 'rhizomelic chondrodysplasia punctata type 1'? Currently, they are siblings.

Response: It is appropriate that “rhizomelic chondrodysplasia punctata type 1” and “adult refsum disease due to PEX7 defect” are siblings as they are both phenotypic presentations of “peroxisome biogenesis disorder due to PEX7 defect”. 

2. Should MONDO_0100307 'adult Refsum disease due to PEX7 defect' be a child of MONDO_0009958 'adult Refsum disease'?

Response: I don’t think this should be done. “adult Refsum disease due to PEX7 defect” should be a child only to “peroxisome biogenesis disorder due to PEX7 defect”.

3. Regarding adult refum disease: could I please ask you to review this class further, it has several parent classes. Do you think some of these should be excluded (ie removed)?

•	leukodystrophy- _White matter hyperintensities can be seen in Adult Refsum Disease. Perhaps a more appropriate term 
would be “leukoencephalopathy” as these are not invariably progressive as seen in a leukodystrophy. We could replace with the parent term “leukoencephalotpathy"?_
•	autosomal recessive congenital ichthyosis - _remove. Icthyosis in ARD  is not congenital._ 
•	neurometabolic disease
•	autosomal recessive metabolic cerebellar ataxia
•	disorder of peroxisomal alpha-, beta- and omega-oxidation - _remove. It is a disorder of alpha oxidation only_
 •	genetic peripheral neuropathy
•	cerebellar degeneration
•	eye degenerative disease
•	cataract associated with a metabolic disease - _if it is due to PEX7 deficiency, cataract can also occur._ 
•	autosomal ichthyosis syndrome with prominent neurologics signs

4. MONDO_0031446 'hypercholanemia, familial 1' is not a single enzyme defect according to OMIM and Orphanet (per the doc, it was requested that 'hypercholanemia, familial 1' be a child of 'bile acid CoA:amino acid N-acyltransferaseSE (BAAT) deficiency', which is a descendent of 'peroxisomal single enzyme/protein defect'

Response: Familial hypercholanemia (MONDO:0100327) is one of the phenotypes of BAAT deficiency, but isn’t itself the single enzyme defect. We understand that its placement would suggest that familial hypercholanemia is single enzyme/protein defect. Would it make sense to add this as a “related synonym”?

5. Should MONDO_0013939 'peroxisome biogenesis disorder 7B' be a child of 'Zellweger spectrum disorders' or 'non-Zellweger spectrum disorder'? Currently it is a child of 'peroxisome biogenesis disorder'

Response: I’m not sure how this was missed in the Google doc. 'peroxisome biogenesis disorder 7B' is a child of PEX26 defect. I have updated this in the Google doc as well.

6. Could you provide a definition for 'non-Zellweger spectrum disorder'?

Response: Peroxisome biogenesis disorders are divided into 2 groups: Zellweger Spectrum Disorders due to defects in 13 PEX genes and non-Zellweger Spectrum Disorder which are rhizomelic chondrodysplasia punctata due to defects in PEX7 and specific defects in PEX5 and adult Refsum Disease due to defects in PEX7.

**Comment by nicolevasilevsky** [comment]
This is great, thanks @Mohan-Shruthi!

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi 

> Response: Familial hypercholanemia (MONDO:0100327) is one of the phenotypes of BAAT deficiency, but isn’t itself the single enzyme defect. We understand that its placement would suggest that familial hypercholanemia is single enzyme/protein defect. Would it make sense to add this as a “related synonym”?

Is Increased serum bile acid concentration a phenotype associated with BAAT deficiency? We can add the phenotype association in Mondo, if that works.

**Comment by Mohan-Shruthi** [comment]
@nicolevasilevsky 

So increased serum levels of unconjugated bile acids is a feature of BAAT deficiency. However, I will verify with the experts if the "Increased serum bile acid concentration" should be added as a phenotype and get back to you. Thanks!

**Comment by Mohan-Shruthi** [comment]
@nicolevasilevsky 

I don't think we want to add "Increased serum bile acid concentration" as a phenotype as the feature is increased _unconjugated_ bile acids. 
Definition from experts: The biochemical profile of patients with BAAT deficiency is characterized by increased levels of predominantly unconjugated cholic acid and absence of glycine and taurine conjugated bile acids in serum, urine and bile.

**Comment by nicolevasilevsky** [comment]
Ok great, we'll just leave it as it is then.
