### ISSUE TITLE
Schaaf-Yang syndrome

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#3338]
**Mondo term (ID and Label)**: MONDO:0014243 Prader-Willi syndrome due to point mutation

**Synonym to be added**: Schaaf-Yang syndrome

**Synonym subtype: ie, broad/exact/narrow/related**: Unsure.

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.: 
PMID: 24076603
OMIM: # 615547

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
ClinGen ID/Autism GCEP

**Comment by tibingaman** [comment]
I see that it is already labeled as a synonym however, is there any way to relabel this as Schaaf-Yang syndrome with Prader-Willi syndrome due to point mutation as a synonym. Please let me know if you have any questions. Happy to discuss this further. Thank you.

**Comment by nicolevasilevsky** [comment]
@tibingaman yes, we'll do that.

Action items:
- [ ] relabel term as Schaaf-Yang syndrome
- [ ] add exact synonym Schaaf-Yang syndrome, add has synonym type 'clingen preferred', add dbxref: OMIM:615547, PMID:24076603
- [ ] add exact synonym Prader-Willi syndrome due to point mutation, add dbxref: Orphanet:398069
- [ ] add seeAlso: this ticket

**Comment by nicolevasilevsky** [comment]
@kallia-p would you be able to work on this ticket before the end of the week? We'd like to get this in for the September release. No worries if not, we can reassign. Thanks!

**Comment by kanems** [comment]
Is there a difference between
MONDO:0018355 Prader-Willi-like syndrome due to point mutation
and MONDO:0014243 Schaaf-Yang syndrome that I am missing? 
Maybe MONDO:0018355 should be renamed to match ORPHA:398079: "SIM1-related Prader-Willi-like syndrome"   or "Prader-Willi-like syndrome due to SIM1 point mutation" so the disease doesn't start with a gene symbol ?

**Comment by nicolevasilevsky** [comment]
- I added the synonym MAGEL2-related Prader-Willi-like syndrome (from Orphanet) to MONDO:0014243 Schaaf-Yang syndrome
- I deprecated the synonyms Prader-Willi syndrome due to point mutation and PWS due to a point mutation on MONDO:0014243 Schaaf-Yang syndrome, as these do not appear to be used by Orphanet
- I relabeled MONDO_0018355 to SIM1-related Prader-Willi-like syndrome and added the synonym SIM1-related PWLS (from Orphanet)
- I deprecated the synonyms Prader-Willi-like syndrome due to a point mutation, PWS-like due to a point mutation, and PWS-like due to point mutation, as these do not appear to be used by Orphanet any longer either.
