### ISSUE TITLE
Addition or change of rare genetic diabetes mellitus to Monogenic diabetes

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#337]
For new term requests, please provide the following information:

## Monogenic Diabetes

We request that Monogenic Diabetes is either (1) included as sibling term to rare genetic diabetes mellitus, **or** (2) can replace the current rare genetic diabetes mellitus term.

## Synonyms
rare genetic diabetes mellitus

## Definition

Monogenic diabetes constitutes rare forms of diabetes mellitus that result from changes or mutations in a single gene. Monogenic diabetes can include, but is not limited, to the following disease entities: neonatal diabetes mellitus, maturity onset of diabetes of the young (MODY), and syndromic forms of diabetes mellitus that are attributed to changes in a single gene.  

**References include:** PMID: 29734081, PMID: 28432734, PMID: 29406006  and the NIDDK link: https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes/monogenic-neonatal-mellitus-mody

## Suggested parent term

Rare diabetes mellitus

## Attribution

Could this be attributed to the ClinGen Monogenic Diabetes Expert Panel?

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@courtneythaxton could you give me more info - is monogenic diabetes the same as _MONDO_0015967 rare genetic diabetes mellitus_ or a sibling? I cannot add _rare genetic diabetes mellitus_ as a synonym for a new class, because that class already exists. I can add _monogenic diabetes_ as a synonym for _MONDO_0015967 rare genetic diabetes mellitus_, if you prefer.

 I am unable to find much information about _MONDO_0015967 rare genetic diabetes mellitus_, it doesn't have a text def and the Orphanet term does not have a def either.

Thanks!

**Comment by courtneythaxton** [comment]
Hi Nicole, 

The ClinGen Monogenic diabetes Expert Panel wants to curate the gene HNF1A under a "Monogenic Diabetes" disease entity, as it is a presentation of MODY (maturity onset diabetes of the young) but newer evidence is emerging that individuals with MODY may be developing renal cancer at a greater rate than the general population. Because of this emerging evidence for HNF1A as well as other MODY genes, they felt haver a broader disease entity would be preferable. In looking over the MonDO ontology trees they felt that rare genetic diabetes was the best disease ontology/ disease entity, but they wanted the nomenclature to reflect "Monogenic diabetes"  for the classification and on the ClinGen website. I think adding Monogenic diabetes as a synonym for rare genetic diabetes would be good, is there a way we can specify the nomenclature?

**Comment by nicolevasilevsky** [comment]
yes, I will add monogenic diabetes as an exact synonym for MONDO_0015967 rare genetic diabetes mellitus, the primary label will be rare genetic diabetes mellitus though. What do you mean by a way to specify the nomenclature?

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky @cmungall 

I noticed that the Monogenic diabetes MONDO MONDO:0015967 has been obsoleted and turned back into diabetes mellitus. 

Is there a way that we can create a MONDO ID for monogenic diabetes to satisfy disease entities chosen by the ClinGen Monogenic diabetes Gene curation expert panel? If I need to create a new ticket, please let me know and I will be happy to do so.

Thanks,
@courtneythaxton

**Comment by cmungall** [comment]
Apologies, this was obsoleted accidentally because it had the "pattern" of the "rare-X" grouping classes from Orphanet.

Back in October, when we renamed "rare genetic diabetes mellitus" we should have either retained the other ID or changed the pattern.

@nicolevasilevsky can you unobsolete MONDO:0015967?

**Comment by nicolevasilevsky** [comment]
yes!
