### ISSUE TITLE
create summary stats for Mondo for RPPR

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3458]
Current # of classes	
Defined	
Obsolete	
Total

**Comment by nicolevasilevsky** [comment]
Potential additional stats:
- take current mondo and compare it to mondo from before the last RPPR (June 2020)
- # of changed definitions
- # of new terms
- # of obsoleted terms
- relationship by source
- relationship by xref

**Comment by matentzn** [comment]
I think these numbers are enough for the RPPR:
https://docs.google.com/spreadsheets/d/1m4nYD0b4F8Cv4RyTZGBDVS0qI1XXQ3WJYUW4K5DS6Tc/edit#gid=0

Please let me know if any others are needed.

This is how your read:

- 2374 definitions added or changed since June 2020
- 333 cross-references to OMIM added/changed since June 2020

**Comment by nicolevasilevsky** [comment]
Thank you Nico!
