### ISSUE TITLE
Question re: new Orphanet class: MONDO_0035398 'hypomyelination of early myelinating structures'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3544]
Action item:
- [x] obsolete MONDO:0035398 'hypomyelination of early myelinating structures'

Reason: phenotype and not a disease

_updated 10/21/21 by NV_
----

@ahamosh 

We added: MONDO_0035398 'hypomyelination of early myelinating structures' which is equiv to [Orphanet:599376](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_599376) and has a mutation in the gene PLP1.

This seems like it is distinct from the [PLP1 diseases in OMIM](https://www.omim.org/entry/300401). Do you know if OMIM is going to add an equivalent term?

**Comment by ahamosh** [comment]
This looks like a feature and not a disease. @pnrobinson  what do you think?

**Comment by pnrobinson** [comment]
I agree this is a phenotypic feature rather than a disease. It is underspecified since it is not clear what anatomical parts exactly are meant by early myelinating structures and it is not 100% clear if this is a delay in myelination or a permanent feature.
The corresponding Orphanet entry does not provide any information
https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=29925&Disease_Disease_Search_diseaseGroup=hypomyelination-of-early-myelinating-structures&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hypomyelination-of-early-myelinating-structures&title=Hypomyelination%20of%20early%20myelinating%20structures&search=Disease_Search_Simple

I sent a message asking for more information.
