### ISSUE TITLE
need SPARQL query for obsoletion candidates that includes seeAlso: GitHub link

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3549]
- need SPARQL query for obsoletion candidates that includes seeAlso: GitHub link
- I will ensure all of the current obsoletion candidates have a seeAlso link

**Comment by nicolevasilevsky** [comment]
@matentzn - I added this to our agenda to work on together

**Comment by matentzn** [comment]
you and Sabrina should be able to do this now :) @sabrinatoro was using obsoletion candidates to actually build her harrisons view queries - do you want to give it a shot by yourself? I will review!

**Comment by sabrinatoro** [comment]
I'll give it a try.

**Comment by nicolevasilevsky** [comment]
I was thinking we could add comments too, like 'term to be merged with' or 'term will be split'. @sabrinatoro could you SPARQL for the comment field too, thanks!

**Comment by sabrinatoro** [comment]
@nicolevasilevsky @matentzn 
update: 
- I created a new sparkl query, but it was pushed to "master" instead of pushed to a branch! (urgh! I did check! and I still managed to push to the "wrong branch"). I am not going to try to "repair" this mistake as I am worried I will create more problems.
- I think the query is correct based on my test on the other website BUT running the query here gives zero results (running it on the other website (https://yasgui.triply.cc/#) gave only 8 results. 
@matentzn is it possible that the query says that the report should have BOTH the obsoletion_candidate AND a comment? (instead of "should the comment if there is one)

**Comment by matentzn** [comment]
@sabrinatoro you didnt share the correct link:

click on the three linked dots in the top right corner of yasgui, then on shorten.

![image](https://user-images.githubusercontent.com/7070631/130574040-add8d72d-08d3-4271-a49d-7a18f987e74d.png)


There is no problem with pushing report queries to master - they don't affect anything. Still, in general you don't want to get in the habit :) but for now its fine.

To make sure that you get all candidates, indeed, you need to tell SPARQL that the comment is optional:

```
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix inSubset: <http://www.geneontology.org/formats/oboInOwl#inSubset>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix mondoSubset: <http://purl.obolibrary.org/obo/mondo#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT  ?cls ?clsLabel ?comment
WHERE 
{
  ?cls <http://www.geneontology.org/formats/oboInOwl#inSubset> <http://purl.obolibrary.org/obo/mondo#obsoletion_candidate>.

  ?cls rdfs:label ?clsLabel .

  OPTIONAL {
  	?cls rdfs:comment ?comment
  }

  FILTER NOT EXISTS { ?cls owl:deprecated "true"^^xsd:boolean }
}
ORDER BY ?cls 
```

Thats all, very nice job!

**Comment by sabrinatoro** [comment]
add 'seeAlso' in the query
