### ISSUE TITLE
Friedreich ataxia: clarify whether this is a grouping or a specific class

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#3590]
http://purl.obolibrary.org/obo/MONDO_0100339

see highlighted:

![image](https://user-images.githubusercontent.com/50745/131200821-749d86f4-a361-4207-bf22-468a23b1cdcb.png)

AFAIK the FXN gene is only for type 1. It looks like when we split this when type 2 was discovered the parent inappropriately inherited the definition of the prototypical member

**Comment by turbomam** [comment]
I passed this on to a friend who is knowledgeable about FA but not semantic modelling.

**Comment by turbomam** [comment]
Partially related: ICD10:G11.11 may be a better coding than G11.1 now

https://curefa.org/news/new-icd-10-cm-diagnosis-code-g11-11-for-friedreich-s-ataxia-effective-october-1-2020#:~:text=11%20for%20Friedreich's%20Ataxia%20Effective%20October%201%2C%202020,-Written%3A%20Wednesday%2C%20September

**Comment by nicolevasilevsky** [comment]
I think this is the case because Orphanet links this to FXN1. I agree that this is a more general grouping class and should not have the gene annotated to it, I'll remove it.

See: https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=45&Disease_Disease_Search_diseaseGroup=95&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Friedreich-ataxia&title=Friedreich%20ataxia&search=Disease_Search_Simple
