### ISSUE TITLE
[Revise subclass] 'malignant atrophic papulosis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3602]
**Mondo term (ID and Label)**
'malignant atrophic papulosis'

**Suggested revision and reasons**
vasculopathy

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
There is no term for "vasculopathy"
I made the parent term "vascular disease". Can (should) "vasculopathy" be a synonym of this term? (I think it can be, but maybe there is subtle difference?)

**Comment by nicolevasilevsky** [comment]
That seems like the appropriate parent to me.

Vasculopathy sounds like it would be a child of vascular disease, see:
https://medical-dictionary.thefreedictionary.com/vasculopathy

@pnrobinson and @ahamosh do you think we should add a new term to Mondo or would vasculopathy be synonymous with vascular disease?

**Comment by pnrobinson** [comment]
etymologically, vasculopathy is a synonym of vascular disease, but there seems to be a special use case as mentioned below.
I would suggest we add it as a RELATED SYNONYM of vascular disease/disorder, and would further suggest we adapt the current definition of the latter term.

https://link.springer.com/chapter/10.1007/978-3-540-78785-3_7

Vasculopathy is a general term used to describe any disease affecting blood vessels [1]. It includes vascular abnormalities caused by degenerative, metabolic and inflammatory conditions, embolic diseases, coagulative disorders, and functional disorders such as posteri or reversible encephalopathy syndrome. The etiology of vasculopathy is generally unknown and the condition is frequently not pathologically proven. Vasculitis, on the other hand, is a more specific term and is defined as inflammation of the wall of a blood vessel [2]. However, the term vasculopathy is also used for “vasculitis” that has not been pathologically established.

**Comment by ahamosh** [comment]
I agree.  A synonym, not a child.

**Comment by nicolevasilevsky** [comment]
Thanks! I updated the def, synonym and added a comment.
