### ISSUE TITLE
[NTR] UMLS:C3276419 Usher Syndrome, Type 1D/F

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#3626]
**Preferred term label:**
Usher syndrome, type 1D/F 

**Synonyms**
Exact:
Usher syndrome, type 1D/F, CDH23/PCDH15, digenic
USH1D/F, CDH23/PCDH15, digenic

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Any Usher syndrome in which the cause of the disease is a mutation in the CDH23 and PCDH15 genes.
dbxef: MONDO:patterns/OMIM_disease_series_by_gene

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
'Usher syndrome type 1'

**Database cross reference**
OMIM:601067
source: MONDO:equivalentTo

**Logical definition**
'Usher syndrome type 1'
and ('disease has basis in dysfunction of' some CDH23)
and ('disease has basis in dysfunction of' some PCDH15)

From OMIM:
"Type ID/F Usher syndrome is caused by digenic mutation in the CDH23 and PCDH15 (605514) genes."

This disease does not have an OMIM id but is part of the record for Usher Syndrome 1D - https://omim.org/entry/601067
The UMLS id is C3276419

A user reached out asking why the ClinVar record  [RCV000005209.3](https://www.ncbi.nlm.nih.gov/clinvar/RCV000005209.3/) was not represented on the monarch UI.  cc @wenwenzn

**Comment by nicolevasilevsky** [comment]
@ahamosh is it possible to get a separate OMIM number for USHER SYNDROME, TYPE ID/F, CDH23/PCDH15, DIGENIC, INCLUDED?

**Comment by ahamosh** [comment]
Hi Nicole,
Because of how icky and limited the evidence is for all the digenic, we are keeping them as included for now.  We can revisit this in the future.
Thanks,
Ada

Ada Hamosh, MD, MPH
Dr. Frank V. Sutland Professor
McKusick-Nathans
Department of Genetic Medicine (DGM)
Clinical Director, DGM
Scientific Director, OMIM
Johns Hopkins University
Blalock 1007
600 N. Wolfe St
Baltimore, MD 21287-4922
Phone:  410-614-3313
Fax: 410-367-3231
***@***.***

Assistant:  Heather Dozier
phone:  410-955-6641
e-mail:  ***@***.***

________________________________

**Comment by nicolevasilevsky** [comment]
No problem, thanks @ahamosh!

**Comment by nicolevasilevsky** [comment]
'Type ID/F Usher syndrome'
 and ('disease has basis in dysfunction of' some GENE)
 and ('disease has basis in dysfunction of' some GENE)
