### ISSUE TITLE
merge MONDO_0002510 'germ cell and embryonal cancer'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#376]
there is a note to merge this class, but it doesn't specify which term it should be merged with

**Comment by nicolevasilevsky** [comment]
I'm guessing the proposal is to merge with MONDO_0005040 | germ cell tumor'

**Comment by cmungall** [comment]
Hmm, generally in mondo we like to follow the naming conventions in the DPs

tumor/neoplasm = malignancy neutral
cancer = malignant tumor/neoplasm

this would indicate against a merge of GCT with 'germ cell and embryonal cancer'

however, I think MONDO:0002510 'germ cell and embryonal cancer' is just confused. It comes from mesh. it has cancer in the name, but for some reason we didn't axiomatize it as malignant. if we were to then we would have incoherency, as this is a parent of teratoma, which can be benign.

why is trophoblastic neoplasm classified under this?

why is PNET under this?

I think it would be good to do further digging on what the literature says, but the safe thing is to obsolete this, rather than merge, just do a consider to GCT

**Comment by maglott** [comment]
My guess is that 'the literature' will also be inconsistent.  As long as MONDO's labels are consistent with rules, and there is a comment about why a 'cancer' term points to a benign record, more may be careful about term usage.  But thanks for this example.  When OMIM  deprecates a MIM number, and added the 'former' term to remaining MIM number, is the management of the 'former' term managed as a 'consider'?

**Comment by nicolevasilevsky** [comment]
From what I understand, in Mondo we either have the annotation 'term replaced by', which means the two terms are merged, or 'consider', which isn't a merger, but a recommended term that _could_ be used instead.

(Note to self) Action item:
- [ ] obsolete MONDO_0002510 'germ cell and embryonal cancer'
- [ ] add 'consider' annotation to MONDO_0005040 | germ cell tumor' (do not merge these terms)

**Comment by nicolevasilevsky** [comment]
From NCIT:

Germ cell and embryonal cancer: This is a poor term, should be removed. Embryonal malignancies are composed of primitive (immature) tissues and do not originate from the germinal layer. Germ cell malignancies originate from the germinal layer. These two should not be confused. They are distinct cancers, biologically and morphologically.

**Comment by nicolevasilevsky** [comment]
from NCIT: 

The term “germ cell and embryonal cancer” should not be merged with the term “germ cell tumor”. The former is a poor term. We recommend deleting it. Germ cell tumors and embryonal tumors are distinct entities, biologically, morphologically, and clinically. PNET is an embryonal tumor. It is not a germ cell tumor.
