### ISSUE TITLE
question about MONDO_0012172 mitochondrial trifunctional protein deficiency

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#38]
I am unsure about the subclass assertion of MONDO_0012172 mitochondrial trifunctional protein deficiency as a subclass of MONDO_0012173 long chain 3-hydroxyacyl-CoA dehydrogenase deficiency.

Looks like MONDO_0012173 long chain 3-hydroxyacyl-CoA dehydrogenase deficiency is caused by mutations in the HADHA gene, and MONDO_0012172 mitochondrial trifunctional protein deficiency is caused by mutations in either the HADHA or HADHB gene.

Orphanet does not classify them as subclass/parent, so maybe this is incorrect?

![image](https://user-images.githubusercontent.com/6722114/33636419-dd4ab106-d9d0-11e7-9107-b7e4aca8f2d9.png)

**Comment by cmungall** [comment]
yes youre right, look at the low probs on the axioms

**Comment by nicolevasilevsky** [comment]
How do we address this in MONDO? It doesn't seem to be caused by incorrect xrefs. I don't think I've addressed an example like this before.
Thanks for your help!

**Comment by cmungall** [comment]
It was caused by a shared UMLS xref between each pair, e.g. UMLS:C1969443. Unfortunately this isn't visible in the displays I have given you. Shared UMLS on its own has a low prior of equivalence hence the low probs associated and their ranking in the to-be-checked report.

Looks like medgen merges these https://www.ncbi.nlm.nih.gov/medgen/C1969443

While I think the subclass is wrong we should investigate this. There is some kind of close similarity, e.g. both are mitochondrial and involve fatty acid oxidation. Do we fully capture this?

**Comment by nicolevasilevsky** [comment]
note to self, see if this is in the medgen spreadsheet #1244

**Comment by nicolevasilevsky** [comment]
it is not in the MedGen spreadsheet

**Comment by nicolevasilevsky** [comment]
I think this has been resolved.
