### ISSUE TITLE
split term: MONDO:0010528  anosmia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3834]
**Term to split:**
MONDO:0010528 anosmia

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
congenital anosmia, X-linked (child of anosmia original term)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
OMIM: 301700, ANOSMIA, ISOLATED CONGENITAL

**Other notes**
Add UMLS CUI: C0003126 as an X-ref to MONDO:0010528 (also SCTID : 44169009 is for "Loss of sense of smell" which UMLS maps to that same CUI)
Make MONDO:0007137 isolated congenital anosmia a sibling to the new term. 

I realize the names on OMIM 301700 and 107200 are very similar to each other (and to ORPHA:88620), but the two MIM numbers seem to have different inheritance patterns (X-linked and autosomal, respectively), and the ORPHA term encompasses both forms of inheritance. So another option would be to have the Orpha term as a parent concept to both MIM numbers and all of those as children of the anosmia/genetic otorhinolaryngologic disease branch? I'm not sure what the correct display is...
Would probably also be good if OMIM @ahamosh and OrphaNet @ana-rath-orphanet  took a look at this, in case they want to update any of their preferred names or X-refs.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I reclassified anosmia as a child of nasal disorder, and excluded Mendelian disease as the superclass, because it was not consistent with the text definition:
"Loss of or impaired ability to smell. This may be caused by olfactory nerve diseases; paranasal sinus diseases; viral respiratory tract infections; craniocerebral trauma; smoking; and other conditions."

I created a new class MONDO:0100469 anosmia, isolated congenital, X-linked and made that a child of anosmia, along with MONDO_0007137 'isolated congenital anosmia'
