### ISSUE TITLE
Orphanet grouping class clean up

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3886]
This is a big project to clean up orphanet grouping classes in Mondo.

The action items are (_updated 2021-08-26_): 
- [x] Nicole and Sabrina should review [these terms ](https://docs.google.com/spreadsheets/d/1W6Fso7Gwbdra2eDd_6FthP0-xw3F4TWS/edit#gid=1723790196) carefully and determine they are needed. 
- [x] Add obsoletion candidate tags to these. There is a [tab](https://docs.google.com/spreadsheets/d/1W6Fso7Gwbdra2eDd_6FthP0-xw3F4TWS/edit#gid=1723790196) with terms that have already been reviewed. We should add obsoletion tags to these.
- [x] Check with ClinGen and EFO lists to see if these are used

There are many related tickets, which I've closed on the tracker but will reference here for tracking purposes:
https://github.com/monarch-initiative/mondo/issues/667
https://github.com/monarch-initiative/mondo/issues/324
https://github.com/monarch-initiative/mondo/issues/1674

**Comment by justyneross** [comment]
The ClinGen Aminoacidopathy GCEP would like to consider maintaining the MONDO:0018162 "neurometabolic disorder due to serine deficiency" currently included in this Orphanet grouping class clean up ticket. This ID has been used on three ClinGen gene curations (https://search.clinicalgenome.org/kb/conditions/MONDO:0018162) and the expert panel feels it is the appropriate term. We recognize that there are child terms for deficiency of each specific gene but prefer this broader term as each gene results in a similar neurometabolic disorder as a result of its role in serine biosynthesis.

**Comment by nicolevasilevsky** [comment]
No problem! We will keep it, I removed the obsoletion candidate tag, and it will no longer be on the list after the next release.

**Comment by nicolevasilevsky** [comment]
NV to do (per Mondo QC call on 01/21/22):
- [ ] need to manually review the children of Orphanet classes to be obsoleted and reclassify them. Then we can automatically obsolete the ORDO grouping classes.

**Comment by nicolevasilevsky** [comment]
@matentzn to do:

- [ ] Relabel: obsolete [current label]
- [ ] Add annotation: 'has obsolescence reason': string out of scope
- [ ] Any source annotation that is MONDO:equivalentTo should be changed to MONDO:obsoleteEquivalent
- [ ] Remove annotations:
  - [ ] in_subset obsoletion candidate
  - [ ] ‘scheduled for obsoletion on or after’ 2022-03-01
- [ ] Remove all superclass assertions

Thank you!

**Comment by nicolevasilevsky** [comment]
we're doing a new Orphanet ingest (4.0)
-Take in new ORDO ontology and remove all the previously supported orphanet axioms (subclassOf), then add new ORDO supported subclassOf axioms
- We’ll end up with unsupported subclassOf axioms and these can be reviewed/removed
