### ISSUE TITLE
BAFopathy and its subtypes

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#3939]
**Preferred gene-related syndrome label**
ACTB-related BAFopathy
ACTL6A-related BAFopathy
ACTL6B-related BAFopathy
ARID1A-related BAFopathy
ARID1B-related BAFopathy
ARID2-related BAFopathy
BCL11A-related BAFopathy
BCL11B-related BAFopathy
PBRM1-related BAFopathy|
SMARCA2-related BAFopathy
SMARCA4-related BAFopathy
SMARCB1-related BAFopathy
SMARCC1-related BAFopathy
SMARCC2-related BAFopathy

**Synonyms**
Not sure
**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Definition**
Please write the definition in the format: Any BAFopathy in which the cause of the disease is a mutation in the [gene name] gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
https://jhu.pure.elsevier.com/en/publications/expanding-the-spectrum-of-baf-related-disorders-de-novo-variants-

https://www.sciencedirect.com/science/article/pii/S0002929718304105
**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

*Comment*
ClinVar has received several submissions from Baylor using this term:
https://www.ncbi.nlm.nih.gov/clinvar/?term=bafopathy

I do not have any expertise in determining which of these are equivalent to the intent of gene-related disorders for Coffin-Siris or  Nicolaides-Baraitser

**Comment by sabrinatoro** [comment]
### 1) Import genes into Mondo 
_(note that the other genes are already in Mondo)_
ACTL6B = http://identifiers.org/hgnc/160
ARID2 = http://identifiers.org/hgnc/18037
BCL11B = http://identifiers.org/hgnc/13222
SMARCC2 = http://identifiers.org/hgnc/11105
DPF2 = http://identifiers.org/hgnc/9964
ACTL6A = http://identifiers.org/hgnc/24124
PBRM1 = http://identifiers.org/hgnc/30064
SMARCC1 = http://identifiers.org/hgnc/11104

### 2) Create a new term: **BAFopathy**
**Definition:** Disorder caused by mutations in the various subunits composing the BAF complex. 
(PMID:30580808)
**Parents:** Mendelian disease (MONDO:0003847) 
_Note: @nicolevasilevsky - can you please confirm this is correct (if you know). This is consistent with what we did with RASopathy_ 
**Children:**  
From PMID:30580808 : “The most recognizable syndrome associated with BAF abnormalities is Coffin-Siris syndrome (...). CSS can result of pathogenic changes in other chromatin remodeling proteins with no direct interaction with BAF complex, including SOX11 (MIM: 600898)18 and PHF6 (MIM: 300414).19” 
→ children of BAFopathy need to be specific,ie “CSS" cannot be the child of BAFopathy since some of CSS children are not a BAFopathy. 

### 3) create new terms/update existing terms
- based on OMIM records, some Mondo terms should be updated and the gene should be added
- based on PMID:30580808 and this issue: some terms should be children of BAFopathy
- some NTR are already in Mondo (under another name). Therefore a synonym should be added instead of creating new terms
The working table is [here](https://docs.google.com/spreadsheets/d/1-T5ezrbkFKvZ7VcbxKNnXMpvCDrQQrFjItT4g4rdZ2Y/edit?usp=sharing). 
@nicolevasilevsky, could you take a look at it and comment, please. My questions are mostly related to the xref and source, specifically: 
--col F and G
--col L
--col M (see comment in line 7)
Once this table is reviewed, I will create a ROBOT template.

**Comment by nicolevasilevsky** [comment]
This looks good Sabrina, really nice work. :)
