### ISSUE TITLE
MONDO:0015057  susceptibility to angioedema induced by ACE inhibitors [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3945]
**Mondo term (ID and Label)**
MONDO:0015057  susceptibility to angioedema induced by ACE inhibitors 

**Reason for deprecation**
ORPHA:100057 says it maps to OMIM: 300909 and no other MIM numbers. And includes alt name ACE inhibitor-related acquired angioedema

**Term to be merged with**
MONDO:0015057 renin-angiotensin-aldosterone system-blocker-induced angioedema
I suspect we can keep the OrphaNet name as preferred, since the 'suceptibility' terms are kind of fading out?
May want to consider if this concept is similar enough of a match to "Angioedema due to angiotensin-converting-enzyme inhibitor" from SNOMEDCT_US, 403607004  which maps to UMLS CUI: C1304495 (there is also ACE inhibitor-aggravated angioedema" SNOMED_CT 371627004 on UMLS C1268945, but this seems to be redundant with the other term/CUI)
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems I don't think we want to merge these two together, as the OMIM term is a susceptibility term in the susceptibility branch.

Note to self: look into Megan's suggestion here:

May want to consider if this concept is similar enough of a match to "Angioedema due to angiotensin-converting-enzyme inhibitor" from SNOMEDCT_US, 403607004 which maps to UMLS CUI: C1304495 (there is also ACE inhibitor-aggravated angioedema" SNOMED_CT 371627004 on UMLS C1268945, but this seems to be redundant with the other term/CUI)

**Comment by kanems** [comment]
@nicolevasilevsky your point makes sense, the ACE-inhibitor associated angioedema (like most adverse drug reactions) can certainly occur in the absence of a genetic susceptibility/variation, so it makes sense to have both concepts in Mondo.
Maybe sync the Orphanet X-ref with the MIM x-ref since OrphaNet says they are equivalent? I'm not sure. We will align as best we can with Mondo's decision without generating conflicts in the MedGen database.

**Comment by nicolevasilevsky** [comment]
@kanems I don't think the mapping between OMIM and Orphanet is 1:1 (see: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_100057)

**Comment by nicolevasilevsky** [comment]
I added xrefs to SNOMEDCT_US, 403607004 and UMLS CUI: C1304495
