### ISSUE TITLE
add subclassOf to congenital diseases: 'has modifier' some congenital

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4069]
For any class that has 'congenital' in the title, we should do a SPARQL query for these terms and add a subclassOf axiom 
`'has modifier' some congenital` (MONDO_0021140) using ROBOT

**Comment by sabrinatoro** [comment]
This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

**Comment by sabrinatoro** [comment]
@matentzn : I am trying to create a sparql query to get: 
All terms with "congenital" in the label  
and
filter to get the terms that do not have the axiom `"has modifier" some "congenital"`. 

I am able to get all the terms with "congenital" in the label. 
However, I cannot filter terms based on the axiom. I tried the following 2 queries, but it is unclear what is being filtered. 
Could you help, please? Thank you

Here is my sparql queries. 
https://api.triplydb.com/s/PgxwM704v
https://api.triplydb.com/s/PgxwM704v

**Comment by matentzn** [comment]
Very good proposal, you simply needed to use complex owl restriction syntax instead of `?diseases :has_modifer ?c`

https://api.triplydb.com/s/troQ8I-vC

This query exclude all cases that have a SUBCLASS axiom (not logical definition!) that "has modifier some congenital"

**Comment by sabrinatoro** [comment]
Thank you @matentzn .

Note to self: 
- running the query against the ontology or the reasoned ontology does give the same results (which was to be expected since "congenital disease" grouping term is already obsoleted. 
- The list should be reviewed as some terms might not fit the "congenital" pattern. For example "hereditary thrombophilia due to congenital protein C deficiency" might not be "congenital"

Report [here](https://docs.google.com/spreadsheets/d/13iP1d9aQxo-XiBjdzdiX-QaKvoxa2f2PLgvd56Nf0UE/edit?usp=sharing)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : terms which are "_disease_ due to congenital ~~" were excluded as I don't believe they should get the congenital modifier. (there were only 6 terms, please see report above to review).

ROBOT template: https://docs.google.com/spreadsheets/d/e/2PACX-1vQj7JiEHKb4EqxRC7uWV1bmkUMTmpM1O-8x92rIwvEEm061e61o2WhJiSVpETu0O0HAqyum2I7Snrjn/pub?gid=1977378741&single=true&output=tsv
