### ISSUE TITLE
[Revise subclass] neurofibromatosis type 6

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#4374]
One of our users (Yojana Gadiya) sent a message about a missing parent (see below)

===

Dear Curator team,

Great work on the creation of PomBase. It is really helpful for data stewards and scientists like me. I have found a missing link in PomBase for one of the entries.

Entry name - neurofibromatosis type 6 https://www.pombase.org/term/MONDO:0007245 

Potential parent -  neurofibromatosis https://www.pombase.org/term/MONDO:0021061

**Comment by ValWood** [comment]
YojanaGadiya

**Comment by nicolevasilevsky** [comment]
Hi @ValWood and @YojanaGadiya- 
these labels match, but it does not seem like these terms are actually related to each other. 

'neurofibromatosis type 6' is defined as:
Neurofibromatosis type 6 (NF6), also referred as cafe-au-lait spots syndrome, is a cutaneous disorder characterized by the presence of several cafe-au-lait (CAL) macules without any other manifestations of neurofibromatosis or any other systemic disorder.

neurofibromatosis is defined as:
A hereditary neoplastic syndrome in which tumors grow in the nervous system. There are typically 3 main types recognized, but other forms with uncertain etiology exist.

**Action:**
I will rename 'neurofibromatosis type' 6 to 'cafe-au-lait spots, multiple'

Thanks!

**Comment by ValWood** [comment]
oops, I didn't check the definitions. Renaming will be useful though ;)

**Comment by cmungall** [comment]
@nicolevasilevsky let's talk on the tech call about how to prospectively avoid things like this in the future

Anything lexically matching the omim-gene-in-series pattern (e.g. FOO 1 where there is a FOO) that is not actually marked to be in that pattern should be flagged. More generally "FOO N" not subclass of "FOO" is an anti-pattern. This probably holds for most ontologies. FOO N should be relegated to a synonym, and tagged possibly a deprecated synonym

Your PR looks good, made some comments. In this case we might want to make an upstream issue to ORDO since they are the originators of NF6 as the primary label. I wonder if we want to keep the synonym but as deprecated. Is there literature supporting its use?

**Comment by nicolevasilevsky** [comment]
Sounds good @cmungall! I will create a ticket for Orphanet and I'll check the literature to see if this label is still used.

**Comment by ValWood** [comment]
Although, I think
 neurofibromatosis-Noonan syndrome (MONDO:0011035)
should probably be is_a neurofibromatosis (it is a type I variant), with additional symptoms of Noonan syndrome If not, it should be is_a hereditary neoplastic syndrome (MONDO:0015356) because it  is definitely increased disposition of tumours.
v

**Comment by nicolevasilevsky** [comment]
To do:
- [ ] review relationship between neurofibromatosis and cafe au lait spots, see: https://www.mayoclinic.org/diseases-conditions/neurofibromatosis/symptoms-causes/syc-20350490
- [ ] create a ticket for Orphanet if the orphanet label is no longer being used
- [ ] check neurofibromatosis-Noonan syndrome (MONDO:0011035) per Val's [comment](https://github.com/monarch-initiative/mondo/issues/4374#issuecomment-1023541161) above

**Comment by sabrinatoro** [comment]
I couldn’t find evidence that “cafe au lait spots, multiple” (MONDO:0007245) should be a child of ‘neurofibromatosis’. Based on [here](https://www.mayoclinic.org/diseases-conditions/neurofibromatosis/symptoms-causes/syc-20350490,) ‘cafe au lait spots’ is a phenotype/trait/symptom of NF1, but is not, on it own, a neurofibromatosis. The counter argument would be in PMID:22630574 (2012) (and [here](https://escholarship.org/uc/item/3d56c2q8)): "“A conundrum exists in the entity’s nomenclature concerning whether it should be designated as neurofibromatosis or not as others have argued” which refers to PMID:8456833 (1993) "We propose that this condition be called Familial Café-Au-Lait Spots (FCAL) to distinguish it from the neurofibromatosis syndromes."

An argument to keep NF6 as a synonym is made in PMID:22630574 (2012) (and [here](https://escholarship.org/uc/item/3d56c2q8)): from the abstract, "Herein is a description of the condition and justification for this entity to be named Neurofibromatosis type 6." 
However, I didn't find this name used anywhere else, and this article was published in 2012. 
@nicolevasilevsky, based on this information, do you think we should go on and make it deprecated synonym?

**Comment by sabrinatoro** [comment]
neurofibromatosis-Noonan syndrome (MONDO:0011035).
From the omim record: 
- Allanson et al. (1985) reported 4 unrelated patients with neurofibromatosis who had manifestations of Noonan syndrome 
- evidence that some cases of neurofibromatosis-Noonan syndrome are caused by heterozygous mutation in the neurofibromin gene (NF1; [613113](https://omim.org/entry/613113 = )) on chromosome 17q11.

I think that it is ok to have this term, also named "NEUROFIBROMATOSIS WITH NOONAN PHENOTYPE" a child of 'neurofibromatosis'. 
@nicolevasilevsky feel free to accept or reject the PR.

**Comment by nicolevasilevsky** [comment]
> An argument to keep NF6 as a synonym is made in PMID:22630574 (2012) (and [here](https://escholarship.org/uc/item/3d56c2q8)): from the abstract, "Herein is a description of the condition and justification for this entity to be named Neurofibromatosis type 6."
However, I didn't find this name used anywhere else, and this article was published in 2012.
@nicolevasilevsky, based on this information, do you think we should go on and make it deprecated synonym?

It looks like it is still being used by Orphanet, so I don't think we should deprecate it.
