### ISSUE TITLE
About the accuracy of ontology alignment in MONDO

### ISSUE THREAD

**Issue by acadTags** [monarch-initiative/mondo#4477]
Dear MONDO team, 

We are interested in using the ontology alignment (e.g. xref) in MONDO as a gold standard in our experiment, for example, those used in https://mondo.monarchinitiative.org/pages/sources/. Wondered what it is the latest accuracy of the alignments? We found some results (87%) in the slides in https://f1000research.com/slides/5-1648, but the results seem a bit outdated. Please let us know the latest figures if you have them.

Best regards
Hang

**Comment by matentzn** [comment]
@acadTags Awesome, I think you should be fine using Mondo mappings as a gold standard now. There is no guarantee of 100% accuracy (it is not technically possible to guarantee that) but what we can guarantee is that all the mappings in Mondo are:

- 1:1 or
- proxy merges, i.e. two disease concepts in the resource we map to are considered the same.

@hrshdhgd is currently working on providing the mappings as SSSOM tables, which we would encourage you to use when they become available.

Some of the mapping sources (SNOMED, NCIT, DO) have not been updated in a while, we are currently working on updating ICD10CM again, and OMIM has been kept reasonably up to date - so you should factor into your experiment that missing mappings could be simply because they have not been recently synced up. Let me know if I can be of further help -  this ticket can be closed when we:

- [ ] provide all official Mondo mappings as SSSOM tables (@hrshdhgd)

**Comment by matentzn** [comment]
@acadTags If you would you like to take the mappings for a spin:

https://github.com/monarch-initiative/mondo/tree/master/src/ontology/mappings

Feedback welcome!

**Comment by acadTags** [comment]
Thanks @matentzn!
