### ISSUE TITLE
reading disorder has only 1 child- dyslexia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4484]
I'm not sure of the correct action here, but I see Reading Disorder (MONDO:0001697) has only a single child: dyslexia MONDO:0005489.

UMLS treats Reading Disorder and Dyslexia as synonymous (partially) following MESH [D004410], MedDRA 10013932. 
https://www.nichd.nih.gov/health/topics/reading/conditioninfo/disorders suggests there are 3 general kinds of reading disorders:
-dyslexia
-alexia (exists in HPO)
- hyperlexia  (MONDO:0009386, based on an OMIM entry that may or may not align with the NICHD definition above)
So perhaps Mondo should group Hyperlexia under reading disorder and we can contact UMLS about the mixing of concepts on their dyslexia CUI?

**Comment by sabrinatoro** [comment]
I agree that alexia (MONDO:0001712) and hyperlexia (MONDO:0009386) should be added as children of 'reading disorder' (MONDO:0001697). 
I think the confusion in the x-ref is due to the fact that there are multiple concepts: some referring to a disease/disorder (and should be represented in Mondo), and others referring to a feature (and should be represented in HPO).

In addition, the 'dyslexia susceptibility' terms should be moved to the 'disease susceptibility' branch.
