### ISSUE TITLE
Questions about MonDO source ontologies

### ISSUE THREAD

**Issue by MichaelaEBI** [monarch-initiative/mondo#4589]
First of all, great work on unifying different disease ontologies with MonDO. This is a much-needed effort. Having worked with different disease ontologies, I really appreciate the efforts that go into MonDO.

I have a few questions related to MonDO and I hope that this is the right place to ask these.

1. Which parts of different ontologies are in Mondo? Or which ones are excluded? For example, the Disease branch of a recent MeSH release contains ~5,000 terms. However, the recent paper 'Disease ontologies for knowledge graphs' (Kurbatova & Swiers, BMC Bioinformatics 2021) found >8,000 MeSH terms in MonDO (Table 1 in the paper). Are some of the supplementary MeSH concepts included? Another example is EFO - a recent EFO Open Targets SLIM (based on the EFO disease and phenotype entities) has >18,000 terms and the same paper found about 5,000 EFO terms represented in MonDO.
2. EFO is listed on the Mondo Sources Website (https://mondo.monarchinitiative.org/pages/sources/) with role ‘xref/Alignment’ and with note *historic - what does that mean?
3. One of the strengths of MonDO is that it is actively being curated. From reading some of the questions here on GitHub I gather that for most source ontologies, it is not the latest version that is integrated in MonDO. Looking through terms new in MeSH in 2022 (https://www.nlm.nih.gov/mesh/2022/download/2022NewheadingsbycategorywithScopeNotes.pdf) I noticed that terms like ‘Persistent Infection’ (D000088562), ‘Axial Spondyloarthritis’ (D000089183), ‘Neuroinflammatory Diseases’ (D000090862) are not in MonDO yet. What are the plans for keeping MonDO up to date with regards to the source ontologies?

Thank you very much for your time!
Michaela

**Comment by MichaelaEBI** [comment]
To look into this a bit more, I pulled out all MeSH IDs from a recent Mondo release (~8,000) and compared that list against the MesH IDs in the MeSH Disease branch of a recent MeSH release (~5,000). ~1,800 MeSH IDs were not found by me in Mondo. It is possible that I made a mistake along the way and the final number should be lower (I will try it a third time tomorrow, just to make sure), but I checked a few examples and I 1) either did not find the term at all, 2) found the term as a phenotype but without MeSH mapping or 3) I found the term as a disease but with missing MeSH ID. I am providing a few examples below and will try tomorrow to automatically assess the whole list. I assume there is some logic about MeSH terms that are actually phenotypes. I am sorry if I missed some documentation somewhere. Also, some of the terms seem to not be very specific subtypes of diseases but more general terms that would contribute to the ontology structure.

All terms were looked up on https://monarchinitiative.org/.

Terms that I cannot find:
```
D059369	Pott Puffy Tumor
D007249	Inflammation
D007239	Infections
D001259	Ataxia
D013616	Tachycardia, Sinus
```

Terms that appear as 'Phenotype' in the search results without MeSH mapping:
```
D000855	Anorexia
D064706	Vocal Cord Dysfunction
D013117	Spinal Cord Compression
D018805	Sepsis
D013610	Tachycardia
```

And a few where the disease is in Mondo but the MeSH mapping is missing:
```
D006816	Huntington Disease
D015776	Keratoderma, Palmoplantar, Diffuse
D006819	Hyaline Membrane Disease
```

**Comment by matentzn** [comment]
Hey @MichaelaEBI :) thank you for your interest! I am not speaking for all of Mondo (its a community project after all), but I will give you my view on your questions.

- We have been terrible at documenting the exact branches of the ontologies/terminologies we align with. We are only now getting better, carefully documenting every single class we exclude from our alignment with ICD10 (which is our current effort). From my experience, I can tell you that both cases can happen: relevant _disease_ terms outside the disease branch of some terminology, and non-disease terms (phenotypes, procedures gone bad etc) inside disease branches. I don't have examples right now, but I just want to point out that it's sometimes not super straightforward to pin that down. But that said, mostly it is, and we have started documenting the branches from NCIT, SNOMED, ORDO and others we aim to align with (not published yet, but can dig it out if of interest).
- MESH. The 8000 MESH xrefs are not considered "harmoninsed" in the same way as the OMIM, ORDO, DO and NCIT ones are - I would recommend _only_ considering skos:exactMatch as published in Mondo.owl, not any of the xrefs which have much weaker semantics. 
- It is our plan to syncronise with all other external terminologies in roughly this order (can change):
    1. OMIM (done)
    2. ORDO (underway, see #4579)
    3. ICD10CM (underway)
    4. DO
    5. NCIT
- Only after this, we will Sync up with Mesh, Meddra, UMLS and some of the others. So the best thing I can tell you know is that it will take a while (almost certainly after August).
- The EFO mappings are deemed "historical" because EFO uses Mondo now directly. However, as the full migration is still underway, EFO itself is maintaining a mapping here: https://github.com/EBISPOT/efo/blob/master/src/ontology/components/mondo_efo_mappings.tsv for all those diseases that are not fully migrated to Mondo yet!

Does this answer your questions? If so, feel free to close this issue, or open a new one, as you prefer!

**Comment by MichaelaEBI** [comment]
Hi @matentzn! Thank you very much for the detailed response. Documentation is always very important, but also very hard to keep up to date. Great to see that the different resources will be updated this year and that MeSH is on the list. MeSH will be great because it is the ontology/dictionary of choice for text mining diseases from PubMed abstracts. I will have a look at the skos:exactMatch MeSH IDs, thank you for the info. 

The Mondo-EFO mapping file, what are the mappings in there? I looked up a few and most seem to be present in Mondo.

I do have one more question: Are there mappings between MeSH and HPO? In my second message there were a few MeSH terms I found that show up as phenotypes (so they should be in HPO and UPheno) but there was no mapping to MeSH.

Thank you!

**Comment by matentzn** [comment]
>  The Mondo-EFO mapping file, what are the mappings in there? I looked up a few and most seem to be present in Mondo.

Most of them are indeed in Mondo, but they may have become out of sync, as EFO is curating these mappings now moving forward. Their purpose is to be able to `pull in Mondo term` but then change their IDs to EFO ids before the release. This is because Open Targets and many other resources across EBI have historically used EFO IDs to curate diseases, and it was deemed too major an effort to change all these retrospectively to Mondo IDs. I put it on the list to sync them up, but it is not very high priority right now. 

> Are there mappings between MeSH and HPO?

No formal ones, but:

There are about 1800 cross-references in HPO (see for example here: https://www.ebi.ac.uk/spot/oxo/datasources/HP), and HPO is also in UMLS from where you may be able to derive MeSH mappings:

https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/HPO/metarepresentation.html

**Comment by MichaelaEBI** [comment]
Thank you very much again @matentzn. I will close this issue.

**Comment by MichaelaEBI** [comment]
I hope it is ok that I am re-opening this issue. I wanted to follow up and see where things are at regarding the synchronisation of MeSH terms into Mondo. I am happy to provide a list of Mondo terms with missing MeSH XRefs based on our mappings.

**Comment by nicolevasilevsky** [comment]
@MichaelaEBI - you are always more than welcome to re-open tickets! :)

I'll look into this and get back to you asap.

**Comment by MichaelaEBI** [comment]
To give a bit more detail - we have a list of 85 disease MeSH terms that seem to have exact matches in Mondo (except for lower case/upper case, ie., dyslexia vs Dyslexia). Would it make sense for me to open a ticket to ask for these 85 specific Xrefs to be added? Our file has the Mondo ID, MeSH ID and the exact terms from each ontology.

**Comment by matentzn** [comment]
@MichaelaEBI that would be amazing!

If you could fill in this [spreadsheet](https://docs.google.com/spreadsheets/d/1RuWBa0mM_PQZAKzwXUvxdd8cD009MnOVjYgXWkXyt9w/edit?usp=sharing), we can easily add the xrefs.

We can also add synonyms etc much the same way, if you have them!

MeSH is still on the horizon for sync, but not immediately. We are working on it, but no super exact timeline. Best guess is December.

**Comment by kanems** [comment]
Just a comment regarding the use of MeSH "Entry terms" as synonyms: not all of the entry terms/synonyms on MeSH concepts are exact synonyms. Case example: https://www.ncbi.nlm.nih.gov/mesh/?term=D007418 
Intestinal pseudo-obstruction is defined as a "functional but not mechanical obstruction of the small intestines" and MSH D007418 seems to have conflated "congenital short bowel" with the pseudo-obstruction concept.
Congenital short bowel (i.e. OMIM 615237 and one phenotype associated with FLNA mutation (see OMIM 300048) ) is a physically distinct presentation due to the length of the small intestine (SNOMED_CT 715201005), NOT the same as a muscle or nervous system disorder affecting gut motility (definition from SNOMED_CT 235825006) 
UMLS has mixed mappings on many CUIs due to naming issues from MeSH and I hope Mondo can avoid that same pitfall.

**Comment by MichaelaEBI** [comment]
@matentzn I filled the spreadsheet with the 85 terms we found now, but I will have another look. Based on my initial work earlier this year I think there are more terms.

**Comment by nicolevasilevsky** [comment]
Thanks @MichaelaEBI! I'll add these to Mondo, thanks for your contribution. 😸

**Comment by nicolevasilevsky** [comment]
@kanems thanks for this info, this is good to know. :)

**Comment by nicolevasilevsky** [comment]
Yes! @MichaelaEBI
