### ISSUE TITLE
[Obsolete] blood protein disease

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4624]
**Mondo term (ID and Label)**
blood protein disease
MONDO:0003804

**Reason for deprecation**
out of scope

**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
What do you think the source annotation should be for "blood protein disease"? (from [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/))

**Comment by nicolevasilevsky** [comment]
did you write this comment that said it was specific to an autosomal disorder? I don't see anything that suggests this was an autosomal disorder- maybe this shouldn't be obsoleted after all (if that is the reason).

If it was though, I think we could use the exclusion reason: MONDO:excludeGeneticFormOfDisease, description: A grouping class that that is characterized by the feature of having a genetic or inheritable component. We don't include these terms in Mondo because it is a grouping class that is not commonly used.

**Comment by sabrinatoro** [comment]
No, I didn't add it was an autosomal disorder... I wonder whether this was added as a wrong "copy/paste". 
I will remove that.

**Comment by nicolevasilevsky** [comment]
I am not sure if this needs to be obsoleted? It seems like a valid class.

**Comment by sabrinatoro** [comment]
I would have to re-listen to the recording of the workshop, but I kind of remember that "blood protein disease" wasn't a useful grouping class. 
It has no definition, and it seems to group things only based on the fact that one of the phenotype is related to a protein in the blood. When you look at the children, it is a mix of immunodeficiency, blood clotting issue, and presence of sulfmethemoglobin in the blood.

**Comment by nicolevasilevsky** [comment]
Ah, okay - so it was mentioned on one of our calls - sounds good! Let's obsolete it.
