### ISSUE TITLE
MONDO:0005493 delayed encephalopathy after acute carbon monoxide poisoning [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4632]
**Mondo term (ID and Label)**
MONDO:0005493 delayed encephalopathy after acute carbon monoxide poisoning 

**Suggested revision and reasons**
Add this as a child of the "poisoning" branch (MONDO:0029000)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems I'm not sure this is correct - this is a phenotype that occurs after poisoning, it is not a type of poisoning. In fact, I'm not sure if this is even an appropriate disease, we should consider obsoleting it.

@sabrinatoro what do you think?

**Comment by sabrinatoro** [comment]
Discussed on the Mondo curation call on March 24, 2022 : 
This term does look like a phenotype, however, HP might not have a post-composed term like this one. Since this is a term that is needed (in EFO based on the x-ref), it is probably ok to keep it in the "poisoning" branch of the ontology (right now, the poisoning branch is a "grab bag" of terms needed elsewhere) until we review and we know how to proceed with this branch. 
Proposal: update the label to make the "poisoning" the major part (for example: acute carbon monoxide poisoning leading to delayed encephalopathy). 
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
sounds good!
