### ISSUE TITLE
MONDO:0004978 "aortic stenosis"

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4636]
**Mondo term (ID Label)**
MONDO:0004978 "aortic stenosis"

**Bug/Typo/Error description**
I am having trouble understanding the scope/intent of this term. 
Definition: "In the same amount or manner; to the same degree; in the role, function, or capacity of. [ NCIT:P378 ]" (Is this the NCIT definition of "as" when used as an adjective? )
Exact Synonyms: AS ; aortic stenosis; rheumatic aortic stenosis; rheumatic aortic valve stenosis

- Is this stenosis (narrowing) of the Aorta at any point Or limited to aortic Valve stenosis (presumablyit's valve limited since it's immediately under aortic valve disease)? IF so, why not merge with MONDO:0042981 (aortic valve stenosis)?

- Why is 'Rheumatic aortic stenosis' an exact syn? Are there no other potential causes of aortic valve stenosis? Perhaps Rheumatic AS should be split out as a separate concept?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems, these are all good points.

We are looking at this more closely and we are going to review the entire 'aortic malformation' branch, as these seem like they could be phenotypes, and we may obsolete these and point to HPO instead.

**Comment by sabrinatoro** [comment]
The current definition definitely doesn't make sense. The definition and the x-ref NCIT:C64938 (not Mondo:equivalent) refer to the word "As". My guess is that it was added to 'aortic stenosis" because it is the same as the abbreviation 'AS'
Therefore, this definition should be updated. 

I think 'aortic stenosis' (MONDO:0004978) and aortic valve stenosis (MONDO:0042981) should be merged. Based on the parentage of 'aortic stenosis', it is inferred that it is referring to the aortic valve.

xref: UMLS:C0155567 ("MONDO:equivalentTo") refers to "rheumatic aortic stenosis". UMLS point to SCTID:72011007, and ICD10CM:I06.0, both are NOT "MONDO:equivalent".  I cannot find enough information that would justify creating a new term for "rheumatic aortic stenosis". However, I think we can make that synonym narrow and update the x-ref. 

To do:
- [ ] update the definition. Maybe use the definition from GARD:0005830:
        - Aortic valve stenosis (AVS) is a condition characterized by narrowing of the heart's aortic valve opening. This narrowing prevents the valve from opening fully, which obstructs blood flow from the heart into the aorta, and onward to the rest of the body. AVS can range from mild to severe. Signs and symptoms typically develop when the narrowing of the opening is severe and may include chest pain (angina) or tightness; shortness of breath or fatigue (especially during exertion); feeling faint or fainting; heart palpitations; and heart murmur. Individuals with less severe congenital AVS (present at birth) may not develop symptoms until adulthood. Individuals with severe cases may faint without warning. AVS can have several causes including abnormal development before birth (such as having 1 or 2 valve leaflets instead of 3); calcium build-up on the valve in adulthood; and rheumatic fever.

- [ ] make "rheumatic aortic stenosis", "rheumatic aortic valve stenosis" narrow synonyms (hasNarrowSynonym)
- [ ] update the x-ref for "rheumatic aortic stenosis" to 'MONDO:mondoIsBroaderThanSource'. These x-ref are: 
        - [ ] UMLS:C0155567 
        - [ ]SCTID:72011007
        - [ ]ICD10CM:I06.0 

- [ ] merge : aortic stenosis (MONDO:0004978) into aortic valve stenosis (MONDO:0042981)

@nicolevasilevsky do you agree?

**Comment by nicolevasilevsky** [comment]
sounds good @sabrinatoro!
