### ISSUE TITLE
Aspiration and anaerobic pneumonias[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4660]
**Mondo term (ID and Label)**
MONDO:0000265 - aspiration pneumonia
MONDO:0004649 - anaerobic pneumonia

**Suggested revision and reasons**
-Aspiration pneumonia isn't inherently an "infectious disease" Should this parentage be removed for this term? (Leave as a child of inflammatory disease)

-Why is anaerobic pneumonia a child of aspiration pneumonia? It seems like this doesn't quite add up; setting it as a child of only bacterial pneumonia (which is, indeed, an infectious disease) seems to make sense.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@pnrobinson could I ask you for some input here? As @kanems points out, aspiration pneumonia is incorrectly classified as an infectious disease based on my understanding.

MONDO_0005249 pneumonia is defined as:
An acute, acute and chronic, or chronic inflammation focally or diffusely affecting the lung parenchyma, caused by an infection in one or both of the lungs (by bacteria, viruses, fungi, or mycoplasma.). Symptoms include cough, shortness of breath, fevers, chills, chest pain, headache, sweating, and weakness.

Do you think the definition of MONDO_0005249 pneumonia should be expanded to include the abnormal entry of fluids into the respiratory tract (based on this: https://www.ncbi.nlm.nih.gov/books/NBK470459/) or should aspiration _not_ be a child of pneumonia (and be reclassified as a child of MONDO_0021166 inflammatory disease?)

thanks!

**Comment by nicolevasilevsky** [comment]
@kanems anaerobic pneumonia a child of aspiration pneumonia because of DOID:873:
https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_873&viewMode=PreferredRoots&siblings=false

It looks like they define anaerobic pneumonia differently than we do. I will exclude this subclassOf relationship and make anaerobic pneumonia a child of 'bacterial pneumonia' and 'anaerobic bacteria infectious disease' only.
Thanks!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro and I moved aspiration pneumonia to a child of lung disease
