### ISSUE TITLE
[NTR] Microcephaly 6 with or without short stature

### ISSUE THREAD

**Issue by marwa-elnagheeb** [monarch-initiative/mondo#4686]
**Preferred term label:**
Microcephaly 6 with or without short stature

**Synonyms**
N/A

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Primary microcephaly refers to the clinical finding of a head circumference more than than 3 standard deviations (SD) below the age- and sex-related mean, present at birth. Primary microcephaly is a static developmental anomaly, distinguished from secondary microcephaly, which refers to a progressive neurodegenerative condition. Microcephaly is a disorder of fetal brain growth; individuals with microcephaly have small brains and almost always have mental retardation, although rare individuals with mild microcephaly (-3 SD) and normal intelligence have been reported. Additional clinical features may include short stature or mild seizures. These clinical features include Seckel syndrome, a rare autosomal recessive disorder characterized by intrauterine growth retardation, dwarfism, microcephaly with mental retardation, and a characteristic 'bird-headed' facial appearance (Shanske et al., PMID: 9128935). MCPH is associated with a simplification of the cerebral cortical gyral pattern and a slight reduction in the volume of the white matter, consistent with the small size of the brain, but the architecture of the brain in general is normal, with no evidence of a neuronal migration defect (Woods et al., PMID: 15806441). Seckel syndrome 4 and autosomal recessive primary microcephaly 6 are currently lumped together into one disease entity per the criteria outlined by the ClinGen Lumping and Splitting Working Group, while more published literature detailing Seckel syndrome 4 may support two split disease entities in the future.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
"microcephaly 6, primary, autosomal recessive" and "Seckel syndrome 4" and "CENPJ"

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
N/A

**Attribution**
This is a request from the ClinGen Syndromic Disorders GCEP. 
@RyanFWebb

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
@marwa-elnagheeb 
Thank you for submitting this issue. 
I have some questions to make sure I understand what is needed, and therefore to ensure that this term is added correctly in Mondo. 

1) Based on your description,  **‘microcephaly 6 with or without short stature’** is a more specific version of both diseases: ‘microcephaly 6, primary, autosomal recessive’ AND ‘Seckel syndrome’. 
Is that correct? 
(or is it the opposite, ‘microcephaly 6 with or without short stature’ would be a grouping term for these 2 diseases?)

2) Could you please review the proposed **definition** for 'microcephaly 6 with or without short stature'?
_(note that the description you submitted will be in the term comment)_
‘Microcephaly 6 with or without short stature’ is a disorder of fetal brain growth; individuals have small brains and almost always have mental retardation, although rare individuals with mild microcephaly (-3 SD) and normal intelligence have been reported.  Clinical features include the features of ‘microcephaly 6, primary, autosomal recessive’ and 'Seckel syndrome', and may include short stature or mild seizures.

Thank you in advance!

**Comment by nicolevasilevsky** [comment]
@marwa-elnagheeb 

Just to clarify, upon first glance I think you are suggesting the new class 'Microcephaly 6 with or without short stature', which is due to a mutation in CENPJ and this should be a parent of 'microcephaly 6, primary, autosomal recessive' and "Seckel syndrome 4" (ie, group these two terms together)?

Thanks!

**Comment by RyanFWebb** [comment]
Hi all,

1. Yes, the conclusion from the ClinGen Syndromic Disorders GCEP was to
group the two terms together due to what is currently published in the
literature with "Microcephaly 6 with or without short stature" being a
grouped, parent term for both "microcephaly 6, primary, autosomal
recessive" and "Seckel syndrome 4".

2. The proposed definition seems to be consistent with the originally
proposed definition, but summarized in a more concise way.

Thank you for following up with this, the email chain had become buried in
my inbox and escaped my attention.

All the best,
Ryan

*Ryan Webb*

Research Associate I

Broad Institute of MIT and Harvard

105 Broadway, Cambridge, MA 02142

***@***.***

207.752.4372

Pronouns: he/him

[image: BroadInstLogoforDigitalRGB.png] <https://www.broadinstitute.org/>

**Comment by nicolevasilevsky** [comment]
Thanks @marwa-elnagheeb! We'll work on this ASAP.
cc @sabrinatoro
