### ISSUE TITLE
Spinocerebellar ataxia with axonal neuropathy type 2 (SCAN2) vs Ataxia-oculomotor apraxia type (AOA2)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#48]
Orphanet merges these concepts

```
[Term]
id: Orphanet:64753
name: Spinocerebellar ataxia with axonal neuropathy type 2
def: "Ataxia with oculomotor apraxia type 2 (AOA2) is a rare autosomal recessive cerebellar ataxia (ARCA; see this term), characterized by progressive cerebellar ataxia associated with frequent oculomotor apraxia, severe neuropathy and an elevated serum alpha-fetoprotein (AFP) level." []
synonym: "AOA2" EXACT []
synonym: "Ataxia-oculomotor apraxia type 2" EXACT []
*synonym: "SCAN 2" EXACT []
synonym: "SCAR1" EXACT []
xref: ICD10:G60.2
xref: OMIM:606002
xref: OMIM:615217
is_a: Orphanet:377788  ! disease
relationship: has_AgeOfOnset Orphanet:409946 ! Childhood
relationship: has_AgeOfOnset Orphanet:409947 ! Adolescent
relationship: has_AgeOfOnset Orphanet:409948 ! Adult
relationship: has_inheritance Orphanet:409930 ! autosomal recessive
relationship: part_of Orphanet:98097 ! Autosomal recessive cerebellar ataxia due to a DNA repair defect
relationship: part_of Orphanet:98497 ! Genetic peripheral neuropathy
relationship: part_of Orphanet:98688 ! Oculomotor apraxia or related oculomotor disease
property_value: definition:citation "orphanet" xsd:string
```

(note the def uses AOA2 and the label uses SCAN2)

Both AOA2 and SCAN2 arise from mutations in SETX and present with the same phenotypes so merge is justified. What we are lacking in a clear way in MONDO to state that what may once have been considered two distinct concepts are now one. We can of course use alternate labels as syns and annotate these. But it would be good to be more explicit somehow, such as a separate synonym type?

of interest reviews often do not acknowledge the other concept/label, all the more reason to be very explicit here:

 - gene reviews AOA2 https://www.ncbi.nlm.nih.gov/books/NBK1154/
 - GARD SCAN2 https://rarediseases.info.nih.gov/diseases/12860/spinocerebellar-ataxia-with-axonal-neuropathy-type-2

**Comment by kanems** [comment]
I am looking for clarification on these disease terms.
OMIM 606002 combines SCAN2, AOA2 and SCAR1 as equivalent/alternate names for the same disorder, as does UMLS/SNOMEDCT (UMLS CUI: C1853761). NCI equates SCAN2 and AOA2 (NCI Thesaurus Code:  C165500) (SCAR1 is apparently no longer represented in NCIT as it's own entity, still attached to SETX wt allele entry). 

However, MONDO represents SCAN2 (MONDO:0018996) as a parent term to AOA3 (MONDO:0014084)  and spinocerebellar ataxia, autosomal recessive 1 (MONDO:0011623) . Based on OMIM, it seems SCAR1 is a "former" term and no longer used; and since it appears that SCAN2 (MONDO:0018996) already encompasses the synonym "SCAR1," is this child term needed? 
And should AOA3 be a child of SCAN2 or rather a sibling (it is also Autosomal recessive, but has a different genetic etiology) ?

**Comment by nicolevasilevsky** [comment]
This is what we currently have:
![image](https://user-images.githubusercontent.com/6722114/102415185-9c0db180-3fac-11eb-904f-9f9b616224ca.png)

**Comment by nicolevasilevsky** [comment]
@kanems is proposing we make MONDO:0014048 a sibling of MONDO:0018996 (this looks confusing, but I think this is how it would look):
![image](https://user-images.githubusercontent.com/6722114/102415415-f9096780-3fac-11eb-8710-b85e1cf0a09a.png)

**Comment by nicolevasilevsky** [comment]
related ticket:
https://github.com/Orphanet/ORDO/issues/11

**Comment by nicolevasilevsky** [comment]
FYI
@galyea-gard
@ahamosh 
@ana-rath-orphanet

**Comment by galyea-gard** [comment]
Spinocerebellar ataxia with axonal neuropathy type 2 and AOA2 are the same. Autosomal recessive spinocerebellar ataxia with axonal neuropathy-1 is the same as Spinocerebellar ataxia with axonal neuropathy type 1 (SCAN1). GARD decided to use AOA2 after a message from an organization back in 2018 but kept the other terms as synonyms. Thank you! Gioconda
