### ISSUE TITLE
Add Chung-Jansen Syndrome as Synonym for PHIP-related...

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#4803]
**Mondo term (ID and Label)**: PHIP-related behavioral problems-intellectual disability-obesity-dysmorphic features syndrome MONDO:0035133

**Synonym to be added**: Chung-Jansen Syndrome

**Synonym subtype: ie, broad/exact/narrow/related**: Exact

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.: PMID: 29209020, https://chungjansensyndrome.eu/en/ 

**Your nano-attribution (ORCID)**: ClinGen ID/Autism GCEP
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@tibingaman Chung-Jansen Syndrome is an exact synonym of 'developmental delay, intellectual disability, obesity, and dysmorphic features'. 

Do you think that PHIP-related behavioral problems-intellectual disability-obesity-dysmorphic features syndrome MONDO:0035133 is in fact the same as 'developmental delay, intellectual disability, obesity, and dysmorphic features' and these two classes should be merged?

Thanks!

**Comment by tibingaman** [comment]
Great question @nicolevasilevsky! I am looping in @ErinRiggs to see if she has any thoughts about this.

**Comment by ErinRiggs** [comment]
Looks like OMIM has "Chung-Jansen" (617991) associated with the gene PHIP.  As you said Nicole, MONDO has Chung-Jansen listed as a synonym to "developmental delay, intellectual disability, obesity, and dysmorphic features" (MONDO:0060712) with a map back to OMIM, as well as the separate term "PHIP-related behavioral problems-intellectual disability-obesity-dysmorphic features syndrome" (MONDO:0035133) with only a map to ORPHA, not OMIM.

I'd argue that the former term is very non-specific (you could be referring to Prader Willi syndrome with that description, for example), so if I had to choose, I'd vote for merging the former in with the latter (the one with the gene name in it) rather than the other way around (so that the term that included "PHIP" was the one of record, with both the OMIM and the ORPHA map, and the synonym Chung-Jansen).  I do think they are referring to the same entity - we did not find evidence for any other distinct condition at this time in our precuration, right @tibingaman?

**Comment by nicolevasilevsky** [comment]
note to self:

`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0060712 MONDO:0035133 -o -f obo mondo-edit.obo`
