### ISSUE TITLE
stage II endometrioid carcinoma

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#490]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004962

This term is listed as a child of stage of disease, which seems wrong. The disease stages should be like "Stage I", stage II etc., although to be honest I do not think that the stages are standardized enough for it to make sense to have ontology terms for stages (which are quite different for different diseases, i.e., stage 1 has no "generic" meaning.

**Comment by cmungall** [comment]
@zoependlington @paolaroncaglia what are your requirements for including specific stages of disease? We only have a handful of these, seems if we do this we do this right and make it complete.

For modeling, it could go either as a subtype of stage (but name would need changed, eg stage S of disease D) or as a subclass of the disease itself. I prefer the former as it doesn't get mixed in with main disease hierarchy

**Comment by paolaroncaglia** [comment]
@cmungall  
I haven't come across cancer stage terms in EFO previously, and I suspect that there may not be an official policy in EFO yet. At a first glance, 'stage I/II endometrioid carcinoma' seem to be the only terms of that kind in EFO (but I haven't had time to look at all search results for 'stage', or to search for 'grade'). We do have EFO:0004925 'tutor stage' with children (and some siblings too) that may be relevant to this discussion, but I agree with @pnrobinson that stage I of cancer X will be different from stage I of cancer Y, so not sure what the best solution is. In EFO, if it's only those 2 terms, I'd just move them under 'endometrioid carcinoma' (rather than 'carcinoma' as they are now). 
@zoependlington @simonjupp any insight or objection please? 
Thanks!

**Comment by paolaroncaglia** [comment]
P.S. The def of the stage II term needs to be edited in both MONDO and EFO, the last sentence is incorrect for stage II and was probably thought for stage I, where it would probably be redundant though. And there's a missing space after the first period.

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I made the same edits in Mondo that you did in EFO

**Comment by cmungall** [comment]
Can we obsolete 'stage of disease' as well, it's now useless as all it was doing was grouping these

**Comment by nicolevasilevsky** [comment]
yes, i created a new PR #958
