### ISSUE TITLE
EDS 6 vs VI

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4918]
**Mondo term (ID Label)**
MONDO:0016002 Ehlers-Danlos syndrome, kyphoscoliotic type 1
MONDO:0034024 Kyphoscoliotic Ehlers-Danlos syndrome

**Bug/Typo/Error description**
Both of these terms suggest an acronym of EDS 6/VI is valid, but this confusing for some of our labs who use MedGen and submit to GTR. 

@ahamosh OMIM uses EDS6 as an alternate name/acronym for EHLERS-DANLOS SYNDROME, KYPHOSCOLIOTIC TYPE, 1; EDSKSCL1 , but might that alternate name also be true of EDSKSCL2, as the more historic descriptor/classifier, aligning with Orpha's representation of these two disorders?  Or @ana-rath-orphanet could the EDS VI name/abbreviation be specific to one of the molecular subtypes of kyphoscoliotic EDS? 
Thank you OMIM and Orphanet teams for looking at this, we'd like to be accurate to your data but we also need to be precise in our terms for submissions.

Also for Mondo team: FKBP22 is no longer the preferred symbol for the causative gene for one of the kyphoscoliotic subtypes, per HGNC, Can the definition on MONDO:0034024 be updated to indicate the current preferred symbol? https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:18625 "FKBP14"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by ahamosh** [comment]
From Joanna and Carol at OMIM:
See 601776 was formerly EDS VIb.  The nomenclature section in this
entry has this explanation:

NOMENCLATURE
The kyphoscoliotic type of Ehlers-Danlos syndrome (see 225400) was at
one time separated into EDS VIA (with lysyl hydroxylase deficiency)
and EDS VIB (with normal lysyl hydroxylase activity). What was
designated EDS VIB is now known to represent 2 distinct entities: the
brittle cornea syndrome (229200), caused by mutation in the ZNF469
gene (612078), and musculocontractural EDS-1.

OrphaNet has EDS VI (kyphoscoliotic due to FKBP2 deficiency) and EDS
VIb (kyphoscoliotic due to lysyl hydroxylase 1 deficiency)

OMIM uses the classification by Malfait et al., 2017 (see 130000).
The Roman numerals are no longer being used.

I hope this is clear.

Joanna

**Comment by nicolevasilevsky** [comment]
> Can the definition on MONDO:0034024 be updated to indicate the current preferred symbol? https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:18625 "FKBP14"

done!

**Comment by nicolevasilevsky** [comment]
@kanems I'm not sure how to properly address this. It seems that type 6 is a proper synonym for both terms. I made the following revisions below on a pull request for Ehlers-Danlos syndrome, kyphoscoliotic type 1

Could you please let me know if you'd like any other revisions?
thanks!

[Term]
id: MONDO:0016002
name: Ehlers-Danlos syndrome, kyphoscoliotic type 1
def: "A form of Ehlers-Danlos syndrome characterized by severe hypotonia and kyphoscoliosis at birth, generalized joint hyperextensibility and ocular globe fragility." [Orphanet:1900]
subset: ordo_disease {source="Orphanet:1900"}
synonym: "EDS 6" EXACT [OMIM:225400]
synonym: "EDS 6 (formerly)" RELATED [GARD:0002083]
synonym: "EDS VI" RELATED [MESH:C536198]
synonym: "EDS VIA" NARROW [Orphanet:1900]
synonym: "EDS, kyphoscoliotic type" EXACT [Orphanet:1900]
synonym: "EDS, oculoscoliotic type" EXACT [Orphanet:1900]
synonym: "EDS6" EXACT ABBREVIATION [MESH:C536198, MONDO:Lexical, OMIM:225400]
synonym: "EDS6A, formerly" RELATED [MESH:C536198]
synonym: "EDSKSCL1" RELATED ABBREVIATION [OMIM:225400]
synonym: "Ehlers-Danlos syndrome kyphoscoliotic type" EXACT []
synonym: "Ehlers-Danlos syndrome oculoscoliotic type" RELATED [GARD:0002083]
synonym: "Ehlers-Danlos syndrome type 6 (formerly)" RELATED [GARD:0002083]
synonym: "Ehlers-Danlos syndrome type 6A" NARROW [Orphanet:1900]
synonym: "Ehlers-Danlos syndrome type 6A (formerly)" RELATED [GARD:0002083]
synonym: "Ehlers-Danlos syndrome, kyphoscoliosis type" RELATED [GARD:0002083]
synonym: "Ehlers-Danlos syndrome, kyphoscoliotic type" EXACT [MESH:C536198, OMIM:225400]
synonym: "Ehlers-Danlos syndrome, kyphoscoliotic type 1" EXACT CLINGEN_PREFERRED []
synonym: "Ehlers-Danlos syndrome, kyphoscoliotic type, 1" RELATED [OMIM:225400]
synonym: "Ehlers-Danlos syndrome, ocular-scoliotic type" RELATED [MESH:C536198, OMIM:225400]
synonym: "Ehlers-Danlos syndrome, oculoscoliotic type" EXACT [Orphanet:1900]
synonym: "Ehlers-Danlos syndrome, type 6" EXACT [MESH:C536198, MONDO:0009160]
synonym: "Ehlers-Danlos syndrome, type 6 A" RELATED [MESH:C536198]
synonym: "Ehlers-Danlos syndrome, type VI" RELATED [MESH:C536198, MONDO:Lexical, OMIM:225400]
synonym: "Ehlers-Danlos syndrome, type VIA" NARROW [MESH:C536198]
synonym: "Ehlers-Danlos syndrome, type Via" NARROW [OMIM:225400]
synonym: "Ehlers-Danlos syndrome, type VIA, formerly" NARROW [MESH:C536198]
synonym: "Ehlers-Danlos syndrome, type Via, formerly" NARROW [OMIM:225400]
synonym: "kEDS" RELATED [GARD:0002083]
synonym: "kyphoscoliotic EDS" RELATED [GARD:0002083]
synonym: "kyphoscoliotic Ehlers-Danlos syndrome" RELATED [GARD:0002083]
synonym: "kyphoscoliotic Ehlers-Danlos syndrome due to lysyl hydroxylase 1 deficiency" EXACT [Orphanet:1900]
synonym: "nevo syndrome" EXACT DEPRECATED [MESH:C536198, OMIM:225400, PMID:19760654]
xref: GARD:0002083 {source="MONDO:Orphanet-shared", source="MONDO:equivalentTo", source="MONDO:OMIM-shared"}
xref: ICD10CM:Q79.6 {source="Orphanet:1900/attributed", source="Orphanet:1900/ntbt", source="Orphanet:1900"}
xref: MESH:C536198 {source="MONDO:equivalentTo"}
xref: NCIT:C125700 {source="MONDO:equivalentTo"}
xref: OMIM:225400 {source="Orphanet:1900/e", source="MONDO:equivalentTo", source="Orphanet:1900"}
xref: Orphanet:1900 {source="MONDO:equivalentTo", source="OMIM:225400"}
xref: SCTID:718211004 {source="MONDO:equivalentTo"}
xref: UMLS:C0268342 {source="MONDO:equivalentTo", source="MONDO:ncbi_mim2gene_medline", source="OMIM:225400", source="NCIT:C125700", source="Orphanet:1900"}
xref: UMLS:CN202461 {source="MONDO:equivalentTo"}
is_a: MONDO:0002254 {source="MONDO:0016002/inferred", source="MONDO:Redundant", source="MONDO:cjm", source="NCIT:C125700/inferred"} ! syndromic disease
is_a: MONDO:0003900 ! connective tissue disorder
is_a: MONDO:0005328 ! eye disorder
is_a: MONDO:0006025 {source="MONDO:Redundant", source="MONDO:linkedlifedata"} ! autosomal recessive disease
is_a: MONDO:0020066 {source="DC-OMIM:225400", source="MESH:C536198", source="MONDO:linkedlifedata", source="NCIT:C125700", source="OMIM:225400", source="Orphanet:1900"} ! Ehlers-Danlos syndrome
is_a: MONDO:0034024 {source="https://orcid.org/0000-0001-5493-2602"} ! kyphoscoliotic Ehlers-Danlos syndrome
relationship: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/9081 {source="MONDO:mim2gene_medgen"} ! PLOD1
relationship: has_modifier HP:0000007 {source="MONDO:HPOA", source="OMIM:225400", source="Orphanet:1900"} ! Autosomal recessive inheritance
relationship: has_modifier MONDO:0021136 ! rare
property_value: confidence "0.6428571428571428" xsd:double
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/4220 xsd:string
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/4918 xsd:string

**Comment by kanems** [comment]
@nicolevasilevsky - so will Mondo be leaving 'EDS6' as the exact on "type 1" Mondo record and 'EDS VI' as exact syn on the parent term that maps to Orpha? MedGen will have to sort those out somehow because our names have to be unique to support GTR and ClinVar condition mapping, but we will do our best to reflect what the community uses as exact synonyms for these conditions. I'll be sure to bring this case up internally so we can determine how best to handle these before the July Mondo release. Thanks for everyone's input here!
