### ISSUE TITLE
Self-Limited Familial Neonatal Seizures

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#4940]
**Mondo term (ID and Label):** Self-Limited Familial and Non-Familial Neonatal Seizures (MONDO:0100023)

**Suggested new label:** self-limited familial neonatal seizures

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)** We have also updated the definition. It is as follows: An epilepsy syndrome associated with infantile period seizures, complete or nearly-complete seizure remission afterwards, usually good developmental outcome, and dominant transmission with high penetrance in pedigrees.  For most affected infants, seizures begin within the first week after term birth.  In a minority, however, seizures can begin after the first week but within the first several months of life.  At onset, seizures may be highly recurrent, and often feature unilateral tonic limb stiffening that may alternate sides from seizure to seizure, accompanied by cyanosis and autonomic features.  Limb shaking movements occur, but not in the evolving rhythmic pattern of tonic-clonic convulsions in older individuals. Neurological examination of the infant is normal between seizures. Although these seizures remit by 4-12 months of age in the majority, 15-30% of those affected have one or more seizure recurrences later, including febrile seizures, focal-onset seizures, and convulsions.  Although most affected children show normal subsequent development, individuals with mild learning difficulties have been reported in families where the majority develop typically.

Additional Information: Scheffer IE, Berkovic S, Capovilla G, et al. ILAE classification of the epilepsies: Position paper of the ILAE Commission for Classification and Terminology. Epilepsia. 2017;58(4):512-521. doi:10.1111/epi.13709    PMID:28276062

**Comment by sabrinatoro** [comment]
Before making changes in the ontology, I want to make sure that these changes will not change the meaning of the current concept, in which case, we should create a new term. Here are my specific questions and concerns: 

- The suggested new definition refers to a “dominant transmission with high penetrance in pedigrees”. This would make the disease concept more specific than the current one. Are “Self-Limited Neonatal Seizures” **always** of dominant transmission? Is it **always** familial, or are there cases when it is non-familial?

- The new definition refers to neonatal seizures (“For most affected infants, seizures begin within the first week after term birth.”) AND infantile seizures (“In a minority, however, seizures can begin after the first week but within the first several months of life.”). We currently have 2 separate terms in Mondo, one for the neonatal seizures (MONDO:0100023) and one for the infantile seizures (MONDO:0100024). This new definition, therefore, seems to refer (if we ignore the dominant transmission, see point above) to a term grouping the two Mondo terms. Do we want such grouping term? Should we merge the two Mondo terms or is there use cases to have a specific term for "neonatal" and "infantile"? 

@nicolevasilevsky @tibingaman @pnrobinson @ahamosh  
Please share your thoughts! Thank you

**Comment by nicolevasilevsky** [comment]
I think @tibingaman is probably the best person to answer these questions (or Ada or Peter).

**Comment by tibingaman** [comment]
@nicolevasilevsky @sabrinatoro I will check in with our experts and get back to you. Thanks for passing these questions along!

**Comment by sabrinatoro** [comment]
Hi @tibingaman, just checking whether you had a chance to check with your experts. Thank you!

**Comment by sabrinatoro** [comment]
Hi @tibingaman, 
could you please let me know if you have any update of this? Thank you!

**Comment by ARosselClinGen** [comment]
Sorry we missed this! Taylor has left the team. We have picked up this issue and will be following up shortly with our group. 

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
thanks @ARosselClinGen!

**Comment by ARosselClinGen** [comment]
Sorry for the delay!

I have just checked with the group and they would like to **modify** the initial request. We will be submitting a new term request and another relabel request for the infantile term (MONDO:0100024). I have addressed your questions below, but please let us know if you'd like additional clarification!

With regard to removing **non-familial**, this was requested because these self-limited familial neonatal seizures are always inherited in an autosomal dominant fashion (I have confirmed this with the group) and the cases in which the epilepsy is _not seen throughout a pedigree_ are due to de novo cases of an autosomal dominant variant. These variants can thus still be inherited in future gerenerations and cause epilepsy despite a lack of history in the family. Therefore, "non-familial" is a misnomer and can cause unnecessary confusion.

We are changing the request to address your point about infantile vs neonatal onset.

We are also requesting the change from "seizures" to "epilepsy" in this term because that is in-line with modern naming practices.

**Mondo term (ID and Label):** Self-Limited Familial and Non-Familial Neonatal Seizures (MONDO:0100023)

**Suggested new label:** Self-Limited Familial Neonatal Epilepsy

**Your nano-attribution (ORCID)**
 Request made on behalf of the ClinGen Epilepsy GCEP

Optional: Any additional information (like supporting evidence, PubMed ID, etc.) 

They would like to modify the existing definition for this term as follows: A neonatal/infantile epilepsy sndrome that is characterized by the onset of seizures that start in the in the neonate between day 1 and 7 of life and are often unilateral clonic events that recur and may alternate sides from seizure to seizure. Seizures can be repetitive over hours to days. Seizures remit by 4-6 months of age. A proportion of those affected may have seizures in later life. The child is expected to have typical developmental progress. [ https://www.epilepsydiagnosis.org/syndrome/self-limited-neonatal-overview.html https://orcid.org/0000-0001-8486-0558 ]

Additional Supporting Evidence: Scheffer IE, Berkovic S, Capovilla G, et al. ILAE classification of the epilepsies: Position paper of the ILAE Commission for Classification and Terminology. Epilepsia. 2017;58(4):512-521. doi:10.1111/epi.13709 PMID:28276062
