### ISSUE TITLE
difference of sexual differentiation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4949]
**Mondo term (ID and Label):**
difference of sexual differentiation

**Suggested new label:**
disorder of sexual development (this is by far the most commonly used term for this class of diseases).
@matentzn can we automatically infer class membership? for instance, 46,xx sex reversal is not a subclass. Should we be annotating this manually?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by matentzn** [comment]
We can certainly hack the subclasses with sparql+regex. I will let @nicolevasilevsky guide me on this!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro could we axiomatize these terms using monochrome (or something else?) so we get automatic inferences for these terms?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky, I don't understand your question... 
Is the assumption that "disorder of sexual development" is always related to a chromosomal anomaly in X or Y chromosome? My thought (without having any expertise) is that it is not especially the case. especially since we now know that sexual development is more complex than just the X and Y chromosome. For instance, there might be a gene on a different chromosome that could be involved in sexual development. 
Also, are ALL the disorders affecting the X and Y chromosome "disorder of sexual development"?

Therefore :
1) I don't think we should axiomatized using monochrome or other genes/chromosomes
2) It might make more sense to axiomatize based on feature? but I don't know if all the Mondo terms would have that feature annotated in Mondo (this annotation could be in Mondo or somewhere else, eg monarch)

**Comment by pnrobinson** [comment]
Not all "disorder of sexual development"s are disorders affecting the X and Y chromosome. However, specific gene mutations manifest differently according to the chromosomal status. One often sees categorizations like this one
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6976999/

**Comment by nicolevasilevsky** [comment]
talking to Peter. Action items:

- [ ] '46,XX testicular disorder of sex development' should be a subclass of '46,XX disorder of sex development'
- [ ] rename gynecomastia to 'gynecomastia disorder', syn 'isolated gynecomastia'
