### ISSUE TITLE
Acquired factor VIII deficiency [NTR]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5040]
**Preferred term label:**
Acquired factor VIII deficiency

**Synonyms**
Factor 8 deficiency, acquired (C536392- MeSH) 
-->MeSH also uses "hemophilia A, acquired" but that is essentially already in use in Mondo for the acquired autoimmune form, so unless you are going to change the preferred name on MONDO:0035735, I would maybe use the MeSH syn foras 'related' synonym but not exact.

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Definition:  An acquired coagulation disorder characterized by the partial or complete absence of factor VIII activity in the blood. (NCI)
https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C35345

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0020599 
**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
No children.

**Xrefs**
UMLS CUI: C0272325
NCIT: C35345
MeSH: C536392 

Looks like GARD is also developing a page for this: https://rarediseases.info.nih.gov/diseases/6405/acquired-hemophilia-a 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
@kanems 
I am trying to understand what the difference between this new term and 'acquired hemophilia a' (MONDO:0035735) would be.
The definition of 'acquired hemophilia a' (MONDO:0035735) suggests an autoimmune cause, but the term is not defined as the autoimmune form. 
definition for MONDO:0035735: An acquired form of hemophilia A, resulting in spontaneous bleeding in individuals with no history of bleeding disorders. It is believed to be caused by spontaneous inhibition of clotting factor VIII by autoantibodies, and is usually associated with other autoimmune conditions.

Therefore, options are: 
Option 1: update the current term 'acquired hemophilia a' (MONDO:0035735),  to include all the x-ref suggested above and reword the definition to make it very clear. The term would include both autoimmune and non-autoimmune form
Option 2: create a new term and clearly distinguish the autoimmune form from the non-autoimmune form
What do you think is the best option? Another way to ask is: do we know whether there is an autoimmune vs non-autoimmune form of acquired hemophiliaA/factor VIII deficiency?
Thank you!

Note to self: the parent term "acquired hemophilia" should be reviewed as orphanet (where the definition comes from) has obsoleted this term.

**Comment by nicolevasilevsky** [comment]
@kanems pinging you, please see the question above - whenever you have a chance, thanks! :eyes:

**Comment by kanems** [comment]
Thanks for the ping, @nicolevasilevsky!
@sabrinatoro I am not an expert on this topic, but ran into this case when trying to map Mondo IDs to terms in our database. Based on UMLS's display of SNOMEDCT and NCI concepts, there are these 'subtypes' of Acquired factor 8 (VIII) deficiency:
Autoimmune factor VIII deficiency (https://uts.nlm.nih.gov/uts/umls/concept/C0585375)
Factor VIII Inactivation(https://uts.nlm.nih.gov/uts/umls/concept/C4329969) (But this is based on an NCI term that is defined as being due to "inactivating antibodies in the blood" NCIT C131666, so we may need to ask NCI if these are assumed to be auto-antibodies or could be exogenous somehow?? Like, post-transfusion maybe? I don't know.)
Idiopathic factor VIII deficiency(https://uts.nlm.nih.gov/uts/umls/concept/C0585374) (SCTID 307514008) 
Malignancy-related factor VIII deficiency(https://uts.nlm.nih.gov/uts/umls/concept/C0585377) (SCTID 307518006)
Pregnancy-related factor VIII deficiency(https://uts.nlm.nih.gov/uts/umls/concept/C0585376) (SCTID 307517001)
I see MeSH uses acquired hemophilia A as a syn, but I am always hesitant to use these synonyms as exact matches, since sometimes they can be a little too broad or cause confusion for the actual intended definition. https://www.ncbi.nlm.nih.gov/mesh/?term=C536392
If the hemophilia naming authorities use type "A" to always indicate Factor 8/VIII as the affected factor, then it stands to reason that the ACQUIRED form of hemophilia affecting factor 8/VIII would also be called "acquired hemophilia A" but that's not something I can speak to with any authority. 

So a quick look around PubMed suggests that multiple authors defined acquired hemophilia A as being caused by autoantibodies against factor VIII (ex https://pubmed.ncbi.nlm.nih.gov/34535289/ , https://pubmed.ncbi.nlm.nih.gov/34095769/ and "similar articles") so perhaps these are indeed the same and the references in my original request above can be added to the current term (MONDO:0035735).
As far as SNOMED/NCI's narrower concepts, as long as the Mondo term is agnostic to the associated/underlying cause of the autoantibody formation, maybe the more narrow concepts don't need to be in Mondo unless another user/community wants those represented (or if Mondo's aim is to have all valid SNOMEDCT concepts represented?) . 
(also, side note, I am not seeing where the OrphaNet concept is obsoleted in v. 4.0 ? http://www.orpha.net/ORDO/Orphanet_599480 is not under the 'inactive' branch;  and then https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=599480 "An Orphanet summary for this disease is currently under development. However, other data related to the disease are accessible from the Additional Information menu located at the bottom of this page.")

**Comment by sabrinatoro** [comment]
> "(also, side note, I am not seeing where the OrphaNet concept is obsoleted in v. 4.0 ? http://www.orpha.net/ORDO/Orphanet_599480 is not under the 'inactive' branch; and then https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=599480 "An Orphanet summary for this disease is currently under development. However, other data related to the disease are accessible from the Additional Information menu located at the bottom of this page.")

It is the parent term, "acquired hemophilia" that has been obsoleted in Orphanet: 
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_73274
