### ISSUE TITLE
Mondo is not updated on Bioportal

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5174]
https://bioportal.bioontology.org/ontologies/MONDO

**Comment by nicolevasilevsky** [comment]
how do we get it updated?

**Comment by kgcl-change-request** [comment]
BioPortal's nightly pull process for MONDO fails due to a known issue, documented mostly in these tickets:

https://github.com/ncbo/ontologies_linked_data/issues/112
https://github.com/ncbo/ncbo_cron/issues/23

We actually have an open pull request from an external developer that I believe would fix this issue. Let me consult with the team to see if we can accept it and get a REST API release out.

**Comment by jvendetti** [comment]
The latest MONDO that I manually uploaded is [available in BioPortal](https://bioportal.bioontology.org/ontologies/MONDO?p=classes) now. This is the version number:

`data-version: releases/2022-07-01/reasoned.owl.owl`

**Comment by matentzn** [comment]
@jvendetti Thank you for dealing with that manually for now:

1. What URL are you using for obtaining mondo? We have no ontology with that `data-version`
2. Is there anything we can do to help moving the fix of the PURL->GitHub release issue along? Many of the key OBO ontologies are published as GitHub releases, including Uberon, Mondo, ZP and they will only become more now.. Also is there a way to see publicly which URLs you are using for downloading all the ontologies in bioportal? For OBO ontologies, do you always use the OBO Purl?

**Comment by jvendetti** [comment]
Hi @matentzn

> What URL are you using for obtaining mondo? We have no ontology with that data-version

I did the following to download the latest MONDO:

- Navigated to the MONDO page at the OBO Foundry website: https://obofoundry.org/ontology/mondo.html
- Clicked on the "mondo.obo" link in the "Products" section

With the developer console open in the browser, I can see that clicking on that link results in the following series of redirects:

```
GET http://purl.obolibrary.org/obo/mondo.obo
GET https://github.com/monarch-initiative/mondo/releases/latest/download/mondo.obo
GET https://github.com/monarch-initiative/mondo/releases/download/v2022-07-01/mondo.obo
```
... and here is the first 5 lines of the resulting download that shows the data-version attribute:

```
format-version: 1.2
data-version: releases/2022-07-01/reasoned.owl.owl
subsetdef: clingen "initial subset used by clingen"
subsetdef: disease_grouping "disease_grouping"
subsetdef: do_inheritance_inconsistent "classes where the corresponding DO term is both AR and AD https://github.com/monarch-initiative/monarch-disease-ontology/issues/406"
```

If there's a different file you'd like me to manually upload, let me know.

> Is there anything we can do to help moving the fix of the PURL->GitHub release issue along?

I'm looking into this now, and hope to have something in place by next week. I'll follow up if something goes awry.

> Also is there a way to see publicly which URLs you are using for downloading all the ontologies in bioportal?

We don't offer a page with this sort of listing. Each BioPortal user has access to this information for the ontologies that they maintain. I looked at MONDO and see that I'm the only person with administrative access. If you or others in your group have BioPortal accounts, I'm happy to add you as MONDO administrators so that you can access/modify your ontology metadata.

> For OBO ontologies, do you always use the OBO Purl?

Not necessarily - we don't have an official policy for this. Essentially it's up to the person who submits the ontology to specify the URL they'd like to use.

**Comment by matentzn** [comment]
@jvendetti thank you for your detailed report. It lead me to fix some oddity in the version IRI #5181 :)

Is there any reason you use the mondo.obo instead of mondo.owl (which is more complete)?

**Comment by jvendetti** [comment]
@matentzn - BioPortal calculates and displays a series of metrics for every ontology:

![Screen Shot 2022-07-15 at 9 18 34 AM](https://user-images.githubusercontent.com/1696923/179265077-3e2d86c1-933d-42e7-8440-4e7cd1410972.png)

... and this part of the processing fails for mondo.owl. See https://github.com/ncbo/bioportal-project/issues/125 for full details. We've been serving the OBO version since this issue was reported.

Something occurs to me - @stdotjohn is in the process of refactoring the code to calculate max depth. When the new code is committed, we should test against mondo.owl to see if the problem persists.

**Comment by matentzn** [comment]
Thank you @jvendetti

**Comment by jvendetti** [comment]
@matentzn - I performed a production release yesterday that contained the fix for the PURL -> GitHub release issue. I reinstated the pull URL (http://purl.obolibrary.org/obo/mondo.obo) for MONDO and verified that BioPortal successfully pulled the source file from GitHub. Going forward, the nightly pull process should automatically pick up new versions.
