### ISSUE TITLE
Legg-Calve-Perthes disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#521]
It is not correct to classify this disease as a type 2 collagenopathy (as is currently done in MONDO, see 
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0007885).

It is also not a Mendeiian disease although this feature can be seen in some Mendelian diseases.

The primary classification could be disease of the hip

https://en.wikipedia.org/wiki/Legg%E2%80%93Calv%C3%A9%E2%80%93Perthes_disease

**Comment by cmungall** [comment]
Agreed. @Orphanet do you have opinions on this?

The classification comes from ORDO:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2380

I assume that this is because in OMIM we have: https://omim.org/entry/150600 associated with COL2A1

If we believe there is a familial disease susceptibility we should have a separate class.

Note I have also added this to the pheno-group-obsoletion project

**Comment by courtneythaxton** [comment]
You are right we have not reviewed this gene for the full lumping and splitting, it was curated for spondyloepiphyseal dysplasia, Stanescu type  MONDO:0014701. 

I agree with the principle that if this is a susceptibility gene to certain phenotypes, and not Mendelian, then there should be some caution to the classification of the diseases. 

I"ll update you all if we go through this Lumping and splitting, I am putting it on my list for procuration :)
