### ISSUE TITLE
Update enum file for exclusion reasons

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5270]
The enum file (https://github.com/monarch-initiative/mondo/blob/master/src/schema/mondo.yaml) should be updated to add the updated exclusion reasons. 
The exclusion reasons can be found [here](https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180) and [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/)

**Comment by joeflack4** [comment]
I'm on it!

**Comment by joeflack4** [comment]
@sabrinatoro Just wanted to let you know I made some minor edits to the [exclusion reasons tab of that google sheet](https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180).
1. Simplified header names
2. Added a comment to the `exclude_children` header
3. Collapsed A-D into a single column (I looked, and there was no reason for these cells to be merged anyway)

I added a version name to the file before and after my changes, just in case you want to revert.

**Comment by joeflack4** [comment]
@sabrinatoro I did a check to see if there were any exclusion reasons listed in the [Mondo LinkML schema enum](https://github.com/monarch-initiative/mondo/blob/master/src/schema/mondo.yaml) but not located in the [GoogleSheet](https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180), and I found these:

```
excludeClinicalModifier
excludeConditionsCausedByExternalForce
excludeCausingAgents
excludePresenceOfEnvironmentalMaterials
excludeGeneticCarrier
excludeGeneticFormOfDisease
excludeGroupingClass
excludePhenotypeForMetastasis
excludePhenotypeForTumor
excludeRare
excludeConditionsCausedByExternalFactor
excludeBehavior
excludeTraumaticCause
```

I just want to check; are these missing from the GoogleSheet because they don't need any updates, or do they need to be added to it?

I'm writing a script to update from the GoogleSheet, so future updates to the schema enum should be fairly painless.

**Comment by sabrinatoro** [comment]
@joeflack4 these missing ones are "old" codes that should be deleted (and not used anymore).

**Comment by joeflack4** [comment]
Oh OK, I will delete them then.
