### ISSUE TITLE
acute stress reaction

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#532]
This is not a mental disorder, it is a normal response to an abnormal situation! I am not sure where to put this term, but this part of MONDO needs revision and expert TLC.

**Comment by cmungall** [comment]
cc @paolaroncaglia; from EFO

**Comment by cmungall** [comment]
We shouldn't have reactions at all. This should have been merged with MONDO:0003763 acute stress disorder

This is what NCIT says

```
 / NCIT:C7057 ! Disease, Disorder or Finding
  is_a NCIT:C2991 ! Disease or Disorder
   is_a NCIT:C2893 ! Psychiatric Disorder
    is_a NCIT:C2878 ! Anxiety Disorder
     is_a NCIT:C92621 ! Acute Stress Disorder *** 
```

_An anxiety disorder precipitated by an experience of intense fear or horror while exposed to a traumatic (especially life-threatening) event. The disorder is characterized by dissociative symptoms; vivid recollections of the traumatic event; avoidance of stimuli associated with the traumatic event; and a constant state of hyperarousal for no more than one month._ [NCIT:C92621]

I think we can do a much better job with mental/psychiatric disorders, this is not trivial and needs a lot of work but I think what we have is an OK starting point

**Comment by paolaroncaglia** [comment]
@cmungall @pnrobinson 
Thanks for pointing this out. I agree that classification under mental disorders is tricky. At first sight, one could say that the classification of 'anxiety disorder' in EFO is less problematic than in MONDO because its parent is labeled 'mental _or behavioural_ disorder' rather than just 'mental disorder'. 
This said, the definition of EFO:0000677 'mental or behavioural disorder' leaves little space for non-strictly-psychiatric disorders ("Psychiatric illness or diseases manifested by breakdowns in the adaptational process expressed primarily as abnormalities of thought, feeling, and behavior producing either distress or impairment of function (MeSH)."; "Disorders in which there is a loss of ego boundaries or a gross impairment in reality testing with delusions or prominent hallucinations. (From DSM-IV, 1994)"; Synonyms: Psychiatric Disorder, Disorders, Psychotic, Disorder, Psychotic, Psychotic Disorder, mental disorders, Behavior Disorder, disease of mental health, Psychoses, Reactive Psychosis, Brief, PSYCHOTIC DIS, Psychosis, Brief Reactive, Brief Reactive Psychoses, Psychotic Disorders, mental or behavioral disorder, Psychoses, Brief Reactive, Brief Reactive Psychosis, Mental Disorder, Reactive Psychoses, Brief).
EFO would certainly be interested in how MONDO solves this classification issue, so I'll open an EFO ticket to keep track. Thanks.

**Comment by pnrobinson** [comment]
I do not think that acute stress reaction is necessariiy a disease and it could just as well be conceptualized as a phenotype. I think that the way we are modeling the corresponding branches in MONDO and HPO still needs a certain amount of work. We are probably going to be having a workshop about this at the Sanger in 2019 for the HPO but perhaps we should try to include MONDO as well.

**Comment by nicolevasilevsky** [comment]
is there an action item here? Do we want to merge acute stress reaction with MONDO:0003763 acute stress disorder or just obsolete it altogether? And add it as a phenotype to HPO? (I don't see it in HPO)

**Comment by nicolevasilevsky** [comment]
pinging @cmungall and @pnrobinson

**Comment by pnrobinson** [comment]
acute stress reaction can be modeled as a disease or phenotype I would say
https://en.wikipedia.org/wiki/Acute_stress_reaction
according to WP they are synonyms.

I doubt thought that ASR is really a homogeneous disease that we can easily definie computationally, and would guess that it is a convenience phrases used mainly to describe commonly encountered symptoms. Still that is not a reason for not including it in mondo, but I would say let us try to follow DSM for this sort of term.


Possibly we should distinguish from acute stress reactant
https://clinicaltrials.gov/ct2/show/NCT01304537

**Comment by maglott** [comment]
Seems SNOMED (https://www.ncbi.nlm.nih.gov/medgen/116022)  and wikipedia treat acute stress reaction and acute stress disorder as alternate terms for the same concept, but MeSH does not
https://www.ncbi.nlm.nih.gov/mesh?LinkName=medgen_mesh&from_uid=116022. So no clear answer; seems DSM should be the authority.

**Comment by nicolevasilevsky** [comment]
@cmungall could you clarify the action item here? Should we obsolete acute stress reaction from Mondo? @pnrobinson should it be added to HPO?

**Comment by pnrobinson** [comment]
I think we need to make an editorial decision or to get expert advice. I think we could model the concept either as a disease, a phenotype, or both.

**Comment by nicolevasilevsky** [comment]
We could send an email out to the Mondo users list and see if any experts weigh in?

**Comment by nicolevasilevsky** [comment]
looks like acute stress reaction has been obsoleted and merged with acute stress disorder.

closing, reopen if further action is needed
