### ISSUE TITLE
neurodevelopmental disease parentage is circular in OLS

### ISSUE THREAD

**Issue by sambaxter** [monarch-initiative/mondo#537]
In OLS the same name is used multiple times in multiple branches which is confusing
![image](https://user-images.githubusercontent.com/19212392/49179049-6c38d600-f31f-11e8-8d4b-05e4d6f86814.png)

**Comment by cmungall** [comment]
@sambaxter, this is actually the same concept with multiple parentage, the OLS shows multiple parentage by showing different linearizations/trees. @simonjupp anything we can do to make this more obvious

note to all: the confusion is compounded here because "complex neurodevelopmental disorder" should really be a high level concept with little or no multiple inheritance. This will be simplified after we get rid of the rare-X groupings (#254) and some of the other groupings from ORDO. But still, there are other examples of genuine multiple parentage and it would be good to have the display default to something intuitive

**Comment by paolaroncaglia** [comment]
@cmungall @simonjupp 
I opened an OLS ticket, https://github.com/EBISPOT/OLS/issues/232

**Comment by nicolevasilevsky** [comment]
I think this has been addressed
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100038

Please reopen if further action is needed
