### ISSUE TITLE
sulfhemoglobinemia

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#539]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006988

This disease is mistakenly classified as an immune system disease

**Comment by cmungall** [comment]
@paolaroncaglia we got this from EFO, 

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1001200

I think we should classify this under
MONDO:0005570 ! hematological system disease

any objections?

**Comment by paolaroncaglia** [comment]
@cmungall @pnrobinson 
Thanks for catching this. I agree and made a ticket in EFO (https://github.com/EBISPOT/efo/issues/323).

**Comment by nicolevasilevsky** [comment]
This is currently also classified under 'blood protein disease', which is a child of 'hematological system disease'. I'll remove the parent 'immune system disease'. Let me know though if you'd like it to be a direct subclass of 'hematological system disease' instead of a child of 'blood protein disease'.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks. In EFO, I'll make 'sulfhemoglobinemia' a direct child of 'hematological system disease'. The disorder stems from incorporation of a "wrong" sulfur atom into an otherwise correct haemoglobin protein, so I'm not entirely sure that it is a type of 'blood protein disease', though I can see the rationale behind that and I don't object. EFO doesn't have 'blood protein disease' and I think we might avoid adding it for now (though it may get imported from MONDO in EFO 3, I haven't checked yet). BTW, I notice that MONDO also has 'sulfhemoglobinemia, congenital' that is undefined and sits under 'inherited genetic disease'... :-)

**Comment by pnrobinson** [comment]
Can we just say "Hematologic disease" instead of 'hematological system disease', which seems redundant and wordy? Or consider "Blood disorder"?

**Comment by nicolevasilevsky** [comment]
See PR: https://github.com/monarch-initiative/mondo/pull/571

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I added the parent sulfhemoglobinemia to 'sulfhemoglobinemia, congenital' on the PR.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I relabeled 'hematological system disease' to 'Hematologic disease' on the PR
