### ISSUE TITLE
Atypical Rett syndrome vs. Rett syndrome, congenital variant

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo#54]
Hello.  The ClinGen ID/Autism WG is curating FOXG1 (OMIM term 613454, "Rett syndrome, congenital variant," and ORPHANET term 3095, "Aytpical Rett syndrome").  Both OMIM and Orphanet cross reference each other here, but MONDO has terms for both (MONDO:0017746 and MONDO:0013270).  Which one should we use?  They appear to be the same thing, but please let me know if that is incorrect.

Thanks,
Erin

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/tbn)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by cmungall** [comment]
My understanding, informed by 
https://rarediseases.info.nih.gov/diseases/4694/atypical-rett-syndrome is that the name "Atypical Rett" encompasses different disease entities sometimes caused by different genes.

One of those forms is called the "congenital variant" which to me is confusing since others are also congenital, but this string refers to a distinct form (_the most severe form of atypical Rett syndrome, with onset of classic Rett features during the first three months of life. This variant is generally caused by mutations in the FOXG1 gene_).

We include two subtypes:

* [MONDO:0017746](http://purl.obolibrary.org/obo/MONDO_0017746) ! atypical Rett syndrome  
     * [MONDO:0010396](http://purl.obolibrary.org/obo/MONDO_0010396) ! epileptic encephalopathy, early infantile, 2 (CDKL5)
     * [MONDO:0013270](http://purl.obolibrary.org/obo/MONDO_0013270) ! Rett syndrome, congenital variant (FOXG1)

The [the OMIM entry](https://omim.org/entry/300672) specifically says "There is some phenotypic overlap with Rett syndrome (312750), but EIEE2 is considered to be a distinct entity (summary by Fehr et al., 2013)". But note this is talking about classic Rett rather than Atypical.

The MONDO hierarchy is consistent with the Orphanet BTNT calls, see:
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_3095

Note also that orphanet has 4 different genes implicated for the generic Atypical Rett

It gets a bit more confusing, as OMIM seems to bundle the preserved speech variant of Atypical Rett in with (Classic) Rett, presumably based on  MECP2. It seems there is tension between a gene-based classification and a phenotype based one. My inclination would be to make a new subtype of Atypical Rett specifically for the PSV, consistent with GARD. But my inclination is also to wait till the epilepsy group have completed their first pass. However, if you can provide some additional info or thoughts in classification here we can implement them.

**Comment by nicolevasilevsky** [comment]
@ErinRiggs can this be closed?

**Comment by ErinRiggs** [comment]
I think so - looks like we ended up using MONDO:0100040 (FOXG1 disorder) for this particular curation.

**Comment by nicolevasilevsky** [comment]
great, thanks!
