### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by psiotwo** [monarch-initiative/mondo#5429]
**Mondo term (ID Label)**
MFOMD_0000004 
MONDO_5084

**Bug/Typo/Error description**
They seem to share label (as well as other 12 pairs in MONDO import closure). Not a domain expert, so not advising on any type of resolution (e.g. merging concepts).

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-6299-4766

**Comment by nicolevasilevsky** [comment]
Hi @psiotwo- thanks for the ticket, we'll look into this asap. :)

**Comment by nicolevasilevsky** [comment]
Hi @psiotwo - sorry for the delayed reply. It looks like this particular MFOMD term was imported via OGMS, and it is a disease course, vs a disease. We've taken a different approach to classifying mental disease, where it is a child of MONDO:0000001 'disease'.

I imagine the other duplicate terms may be due to similar circumstances.

I will close this ticket, but if there is any action required, please feel free to reopen. Thanks!
