### ISSUE TITLE
cervical aortic arch

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#543]
cervical aortic arch is mistakenly listed as integumentary system disease

**Comment by pnrobinson** [comment]
many of the children of integumentary system disease are wrong, please check for some systematic issue!

**Comment by nicolevasilevsky** [comment]
@pnrobinson we are getting this inferred superclass because of this subclassOf axiom:
'disease has location' some 'pharyngeal arch artery'

@cmungall would the best approach be to remove that axiom?

![image](https://user-images.githubusercontent.com/6722114/50114587-bcf26f00-01f9-11e9-8073-6d737dbc27db.png)

**Comment by nicolevasilevsky** [comment]
@pnrobinson which other classes are incorrectly inferred to be subclasses of 'integumentary system disease'?

**Comment by pnrobinson** [comment]
integumentary system is basically skin and things that grow on the skin. It has no relation to pharyngeal arch that I know of.

**Comment by nicolevasilevsky** [comment]
in Uberon pharyngeal arch is a child of protuberance, which is a child of surface structure, which is part of integumental system.

**Comment by cmungall** [comment]
ugh, this will be fixed

**Comment by nicolevasilevsky** [comment]
I think we need to regenerate the Uberon import in order to see this fix

**Comment by nicolevasilevsky** [comment]
I think this has been fixed! Thanks @pnrobinson and @cmungall. Closing.
