### ISSUE TITLE
[potential merge] 'hypercalciuria, absorptive, 2' and 'idiopathic inherited hypercalciuria'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5503]
**Mondo term (ID and Label)**
MONDO:0007748 'hypercalciuria, absorptive, 2'

**Reason for deprecation**
I think MONDO:0007748 'hypercalciuria, absorptive, 2' ([https://omim.org/entry/143870](https://omim.org/entry/143870)) is the same as MONDO:0016352 'idiopathic inherited hypercalciuria' ([ORPHA:2197](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=2197)). The same gene is implicated and the descriptions seem similar. I think this is a kidney disease that predisposes towards kidney stones.

I'm not sure if it should be a 'inherited disease susceptibility' or a proper renal disease.

**Term to be merged with**
MONDO:0016352 'idiopathic inherited hypercalciuria'

Adding this to November release for you to review. If you agree, we'll need to add the obsoletion tag. Thanks for reviewing this.

**Comment by sabrinatoro** [comment]
I don't think it is correct: 

'idiopathic inherited hypercalciuria' (MONDO:0016352) 
= Orphanet:2197
= parent term, no associated gene, 

children = 
- 'hypercalciuria, absorptive, 2' (MONDO:0007748) = OMIM:143870
= 'idiopathic inherited hypercalciuria'
 and ('has material basis in germline mutation in' some ADCY10)
- 'hypercalciuria, absorptive, 1' (MONDO:0011802) = OMIM:607258

Also, in the definition of the Orphanet:2197 record, I don't see a reference to a gene. 

Therefore, I don't think 'idiopathic inherited hypercalciuria' (MONDO:0016352)  and 'hypercalciuria, absorptive, 2' (MONDO:0007748) should be merged.

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@sabrinatoro where are you looking at the Orphanet term?

On this [page](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3625&Disease_Disease_Search_diseaseGroup=2197&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Idiopathic-hypercalciuria&title=Idiopathic%20hypercalciuria&search=Disease_Search_Simple), it links to this [gene](https://www.orpha.net/consor/cgi-bin/Disease_Genes_Simple.php?lng=EN&LnkId=3625&Typ=Pat&diseaseType=Gen&from=rightMenu).

And it is also shown in OLS [here](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2197), I pasted a screenshot below:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/6722114/196254270-769e95be-fb51-46a7-a0a1-57c80d7a8330.png">

**Comment by sabrinatoro** [comment]
> On this [page](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3625&Disease_Disease_Search_diseaseGroup=2197&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Idiopathic-hypercalciuria&title=Idiopathic%20hypercalciuria&search=Disease_Search_Simple), it links to this [gene](https://www.orpha.net/consor/cgi-bin/Disease_Genes_Simple.php?lng=EN&LnkId=3625&Typ=Pat&diseaseType=Gen&from=rightMenu).

I do not see that the gene is related to the disease on the disease page. The etiology section says:
"(...) Genetic susceptibility to absorptive IH is correlated to mutations on the ADCY10 gene (...) pathological elevation of tissue vitamin D receptor (VDR) level is suggested as a molecular basis* of IH (...)"
*granted, we don't know which actual gene is responsible for this. It could be ADCY10, though there might be other genetic reasons. 
In other word, there are potentially more than ADCY10 involved in the disease
Also, this orphanet id maps to 2 omim terms. 


> And it is also shown in OLS [here](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2197)

Related from: disease-causing germline mutation(s) in
Does not appear to mean that the disease is caused by mutation in gene X. 
It appears that it means that the disease is related to/includes version of the disease for which the gene is responsible.

Supporting evidence for this: [Usher syndrome type 2](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_231178)
![Screen Shot 2022-10-17 at 11 46 25 AM](https://user-images.githubusercontent.com/12737987/196257878-17f0c3c3-ff52-418f-934c-f619fc00d443.png)

'Usher syndrome type 2' is a grouping term that includes 
~type 1B (caused by mutation in myosin VIIA) ---> not correct? 
~type 2C (caused by mutation in adhesion G protein-coupled receptor V1)
~type 2A (caused by mutation in usherin)
~type 2D (caused by mutation in whirling)

**Comment by nicolevasilevsky** [comment]
Ah, I see! Thanks for looking into this so closely. If you don't think these should be merged, we can close this ticket. Thanks for looking into this!
