### ISSUE TITLE
tissue agnostic cancers

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5538]
Two recommendations for tissue agnostic cancers (specific molecular alterations across multiple cancer types) in attached spreadsheet. Please let me know if you have questions - I understand that this may not fit well into this system but would be happy to discuss further. Thanks.
[TISSUE_AGNOSTIC_CANCERS.Github_MONDO.Recommendations.xlsx](https://github.com/monarch-initiative/mondo/files/9883230/TISSUE_AGNOSTIC_CANCERS.Github_MONDO.Recommendations.xlsx)

**Comment by nicolevasilevsky** [comment]
Thanks @OOPD-LJF, we'll look at this asap.

Note to self - I added the spreadsheet contents below.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/nicolevasilevsky/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/nicolevasilevsky/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Preferred   term Label | Synonyms | Definition | PMID | PARENT Term | CHILDREN Term | Nano-Attribution   (ORCID)
-- | -- | -- | -- | -- | -- | --
Neurotrophic   Tyrosine Receptor Kinase (NTRK) Fusion-positive Solid Tumors |   | NTRK fusion-positive tumors have   been identified in a broad range of solid tumor types, including breast,   cholangiocarcinoma, colorectal, gynecological, neuroendocrine, non-small cell   lung, salivary gland, pancreatic, sarcoma and thyroid cancers. | 30333516 | neoplastic disease or syndrome |   | 0000-0001-7151-1615
RET   fusion-positive solid tumors |   | RET mutations influence disease   in a variety of organ systems from Hirschsprung’s disease and multiple   endocrine neoplasia 2 (MEN2) to papillary thyroid carcinoma (PTC) and   non-small cell lung cancer (NSCLC). Changes in RET expression have been   discovered in 30–70% of invasive breast cancers and 50–60% of pancreatic   ductal adenocarcinomas in addition to colorectal adenocarcinoma, melanoma,   small cell lung cancer, neuroblastoma, and small intestine neuroendocrine   tumors. | 31715421 | neoplastic disease or syndrome |   |  



</body>

</html>

**Comment by sabrinatoro** [comment]
We could add an axiom like the one we added for MONDO:0006244 : 'HER2 positive breast carcinoma' = 'breast cancer' and ('disease has feature' some 'HER2/Neu Positive')

NCIT terms exist: 
- RET Fusion Positive (http://purl.obolibrary.org/obo/NCIT_C131069)
- NTRK Fusion Gene Positive (http://purl.obolibrary.org/obo/NCIT_C183255)

Question: 
- are the terms "RET fusion-positive solid tumor" and "NTRK Fusion-positive Solid Tumor" diseases (and therefore would be in Mondo) or phenotypes? 
- if they are to be added in Mondo, the parent should probably be "neoplasm", however there are no term that have only "neoplasm" as a parent. Is that ok?

**Comment by OOPD-LJF** [comment]
Sorry I haven't replied on this one yet - I do think the terms "RET fusion-positive solid tumor" and "NTRK Fusion-positive Solid Tumor" ARE diseases and not phenotypes. I also think it is reasonable to have its parent as "neoplasm". Thanks.

**Comment by sabrinatoro** [comment]
These new terms will be added into Mondo. @OOPD-LJF, could you please review them as I have made a few changes in the definitions and labels. If it is ok with you, we can merge the PR, and the terms will be available after the next release

1) **NTRK fusion-positive cancer** : MONDO:0700215

_Synonyms_: 
- NTRK fusion positive neoplasm
- NTRK fusion positive solid tumor
- neurotrophic tyrosine receptor kinase fusion positive solid tumor
- neurotrophic tyrosine receptor kinase fusion positive neoplasm
- neurotrophic tyrosine receptor kinase fusion positive cancer

_Definition_: 
Neoplasm defined by the expression of a Neurotrophic Tyrosine Receptor Kinase (NTRK) Fusion. NTRK fusion-positive tumors have been identified in a broad range of solid tumor types, including breast, cholangiocarcinoma, colorectal, gynecological, neuroendocrine, non-small cell lung, salivary gland, pancreatic, sarcoma and thyroid cancers.

2) **RET fusion positive cancer** : MONDO:0700216

_Synonyms_: 
- RET fusion positive neoplasm
- RET fusion positive solid tumor

_Definition_: 
Neoplasm defined by the expression of a RET (REarranged during Transfection) Fusion. 
_(Note: I didn't include the part about the mutations in RET since it is different from the fusion protein)_



NOTE: the equivalents will need to be added once we added the NCIT terms into Mondo. 
_MONDO:0700215 Equivalent:_ 
'Neoplasm' and ('disease has feature' some 'NTRK Fusion Gene Positive')
Where ‘NTRK Fusion Gene Positive’ = http://purl.obolibrary.org/obo/NCIT_C183255)

_MONDO:0700216 Equivalent:_ 
'Neoplasm' and ('disease has feature' some 'NTRK Fusion Gene Positive')
Where 
RET Fusion Positive (http://purl.obolibrary.org/obo/NCIT_C131069)

**Comment by sabrinatoro** [comment]
Thank you @OOPD-LJF. I have updated the definitions.
