### ISSUE TITLE
[NTR] Microcephaly with lissencephaly and/or hydranencephaly

### ISSUE THREAD

**Issue by Bryannavanhoute** [monarch-initiative/mondo#5582]
**Preferred term label:**
Microcephaly with lissencephaly and/or hydranencephaly

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A brain disorder caused by biallelic variants in NDE1 that is characterized by extreme microcephaly (typically head circumference of more than 10 standard deviations (SD) below the mean), profound motor and intellectual disability, spasticity, and incomplete cerebral formation. Radiologic studies demonstrate overt microcephaly with cortical dysgenesis ranging from simplification to pachygyria/lissencephaly to hydranencephaly.  Agenesis of the corpus callosum as well as hypoplasia of the brainstem and cerebellum are typically present. (PMIDs 21529751, 22526350)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Microcephaly MONDO: 0001149

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Lissencephaly 4 and Microhydranencephaly

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Requested by the ClinGen Brain Malformations GCEP (https://www.clinicalgenome.org/affiliation/40020/)

CC: @ErinRiggs

**Comment by sabrinatoro** [comment]
Based on the definitions, I don't think that 'lissencephaly 4' (MONDO:0013527) and 'NDE1-related microhydranencephaly' (MONDO:0011504). When these diseases include "microcephaly" among their features/symptoms, I don't know that they are "microcephaly". 
Also: microcephaly is a "neurodevelopmental disorder", but these terms suggested children terms are "cerebral malformation". Is that correct? Should microcephaly be a "cerebral malformation" instead of a "neurodevelopmental disorder"? 
@nicolevasilevsky, what do you think?

**Comment by ErinRiggs** [comment]
The experts in the Brain Malformations GCEP requested that this be considered a type of microcephaly.  I am happy to connect you with one of our chairs via email, but they are not on GitHub.  Let me know if you'd like me to make that connection.

-Erin

Erin Rooney Riggs, MS, CGC
Assistant Professor
Autism & Developmental Medicine Institute
Geisinger
***@***.***
________________________________
From: sabrinatoro ***@***.***>
Sent: Tuesday, November 8, 2022 5:57 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Riggs, Erin ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] [NTR] Microcephaly with lissencephaly and/or hydranencephaly (Issue #5582)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


Based on the definitions, I don't think that 'lissencephaly 4' (MONDO:0013527) and 'NDE1-related microhydranencephaly' (MONDO:0011504). When these diseases include "microcephaly" among their features/symptoms, I don't know that they are "microcephaly".
Also: microcephaly is a "neurodevelopmental disorder", but these terms suggested children terms are "cerebral malformation". Is that correct? Should microcephaly be a "cerebral malformation" instead of a "neurodevelopmental disorder"?
@nicolevasilevsky<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnicolevasilevsky&data=05%7C01%7Ceriggs%40geisinger.edu%7C4ca41af0cfaf47d4ef0108dac1e50424%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638035486621071600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mFNzgmqe%2FDqAAgmkvXyqX6trcbe8s%2Fiv79VDFzHVtRg%3D&reserved=0>, what do you think?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F5582%23issuecomment-1307996712&data=05%7C01%7Ceriggs%40geisinger.edu%7C4ca41af0cfaf47d4ef0108dac1e50424%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638035486621071600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wv2Cnczj9JelB4eSO3lyyFnFUZIgQn5D1Gf6yu1NGno%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFJTFF7UULVNWGGFAJZTOTWHLSHDANCNFSM6AAAAAAR2QMHTY&data=05%7C01%7Ceriggs%40geisinger.edu%7C4ca41af0cfaf47d4ef0108dac1e50424%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638035486621071600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U4TBzHAzLPwuCv0KsM7puNSBTJNDtxR%2Bo50q%2BlHaMrA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by nicolevasilevsky** [comment]
Hi @ErinRiggs discussing with the experts over email sounds like the best next step, thank you!

**Comment by nicolevasilevsky** [comment]
per email, I think this is what we want:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/6722114/202820310-06b2636d-db7b-4de8-9304-3e2225b300d8.png">

**Comment by sabrinatoro** [comment]
email: 
 neither of the current Mondo terms are subordinate (child term) to microcephaly currently. So the request we made would be refining the current terminology (without disposing of the old ones by subordinating the existing terms to the new ones). Microcephaly is severe in this NDE1 disorder but is not generally the only finding so I don’t know that it is mandatory to put another child term to microcephaly for NDE1 (I am agnostic).

Many people would consider microcephaly a disorder of neuronal precursor proliferation and a form of malformation. It would not be unreasonable to duplicate it under the “cerebral malformation” tree though I am not sure how many times an item can be duplicated inside of the ontology.

**Comment by Bryannavanhoute** [comment]
We reviewed this ticket today and understood there to be outstanding questions, but see it has been closed.  Has everything been resolved?

**Comment by nicolevasilevsky** [comment]
@sabrinatoro reopening - please let us know if everything is resolved and if yes, please close. thanks!

**Comment by sabrinatoro** [comment]
@Bryannavanhoute Thank you for checking. 
I believe all the questions were answered. 
In order for the new term to be correct ontologically, I reviewed and updated the classification of the term "microencephaly". So everything is fine, and this issue can be closed.
