### ISSUE TITLE
[Merge] 'immunodeficiency without anhidrotic ectodermal dysplasia'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5701]
**Mondo term (ID and Label)**
MONDO:0010368 'immunodeficiency without anhidrotic ectodermal dysplasia'

**Reason for deprecation**
merged in OMIM

**Merge with**:
MONDO:0010386 'immunodeficiency 33'

**Comment by sabrinatoro** [comment]
@nicolevasilevsky looking at the x-ref, I realized that 'immunodeficiency 33' (MONDO:0010386) is both a "disease or disorder" and a "disease susceptibility"
The problem is that the reasoner makes this disease as subclass of "mycobacterial infectious disease", which is wrong. 

Can you take a look and help me figure out what is going on? My specific questions are: 
1) is it correct to have 'immunodeficiency 33' (MONDO:0010386) be both a disease and a susceptibility? (it makes sense intellectually, but not ontologically)

2) (maybe @matentzn and/or @cmungall can help with this) I don't understand how the reasoner makes 'immunodeficiency 33' a subclass of 'mycobacterial infectious disease' (see the red note in the following image):
![Untitled presentation (3)](https://user-images.githubusercontent.com/12737987/206057308-12f71def-c006-4a4e-97f3-80aa9f903b6e.jpg)
is it that the reasoner "thinks" that the term has subclass annotations
"disease and disorder" 
AND 
"disease has 'infectious agent" some Mycobacteria" 
EVEN THOUGH these subclasses are coming from different branches?

**Comment by matentzn** [comment]
1. id33 is a disease or disorder (row 12-15)
2. id33 has infectious agent some M (row 3)
3. infectious disease = 1 AND 2 (row 16)

The questionable axiom is row 12 IMO.

**Comment by nicolevasilevsky** [comment]
I don't think a disease should be a proper disease and a susceptibility. I think the easiest thing would be to exclude the superclass 'X-linked Mendelian susceptibility to mycobacterial diseases' from 'immunodeficiency 33'. Looking at the OMIM [record](https://omim.org/entry/300636), I interpret this as an immunodeficiency disease that causes increased susceptibility to infections, but it seems like it is considered a disease itself.

**Comment by nicolevasilevsky** [comment]
I think this can be closed, yes?

**Comment by sabrinatoro** [comment]
No, this issue should not be closed yet. We still need to do the main work for this issue, which is term merge. I added to the merge list for a later release.
