### ISSUE TITLE
Concerns about Carey-Fineman-Ziter syndrome (MONDO:0009700) as a candidate for obsoletion

### ISSUE THREAD

**Issue by elliebroeren** [monarch-initiative/mondo#5716]
To whom it may concern,
My name is Ellie Broeren and I am the coordinator for the Syndromic Disorders GCEP. We curated MYMK and Carey-Fineman-Ziter syndrome (MONDO:0009700) as definitive in February 2022, and are confused as to why the disease assertion is a candidate for obsoletion. If the MONDO term is made obsolete, we would request that another term is given since there is a definitive gene-disease validity classification.
Thank you for your time,
Ellie Broeren

**Comment by sabrinatoro** [comment]
Thank you for reaching out, @elliebroeren . 
"Carey-Fineman-Ziter syndrome" (MONDO:0009700) becoming a candidate for obsoletion is explained in this issue: https://github.com/monarch-initiative/mondo/issues/5619

In short, the current "Carey-Fineman-Ziter syndrome" (MONDO:0009700) term represents a mix of the general "Carey-Fineman-Ziter syndrome" and "Carey-Fineman-Ziter syndrome type 1" (due to variation in MYMK). 
Users might have used this Mondo term to refer to either the more general or the more specific term. To ensure that existing annotations are correct, we are planning on splitting MONDO:0009700. 
MONDO:0009700 will therefore be obsoleted, and replaced with 2 new terms: 
1) Carey-Fineman-Ziter syndrome (general term) 
2) Carey-Fineman-Ziter syndrome 1 (Carey-Fineman-Ziter syndrome due to variation in MYMK)

(please note that the ids for these new terms are not available yet. But if you want the provisional one, I could share them with you)

Please let me know if you have any questions or concerns, and thank you again for reaching out !

**Comment by nicolevasilevsky** [comment]
Thanks @sabrinatoro for the explanation. @elliebroeren, here is some documentation about splitting terms in Mondo: https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/

Let us know if you have further questions. I'll close this ticket but feel free to reopen if needed.

**Comment by nicolevasilevsky** [comment]
@elliebroeren the new IDs for the terms will be:

id: MONDO:0031415
name: Carey-Fineman-Ziter syndrome

id: MONDO:0800437
name: Carey-Fineman-Ziter syndrome 1
