### ISSUE TITLE
MONDO:0016163 and MONDO:0008120 ? [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5763]
**Mondo term (ID and Label)**
MONDO:0008120  
spinocerebellar ataxia type 7

**Reason for deprecation**
UMLS (C0752125) , MeSH (D020754) suggest the OMIM and Orpha IDs on these records are the same concept. 
Mondo and OrphaNet have only a single child for MONDO:0016163/ORPHA:208508 (autosomal dominant cerebellar ataxia type II)  which suggests there aren't any other "type II" AD cerebellar ataxias
(see https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=18607&Disease_Disease_Search_diseaseGroup=208508&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Autosomal-dominant-cerebellar-ataxia-type-II&title=Autosomal%20dominant%20cerebellar%20ataxia%20type%20II&search=Disease_Search_Simple
(which for some reason is different than http://www.orpha.net/ORDO/Orphanet_208508 ? ) )

**Term to be merged with**
MONDO:0016163 autosomal dominant cerebellar ataxia type II

This issue probably needs follow up with OrphaNet to see if they still want to differentiate between ADCA type II and SCA 7 and what their rationale is. If they opt to maintain as separate, it would be worthwhile to reach out to UMLS as well to get the Orpha IDs mapped to different CUIs. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
It makes sense to merge "MONDO:0008120 - spinocerebellar ataxia type 7" into "MONDO:0016163 - autosomal dominant cerebellar ataxia type II"
Especially since 
1) there is no definition available for MONDO:0016163 - autosomal dominant cerebellar ataxia type II
2) the definition for MONDO:0008120 - spinocerebellar ataxia type 7 states that "Spinocerebellar ataxia type 7 (SCA7), currently the only known form of autosomal dominant cerebellar ataxia type 2 (ADCA2),(...)" Therefore, until other forms of ADCA2 are reported, these terms should be merged. 

I will add the tag, with the term to be merged for the April release. 
in the meantime, we should follow-up with Orphanet

**Comment by sabrinatoro** [comment]
Orphanet team was emailed on Jan 26th 2023
