### ISSUE TITLE
familial lambdoid synostosis MONDO:0017984 [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5782]
**Mondo term (ID and Label)**
familial lambdoid synostosis MONDO:0017984 

**Reason for deprecation**
I'm not sure the sources support maintaining this as a separate disease entity

- Orphanet 3267 "OBSOLETE: Familial lambdoid synostosis" says "This entity has been obsoleted from the Orphanet nomenclature of rare diseases.
Instead, consider using Non-syndromic craniosynostosis" (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=139390)
- SCTID:766884000 the only SNOMED CT ID that is still active using this code in UMLS' metathesaurus is the Spanish version of SNOMED CT, so it's possible this will be obsoleted. 
- UMLS:CN204142 is not an active identifier in MedGen (note the CN CUIs are not from UMLS, but specific to MedGen)
- GARD 3168 is for "lambdoid synostosis" not specific for the familial form, even though it uses that name in the description/definition https://rarediseases.info.nih.gov/diseases/3168/disease  
-     Note that GARD 3168 says the causative gene is ERF, same as OMIM's craniosynostosis 4 ( 600775) 
**Suggested term to consider**
MONDO:0010929 craniosynostosis 4 
(Also note that OMIM points to https://rarediseases.info.nih.gov/diseases/3115/disease and https://rarediseases.info.nih.gov/diseases/3168/lambdoid-synostosis from their entry for 600775) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Taking a quick look, MONDO:0010929 'craniosynostosis 4' is more specific than 'familial lambdoid synostosis' MONDO:0017984. 
Therefore, I would add 'craniosynostosis 4' as a term to consider after 'familial lambdoid synostosis' is obsoleted. 

We should consider adding GARD:3168 as a x-ref to 'craniosynostosis 4'

I am adding the "obsoletion candidate" tag to 'familial lambdoid synostosis' MONDO:0017984, but additional analysis is required to make sure that all the x-ref are correctly updated.

**Comment by nicolevasilevsky** [comment]
Based on my review/interpretation, the GARD disease is caused by ERF
<img width="805" alt="image" src="https://user-images.githubusercontent.com/6722114/228036374-4a224ce7-86a1-4b37-b207-88e5e084a4e6.png">

**Comment by nicolevasilevsky** [comment]
emailed on 2023-03-27, their website says they could take up to 10 business days to response. We should expect a response by April 10.

**Comment by ericsid** [comment]
Hi @nicolevasilevsky and @sabrinatoro  - I can chime in on behalf of GARD. 
Agree with your finding that OMIM#600775 would be a broader concept that includes GARD#3168 as a child concept. 
Since the literature is sparse for that specific phenotype, I would recommend obsoleting GARD#3168 as well - note that it will be several months before this change is reflected on the GARD frontend as we're currently in the process of major backend updates. 

FYI - We are currently working on revising GARD concepts to align better with Orphanet and OMIM with the aim of trying to better identify what rare diseases have any existing knowledge. Just chatted with Nico and Joe yesterday about this and Melissa several months back, please feel free to reach out if you wanted to chat more.

**Comment by nicolevasilevsky** [comment]
Thank you @ericsid! I obsoleted the term in Mondo and noted the GARD class is also obsolete. I appreciate your help.
