### ISSUE TITLE
Acid Ceramidase Deficiency [NTR]

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#5881]
**Preferred term label:** acid ceramidase deficiency

**Synonyms** ASAH1-related disorders (Source: https://www.ncbi.nlm.nih.gov/books/NBK488189/)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)** A spectrum of disorders that includes Farber disease and spinal muscular atrophy with progressive myoclonic epilepsy. Both disorders are caused by mutations in the ASAH1 gene that encodes the lysosomal hydrolase that breaks down the bioactive lipid, ceramide. (PMID:30029679)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)** sphingolipidosis (MONDO:0019255)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term? 
- Farber lipogranulomatosis (MONDO:0009218)
-  spinal muscular atrophy-progressive myoclonic epilepsy syndrome (MONDO:0008045)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/) 
https://clinicalgenome.org/affiliation/40110/

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi - 'acid ceramidase deficiency' is a synonym for Farber lipogranulomatosis (MONDO:0009218). Would it be okay if we added this new term with the label ASAH1-related disorder and 'acid ceramidase deficiency' is a narrow synonym (more specific synonym)?

And we will group the two children terms as subclasses

Thanks!
---

### Note to self:

[Term]
id: MONDO:0100042
name: ASAH1-related disorder
def: "A spectrum of disorders caused by mutations in the ASAH1 gene that encodes the lysosomal hydrolase that breaks down the bioactive lipid, ceramide, which includes Farber disease and spinal muscular atrophy with progressive myoclonic epilepsy." [https://clinicalgenome.org/affiliation/40110/, PMID:30029679]
synonym: "acid ceramidase deficiency" NARROW [https://clinicalgenome.org/affiliation/40110/]
is_a: MONDO:0019255 {source="https://clinicalgenome.org/affiliation/40110/"} ! sphingolipidosis
relationship: has_material_basis_in_germline_mutation_in http://identifiers.org/hgnc/735 {source="https://clinicalgenome.org/affiliation/40110/"} ! ASAH1
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5881" xsd:anyURI

**Comment by Mohan-Shruthi** [comment]
Thank you, Nicole. Let me discuss this with the Lysosomal Diseases GCEP and get back to you.

Best,
Shruthi
-----------------------------
Shruthi Mohan, Ph.D.
ClinGen Senior Biocurator
Berg Lab | Department of Genetics | UNC – Chapel Hill
919-843-3549 | ***@***.***

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi - have you had a chance to check in with your GCEP about this ticket? Thanks!

**Comment by Mohan-Shruthi** [comment]
Hi Nicole,

Thank you for the follow-up. Our group would need some more time to decide on this disease entity. We are having a larger discussion considering several other disease names towards the end of April, and we will revisit this question as well. I’ll be in touch again once we have made a decision.

Best,
Shruthi
-----------------------------
Shruthi Mohan, Ph.D.
ClinGen Senior Biocurator
Berg Lab | Department of Genetics | UNC – Chapel Hill
919-843-3549 | ***@***.***

**Comment by Mohan-Shruthi** [comment]
Hi Nicole,
The LD GCEP would like to retain "Acid ceramidase deficiency" as the overarching term label. We don't think "ASAH1-related disorders" sufficiently addresses the underlying disease mechanism. As mentioned before, we would prefer to move the terms Farber lipogranulomatosis (MONDO:0009218), spinal muscular atrophy-progressive myoclonic epilepsy syndrome (MONDO:0008045) as subclasses. Is this possible?

**Comment by courtneythaxton** [comment]
@Mohan-Shruthi 

Because the acid cermidase deficiency is a current synonym of the Farber disease, then how Mondo would display and add child terms will be different than requesting a new term. 

One thing to think about is whether a new term should be made to the affect of ASAH1- related shinolipidosis, and have the Farber and SMA be child terms. The definition of this new entity can include that is is an acid cermidase deficiency.

@nicolevasilevsky @sabrinatoro  just a thought but let me know if that does or doesn't work?

**Comment by lestergb** [comment]
I second Courtney's suggestion. ASAH1-related sphingolipidosis would be a good dyadic descriptor. I would also be fine with ASAH1-related acid ceramidase deficiency. I also could support ASAH1-related Farber lipogranulomatosis (I am a fan of eponyms). Up to the clinical experts to determine if ASAH1-related Spinal muscular atrophy with progressive myoclonic epilepsy is distinct from ASAH1-related Farber granulomatosis and both are types (children) of ASAH1-related sphingoliidosis (or both are children of ASAH1-related acid ceramidase deficiency) or if all are synonyms and represent a single spectrum of disease manifestations.

**Comment by ahamosh** [comment]
Hi Nicole,
I am teaching at the Short Course.  We can look at this next week.  Sorry for the delay.
Ada

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mellybelly** [comment]
Just to note that we can have a term with a primary label that is the same as a secondary label of another term so long as it is not an EXACT synonym. Obviously we want to align with OMIM if we can, so hopefully OMIM agrees to change synonyms in alignment (though its not a requirement for Mondo to be perfectly align, just better :-))

**Comment by Mohan-Shruthi** [comment]
Hi @nicolevasilevsky. The LD GCEP agreed using the suggested dyadic descriptor, "ASAH1-related sphingolipidosis", with 'acid ceramidase deficiency' as the narrow synonym, as you had mentioned before. Would this work for Mondo and everyone involved?

**Comment by ahamosh** [comment]
Hi Everyone, 
Apologies for the delayed response.  OMIM is treating Farber as complete acid ceramidase deficiency and the SMA with progressive myoclonic epilepsy as partial deficiency (they retain some enzyme activity).  I think that  ASAH1-related acid ceramidase deficiencies is ok as parents, with Farber lipogranulomatosis and SMAPME as the children.

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi I added this term term, please let me know if any changes are needed:

id: MONDO:0100524
name: ASAH1-related sphingolipidosis
def: "A spectrum of disorders that includes Farber disease and spinal muscular atrophy with progressive myoclonic epilepsy. Both disorders are caused by mutations in the ASAH1 gene that encodes the lysosomal hydrolase that breaks down the bioactive lipid, ceramide." [PMID:30029679] {source="https://clinicalgenome.org/affiliation/40110/"}
synonym: "acid ceramidase deficiency" NARROW [https://clinicalgenome.org/affiliation/40110/]
is_a: MONDO:0019255 {source="PMID:30029679", source="https://clinicalgenome.org/affiliation/40110/"} ! sphingolipidosis
property_value: http://purl.org/dc/terms/creator https://orcid.org/0000-0001-5208-3432
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5881" xsd:anyURI
