### ISSUE TITLE
New term: polygenic disease

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6083]
from the DO alignment: 

DOID:0080577
polygenic disease

Definition: A genetic disease that is characterized by the additive contributions of variants in multiple genes at different loci.

It looks like we have been going back and forth between having "monogenic" and "polygenic" terms.
[Here](https://github.com/monarch-initiative/mondo/issues/1758) it was decided to not have these terms. 
However [here](https://github.com/monarch-initiative/mondo/issues/5539) it was decided to have "hereditary disease", with a term for 'monogenic/mendelian disease'. 

Where are we standing on this right now? Do we want terms for "monogenic" and "polygenic" diseases (under the parent 'hereditary disease'? 

@cmungall @pnrobinson @ahamosh 
Thanks!

**Comment by pnrobinson** [comment]
in the vast majority of cases, a disease's causality is not purely polygenic, but other environmental factors play a role. Some pople use the word multifactorial, others "complex" (see e.g. https://www.genomicseducation.hee.nhs.uk/genotes/knowledge-hub/multifactorial-conditions/). I doubt that this class is very useful, since there are subtle gradations that are difficult to model in a hierarchy and nobody will go into a disease ontology and begin their search with "polygenic". Instead, we could add an attribute that would label diseases as having known polygenic factors.
Another problem is that the variant effects are not necessarily additive!

**Comment by nicolevasilevsky** [comment]
Discussed on curation call - this is too hard to maintain. We do not want to add this term
