### ISSUE TITLE
Update URL for ORCID to begin with https://

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/mondo#6261]
In the 'created by' field, the URL for the creator's ORCID should begin with `https://` instead of `http://`

**Comment by matentzn** [comment]
- [ ] please add https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/sparql/orcid-contributor-violation.sparql to src/sparql/qc/general so that this issue does not happen again
- [ ]  in https://github.com/monarch-initiative/mondo/blob/master/src/sparql/qc/general/qc-permitted-properties.sparql#L18 remove oboInOwl:createdBy and change dce:creator to dc:creator
- [ ] Change all createdBy in mondo to dc:creator

This way we are all aligned.

**Comment by nicolevasilevsky** [comment]
- do Nico's instructions first, and then Moni's errors will show up in QC
- fix them with search and replace

**Comment by nicolevasilevsky** [comment]
In protege (after the above steps are done), cc @sabrinatoro 

- go to New entities metadata
- in creator property, search for creator
- click dcterms:contributor
- edit manually - dcterms:creator

**Comment by nicolevasilevsky** [comment]
@matentzn when I copy and replace created_by with dc:creator, then I save as in Protege, the annotations look weird/wrong:

<img width="1384" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/c3274010-0e42-47e8-b1e8-168d212f062a">

**Comment by matentzn** [comment]
yes, the syntax is a bit different.

Match:

```
created_by: https?://orcid.org/([A-Z0-9-]+)
```

Replace:

```
property_value: http://purl.org/dc/elements/1.1/creator https://orcid.org/$1
```

After that, do a search for the remaining `created_by` annotations and fix them manually, using the pattern above:

```
property_value: http://purl.org/dc/elements/1.1/creator https://orcid.org/..
```

**Comment by nicolevasilevsky** [comment]
thank you @matentzn! I'm working on this now.
