### ISSUE TITLE
Capitalisation rules for disease names

### ISSUE THREAD

**Issue by azankl** [monarch-initiative/mondo#6332]
I noticed that some diseases in MONDO have their first letter capitalised, while others don't:

MONDO:0007037 achondroplasia
MONDO:0007041 apert syndrome 
MONDO:0007043 Pfeiffer syndrome

I would prefer first letter capitalised, i.e. Achondroplasia.
In general, does MONDO have any rules on how to name diseases? I note that Orphanet has a whole protocol on how to name diseases and they recommend capitalising the first letter, as in Achondroplasia:
https://www.orpha.net/orphacom/cahiers/docs/GB/eproc_Disease_naming_rules_in_English_PR_R1_Nom_01.pdf

Does MONDO have something similar?

see also my related question about the dyadic approach to disease naming https://github.com/monarch-initiative/mondo/issues/6333#issue-1747184639

**Your nano-attribution (ORCID)**
0000-0001-8612-1062

**Comment by cmungall** [comment]
This is standard naming convention for ontologies and is an OBO principle: https://obofoundry.org/principles/fp-012-naming-conventions.html

It's a principle for a very good reason.

If I have an application where I want to place an ontology term in a sentence, then this is wrong with leading upper case:

_the genes implicated in Lung cancer are ..._

Also title case as used by NCIT is also wrong

_the genes implicated in Lung Cancer are ..._

It's hard to reliably downcase due to the presence of proper names in diseases; this is wrong:

_the genes implicated in parkinson disease are ..._

In contrast, if an application really wants to see leading upper case or title case, this is a deterministic transformation without any ad-hoc rules

It's a good question, I'll leave it open for now until we add to our FAQ, then we'll close it, unless there are any further clarifications sought...

**Comment by azankl** [comment]
Thought you would have a good reason, that's why I asked ;-)
Agree with the concept of using lower case unless it's a proper name, but would argue that most rare diseases have a proper name. So all of the following should be capitalised as below (they are currently all lower case):

MONDO_ID | Name 
-- | -- | 
MONDO:0007037 | Achondroplasia
MONDO:0007041 | Apert syndrome
MONDO:0007044 | Acrodysostosis 1 with or without hormone resistance
MONDO:0007055 | Acromicric dysplasia
MONDO:0007057 | Acroosteolysis dominant type
MONDO:0007058 | Acropectorovertebral dysplasia
MONDO:0007073 | Hypoglossia-hypodactyly syndrome
MONDO:0007078 | Pseudohypoparathyroidism type 1A
MONDO:0007114 | Angel-shaped phalango-epiphyseal dysplasia
MONDO:0007124 | Ankyloblepharon-ectodermal defects-cleft lip/palate syndrome

Would you agree? If yes, I will go through the list of skeletal dysplasias and submit tickets where the capitalisation is wrong.

**Comment by nicolevasilevsky** [comment]
Yes, we agree with your expert opinion, thanks @azankl. I updated the labels for the term above. Thanks for reviewing the other skeletal dysplasias, please report new tickets. Thank you!
