### ISSUE TITLE
[Revise subclass] Malaria; Melanoma

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/mondo#6369]
**Mondo term (ID and Label)**
MONDO:0005105 Melanoma
MONDO:0005136 Malaria

**Suggested revision and reasons**
While working on the non-human animal branch, it was noted that melanoma is an inferred subclass of 'endocrine system' and 'endocrine gland' and I am not sure if that relationship is correct.

Malaria is an inferred subclass of 'alimentary part of gastrointestinal system' and I am not sure if this relationship is correct. 

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-5002-8648

**Comment by nicolevasilevsky** [comment]
@katiermullen 

> Malaria is an inferred subclass of 'alimentary part of gastrointestinal system' and I am not sure if this relationship is correct.

I believe this is because of the subclass Of axiom:
'disease has location' some hepatocyte

which seems accurate according to this paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4783171/

We can remove this axiom if it is causing issues. When you run the reasoner, can you quick the question mark to explain the inference, and we can confirm this is correct?

<img width="896" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/763273b0-8f92-4ef5-8e44-4a94ae122f62">

**Comment by nicolevasilevsky** [comment]
re: melanonma, I excluded the parent 'neuroendocrine neoplasm'
