### ISSUE TITLE
split term: 'lysosomal acid lipase deficiency'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6379]
**Term to split:**
MONDO:0010204 'lysosomal acid lipase deficiency'

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
1. New term (MONDO:0800440) 'lysosomal acid lipase deficiency' (OMIMPS:278000)
2. MONDO:0019149 Cholesteryl ester storage disease (OMIM:278000)

**Comment by jennygoldstein** [comment]
We got a note that the plan is to obselete the term "lysosomal acid lipase deficiency" (MONDO:0010204) but, upon reading this GitHub, I am unclear on this so just wanted to provide some information. Upon discussion with the ClinGen Lysosomal Diseases Gene Curation Expert Panel, we respectfully request that this term NOT be obseleted. 
We have curated the LIPA gene for this disease entity in order to account for the phenotypic spectrum observed in individuals with pathogenic variants in LIPA. Of note, the term "lysosomal acid lipase deficiency" is recognzed by clinicians, and is commonly used in the literature, including as the title for a GeneReviews article (https://www.ncbi.nlm.nih.gov/books/NBK305870/) and multiple recent papers (e.g. PMID: 37042460, PMID: 37222260, PMID: 37028992).  
If there are any questions, please let me know.
Thank you for your consideration.

**Comment by nicolevasilevsky** [comment]
Hi @jennygoldstein - we are not permanently obsoleting this term, we are just splitting it into a new class, here is some explanation:
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/

Let me know if you'd like further clarification. :)
