### ISSUE TITLE
Add an OAK command to mondo.Makefile for info on obsoletes

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#6436]
As discussed in yesterdays tech call,

use OAK `obsoletes` command to generate a table for all the 785 classes references by GARD and obsoleted by Mondo.

**Comment by joeflack4** [comment]
## Questions
@matentzn 
1. Where does this list of 785 come from? Can I see it?
2. Are these obsolete Mondo terms which map from Mondo to GARD, (a) old mappings before my GARD work? (b) newly generated mappings from my GARD pipeline?
3. Does this strictly need to be implemented as you describe in the OP? Does it have to be a makefile command? In the `mondo` repo? Does it have to use OAK? The OAK part is the most important, because in my PR (#6451) I have tried many different things with OAK, but am not yet having success. I can imagine different ways to do this without OAK that would be much more straightforward for me, and successful implementation would be guaranteed.

**Comment by matentzn** [comment]
re 1. The updated GARD mappings are not on the main branch, they are still here https://github.com/monarch-initiative/mondo/pull/6347, pending review; so this is where you would want to run your analysis.

re 2. See above, --->b (on branch)

re 3.1

1. This is not about technology, its about workflows. All our workflows are implemented make. So unless you want to suggest an entirely new system for managing workflows, this is where all the pipelines (QC, analysis, release, or otherwise, live)

re 3.2

you can query `mondo-edit.obo` in this particular case, but I would prefer `mondo.owl` --> `mondo.db` because other processes with the same logic may depend on the preprocessing performed during the generation of mondo.owl.

re 3.3

Yes, this is as much about solving a specific implementation issue as about convergence. All code written moving forward should be based on OAK, unless something is specifically out of scope - which this is not! I will comment on your specific difficulties wherever you raise them.

**Comment by joeflack4** [comment]
@matentzn Thanks this clarification helps a ton.

I should be able to redo what I did on that branch with `mondo.owl`. I'll check w/ Chris on Slack now, but I'm not aware of a way to do this with 100% OAK commands only; maybe he can help out.

**Comment by matentzn** [comment]
mondo.owl is generally a good dependency to use! I would tell if you if you should use another one, but for most purposes, that's the right one.

DockDockBuild plugin may not be able to handle variable names and wildcards in dependencies, hence it would show unresolvable prereqs?

**Comment by joeflack4** [comment]
Yep I think you're right about `DockDockBuild`.

I connected this to #6451 but it looks like this issue remains open. Up to you if you want to keep it open for some future, similar work, since the implementation of #6451 ended up using SPARQL instead of OAK.

**Comment by matentzn** [comment]
Lets close it and reopen it when we need it again; it will be easy to adopt your PR to arbitrary ontology sources (beyond GARD)
