### ISSUE TITLE
[Merge] MONDO:0016725 'pineal parenchymal tumor of intermediate differenciation'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6505]
**Mondo term (ID and Label)**
MONDO:0016725 'pineal parenchymal tumor of intermediate differenciation'

**Reason for deprecation**
these are the same terms, the ORDO term above has a typo

**Term to be merged with**
MONDO:0006369 'pineal parenchymal tumor of intermediate differentiation'

**Comment by nicolevasilevsky** [comment]
@kanems UMLS has two terms, but I think these are the same:
UMLS:CN201973
UMLS:C1367859

**Comment by nicolevasilevsky** [comment]
Thanks @kanems. Would you mind letting us know when you update that and we'll update it in Mondo. Thank you!

**Comment by kanems** [comment]
So MONDO:0006369 'pineal parenchymal tumor of intermediate differentiation' will be retained as the final Mondo ID, right?
Typically we try to keep Mondo IDs active in MedGen as long as they are valid (even if slated for obsoletion in a near-term release) because we have ClinVar and GTR submitters who may still want to use that ID for submitting data as long as Mondo reports it is ‘active.’ BUT I can go ahead and merge our records to use the CUI and the ‘final’ Mondo ID if that’ll be covered in the December release.
