### ISSUE TITLE
split term: Birt-Hogg-Dube syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6518]
**Term to split:**
MONDO:0007607 [Birt-Hogg-Dube syndrome](https://omim.org/phenotypicSeries/PS135150)

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
Birt-Hogg-Dube syndrome, equiv to OMIMPS:135150
Birt-Hogg-Dube syndrome 1, equiv to OMIM:135150

**Comment by nicolevasilevsky** [comment]
documentation describing the justification for this split is here:
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/#splitting-omim-phenotypic-series-ps-terms

**Comment by Sheng-An** [comment]
Two questions about this BHD issue.

1. I learned that there will be 2 new terms created: MONDO:0800444 (Birt-Hogg-Dube syndrome), and MONDO:0800445 (Birt-Hogg-Dube syndrome 1). Is the MONDO:0800444 (Birt-Hogg-Dube syndrome) a parent class term and is MONDO:0800445 (Birt-Hogg-Dube syndrome 1) a child class term?
2. Birt-Hogg-Dube syndrome 2 (BHD2), which is caused by the mutations in PRDM10, is in the OMIM (Phenotype
MIM number: [620459](https://www.omim.org/entry/620459)). May BHD2 be added as well?

Thank you.

**Comment by sabrinatoro** [comment]
Thank you for your question @Sheng-An 
1. You are correct: MONDO:0800444 (Birt-Hogg-Dube syndrome) will be the parent class, and MONDO:0800445 (Birt-Hogg-Dube syndrome 1) will be the child class.
2. Birt-Hogg-Dube syndrome 2 (BHD2) will also be added as a child class. It looks like this term is not in Mondo yet, therefore we will add it 

Therefore, the ontology will look as follow: 
- Birt-Hogg-Dube syndrome (MONDO:0800444)
  - Birt-Hogg-Dube syndrome 1 (MONDO:0800445)
  - Birt-Hogg-Dube syndrome 2 (MONDO:#### TBD)

Please let us know if you have any other questions

**Comment by Sheng-An** [comment]
Thank you for your response @sabrinatoro 
The ontology for BHD (including BHD1 and BHD2) looks good.
