### ISSUE TITLE
ClinGen gene-based retinopathy terms

### ISSUE THREAD

**Issue by wchankey** [monarch-initiative/mondo#6562]
ClinGen gene-based retinopathy terms:

Please note that the majority of the suggested terms are synonyms of an existing term / terms that follow a dyadic gene-related syndrome format. One of the suggested terms "TSPAN12-related exudative vitreoretinopathy" is just a slight rephrasing of an existing gene-related Mondo terms ("TSPAN12-related vitreoretinopathy (MONDO:0100484)").

Thank you Dr. Vasilevsky for reviewing these suggested terms when you have time!

The ClinGen Retina Gene Curation Expert Panel

[Batch_TermRequests_ClinGenRetinaGCEP_08152023.xlsx](https://github.com/monarch-initiative/mondo/files/12352762/Batch_TermRequests_ClinGenRetinaGCEP_08152023.xlsx)

**Comment by nicolevasilevsky** [comment]
Hi @wchankey, thanks for posting your request. We'll review this as soon as we can.

**Comment by nicolevasilevsky** [comment]
Spreadsheet is here: https://docs.google.com/spreadsheets/d/18eBPSIPhxbtnkh7oO6NfNS44IPGDFQ6S/edit#gid=1389946864

**Comment by sabrinatoro** [comment]
@wchankey we have a few questions about your spreadsheet.
I see a lot of new terms being requested with only 1 child (e.g. "PDE6A-related retinopathy" has only "retinitis pigmentosa 43"), which makes me wonder whether these terms are the same or there are other "PDE6A-related retinopathies". If so, we should make sure they are in Mondo. 

Could we schedule a meeting to discuss the spreadsheet? Thank you in advance! 
(my email is sabrina(at)tislab(dot)org)

**Comment by wchankey** [comment]
Hi Sabrina,

Thank you for writing back with these questions and for the good idea to meet about the spreadsheet of ClinGen gene-based retinopathy terms (Issue #6562). You’re raising a good point about child terms for PDE6A-related retinopathies (for example), and I would similarly benefit from the chance to ask your advice in a few instances about how you’d recommend structuring the parent-child term relationships.

For the PDE6A-related retinopathy example, the clinicians I work with were not aware of a particular alternative child term that PDE6A-related patients were receiving as a diagnosis besides “retinitis pigmentosa 43”. However, they noted that there is a broad spectrum of disease severity (discussed for example in https://pubmed.ncbi.nlm.nih.gov/35533076/) where the combination of mild and severe cases would be better described as “retinopathy” rather than “retinitis pigmentosa”. As a result, they were thinking to ask Mondo to consider creating a new parent term that was more inclusive “PDE6A-related retinopathy” while preserving the existing “retinitis pigmentosa 43” term as a still-valid child term.

Anyways, I’ll put some upcoming times below when I’ll be available to meet by Zoom.

Thursday August 24th 3:30pm – 6pm (EST U.S.)
Friday August 25th 11:30am – 6pm (EST U.S.)
Monday August 28th 12pm – 6pm (EST U.S.)
Tuesday August 29th 9am – 6pm (EST U.S.)
Wednesday August 30th  9am – 6pm (EST U.S.)

Thank you for your patience (since this is my first submission using the spreadsheet) and for checking your schedule for any compatible times!

William


From: Sabrina Toro ***@***.***>
Date: Wednesday, August 23, 2023 at 10:45 AM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] ClinGen gene-based retinopathy terms (Issue #6562)

@wchankey<https://github.com/wchankey> we have a few questions about your spreadsheet.
I see a lot of new terms being requested with only 1 child (e.g. "PDE6A-related retinopathy" has only "retinitis pigmentosa 43"), which makes me wonder whether these terms are the same or there are other "PDE6A-related retinopathies". If so, we should make sure they are in Mondo.

Could we schedule a meeting to discuss the spreadsheet? Thank you in advance!
(my email is sabrina(at)tislab(dot)org)

**Comment by sabrinatoro** [comment]
From email: 
 

**For the recommended names “GPR143-related foveal hypoplasia with or without albinism” and “LRP5-related exudative vitreoretinopathy with or without osteoporosis”, is it possible to move the “with or without” and everything that follows it out of the name and into the definition? Or is there a reason to keep it in the name?** In the LRP5 example, the group wanted to include that these may be syndromic or non-syndromic, but did not have a convenient term like “ciliopathy”. We were concerned about not being inclusive of the non-ocular disease that would be important to patients and providers. We had gone through this with the ClinGen disease naming committee, and with/without seemed to be the best when we couldn’t come up with a disease family term. The group members saw your point and one of the chairs indicated that they would be willing to let this one go if you recommend it. Another group member recommended keeping it in “LRP5-related exudative vitreoretinopathy with or without osteoporosis”, but removing it from the other example to give “GPR143-related foveal hypoplasia”?

 

**For the 16 recommended names that have been proposed as a parent term with a single child term, (“PDE6A-related retinopathy”, “CACNA2D4-related retinopathy”, “ELOVL4-related maculopathy”, “MAK-related retinopathy”, “TSPAN12-related exudative vitreoretinopathy”, “KIZ-related retinopathy”, “TOPORS-related retinopathy”, “PRPF8-related retinopathy”, “RD3-related retinopathy”, “BBS9-related ciliopathy”, “BBS10-related ciliopathy”, “dominant BEST1-related retinopathy”, “recessive BEST1-related retinopathy”, “autosomal dominant BEST1-related vitreoretinochoroidopathy”, “IMPG2-related recessive retinopathy”, and “IMPG2-related dominant retinopathy”), why not consolidate the parent term and the child term into a synonym?** The group members replied that they still prefer the parent-child setup because the gene-first dyadic term captures the disease spectrum better than the usually too-specific OMIM term. So in that sense they are not synonymous. We also decided not to replace or rename the original term because these have been used by clinicians and patients for so long. Keeping as parent-child also allows for future clinical disease terms to be added, so it future-proofs the proposed structure. You had recommended that if the group feels this way, it might be a good idea to add a comment such as; “we have made the decision for now to keep the parent term separate from the parent term (with a date) for this reason, but it’s possible in the future that this could be merged.”

 

**For the recommended name “autosomal dominant BEST1-related vitreoretinochoroidopathy”, are there other examples of vitreoretinochoroidopathy that are autosomal recessive? Or is it always autosomal dominant, so we can remove the mode of inheritance from the name?** “Autosomal dominant vitreoretinochoroidopathy” is an existing term that has been published in relation to BEST1 (PMID: 18611979, PMID: 36712704), so the group was proposing to preserve the existing term in a dyadic format that starts with “BEST1-related“. The group has also been trying to maintain consistency with their previous convention of “gene-related dominant/recessive disease” (for example “RP1-related dominant retinopathy”) when a gene has multiple inheritance patterns. After reconsideration, the group members recommended reorganizing these 3 terms to “BEST1-related dominant vitreoretinochoroidopathy” (with “autosomal dominant vitreoretinochoroidopathy” as a synonym), “BEST1-related dominant retinopathy” (with “Best disease” and “vitelliform macular dystrophy 2” as synonyms), and “BEST1-related recessive retinopathy” (with “autosomal recessive Bestrophinopathy” as a synonym).

**Comment by sabrinatoro** [comment]
New terms were created: 

MONDO ID | term labels
-- | --
MONDO:0700224 | PDE6A-related retinopathy
MONDO:0700227 | ELOVL4-related maculopathy
MONDO:0700228 | LRP5-related exudative vitreoretinopathy
MONDO:0700229 | MAK-related retinopathy
MONDO:0700230 | GPR143-related foveal hypoplasia
MONDO:0700231 | TSPAN12-related exudative vitreoretinopathy
MONDO:0700232 | KIZ-related retinopathy
MONDO:0700233 | TOPORS-related retinopathy
MONDO:0700234 | PRPF8-related retinopathy
MONDO:0700235 | RD3-related retinopathy
MONDO:0700236 | BBS9-related ciliopathy
MONDO:0700237 | BBS10-related ciliopathy
MONDO:0700238 | BEST1-related dominant retinopathy
MONDO:0700239 | BEST1-related recessive retinopathy
MONDO:0700240 | BEST1-related vitreoretinochoroidopathy
MONDO:0700241 | IMPG2-related recessive retinopathy
MONDO:0700242 | IMPG2-related dominant retinopathy
MONDO:0700243 | CACNA1F-related retinopathy
MONDO:0700244 | CACNA2D4-related retinopathy

Note that disease names reported in the spreadsheet were added as synonyms and tagged as "ClinGen preferred"

@wchankey These should be available in the next Mondo release, early January. 
Thank you for your patience.

**Comment by wchankey** [comment]
Thank you Sabrina for sorting through these complicated requests and creating the most appropriate terms! I’m grateful for your time and the group will appreciate your thoughtful approach to determining the correct terminology. Wishing you excellent holidays ahead,

William


From: Sabrina Toro ***@***.***>
Date: Wednesday, December 20, 2023 at 8:05 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] ClinGen gene-based retinopathy terms (Issue #6562)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

New terms were created:
MONDO ID
term labels
MONDO:0700224
PDE6A-related retinopathy
MONDO:0700227
ELOVL4-related maculopathy
MONDO:0700228
LRP5-related exudative vitreoretinopathy
MONDO:0700229
MAK-related retinopathy
MONDO:0700230
GPR143-related foveal hypoplasia
MONDO:0700231
TSPAN12-related exudative vitreoretinopathy
MONDO:0700232
KIZ-related retinopathy
MONDO:0700233
TOPORS-related retinopathy
MONDO:0700234
PRPF8-related retinopathy
MONDO:0700235
RD3-related retinopathy
MONDO:0700236
BBS9-related ciliopathy
MONDO:0700237
BBS10-related ciliopathy
MONDO:0700238
BEST1-related dominant retinopathy
MONDO:0700239
BEST1-related recessive retinopathy
MONDO:0700240
BEST1-related vitreoretinochoroidopathy
MONDO:0700241
IMPG2-related recessive retinopathy
MONDO:0700242
IMPG2-related dominant retinopathy
MONDO:0700243
CACNA1F-related retinopathy
MONDO:0700244
CACNA2D4-related retinopathy

Note that disease names reported in the spreadsheet were added as synonyms and tagged as "ClinGen preferred"

@wchankey<https://github.com/wchankey> These should be available in the next Mondo release, early January.
Thank you for your patience.
