### ISSUE TITLE
Relabel term request [inherited neurodegenerative disorder, MONDO:0024237

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#6620]
**Mondo term (ID and Label):**
inherited neurodegenerative disorder (MONDO:0024237)

**Suggested new label:**
genetic neurodegenerative disorder

**Your nano-attribution (ORCID)**
N/A - request on behalf of the ClinGen Epilepsy Gene Curation Expert Panel

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Given the child terms for this Mondo term, we feel that "inherited" is a misnomer and the word "genetic" should be used instead. De novo genetic changes are responsible for disease, as are inherited variants, and it is likely that many of these inherited neurodegenerative diseases have de novo variants that cause disease and are not inherited. This is true, at the very least, for the neuronal ceriod lipofuscinosis child term--we have applied this term to curations for which de novo variants have been reported ([see CLN3](https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_6be652b4-092f-4d1c-9606-4dfeb689c4b9-2023-04-04T040000.000Z)). For this reason, we propose updating this term from inherited to genetic neurodegenerative disorder.

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
Hi @ARosselClinGen - thanks for reporting this. We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this more closely in November or later. We appreciate your patience.

**Comment by nicolevasilevsky** [comment]
@pnrobinson @ahamosh, do you have opinions about this suggested change?

This is related to https://github.com/monarch-initiative/mondo/issues/5952

thank you!

**Comment by pnrobinson** [comment]
Well, pretty much every disease is genetic - ranging from Mendelian (mainly genetic) to common disease (genetic contributions to risk etc). I think the field needs to come up with new terminology, since we all know what we mean. I think that "inherited" is less wrong than "genetic". Possibly a better word would be "heritable", since in principle de novo mutations can be transmitted to the next generation; however, this is also not always true, e.g., if the disease is so severe that the affected individual is not born or does not reach reproductive age.

**Comment by ARosselClinGen** [comment]
We have discussed this as a group and are moving forward with an alternate Mondo ID for our curation. We are happy to close this issue without updating the disease term for MONDO:0024237.

**Comment by nicolevasilevsky** [comment]
Ok great, thanks @ARosselClinGen.
