### ISSUE TITLE
Mass Obsoletion: focus on branch 'inflammatory disease' (MONDO:0021166)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6748]
branch : 'inflammatory disease' (MONDO:0021166)

Terms to obsolete: 

obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0015144 | brain inflammatory disease
http://purl.obolibrary.org/obo/MONDO_0020069 | chronic encephalitis
http://purl.obolibrary.org/obo/MONDO_0033947 | hereditary angioedema with normal C1Inh
http://purl.obolibrary.org/obo/MONDO_0015591 | limbic encephalitis associated with antibodies to cell membrane antigens
http://purl.obolibrary.org/obo/MONDO_0019541 | non-infectious posterior uveitis
http://purl.obolibrary.org/obo/MONDO_0020537 | occupational allergic alveolitis
http://purl.obolibrary.org/obo/MONDO_0015488 | predominantly large-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0015489 | predominantly medium-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0015490 | predominantly small-vessel vasculitis
http://purl.obolibrary.org/obo/MONDO_0018745 | superficial pemphigus

Removed from obsoletion list (see [comment below](https://github.com/monarch-initiative/mondo/issues/6748#issuecomment-1771985312))
obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0018640 | secondary vasculitis

- [x] we need to remove the obsoletion tag from this term

**Comment by nicolevasilevsky** [comment]
[spreadsheet here](https://docs.google.com/spreadsheets/d/1ZUBNaTohguyPnz-ruVGxw9V6QMqlrmuCUIa5H6Ps9Pk/edit)

**Comment by nicolevasilevsky** [comment]
There is an explanatory video linked [here](https://drive.google.com/file/d/1Be2Uh3bi-ni8bUOTlhxn6YvD31bEsDgX/view?usp=sharing)

**Comment by nicolevasilevsky** [comment]
we should keep secondary vasculitis - it seems like a legitmate disease as pointed out by Sylvia Matenzoglu and a [google search](https://www.google.com/search?q=secondary+vasculitis&sca_esv=575056345&ei=I-YxZbzQDpax0PEP3ZOamAY&oq=secondart+vasculitis&gs_lp=Egxnd3Mtd2l6LXNlcnAiFHNlY29uZGFydCB2YXNjdWxpdGlzKgIIADIHEAAYDRiABDIHEAAYDRiABDIHEAAYDRiABDIGEAAYHhgNMggQABgFGB4YDTIIEAAYBRgeGA0yCBAAGAUYHhgNMggQABgFGB4YDTIKEAAYBRgeGA0YDzIIEAAYCBgeGA1IoCBQxwRYiRNwAXgBkAEAmAGqAaABsgeqAQM1LjS4AQHIAQD4AQHCAgoQABhHGNYEGLADwgIGEAAYBxgewgIIEAAYBxgeGArCAggQABgHGB4YD-IDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp#ip=1)

See [this source](https://www.brighamandwomens.org/medicine/rheumatology-inflammation-immunity/services/vasculitis):
"In some cases, vasculitis occurs due to an underlying condition, which is referred to as secondary vasculitis. Secondary vasculitis can be caused by:

Infections – most cases of cryoglobulinemia are caused by the hepatitis C virus infection, and the hepatitis B virus infection can cause polyarteritis nodosa.
Immune system diseases – rheumatoid arthritis, lupus, and scleroderma can lead to vasculitis.
Allergic reactions – an allergic reaction to a medication can cause vasculitis.
Blood cell cancers – leukemia and lymphoma can cause vasculitis.
Exposure to chemicals/drugs."

Also: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5873754/:
"Secondary vasculitis Secondary causes of vasculitis (frequent causes seen on the acute medical admission ward) include infection, drugs, connective tissue disease (CTD) and malignancy."

I wonder if we need a new 'primary vasculitis' term (in additional to 'primary central nervous system vasculitis'.

I will create a new ticket for this

**Comment by nicolevasilevsky** [comment]
@sabrinatoro can you review the 'leaves the branch' terms. I reviewed the orphaned terms that Sylvia assigned

**Comment by nicolevasilevsky** [comment]
note, this is ready for mass obs/PR

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
