### ISSUE TITLE
Migrating build to Jenkins

### ISSUE THREAD

**Issue by ShahimEssaid** [monarch-initiative/mondo#681]
@cmungall  I would like to migrate the build to the CGRB Jenkins instance. Any thoughts regarding this? Does anyone else need to be aware of this?

The Travis build is still needed in order to trigger the Jenkins build (at least for now) due to some technical reasons. However, the Travis build will be a dummy build that runs an empty make goal and always succeeds. Jenkins will update its status and it will effectively be the overall status on Github.  I've tried it on a branch and it works so far. It takes about 50 minutes to test.

Would it be helpful to push back the merge commit that was done on Jenkins back to GitHub and name it after the branch name and the build number?

I would also like to setup a release build after this. I'll have to learn what else is involved in building a release beyond what is already defined in the Makefile, and I would like to setup some sort of dev or staging area for release candidates, nightly, etc. if that makes sense to current users. Any thoughts?

**Comment by cmungall** [comment]
What is driving this? Is it the fact that the test step is too slow on travis VMs? I would like to find some way of making this faster since if there is a slowdown here, there is a slowdown on anything else that uses odk, cc @matentzn 

Is the CGRB Jenkins instance ci.monarchinitiative.org? Is this fixed so that it's driven by a Jenkinsfile in github yet? I want to avoid another Jenkins instance with diverging patterns. @kltm is setting up an OBO-wide Jenkins this may be a good place. Will you be in Corvallis for our mini-hack? I'd like to discuss Jenkins setup with you @kshefchek @kltm @deepakunni3

**Comment by ShahimEssaid** [comment]
@cmungall  yes, the Travis build times out at 5 minutes and reports a build error as if the tests failed. This was a real hassle the other day while working with Nicole on pull requests. When they do succeed the build time is around 47 minutes so any slowdown on Travis' side will fail the build.

I'm not sure how to speed up the build yet (on Travis or otherwise) but a local build on my machine only took 25 minutes the other day. 

The Jenkins setup is here: https://monarch-jenkins.cgrb.oregonstate.edu/job/test-mondo/

I created a pull request that shows an addition to the .travis.yml to trigger the Jenkins build from Travis, and the Jenkinsfile that gets loaded after a merge is done on Jenkins. The commented out portion of that file at the bottom is what runs on Jenkins before loading the Jenkinsfile.

I'll ask about the Corvallis mini-hack. I didn't know about it but I might be able to attend.

**Comment by nicolevasilevsky** [comment]
closing, please reopen if needed
