### ISSUE TITLE
mass obsoletion pipeline problem

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6820]
(I am happy to add this to another issue if one already exists)

It looks like the filtered_obsolete_me.txt used for the obsoletion is not the newest copy, it is the previous copy. 

Description of the issue: 
- I updated "obsolete_me.txt" with the terms to obsolete
- I ran the obsoletion pipeline using `sh run.sh make mass_obsolete2 -B GITHUB_ISSUE_URL=https://github.com/monarch-initiative/mondo/issues/6746`
- I saw that the "filtered_obsolete_me.txt" has been updated as expected: it contained only the terms that have not been obsoleted yet (and does not include the terms that have already been obsoleted). 
- After the run, the terms obsoleted were not those on the "filtered_obsolete_me.txt". The terms obsoleted were the terms that I tested yesterday (ie that were on the last "filtered_obsolete_me.txt"; and since I tested with these terms, but not officially obsolete them, they were obsoleted)

NOTE: 
- I saw the same thing yesterday, but blamed it on the fact that I couldn't be sure that I had saved  "obsolete_me.txt". And it worked after testing again. But I am seeing the issue again, so this is definitely a bug.

**Comment by sabrinatoro** [comment]
Terms I added in  "obsolete_me.txt":
MONDO:0015679
MONDO:0015817
MONDO:0015818
MONDO:0015822
MONDO:0015975
MONDO:0015976
MONDO:0016361
MONDO:0016513
MONDO:0016599
MONDO:0016667
MONDO:0017036
MONDO:0017057
MONDO:0017144
MONDO:0017146
MONDO:0017397
MONDO:0018340
MONDO:0018796
MONDO:0019044
MONDO:0019138
MONDO:0020081
MONDO:0020084
MONDO:0020118
MONDO:0034872

**Comment by twhetzel** [comment]
@sabrinatoro are you saying that after the second run of the pipeline with a new set of terms to obsolete that the filtered set of terms to obsolete is not updated?

**Comment by sabrinatoro** [comment]
@twhetzel yes, that is "mostly" correct: 
the filtered set of terms to obsolete is not updated EVEN THOUGH the file seems to be updated (because I saw that the list of ID was updated). 
It looks like the file is updated but not "saved" (if that makes sense).

**Comment by twhetzel** [comment]
@matentzn can you help with this issue? The issue is that when the `config/filtered_obsolete_me.txt` file is empty the first time the mass obsoletion pipeline is run, not all changes are applied to `mondo-edit.obo`. If the pipeline is run a second time, with the values still present in `config/filtered_obsolete_me.txt`, the ontology file is updated as expected from the mass obsoletion steps. We have not noticed this behavior until now since I guess after the initial changes (https://github.com/monarch-initiative/mondo/pull/6786/commits) it wasn't clear this was happening. Thanks in advance!
