### ISSUE TITLE
MONDO:0005641 aleutian mink disease [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6841]
**Mondo term (ID and Label)**
MONDO:0005641 aleutian mink disease 

**Suggested revision and reasons**
This is not a human disease- should have a parent of MONDO:0005583 non-human animal disease
 MeSH does show this record as having some relationship in their hierarchies to a human disease, but I am pretty sure it's a tangential relationship (a parvovirus causes this disease, but minks with the Aleutian coat color and homozygous for the underlying lysosomal defect are particularly susceptible, much like humans with Chediak-Higashi are susceptible to infections and present with pigmentation variation)

https://www.ncbi.nlm.nih.gov/mesh/?term=D000453 
vs. human Chediak-Higashi syndrome  https://www.ncbi.nlm.nih.gov/mesh/68002609 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
I think it makes sense for this disease to have a non-human animal disease parent, especially since the definition in Mondo refers to aspects of the disease as it occurs in the mink species.

There is one report of 2 cases of potential zoonotic transmission of AMDV to humans PMID:19961696. @nicolevasilevsky what is the best way to indicate this zoonotic potential in Mondo? And what level of evidence is needed to make this assertion?

**Comment by nicolevasilevsky** [comment]
these are good questions, @katiermullen. I'll add this to the curation call agenda.

Also, I don't think we properly model zoonotic infections in Mondo. See: https://github.com/monarch-initiative/mondo/issues/5898

**Comment by katiermullen** [comment]
@kanems @zoependlington 
We added the term MONDO:0005641 'aleutian mink disease' to the non-human animal disease branch. To reflect that aleutian mink disease can occur in humans, we added the term 'aleutian mink disease, human'. In some of the db-xrefs it is not clear if they are referring to the human or non-human animal disease so we have added these db-xrefs as MONDO:relatedTo instead of MONDO:equivalentTo. If these need to be revised based on information that you have, please let us know.

@zoependlington 
Please be advised that the human rare disease term for the OTAR subset is MONDO:1010029 'aleutian mink disease, human'

Thank you!
