### ISSUE TITLE
MONDO:0005676 borna disease[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6842]
**Mondo term (ID and Label)**
MONDO:0005676 borna disease

**Suggested revision and reasons**
This is not a human disease
should have a parent of MONDO:0005583 non-human animal disease

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @kanems!

@katiermullen - if you have any additional thoughts on this, please let us know. Thnaks!

**Comment by katiermullen** [comment]
I was under the impression that it is a zoonotic disease. 

A recent (2020) study states:  Borna disease virus (BoDV-1) infection has to be considered as a potentially lethal zoonosis in endemic regions with reported spillover infections in horses and sheep. BoDV-1 infection can result in fatal encephalitis in immunocompromised and apparently healthy people. Consequently, all severe encephalitis cases of unclear cause should be tested for bornaviruses especially in endemic regions. PMID:31924550

There are additional case reports of fatal Borna disease virus in humans, see for example: PMID:34376142.

Thanks!

**Comment by kanems** [comment]
Thanks @katiermullen These citations are helpful! MedGen will add them to our entry for this concept as  "suggested reading" for other folks (like me) who seem confused about this apparent animal disease in a human disease set.

**Comment by kanems** [comment]
Should MONDO:0957421 borna virus encephalitis somehow be connected to MONDO:0005676 borna disease in the ontology? They share 'grand' parents in the ontology, but it seems like they should be more closely related in at least one branch of the ontology.

**Comment by katiermullen** [comment]
@kanems this is a great question! I will bring this up in the curation call - what is best way to show the relationship between borna disease and borna virus encephalitis?

**Comment by sabrinatoro** [comment]
This issue should be reviewed when we discuss the infectious disease branch review and modeling.

**Comment by katiermullen** [comment]
@kanems @zoependlington @galyea123 
We added the term MONDO:0005676 'borna disease' to the non-human animal disease branch. The human disease term is MONDO:0957421 'borna virus encephalitis'. To reflect that in some of the db-xrefs it is not clear if they are referring to the human or non-human animal disease so we have added these db-xrefs as MONDO:relatedTo instead of MONDO:equivalentTo. If these need to be revised based on information that you have, please let us know.

@zoependlington @galyea123 
Please be advised that the human term for the rare disease subset is MONDO:0957421 'borna virus encephalitis'

Thank you!

**Comment by galyea123** [comment]
Perfect!  As you known,  this also in Orphanet: https://www.orpha.net/en/disease/detail/637051;  Please tag it to NORD rare too.

Thank you, Gioconda Alyea
