### ISSUE TITLE
Revise ALG2-congenital disorder of glycosylation

### ISSUE THREAD

**Issue by gleon98** [monarch-initiative/mondo#6885]
**Mondo term (ID and Label)**
MONDO:0011933 ALG2-congenital disorder of glycosylation 
MONDO:0014543 congenital myasthenic syndrome 14

**Suggested revision and reasons**
After giving a lumping and splitting presentation on _ALG2_ to the Congenital Disorders of Glycosylation (CDG) GCEP on Nov. 1st, 2023, it was decided amongst the expert panel to lump congenital myasthenic syndrome 14 and ALG2-congenital disorder of glycosylation together. We are requesting that **congenital myasthenic syndrome 14** be added as a child term under ALG2-congenital disorder of glycosylation. 

**Your nano-attribution (ORCID)**
0009-0001-2576-9655
https://orcid.org/0009-0001-2576-9655

**Comment by nicolevasilevsky** [comment]
Thanks @gleon98, we'll look into this as soon as we can. Thanks for the ticket.

**Comment by nicolevasilevsky** [comment]
Hi @gleon98 - sorry for the delay. When I added this parent to congenital myasthenic syndrome 14, it caused an error in Mondo - this new parentage makes congenital myasthenic syndrome 14 a type of 'metabolic disease', which is defined as:

A congenital disorder (due to inherited enzyme abnormality) or acquired (due to failure of a metabolically important organ) disorder resulting from an abnormal metabolic process.

I wanted to confirm that 'congenital myasthenic syndrome 14' is a type of metabolic disorder?

Thanks!

**Comment by gleon98** [comment]
No worries thank you for the update, I was waiting to speak with the expert panel yesterday about this, and they agreed to this change. It would be considered a metabolic disorder!

**Comment by nicolevasilevsky** [comment]
thanks @gleon98!
