### ISSUE TITLE
split term: MONDO:0011876 name: juvenile absence epilepsy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6897]
**Term to split:**

MONDO:0011876 name: juvenile absence epilepsy

**Name for new terms:**

MONDO:0800453 juvenile absence epilepsy
MONDO:0800454 epilepsy, juvenile absence, susceptibility to, 1

Related to https://github.com/monarch-initiative/mondo/issues/6419

**Comment by twhetzel** [comment]
I was starting to work on this and see now there is already a term named MONDO_0020772 epilepsy, juvenile absence, susceptibility to, 1. 

@nicolevasilevsky we talked about deprecating MONDO:0011876 name: juvenile absence epilepsy and creating 2 new terms for MONDO:0800453 juvenile absence epilepsy and MONDO:0800454 epilepsy, juvenile absence, susceptibility to, 1. How should this be handled?

**Comment by sabrinatoro** [comment]
Another way to look at the issue is as follow: 
The concept of MONDO:0011876 (juvenile absence epilepsy) needs to be split because it includes 2 separate concepts: 
- concept 1: juvenile absence epilepsy
- concept 2: epilepsy, juvenile absence, susceptibility to, 1

**Concept 1** does not already exist in Mondo. We therefore need to create a new term to represent this concept, and give it a new ID. This ID was already chosen (to help users) and is MONDO:0800453. Annotations for this new term (synonyms, cross-references,...) will be some of the term being obsoleted/split

**Concept 2**, in this case, is already in Mondo (and represented by MONDO:0020772). Therefore, there is no need to create a new term. You just need to update the existing concept (ie MONDO:0020772) and add the relevant annotations from the term being obsoleted/split (e.g. synonyms, cross-references,...) to this term.

**Comment by twhetzel** [comment]
Ok, that's what I thought. Does it need to be documented anywhere that MONDO:0800454 is not being used for "epilepsy, juvenile absence, susceptibility to, 1" when MONDO:0011876 (juvenile absence epilepsy) is deprecated?

**Comment by sabrinatoro** [comment]
No, there is no need to document that MONDO:0800454 was not used, because this ID was not used in Mondo.

**Comment by twhetzel** [comment]
Sure, it is mentioned in a comment on MONDO:0011876 (juvenile absence epilepsy) and in the ROBOT template.
