### ISSUE TITLE
MONDO:0044981  pseudoallergy [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6936]
**Mondo term (ID and Label)**
MONDO:0044981  pseudoallergy

**Reason for deprecation**
Both sources are obsolete (per the UMLS '23AB release)
http://identifiers.org/snomedct/609397002
[C3662273](http://linkedlifedata.com/resource/umls/id/C3662273)

**Suggested term to consider**
SNOMEDCT now has Non-allergic hypersensitivity to substance (609397002) which UMLS maps to 
C3662273.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro @twhetzel 
do you think we should create a new term called Non-allergic hypersensitivity to substance or add a different 'consider' annotation, like to MONDO:0000605 'hypersensitivity reaction disease'?

**Comment by twhetzel** [comment]
I am not able to see where the sources are deprecated. But I do see that `C3662273` is already included as an xref so I'm a bit confused about the request. If we can't sort out async, can we take a few minutes in the curation call to discuss?

**Comment by nicolevasilevsky** [comment]
@twhetzel `C3662273` was replaced by Non-allergic hypersensitivity to substance

**Comment by nicolevasilevsky** [comment]
If we wanted to add a new term called Non-allergic hypersensitivity to substance, we should merge MONDO:0044981 pseudoallergy into Non-allergic hypersensitivity to substance, because that seems to be what SNOMED and UMLS did.

But if we don't want that term, then we should obsolete pseudoallergy and make the UMLS and SNOMED xrefs MONDO:obsoleteEquivalent
