### ISSUE TITLE
RAB18 Deficiency

### ISSUE THREAD

**Issue by madysoncbrown** [monarch-initiative/mondo#6942]
### Label

RAB18 Deficiency

### Synonyms

Warburg Micro Spectrum 

### Synonym type

None

### Definition

Per GeneReviews (https://www.ncbi.nlm.nih.gov/books/NBK475670/): “RAB18 deficiency is the molecular deficit underlying both Warburg micro syndrome (characterized by eye, nervous system, and endocrine abnormalities) and Martsolf syndrome (characterized by similar – but milder – findings). To date Warburg micro syndrome comprises >96% of reported individuals with genetically defined RAB18 deficiency. The hallmark ophthalmologic findings are bilateral congenital cataracts, usually accompanied by microphthalmia, microcornea (diameter <10), and small atonic pupils. Poor vision despite early cataract surgery likely results from progressive optic atrophy and cortical visual impairment. Individuals with Warburg micro syndrome have severe to profound intellectual disability (ID); those with Martsolf syndrome have mild to moderate ID. Some individuals with RAB18 deficiency also have epilepsy. In Warburg micro syndrome, a progressive ascending spastic paraplegia typically begins with spastic diplegia and contractures during the first year, followed by upper-limb involvement leading to spastic quadriplegia after about age five years, often eventually causing breathing difficulties. In Martsolf syndrome infantile hypotonia is followed primarily by slowly progressive lower-limb spasticity. Hypogonadism – when present – manifests in both syndromes, in males as micropenis and/or cryptorchidism and in females as hypoplastic labia minora, clitoral hypoplasia, and small introitus.”

### Parent term

MONDO:0016073 syndromic microphthalmia, MONDO:0020147 anophthalmia-microphthalmia syndrome, MONDO:0020146 major induction processes eye anomaly, MONDO:0020145 developmental defect of the eye, MONDO:0019755 developmental defect during embryogenesis, MONDO:0021147 disorder of development or morphogenesis, MONDO:0700096 human disease, MONDO:0000001 disease, MONDO:0003847 hereditary disease

### Children term(s)

MONDO:0016649 Warburg Micro Syndrome, MONDO:0010822 Warburg micro syndrome 1, MONDO:0013641 Warburg micro syndrome 2, MONDO:0013638 Warburg micro syndrome 3, MONDO:0014296 Warburg micro syndrome 4, MONDO:0023910 Martsolf Syndrome, MONDO:8000008 Martsolf Syndrome 1, MONDO:0030376 Martsolf Syndrome 2

### ORCID Identifier

0009-0001-4028-4226

### Website URL

https://www.clinicalgenome.org/affiliation/40020/

### Additional comments

We are requesting a new term to encompass a spectrum of disorders characterized by Warburg Micro Syndrome and Martsolf Syndrome phenotypes:  those existing terms and their child terms should be brought under this new term. For parent terms we are suggesting all existing parent terms for Warburg Micro Syndrome and Martsolf Syndrome. Please see GeneReviews for an existing explanation: (https://www.ncbi.nlm.nih.gov/books/NBK475670/).

**Comment by madysoncbrown** [comment]
@ErinRiggs request for RAB18 Deficiency

**Comment by nicolevasilevsky** [comment]
Hi @madysoncbrown 
some of the parents you requested are obsoleted, I added the following parents:
<img width="452" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/08e880fa-a872-49d9-b58c-606e310cd344">

Also, it does not logically make sense to make all of the Warburg Micro Syndrome terms children of this term, because only Warburg Micro Syndrome 3 has RAB1 implicated as the causal gene, so I added RAB1 deficiency as the parent to this term.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro according to the [gene reviews](https://www.ncbi.nlm.nih.gov/books/NBK475670/) article, "**RAB18 deficiency is the molecular deficit underlying** both Warburg micro syndrome (characterized by eye, nervous system, and endocrine abnormalities) and **Martsolf syndrome (characterized by similar – but milder – findings)**", but in OMIM, there is not an instance of Marsolft syndrome where RBA18 is implicated. Do you want to follow up with Ada about this?

**Comment by sabrinatoro** [comment]
@madysoncbrown
I reviewed the children suggested for this new term, and only one of them, 'Warburg micro syndrome 3' (MONDO:0013638) is caused by a variation in RAB18. (note: we could create a new term for "Marsolft syndrome" where RBA18 is implicated, and follow up with OMIM to see if they already have a record for it).

Therefore, I see 2 options: 
1) create a new term called "RAB18 Deficiency" (defined as diseases where RBA18 is implicated), which would have only 2 terms (the ones above)
2) create a term to group all types of "Warburg micro syndrome" and "Marsolft syndrome". This grouping term should however not be defined as implicating RBA18. 

Please let me know how you would like to proceed. Thank you!

**Comment by madysoncbrown** [comment]
@sabrinatoro Hi Sabrina, I am sorry I am not fully understanding your question. Per the GeneReviews (https://www.ncbi.nlm.nih.gov/books/NBK475670/) "RAB18 deficiency is the molecular deficit underlying both Warburg micro syndrome (characterized by eye, nervous system, and endocrine abnormalities) and Martsolf syndrome (characterized by similar – but milder – findings)" and "The diagnosis of RAB18 deficiency is established in a proband who either has suggestive clinical and neuroimaging findings and biallelic pathogenic variant(s) in RAB3GAP1, RAB3GAP2, RAB18, or TBC1D20 identified by molecular genetic testing or meets the clinical diagnostic criteria when molecular genetic testing has not been performed or has not revealed pathogenic variants in one of the four known genes." 

Could you please clarify what you are suggesting? We are trying to create a grouping where all four of these genes and their presentations are together as described in the GeneReviews. Thank you! 

@ErinRiggs

**Comment by sabrinatoro** [comment]
@madysoncbrown 
Looking at the GeneReview, it looks like a group of diseases is called "RAB18 deficiency", even though RAB18 might not be implicated in the diseases grouped under this umbrella term. This is very weird to me, and therefore my confusion. 

So I want to make sure that the request is correct: create a new umbrella term called "RAB18 deficiency" even though the gene might not be implicated in the diseases grouped.

**Comment by sabrinatoro** [comment]
I guess if the other genes associated are part of the same pathway/cascade that would make sense. I haven't found any evidence of that yet, I am still searching.

**Comment by ErinRiggs** [comment]
Yes, that is our understanding.  This is also in the GeneReviews, if helpful:
"Molecular Pathogenesis
The molecular pathology of Warburg micro syndrome and Martsolf syndrome arises either from the absence of Ras-related protein Rab-18 (RAB18) protein or from its functional absence as a result of dysregulation. Because RAB3GAP1, RAB3GAP2, and TBC1D20 are each essential for the regulation of RAB18, biallelic loss-of-function variants in the genes that encode these proteins lead to clinically indistinguishable phenotypes.

RAB18 encodes a highly conserved member of the RAB subfamily of the RAS superfamily of small GTPases [[Handley 2017](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)]. Different RAB protein isoforms function to regulate discrete steps in trafficking between cellular membrane compartments. RAB18 is proposed to have roles in regulation of lipid droplets, lipolysis, and lipogenesis [[Martin et al 2005](https://www.ncbi.nlm.nih.gov/books/NBK475670/#), [Ozeki et al 2005](https://www.ncbi.nlm.nih.gov/books/NBK475670/#), [Pulido et al 2011](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)], trafficking between the Golgi and endoplasmic reticulum (ER) [[Dejgaard et al 2008](https://www.ncbi.nlm.nih.gov/books/NBK475670/#), [Handley et al 2015](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)], ER structure [[Gerondopoulos et al 2014](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)], exocytosis [[Vazquez-Martinez et al 2007](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)], and autophagy [[Feldmann et al 2017](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)]. The specific cellular deficit(s) that underlie the pathology of Warburg micro syndrome and Martsolf syndrome are not yet known.

In common with other small GTPases, RAB proteins function as "molecular switches." They can bind to GDP or GTP and adopt different conformations according to which nucleotide is bound. These different conformations are in turn associated with altered protein-binding characteristics that affect interactions with regulators and with the mediators of their downstream cellular functions. Switching between GDP- and GTP-bound conformations is tightly regulated by two classes of protein, guanine nucleotide exchange factors (GEFs) and GTPase-activating proteins (GAPs). GEFs mediate the exchange of bound GDP for GTP. GAPs stimulate the intrinsic GTPase activity of the RAB proteins, thereby mediating hydrolysis of bound GTP into GDP.

RAB3GAP1 and RAB3GAP2 each encode essential subunits of a binary complex with GEF activity toward RAB18 [[Gerondopoulos et al 2014](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)]. This complex is necessary to mediate GDP-GTP exchange and the associated RAB18 conformational change.

TBC1D20 encodes a RAB-GAP with modest in vitro GAP activity toward RAB18. Several lines of evidence indicate that it functions as a RAB18-GAP physiologically [[Haas et al 2007](https://www.ncbi.nlm.nih.gov/books/NBK475670/#), [Handley et al 2015](https://www.ncbi.nlm.nih.gov/books/NBK475670/#)]. The regulation of RAB18 by TBC1D20 opposes that of the RAB3GAP complex, promoting its GDP- rather than the GTP-bound conformation. However, both regulators are required for RAB18 to function appropriately, in a spatiotemporally restricted manner."

**Comment by sabrinatoro** [comment]
Thank you @ErinRiggs and @madysoncbrown! 
I will create the term and add a comment to make sure that there is no confusion about the involvement of the RAB18 gene. 
The term should be available in the February release. Thanks!
