### ISSUE TITLE
Mondo rare subset: remove non-human disease animal

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7030]
The current rare disease subset includes non-human disease animal diseases. 
The rare disease subset should only include human diseases. 

It looks that the only culprits are 2 non-human disease terms that have the NORD_rare subset annotation: 
- tuberculosis, avian (MONDO:0025135)
- anaplasmosis in cattle (MONDO:0044748)

(the other terms are classification terms which are included for classification reasons)

**Comment by matentzn** [comment]
I just checked the source of truth about this; the table we received from NORD clearly states that avian tuberculosis is "rare"; 

- [ ] Check with Gioconda if they can provide us with an updated table and tell them about the two animal diseases
- [ ] Update NORD subset in Mondo to remove these
- [ ] #6501 
- [ ] Decide if we want to (a) _remove_ non-human animal diseases from the subset, (b) keep them per design, (c) add qc that makes noise when a non-human animal disease is added to mondo

I personally favour (c) rather than (a) because it gives us a change to fix some issues with the source.

**Comment by galyea123** [comment]
Hi!  avian tuberculosis is one of the conditions that I need to review.  While it is a disease that affects birds, it can, in rare occasions, affects mammals too, including humans, specially immunocompromised.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3135220/ 
https://edis.ifas.ufl.edu/publication/PS019 
https://www.woah.org/fileadmin/Home/fr/Health_standards/tahm/3.03.06_AVIAN_TB.pdf

As per anaplasmosis of cattle I removed it from the NORD RD list. Note that Anaplasmosis was formerly known as Human Granulocytic Ehrlichiosis, which affects humans.

Thank you very much!!!  Your finding also allowed me to review all the related terms. Gioconda

**Comment by matentzn** [comment]
Very interesting! @galyea123!

@sabrinatoro maybe we should:

- Add qc when non-human animal diseases end up in the "rare" subset.
- Manually curate qc exceptions as we always do.

Let me know your preference.

The alternative is to carefully rethink by an animal disease - if avian tb can affect humans, why should it be classified as an avian disease? Remember the important difference between and ontology and taxonomy is that we encode biological reality rather than "human classification". Is our definition of animal disease "disease that appears in animal", or is it "disease that predominantly appears in animals"?

I am not suggesting anything, just outlining questions.

**Comment by galyea123** [comment]
Maybe adding the parent term for "Zoonotic diseases" (also known as zoonoses) defined by diseases that are caused by germs that spread between animals and people. https://www.cdc.gov/onehealth/basics/zoonotic-diseases.html
I found the following article very helpful too: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7563794/ (it includes a table with the major zoonotic diseases).
Hope this helps somehow,  Thank you! Gioconda

**Comment by matentzn** [comment]
Agreed with @sabrinatoro for now to ensure that we get notified if an animal disease ends up in the rare disease subset.

@galyea123 the question of Zoonotic disease will surface again later this year (in the context of infectious disease review), but we will keep your very interesting examples in mind!

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
