### ISSUE TITLE
Revise label of MONDO:0005259 'Asperger syndrome'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#705]
Currently, MONDO:0005259 is labeled 'Asperger syndrome'.
However, there was a proposal and some discussion on renaming MONDO:0005259 as 'Autism spectrum disorder without disorder of intellectual development and with mild or no impairment of functional language' and making 'Asperger syndrome' a synonym and mark it 'A synonym that is historic and discouraged'. 
Stemming from that discussion is the broader issue of whether or not the structure of MONDO should reflect the DSM-V, and what to do if MONDO wishes to diverge.
Details here: https://github.com/EBISPOT/efo/issues/275
If MONDO makes any change in label and/or placement of MONDO:0005259 'Asperger syndrome', EFO will pick it up after the MONDO release.
(The current children of MONDO:0005259 'Asperger syndrome' (ASPG1-4) will be taken care of as part of the MONDO work on 'susceptibility' terms, see #699 .)
Thanks.

**Comment by pnrobinson** [comment]
I would suggest that until the community drops Asperger, it would probably be best not to change the label but instead put a summary of the controversy into a comment.

**Comment by nicolevasilevsky** [comment]
I like this idea!

**Comment by ErinRiggs** [comment]
Here is some feedback from Scott Myers, developmental pediatrician and co-chair of the ClinGen Neurodevelopmental Disorders Clinical Domain Working Group:

"I think the proposed change is reasonable, but would propose considering a slight change from “mild or no impairment of functional language” to “mild or no impairment of functional spoken language,” only because they must have deficits in nonverbal communicative behavior to meet the DSM-5 definition of autism spectrum disorder.  
 
The only other issue (very minor) that could make this not quite equivalent to DSM-IV-TR and ICD-10 Asperger Disorder is the requirement of “no clinically significant general delay in language (e.g., single words used by age 2 years, communicative phrases used by age 3 years)” in DSM-IV-TR.  This emphasis on early general language development meant that 2 individuals (at age 10, for example) could have the same IQ, degree of impairment in pragmatic and higher-order semantic aspects of language, reciprocal social behavior, and repetitive behavior/restricted interests, but if historically one did not speak in phrases by age 3 and the other did, the latter would be diagnosed with Asperger Disorder and the former would not meet the criteria (so would have been classified as having PDDNOS). This over-emphasis on early language development is part of why the previous categorization system turned out to be not very useful.

This brings up the fact that the DSM-IV-TR categories were changed in DSM-5 to the single category “autism spectrum disorder” partly because of research demonstrating that the subclassiﬁcations had little scientiﬁc justiﬁcation and were not used reliably, even by experts (e.g., Lord C, Petkova E, Hus V, et al. A multisite study of the clinical diagnosis of different autism spectrum disorders. Arch Gen Psychiatry. 2012;69:306–313).  One could argue to just map the Asperger term to ASD."

**Comment by nicolevasilevsky** [comment]
thank you @ErinRiggs!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Not urgent, but was there an action item here? https://github.com/monarch-initiative/mondo/issues/705#issuecomment-535670438
I won't tag for any Milestone, just following up. Thanks.

**Comment by nicolevasilevsky** [comment]
Action item - I will add a comment on this class
