### ISSUE TITLE
genes/taxon information missing in mondo.obo

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7095]
This issue was uncovered during the January 2024 release. the conversation from slack is below. 

Problem: the following axioms (and equivalent) are not found in the mondo.obo file. 
- 'in taxon' some NCBITaxon (eg all the non-human animal diseases)
- 'has material basis in germline mutation in' some GENE

Nico's investigation: 
1. the current mondo.obo (and only that specific file, all other release products, including the OWL and other OBO files, seem ok) is a bit broken. This command, which has been there from the beginning (8 years ago): 
`owltools --use-catalog $@.tmp.owl --remove-imports-declarations --remove-dangling -o -f obo --no-check $@.tmp`  does the followings
    - It takes the ontology, then removes all imports declaration (which means, importantly, all axiom annotations like labels and definitions on all classes which dont have a Mondo ID).
    - Then, it proceeds to “remove dangling” axioms, which translates to “remove all classes, which do not have an annotation assertion associated with it” (this is how owltools defines “dangling” which is not ideal).
    - “Remove class” means, and here it becomes interesting, removing all axioms using the getReferencingAxioms OWLAPI method which, for some reason, does not look at the values of annotation assertion axioms. So, you see 100 or so annotations to NCBITaxon classes, because they are not caught by this method. In effect, this removes all axioms with external classes in them.
2. The behaviour has always been thus, but I would prefer if you could confirm this observation
My suggestion is that we should replace this owltools command with the normal “mondo-base” product which should not be broken. (@cmungall should confirm)
3. Lastly, I confirmed that mondo-base.obo does not exhibit any of the issues you observed. (neither missing equivalent class axiom, nor taxon constraint).

**Comment by sabrinatoro** [comment]
@matentzn and @twhetzel 
I am assigning this for the February release, but I don't know how long it will take, so please let me know if it will require longer. 
Also, I suspect that testing this will be a bit tricky.

**Comment by twhetzel** [comment]
@matentzn when you have time (perhaps next 1:1), let me know how you would like us to address this issue. One thing I am not clear on is in your point (2) above what "replace this owltools command with the normal “mondo-base” product" means.

**Comment by twhetzel** [comment]
@cmungall is this something you can confirm from Nico's original post (2):
```
My suggestion is that we should replace this owltools command with the normal “mondo-base” product which should not be broken.
```

**Comment by matentzn** [comment]
In slack we came to the conclusion that probably we need to use minimal. @cmungall 

I suggest to add this issue as priority to tech call agenda

**Comment by twhetzel** [comment]
Keep in mind the next Tech call is not until Feb. 2. It's on the agenda.

**Comment by twhetzel** [comment]
From Nico (Slack discussion) - decisions to discuss to determine how to address the issue:
1. To not change the mondo.obo too much from what it is now and only include the Mondo ids, and no relationships?
2. Do we want to include some, but not all relationships (e.g. genes, but not anatomical links)
3. Do we want to include all relationships?

**Comment by sabrinatoro** [comment]
Keeping mondo.obo as is for the February release. 
The team should discuss what we want to do in more depth. Any update should be communicated to the community before changing .obo

**Comment by twhetzel** [comment]
@matentzn will you be making this change for the March release?

**Comment by matentzn** [comment]
The technical side is 2 minutes; I can do it any time. Action items before hand:

- [ ] Compare https://github.com/monarch-initiative/mondo/releases/download/v2024-02-06/mondo-minimal.obo with https://github.com/monarch-initiative/mondo/releases/download/v2024-02-06/mondo-base.obo
- [ ] Decide which one is better for users
- [ ] Prepare a communication for users to explain the change 
- [ ] In the next release, without the change, announce the intended change with a link to one of the two above so people know what will happen.
- [ ] Nico to make the switch.

Someone needs to do the first four before I can do the last. 

- Seems that minimal does not have any axiom annotations?
- Seems that minimal has "equivalent class" statements rather than mappings?

Looks chaotic. Needs curator.

## Short sample of diff

To illustrate the (huge) difference between the two alternatives, check this example.

<details><summary>Diff between mondo-base.obo and mondo-minimal.obo</summary>

# Ontology comparison

## Left
- Ontology IRI: `http://purl.obolibrary.org/obo/mondo/subsets/mondo-minimal.owl`
- Version IRI: *None*
- Loaded from: `file:/work/ws/babelon/mondo-minimal.obo`

## Right
- Ontology IRI: `http://purl.obolibrary.org/obo/mondo/mondo-base.owl`
- Version IRI: `http://purl.obolibrary.org/obo/mondo/mondo-base/mondo/releases/2024-02-06/mondo-base.owl/mondo/mondo-base.owl`
- Loaded from: `file:/work/ws/babelon/mondo-base.obo`

### Ontology imports 



### Ontology annotations 
#### Removed
- [license](http://purl.org/dc/terms/license) "https://creativecommons.org/publicdomain/zero/1.0/"^^[string](http://www.w3.org/2001/XMLSchema#string) 

#### Added
- [IAO_0000700](http://purl.obolibrary.org/obo/IAO_0000700) [disease](http://purl.obolibrary.org/obo/MONDO_0000001) 

- [IAO_0000700](http://purl.obolibrary.org/obo/IAO_0000700) [disease characteristic](http://purl.obolibrary.org/obo/MONDO_0021125) 

- ....

- REMOVED THE REST, BASICALLY NO ONTOLOGY ANNOTATIONS ARE INCLUDED IN `mondo-minimal.obo`.


### 10q22.3q23.3 microduplication syndrome `http://purl.obolibrary.org/obo/MONDO_0017180`
#### Removed
- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GARD:21052"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "UMLS:C5190512"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [exactMatch](http://purl.obolibrary.org/obo/mondo/subsets/mondo-minimal#exactMatch) [Orphanet_276422](http://purl.obolibrary.org/obo/Orphanet_276422) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [exactMatch](http://purl.obolibrary.org/obo/mondo/subsets/mondo-minimal#exactMatch) [C5190512](http://linkedlifedata.com/resource/umls/id/C5190512) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) EquivalentTo [Orphanet_276422](http://purl.obolibrary.org/obo/Orphanet_276422) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) SubClassOf [partial duplication of the long arm of chromosome 10](http://purl.obolibrary.org/obo/MONDO_0016961) 

#### Added
- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [IAO_0000233](http://purl.obolibrary.org/obo/IAO_0000233) "https://github.com/monarch-initiative/mondo/issues/3492"^^[anyURI](http://www.w3.org/2001/XMLSchema#anyURI) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [nord_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#nord_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:NORD"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [has_exact_synonym](http://www.geneontology.org/formats/oboInOwl#hasExactSynonym) "dup(10)(q22.3q23.3)"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "UMLS:C5190512"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:equivalentTo"^^[string](http://www.w3.org/2001/XMLSchema#string) 

  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:MEDGEN"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [orphanet_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#orphanet_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [exactMatch](http://purl.obolibrary.org/obo/mondo/mondo-base#exactMatch) [C5190512](http://linkedlifedata.com/resource/umls/id/C5190512) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [rare](http://purl.obolibrary.org/obo/mondo/mondo-base#rare) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [exactMatch](http://purl.obolibrary.org/obo/mondo/mondo-base#exactMatch) [Orphanet_276422](http://purl.obolibrary.org/obo/Orphanet_276422) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GARD:21052"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [ordo_malformation_syndrome](http://purl.obolibrary.org/obo/mondo/mondo-base#ordo_malformation_syndrome) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:equivalentTo"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [gard_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#gard_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "GARD:21052"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) [has_exact_synonym](http://www.geneontology.org/formats/oboInOwl#hasExactSynonym) "trisomy 10q22.3q23.3"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [10q22.3q23.3 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017180) SubClassOf [partial duplication of the long arm of chromosome 10](http://purl.obolibrary.org/obo/MONDO_0016961) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:276422"^^[string](http://www.w3.org/2001/XMLSchema#string) 


### 11p15.4 microduplication syndrome `http://purl.obolibrary.org/obo/MONDO_0017580`
#### Removed
- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "UMLS:C4749508"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [exactMatch](http://purl.obolibrary.org/obo/mondo/subsets/mondo-minimal#exactMatch) [Orphanet_300305](http://purl.obolibrary.org/obo/Orphanet_300305) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [exactMatch](http://purl.obolibrary.org/obo/mondo/subsets/mondo-minimal#exactMatch) [C4749508](http://linkedlifedata.com/resource/umls/id/C4749508) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GARD:21232"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [overgrowth syndrome](http://purl.obolibrary.org/obo/MONDO_0019716) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [partial duplication of the short arm of chromosome 11](http://purl.obolibrary.org/obo/MONDO_0016948) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [multiple congenital anomalies/dysmorphic syndrome-intellectual disability](http://purl.obolibrary.org/obo/MONDO_0015159) 

#### Added
- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [exactMatch](http://purl.obolibrary.org/obo/mondo/mondo-base#exactMatch) [Orphanet_300305](http://purl.obolibrary.org/obo/Orphanet_300305) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [rare](http://purl.obolibrary.org/obo/mondo/mondo-base#rare) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [ordo_malformation_syndrome](http://purl.obolibrary.org/obo/mondo/mondo-base#ordo_malformation_syndrome) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GARD:21232"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [has_exact_synonym](http://www.geneontology.org/formats/oboInOwl#hasExactSynonym) "trisomy 11p15.4"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [gard_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#gard_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "GARD:21232"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "11p15.4 microduplication syndrome is a rare partial autosomal trisomy/tetrasomy characterized by obesity, global developmental delay and intellectual disability, facial dysmorphism (synophrys, high-arched eyebrows, large posteriorly rotated ears, upturned nose, long smooth philtrum, overbite and high palate), large hands and limb hypotonia. Additional features include seizures and behavioral abnormalities."^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [nord_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#nord_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:NORD"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:equivalentTo"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [exactMatch](http://purl.obolibrary.org/obo/mondo/mondo-base#exactMatch) [C4749508](http://linkedlifedata.com/resource/umls/id/C4749508) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [in_subset](http://www.geneontology.org/formats/oboInOwl#inSubset) [orphanet_rare](http://purl.obolibrary.org/obo/mondo/mondo-base#orphanet_rare) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "UMLS:C4749508"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:equivalentTo"^^[string](http://www.w3.org/2001/XMLSchema#string) 

  - [source](http://www.geneontology.org/formats/oboInOwl#source) "MONDO:MEDGEN"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [has_exact_synonym](http://www.geneontology.org/formats/oboInOwl#hasExactSynonym) "dup(11)p(15.4)"^^[string](http://www.w3.org/2001/XMLSchema#string) 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [IAO_0000233](http://purl.obolibrary.org/obo/IAO_0000233) "https://github.com/monarch-initiative/mondo/issues/3492"^^[anyURI](http://www.w3.org/2001/XMLSchema#anyURI) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) [excluded subClassOf](http://purl.obolibrary.org/obo/mondo/mondo-base#excluded_subClassOf) [syndromic intellectual disability](http://purl.obolibrary.org/obo/MONDO_0000508) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

  - [source](http://www.geneontology.org/formats/oboInOwl#source) "https://orcid.org/0000-0001-5208-3432"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [partial duplication of the short arm of chromosome 11](http://purl.obolibrary.org/obo/MONDO_0016948) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [multiple congenital anomalies/dysmorphic syndrome-intellectual disability](http://purl.obolibrary.org/obo/MONDO_0015159) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

- [11p15.4 microduplication syndrome](http://purl.obolibrary.org/obo/MONDO_0017580) SubClassOf [overgrowth syndrome](http://purl.obolibrary.org/obo/MONDO_0019716) 
  - [source](http://www.geneontology.org/formats/oboInOwl#source) "Orphanet:300305"^^[string](http://www.w3.org/2001/XMLSchema#string) 

</details>

**Comment by twhetzel** [comment]
@sabrinatoro who do you want to make this decision between `mondo-minimal.obo` vs. `mondo-base.obo` and which is better for users?

**Comment by sabrinatoro** [comment]
I don't know that we can choose what is better for users without checking with them, and without understanding what files the users actually use. 
Here is my proposal: 
- make a simple slide explaining the difference between mondo-minimal.obo vs. mondo-base.obo (it could be as simple as showing a term on the left, and a term on the right with the extra annotations)
- Present at an outreach call. The goals are 1) explaining the situation (and offering a space for people to ask questions), 2) finding out what file(s) users use and whether a change would affect them (and ultimately, figuring out what users want)
- Include the slides and explanation in an email (possibly in the next release email), and collect feedback
- (possibly) bring this again on an outreach call where we might have more questions
- proceed according to the feedback/votes we get

This will take 1-2 months, but I think we cannot proceed without involving the users.

**Comment by twhetzel** [comment]
@sabrinatoro is there a date in mind to present this at the outreach call, the next one? I can make a slide unless you prefer to.

**Comment by matentzn** [comment]
I personally think this process is a bit too much work, but I do not have any strong feelings. 

Here is my suggestion (after 90 minutes of analysis).

_We (1) decide to move mondo.obo to mondo-base, (2) announce it with the next release email (with a link to the base file release) and see who responds or complains._ Trish can announce the change in the outreach call and I will help her add some slides towards the difference.

Reasons:

1. Mondo minimal is not well defined and has issues (wrong IRIs in places). mondo-base is a well defined product in OBO ontologies with a proper standard definition in ODK. I even [started writing a proper spec](https://github.com/OBOAcademy/obook/pull/387) for it.
1. Mondo-base hase _more stuff_ then mondo.obo, not less, which means it is lower risk for users (after all people should not be surprised if an ontology suddenly has more information. I just did a thorough diff analysis between the two releases - mondo-base is minus some minor syntactic bugs with the old mondo.obo (xsd:anyUri was wrongly formatted in mondo.obo
1. Users cannot judge exactly what they want. There will be different users, and the most relevant ones may not speak up (thats why I am against, in this instance, to ask users.

In case you agree with me, I made a PR towards this change which should be merged right _after_ the next release:

https://github.com/monarch-initiative/mondo/pull/7324

**Comment by twhetzel** [comment]
Since no users that I am aware of have requested these updates and following on Nico's analysis, is it worthwhile to continue with this change/update?

**Comment by matentzn** [comment]
This very ticket here at least caused some confusion to users.. this would be fixed by moving your base!

**Comment by twhetzel** [comment]
I think Sabrina is the user in this case. I can't find detailed notes in the Curation/Tech notes to confirm, but I think she noticed this difference while checking on a release recently even though no other users had requested any updates.

**Comment by sabrinatoro** [comment]
I think we should use base (add all relations).

**Comment by matentzn** [comment]
#7324 is dealing with this issue, eg. (Taxon example)

```
[Term]
id: MONDO:0005748
name: enzootic pneumonia of calves
def: "Chronic endemic respiratory disease of dairy calves and an important component of bovine respiratory disease complex. It primarily affects calves up to six months of age and the etiology is multifactorial. Stress plus a primary viral infection is followed by a secondary bacterial infection. The latter is most commonly associated with pasteurella multocida producing a purulent bronchopneumonia. Sometimes present are mannheimia haemolytica; haemophilus somnus and mycoplasma species." [MESH:D048089]
xref: EFO:0007256 {source="MONDO:equivalentTo"}
xref: MESH:D048089 {source="MONDO:equivalentTo", source="EFO:0007256"}
xref: UMLS:C0276046 {source="MONDO:equivalentTo"}
is_a: MONDO:0024913 ! cattle disease
is_a: MONDO:0700110 ! pneumonia, non-human animal
relationship: in_taxon NCBITaxon:9913 {source="https://orcid.org/0000-0002-4142-7153", source="https://orcid.org/0000-0002-5002-8648", source="https://www.merckvetmanual.com/"}
property_value: exactMatch http://identifiers.org/mesh/D048089
property_value: exactMatch http://linkedlifedata.com/resource/umls/id/C0276046
```

and other relationships example 

```
[Term]
id: MONDO:0005789
name: hepatitis D virus infection
def: "Inflammation of the liver in humans caused by hepatitis delta virus, a defective RNA virus that can only infect hepatitis B patients. For its viral coating, hepatitis delta virus requires the hepatitis B surface antigens produced by these patients. Hepatitis D can occur either concomitantly with (coinfection) or subsequent to (superinfection) hepatitis B infection. Similar to hepatitis B, it is primarily transmitted by parenteral exposure, such as transfusion of contaminated blood or blood products, but can also be transmitted via sexual or intimate personal contact." [MESH:D003699]
subset: gard_rare {source="GARD:21716"}
subset: nord_rare {source="MONDO:NORD"}
subset: ordo_disease {source="Orphanet:402823"}
subset: orphanet_rare {source="Orphanet:402823"}
subset: rare
synonym: "delta hepatitis" EXACT [DOID:2047]
synonym: "HDV" EXACT ABBREVIATION [Orphanet:402823]
synonym: "Hepatitis D virus" EXACT [Orphanet:402823]
synonym: "hepatitis delta" EXACT [MONDO:0018441]
synonym: "Hepatitis delta virus caused hepatitis" EXACT [MONDO:patterns/specific_infectious_disease_by_agent]
synonym: "Hepatitis delta virus hepatitis" EXACT []
synonym: "hepatitis type D" EXACT [DOID:2047, EFO:0007304, MONDORULE:1]
xref: DOID:2047 {source="EFO:0007304", source="MONDO:equivalentTo"}
xref: EFO:0007304 {source="MONDO:equivalentTo"}
xref: GARD:21716 {source="Orphanet:402823"}
xref: ICD9:070.52 {source="MONDO:relatedTo", source="MONDO:i2s"}
xref: MESH:D003699 {source="EFO:0007304", source="DOID:2047", source="MONDO:equivalentTo"}
xref: NORD:2020 {source="MONDO:NORD"}
xref: Orphanet:402823 {source="MONDO:equivalentTo"}
xref: SCTID:707341005 {source="DOID:2047", source="MONDO:equivalentTo"}
is_a: MONDO:0006011 ! viral hepatitis
is_a: MONDO:0021674 ! post-viral disorder
intersection_of: MONDO:0002251 ! hepatitis
intersection_of: MONDO:0005550 ! infectious disease
intersection_of: MONDO:0100332 NCBITaxon:12475 ! disease has primary infectious agent
relationship: disease_arises_from_feature MONDO:0005344 ! hepatitis B virus infection
relationship: disease_has_infectious_agent NCBITaxon:10407
relationship: has_characteristic MONDO:0021136 {source="MONDO:0015576", source="MONDO:0018928"} ! rare
relationship: MONDO:0100332 NCBITaxon:12475 ! disease has primary infectious agent
property_value: exactMatch DOID:2047
property_value: exactMatch http://identifiers.org/mesh/D003699
property_value: exactMatch http://identifiers.org/snomedct/707341005
property_value: exactMatch Orphanet:402823
```
