### ISSUE TITLE
split term: Noonan syndrome with multiple lentigines

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#713]
Term to split: Noonan syndrome with multiple lentigines

Name for new term to bud off: LEOPARD syndrome 1

Currently MONDO:0007893 conflates the classic form (LEOPARD syndrome 1; OMIM:151100) and the series OMIMPS:151100  / Orphanet:500

This term has been used by ClinGen

I think the need for a split is clear. We need to decide which IDs to use:

 1. obsolete MONDO:0007893 and make 2 new
 2. retain MONDO:0007893 for general form/series and mint new for type 1
 3. retain MONDO:0007893 for type 1 and mint new for general form/series

1 is safest but causes most churn. I think 2 can be justified as the definition is general

**Comment by maglott** [comment]
What is the standard policy for splits?  I vote for 1.  Clearer for those tracking by other ids such as MIM numbers.

**Comment by nicolevasilevsky** [comment]
Should I go ahead and obsolete MONDO:0007893 and create two new terms:

**Label: ** Noonan syndrome with multiple lentigines
**Def:** Noonan syndrome with multiple lentigines (NSML), is a rare multisystem genetic disorder characterized by lentigines, hypertrophic cardiomyopathy, short stature, pectus deformity, and dysmorphic facial features.
**dbxef**: Orphanet:500
and all the current synonyms would stay with this term

 **Label: ** LEOPARD syndrome 1
**Def:** LEOPARD is characterized by multiple lentigines, electrocardiographic conduction abnormalities, ocular hypertelorism, pulmonic stenosis, abnormal genitalia, retardation of growth, and sensorineural deafness.
**dbxef**: OMIM:151100
**synonyms**
lentiginosis, cardiomyopathic
multiple lentigines syndrome

**Comment by mellybelly** [comment]
Given that there is conflation on "Noonan syndrome with multiple lentigines" referencing parent/child synonyms/xrefs, we recommend obsoleting and making two new terms. @courtneythaxton and @larrybabb would you like to weigh in? we'll wait 2 weeks before committing the obsoletion and send out an email to the user list for feedback.

**Comment by courtneythaxton** [comment]
Hi @mellybelly @nicolevasilevsky @larrybabb @cmungall 

From a ClinGen perspective since we have at least 3 curations if not more that use MONDO:007893 for the classification is number 2. Keep the term as a general form series (presumably the parent term of LEOPARD 1, 2, and 3), and mint a new MONDO ID for LEPARD 1 associated with PTPN11 genes per OMIM MIM#151100. This also leaves the MIM151100 to map to a new MONDO term, and Orphaned:500 is left as the broad general term that can map directly the ID. Hopefully that makes sense :)

@courtneythaxton

**Comment by larrybabb** [comment]
I am not a domain expert but I do want to verify that all related issues for Rasopathy are dealt with and considered so that this domain area can be fixed once and for all.  I spoke with @ahamosh at CCG and the ClinGen SC meeting over the past couple days and it seems like it may be worth a discussion with ada involved to make sure we have the Rasopathy domain built with the hierarchy and nodes that will work well with Orpha, OMIM and MONDO.  We (ClinGen) needs the superstructure of MONDO to manage the breadth and various levels of granularity needed throughout the data we capture. But we also need to make sure we can have OMIM, Orpha and Mondo represent these ClinGen clinical domain groups accurately as these experts are generating and disseminating lots of very useful information that relies on these domain areas to be properly and consistently represented for numerous use cases.

please make sure issue #606 and #624 are considered as well while developing the final hierarchy for the entire Rasopathy domain of diseases.  (Again some verification from @ahamosh on the final decision seems critical.)

**Comment by courtneythaxton** [comment]
I do echo and agree with @larrybabb and want to add that we also need to make sure that while there is granularity of phenotypes, that we also represent broader entities. The ClinGen lumping and splitting group has empowered groups with a way to define disease entities and the work with MonDO on this to harmonize. Some consideration by the GCEPs may need to be made to fit within these guidelines and work with @adahamosh and OMI, orphaned, and MonDO (@mellybelly).

@courtneythaxton

**Comment by nicolevasilevsky** [comment]
I created a new term MONDO_0100082 LEOPARD syndrome 1 in PR https://github.com/monarch-initiative/mondo/pull/792

I am a bit uncertain what to do about the xref to Orphanet:500, I left as a xref on MONDO_0007893 'Noonan syndrome with multiple lentigines'
