### ISSUE TITLE
dendritic cell sarcoma MONDO:0004380 & MONDO:0019482[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7175]
**Mondo term (ID and Label)**
MONDO:0019482 dendritic cell sarcoma not otherwise specified

**Reason for deprecation**
The NCI 'NOS' term is already lumped with the broader concept, I am not sure why this ORDO sourced term is not mapped to same term at NCI term. 
UMLS combines the NCI term and the Orphanet term on the same CUI: C1301364 (it also includes the current SNOMED CT codes for 'dendritic cell sarcoma' here as well i.e. 1156495004 & 1156631003 )

**Term to be merged with**
dendritic cell sarcoma MONDO:0004380

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
The merging of MONDO:0019482 dendritic cell sarcoma not otherwise specified into dendritic cell sarcoma MONDO:0004380 seems reasonable for the above rationale. 

Note that MONDO:0019482 dendritic cell sarcoma is a child of MONDO:0020082 dendritic cell tumor that is defined by 5 subtypes: "There are five subtypes of dendritic cell tumors: follicular dendritic cell tumor, interdigitating dendritic cell tumor, Langerhans' cell histiocytosis, Langerhans' cell sarcoma, and dendritic cell sarcoma not specified otherwise."

I don't know if the definition of MONDO:0020082 dendritic cell tumor needs to be revised if MONDO:0019482 dendritic cell sarcoma not otherwise specified is obsoleted?

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0019482 MONDO:0004380 -o -f obo mondo-edit.obo`

**Comment by nicolevasilevsky** [comment]
> I don't know if the definition of MONDO:0020082 dendritic cell tumor needs to be revised if MONDO:0019482 dendritic cell sarcoma not otherwise specified is obsoleted?

these terms were merged and `dendritic cell sarcoma not otherwise specified` is a synonym of 'dendritic cell tumor'
