### ISSUE TITLE
MONDO:0024361 & MONDO:0003406 sleep-wake/circadian sleep disorder[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7189]
**Mondo term (ID and Label)**
MONDO:0003406	Sleep-wake disorder
MONDO:0024361	Circadian rhythm sleep disorder
**Reason for deprecation**

Not sure if this is a merge, but the definitions and synonyms on these 2 terms seem to need review; as is, they seem to be equivalent concepts.  

(Also the sleep-wake disorder MONDO:0003406 term has syns of ‘sleep disorder’ which is the parent concept, so synonyms should probably be reviewed with respect to other terms in this branch.) 

**Term to be merged with**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
Hi @kanems - We decided to keep both of these terms, but updated the definitions and synonyms to make it more clear the difference between these two terms. Also, for MONDO:0003406 sleep-wake disorder the xref was changed from: UMLS:C0877792 to: UMLS:C4042891 since this Mondo term highly references MESH:D012893 and this MESH term is mapped to UMLS:C4042891.

**Comment by kanems** [comment]
Thanks for following up. I agree with the CUI mapping update as well. I'll make sure our Mondo ID-CUI relationships is updated as such.
