### ISSUE TITLE
MONDO:0016819 & MONDO:0023820 Moebius axonal neuropathy hypogonadism[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7198]
**Mondo term (ID and Label)**
MONDO:0023820 Moebius axonal neuropathy hypogonadism 

**Reason for deprecation**
These appear to be the same concept, the MeSH record seems to point to the same concept as the Orphanet term based on the synonym/ definition for the MeSH entry.  https://www.ncbi.nlm.nih.gov/mesh/?term=C535806

**Term to be merged with**
MONDO:0016819 Moebius syndrome-axonal neuropathy-hypogonadotropic hypogonadism syndrome
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0023820 Moebius axonal neuropathy hypogonadism into MONDO:0016819 Moebius syndrome-axonal neuropathy-hypogonadotropic hypogonadism syndrome because they appear to represent the same concept. 

Note there is a typo in the definition of MONDO:0016819 - MC6bius should be Möbius.
