### ISSUE TITLE
MONDO:0006788 hydrophthalmos & MONDO:0020366 congenital glaucoma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7282]
**Mondo term (ID and Label)**
MONDO:0006788 hydrophthalmos

**Reason for deprecation**
UMLS puts the MeSH ID on the same CUI as SNOMED CT [204113001](http://identifiers.org/snomedct/204113001) and NCI C50648.
the DOID definition for  hydrophthalmos (http://purl.obolibrary.org/obo/DOID_11212 ) is 
"A primary _congenital glaucoma_ characterized by early onset glaucoma in one or both eyes with elevated intraocular pressure and increased corneal diameter ... Hydrophthalmus is caused by congenital defects of the trabecular meshwork and anterior chamber angle that _block aqueous outflow and raises intraocular pressure_, leading to optic nerve atrophy and early vision loss. " 
Which seems to be the same as the concept for congenital glaucoma.

**Term to be merged with**
MONDO:0020366 congenital glaucoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
As I read the definitions, MONDO:0006788 hydrophthalmos seems more like a phenotype that should exist in HP. @sabrinatoro what are your thoughts?

**Comment by sabrinatoro** [comment]
@twhetzel I agree, based on the definition MONDO:0006788 hydrophthalmos seems to be a phenotype. 
Looking at the MONDO:equivalentTo DOID refers to an actual disease. 

So if you decide to obsolete MONDO:0006788 based on the fact that the term is a phenotype (instead of merging), you should
1) use "consider" : MONDO:0020366 congenital glaucoma
2) review the MONDO:equivalentTo x-ref and figure out whether they refer to a phenotype (and therefore live on the obsoleted term with the updated source) or to a disease (and move it to the correct disease. ie DO might need to be added as an equivalent to 'congenital glaucoma')
