### ISSUE TITLE
Adult Fanconi syndrome should be merged with "acquired" FS

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#7323]
From @pnrobinson 

> adult Fanconi syndrome --- needs to be merged with "acquired" FS!!!

**Comment by galyea123** [comment]
We do not list adult Fanconi syndrome in NORD as this is not really a separate entity. Thank you! Gioconda

**Comment by sabrinatoro** [comment]
I am not 100% sure that "all" 'adult Fanconi syndrome' are acquired. 
My research reported: 
- Adults with Fanconi syndrome **typically** have the acquired type
- in adults, it is **mainly caused** by medications, exogenous toxins, and heavy metals. 
- In adults, Fanconi syndrome **can be** caused by various things that damage the kidneys, 

The following seem to indicate some possibility of adult 'inherited' Fanconi syndrome
- NCIT:C4377 Definition: Probably related to a recessive gene, this is Fanconi Syndrome, characterized by adult onset.
- [OMIIM:134600](https://omim.org/entry/134600) seems to indicate some adult "inherited" version of the disease.

**Comment by pnrobinson** [comment]
Good catch -- but still, "[Adult Fanconi syndrome](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0060778)" is curretnly pointing to this NCIT term (Probably related to a recessive gene, this is Fanconi Syndrome, characterized by adult onset.) which is out of date because of the OMIM class, and we should model the various subtypes more precisely. The NCIT term is incorrect now that there is one rare genetic cause, and still this is often acquired.

**Comment by sabrinatoro** [comment]
@pnrobinson I agree that the NCIT x-ref is not correct based on the concept of this term (ie Fanconi syndrome in adult). 
Based on your comment, it looks like you agree that "Adult Fanconi syndrome" is most often acquired, but not "always". 
I will update Mondo accordingly. Thank you!

**Comment by galyea123** [comment]
Fanconi renotubular syndrome 1 is a synonym of adult Fanconi syndrome as per OMIM. MONDO currently list these as separate conditions: adult Fanconi syndrome MONDO:0060778  and Fanconi renotubular syndrome 1 MONDO:0024525
Hope this helps, Thank you, Gioconda Alyea
