### ISSUE TITLE
MONDO:0859050 Schistosoma mansoni infection, susceptibility/resistance to & MONDO:0000093 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7352]
**Mondo term (ID and Label)**
MONDO:0000093 Schistosoma mansoni infection, susceptibility

**Reason for deprecation**
I don't know if this susceptibility term is also needed in addition to the one from OMIM?  

**Term to be merged with**
MONDO:0859050  Schistosoma mansoni infection, susceptibility/resistance to
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

(If this is not going to be merged, that's fine, but there is no UMLS concept for the 'susceptibility' concept on its own, so MedGen will have to use a CN CUI)

**Comment by sabrinatoro** [comment]
@katiermullen, I listened to the recording, and I agree with your assessment. 
We basically want to split the omim term. However, we cannot use the "MONDO:equivalentTo" source for both terms, since we would have 2 Mondo terms equivalent to 1 omim term (which is not allowed). 
In this case, the omim x-ref have "MONDO:mondoIsNarrowerThanSource"

 @nicolevasilevsky can you please confirm that what I said is correct?
 Thank you!

**Comment by katiermullen** [comment]
Decision is to merge MONDO:0000093 Schistosoma mansoni infection, susceptibility into MONDO:0859050 Schistosoma mansoni infection, susceptibility/resistance to.

Remove EC. 

Definition:
An inherited predisposition to schistosomiasis reinfection following initial infection. PMID:12241930
