### ISSUE TITLE
MONDO:0000424 inborn vitamin B12 deficiency [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7353]
**Mondo term (ID and Label)**
MONDO:0000424  inborn vitamin B12 deficiency

**Reason for deprecation**
The DOID term referenced for this Mondo ID is "vitamin B12 deficiency" which is a child of 'inherited metabolic disorder' and uses a syn of "cobalamin deficiency" 

**Term to be merged with**
MONDO:0019220 inborn disorder of cobalamin metabolism and transport  (Again, based on the DOID hierarchy and syns, this seems to be a conceptual match, http://purl.obolibrary.org/obo/DOID_0050731 ) And it appears there is some overlap in children between this Mondo:0000424

Or 

MONDO:0020696  vitamin B12 deficiency (the NCI definition on MONDO:0000424 is the same code, C131684, as the exact match to this concept, but this B12 deficiency is stated that it can be acquired or inherited, so i am not convinced this is the right merge.)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

I'm not sure if vitamin B12 really is exactly equivalent with cobalamin... the NCI definition for cobalamin starts with : "An essential nutrient and natural water-soluble vitamin of the B-complex family that must combine with an intrinsic factor for absorption by the intestine, Vitamin B12 (cyanocobalamin) is necessary for hematopoiesis..." (thus B12  == _cyano_cobalamin??) but then B12 is used as a synonym by NCI for cobalamin. https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C939

**Comment by katiermullen** [comment]
To my knowledge B12 and cobalamin are synonymous - see for example - https://www.ncbi.nlm.nih.gov/books/NBK559132/

I am not sure that MONDO:0020696 vitamin B12 deficiency is a disease - it seems like this is a phenotype - but it does have a db-xref to NCIT:C131684 which lists it as a disease. 

One option is to obsolete MONDO:0020696 vitamin B12 deficiency --- MONDO:excludePhenotype

MONDO:0000424 inborn vitamin B12 deficiency has a textual definition, "low serum levels of vitamin B12 (cobalamin) due to poor intestinal absorption, decreased dietary intake, or increased physiologic requirement" that does not fit with it being an inherited disease. It also seems like this is a grouping term. This grouping term could be retained with a suggested definition, "An inherited metabolic disease that results from genetic mutations in genes encoding proteins involved in B12 absorption, transport, and intracellular processing. PMID:36249776

After all of that, I actually favor merging MONDO:0000424 inborn vitamin B12 deficiency into MONDO:0019220 inborn disorder of cobalamin metabolism and transport.  A suggested definition is "an inherited metabolic disease affecting cobalamin (vitamin B12) intestinal absorption, transport in the blood, uptake by peripheral cells or cellular metabolism." PMID:35337626
