### ISSUE TITLE
MONDO:0018214 [Revise subclass]

### ISSUE THREAD

**Issue by kellytoner** [monarch-initiative/mondo#739]
**Mondo term (ID and Label)**
MONDO:0018214 generalized epilepsy with febrile seizures plus

**Suggested revision and reasons**
This term should be moved out from under infantile epilepsy syndrome (MONDO:0020071) and generalised epilepsy (MONDO:0005579) and placed directly under epilepsy (MONDO:0005027). This comes at the request of ClinGen's Epilepsy Gene Curation Expert Panel. Please let me or @ErinRiggs know if you have any questions! Thank you!

**Comment by maglott** [comment]
If the Label "generalized epilepsy with febrile seizures plus" is valid, why wouldn't it be under "generalized epilepsy" (MONDO:0005579) . Is 'generalized epilepsy with febrile seizures plus' not a subcategory of generalized epilepsy? 

Sorry for being so uninformed.

**Comment by ErinRiggs** [comment]
Hi Donna - great question, which triggers a second request :)  We would also like to change the label of this term from GENERALIZED epilepsy with febrile seizures plus to GENETIC epilepsy with febrile seizures plus.  This is because individuals with this phenotype have been observed to have focal seizures as well as generalized.  Our expert group has provided the following references to support this claim:
PMID: 28842445 and
https://www.epilepsydiagnosis.org/syndrome/fbp-overview.html

Please let us know if this second request (changing the name of the term) requires a second ticket.

**Comment by nicolevasilevsky** [comment]
@ErinRiggs we have a class for the reference you are pointing to above:
MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus'

I think this is different from the generalized epilepsy term (MONDO:0005579)

**Comment by ErinRiggs** [comment]
That term sounds good - could we still move it out from underneath "neonatal/infantile epilepsy syndrome"?  We'd like it to be a child term of just "epilepsy."  For some reason, we did not come across that term when searching.    Thanks!

**Comment by nicolevasilevsky** [comment]
@kellytoner or @ErinRiggs is there a URL that lists the members of the Epilepsy Gene Curation Expert Panel, that I could link to in the ontology?

**Comment by nicolevasilevsky** [comment]
Never mind, I think I found it here: https://www.clinicalgenome.org/affiliation/40005/, let me know if this is incorrect

**Comment by ErinRiggs** [comment]
That’s it!

Sent from my iPhone

On Aug 12, 2019, at 5:08 PM, Nicole Vasilevsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Never mind, I think I found it here: https://www.clinicalgenome.org/affiliation/40005/<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.clinicalgenome.org%2Faffiliation%2F40005%2F&data=02%7C01%7Ceriggs%40geisinger.edu%7C3f5c6e917f42484fedb508d71f718c2a%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637012444851701783&sdata=7Mfoc1X%2FvwXPrRI%2BLAioKPL5KKBe94h12uRpc2PwRpk%3D&reserved=0>, let me know if this is incorrect

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F739%3Femail_source%3Dnotifications%26email_token%3DAHFJTFGPRP2XXC6XHF4J5BTQEHNMFA5CNFSM4HZLA46KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4D66FI%23issuecomment-520613653&data=02%7C01%7Ceriggs%40geisinger.edu%7C3f5c6e917f42484fedb508d71f718c2a%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637012444851701783&sdata=q2Gp4uHnfcHp595vscTzqUhwPr22JgI33tzz0M8QyFM%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFJTFDEHCMR6KHNYXOW2WDQEHNMFANCNFSM4HZLA46A&data=02%7C01%7Ceriggs%40geisinger.edu%7C3f5c6e917f42484fedb508d71f718c2a%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637012444851711776&sdata=pcfZKHgJm9Tq%2BkLiNk3vjqWtzpSKHsrM%2FXJqgH8Teu8%3D&reserved=0>.


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by cmungall** [comment]
I'm a bit confused about what needs to be done here, it seems the discussion is not finished?

To address @maglott's point, there was a proposal to change the name from generalized... to genetic...

However, this has some problems:

 * Our textual definition (from Orphanet) embeds generalized in the name. _Generalized epilepsy with febrile seizures plus (GEFS+) is a familial epilepsy syndrome in which family members display a seizure disorder from the GEFS+ spectrum which ranges from simple febrile seizures (FS) to the more severe phenotype of myoclonic-astatic epilepsy (MAE) or Dravet syndrome (DS) (see these terms)._ -- do we need a different definition
 * We have declared this to be equivalent to a number of other classes that call this some variant of Generalized... -- are these all wrong? Or are they talking about a different disease? This includes OMIM PS, Orphanet, and NCIT
 
I believe the answer to these questions is something along the lines of: the terminology "generalized..." is in use because the disease is frequently characterized by generalized seizures, but this is not necessary. Therefore we prefer not not use generalized in the name, but recognize this is still in use, if inaccurate.

If this is correct, then we should also include some kind of comment to this effect in the ontology. Do we want to go as far as marking the synonyms with "generalized" as being weakly deprecated?

We might want to feed this information to NCIT/Orphanet/OMIM too

Sorry to hold things up, just striving for overall consistency.

**Comment by ErinRiggs** [comment]
I think for the textual definition, you could replace “generalized” with “genetic.”

Your assessment of the situation is correct.  What are the consequences of classifying a synonym as “weakly deprecated”?

Erin Rooney Riggs, MS, CGC
Assistant Professor
Autism & Developmental Medicine Institute
Geisinger
eriggs@geisinger.edu

**Comment by nicolevasilevsky** [comment]
Hi @cmungall and @ErinRiggs 

my questions:
1) I am a bit unsure how MONDO:0018214 generalized epilepsy with febrile seizures plus is different from MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus'? The paper and link above ([PMID:28842445](https://www.ncbi.nlm.nih.gov/pubmed/28842445) and https://www.epilepsydiagnosis.org/syndrome/fbp-overview.html) are referring to the latter class, I believe.
2) how do you mark the synonyms as being weakly deprecated? do you add 'has synonym type', 'A synonym that is historic and discouraged'?

**Comment by cmungall** [comment]
See intellectual disability, which has deprecated synonym mental
retardation. Follow the same structure. We should add to editor docs.

(oh, and can you fix that erroneous synonym on ID from DOID, thanks!!)

**Comment by kellytoner** [comment]
Hi Chris,

We looked at https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001071 and it looks like mental retardation is listed as both an exact and a related synonym. We didn’t see where is was marked as a deprecated synonym. Are we missing it?

Thanks,
Kelly Toner, MA 
Genomic Medicine Assistant
Autism & Developmental Medicine Institute
120 Hamm Dr, Suite 2A
Lewisburg, PA 17837
ktoner1@geisinger.edu<mailto:ktoner1@geisinger.edu>
570-214-0168
MC 60-36
[cid:image001.png@01D4385B.315A2E00]

**Comment by nicolevasilevsky** [comment]
@cmungall and @ErinRiggs 

can you confirm if we should change the text definition from generalized to genetic? and mark the synonyms as 'A synonym that is historic and discouraged'?

However, if we make this change, I am wondering how this term (MONDO:0018214 generalized epilepsy with febrile seizures plus) is different from MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus'? The paper and link above (PMID:28842445 and https://www.epilepsydiagnosis.org/syndrome/fbp-overview.html) are referring to the latter class, I believe.

Also, MONDO:0018214 generalized epilepsy with febrile seizures plus is inferred to be a subclass of MONDO_0005579 'generalized epilepsy', but there is no explanation for the inference in Protege.

![image](https://user-images.githubusercontent.com/6722114/63283637-9f811380-c266-11e9-8ca4-027d86f84a88.png)

![image](https://user-images.githubusercontent.com/6722114/63283649-a7d94e80-c266-11e9-9a55-25857aefa87b.png)

**Comment by nicolevasilevsky** [comment]
I wonder if MONDO:0018214 generalized epilepsy with febrile seizures plus and MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus' should be merged?

**Comment by cmungall** [comment]
> We didn’t see where is was marked as a deprecated synonym.

Unfortunately OLS doesn't show all of the metadata associated with a synonym. @simonjupp is aware of this

There is another potential confusing thing about the display, the commas are ambiguous. Where it says

"intellectual disabilities, mental retardation, autosomal recessive 15"

That is actually 2, not 3. 

"mental retardation, autosomal recessive 15" is a synonym - and an incorrect one (see my comments above, @nicolevasilevsky will get rid of this).

Sorry for the confusion...

**Comment by nicolevasilevsky** [comment]
Hi @cmungall and @ErinRiggs

I still have some outstanding questions:

I am a bit unsure how MONDO:0018214 generalized epilepsy with febrile seizures plus is different from MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus'? The paper and link above (PMID:28842445 and https://www.epilepsydiagnosis.org/syndrome/fbp-overview.html) are referring to the latter class, I believe.

I wonder if MONDO:0018214 generalized epilepsy with febrile seizures plus and MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus' should be merged?

**Comment by nicolevasilevsky** [comment]
Looking into this further, I don't think MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus' is a valid class - looking at this webpage (https://www.epilepsydiagnosis.org/syndrome/fbp-overview.html), this is describing two classes.

I think MONDO_0100027 'febrile seizures plus, genetic epilepsy with febrile seizures plus' should be obsoleted and consider MONDO:0018214 generalized epilepsy with febrile seizures plus.

I will reopen a new ticket and close this one.

I will create a new ticket to add the synonym with genetic to MONDO_0100027 and add the tag 'clingen preferred'.
