### ISSUE TITLE
MYOCLONIC EPILEPSY OF LAFORA 2, MONDO:0958201 & MONDO:0800306 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7393]
**Mondo term (ID and Label)**
MONDO:0958201 myoclonic epilepsy of Lafora 2

**Reason for deprecation**
This is a new OMIM record for the previous 'included' concept: https://www.omim.org/entry/620681 
# 620681- MYOCLONIC EPILEPSY OF LAFORA 2; MELF2

Alternative titles; symbols
EPILEPSY, PROGRESSIVE MYOCLONIC, 2B; EPM2B
LAFORA DISEASE 2

**Term to be merged with**
MONDO:0800306 epilepsy, progressive myoclonic, 2b

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Recommend merging these terms since they refer to the same concept in OMIM - https://omim.org/entry/620681

A possible definition is: The Lafora type of progressive myoclonic epilepsy is an autosomal recessive disorder characterized by insidious onset of progressive neurodegeneration between 8 and 18 years of age caused by homozygous or compound heterozygous mutation in the NHLRC1 gene. [OMIM:620681](https://omim.org/entry/620681)
