### ISSUE TITLE
severe early-onset pulmonary alveolar proteinosis due to MARS deficiency

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7434]
severe early-onset pulmonary alveolar proteinosis due to MARS deficiency MONDO:0014206

References that need to be fixed: 
Orphanet:370088 (Acute infantile liver failure-multisystemic involvement syndrome) a different condition.

0000-0019310-0163

Thank you, Gioconda

**Comment by sabrinatoro** [comment]
Orphanet:370088 is equivalent to 'infantile liver failure syndrome 1' (MONDO:0024568)

It is "related", and NOT equivalent to 'severe early-onset pulmonary alveolar proteinosis due to MARS deficiency' *=(MONDO:0014206).

The [OLS page](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0014206) might be confusing because it shows both Orphanet, but one needs to click on the i icon to know one is "related"
