### ISSUE TITLE
Predisposition to severe viral infection due to IRF7 deficiency and Immunodeficiency 39

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7513]
Predisposition to severe viral infection due to IRF7 deficiency MONDO:0035547 and Immunodeficiency 39 MONDO:0014597 seem to be synonyms.  Please review.

Thank you,

Gioconda Alyea

**Comment by sabrinatoro** [comment]
@kanems Could I have your opinion on this issue, please? 
We have 2 terms: 
- 'immunodeficiency 39' - MONDO:0014597 - OMIM:616345 - MEDGEN:904167
- 'predisposition to severe viral infection due to IRF7 deficiency' - MONDO:0035547 - Orphanet:574918 - MEDGEN:1830120

According to Orphanet, Orphanet:574918 maps to OMIM:616345

According to Ada: a lot of immunodeficiencies are only diagnosed because of the patient's predisposition to infection. 

I am tempted to agree and merge these terms, but I would like your input on this before proceeding. 
Thank you for your help!

**Comment by kanems** [comment]
I agree these are the same concept based on Orpha's exact mapping to OMIM, shared causative gene, and general phenotype.
UMLS has 2 CUIs for this disease, so I will follow up with them to request their CUI merge. (Note there is also a SNOMED CT code that matches ORDO's preferred name: 1269234000 if you are looking to add another x-ref)

**Comment by sabrinatoro** [comment]
Thank you @kanems. I will go ahead with the merging
