### ISSUE TITLE
[Revise subclass] Bardet Biedl syndrome 1  is not a subclass of BBS 16 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#754]
**Mondo term (ID and Label)**

**Suggested revision and reasons**
Bardet Biedl syndrome 1  is a subclass of BBS 16 

It should be a subclass of https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015229

**Comment by nicolevasilevsky** [comment]
@pnrobinson Bardet Biedl syndrome 1 is asserted as a subclsas of 'Bardet-Biedl syndrome', and inferred to be a sublcass of 'Bardet-Biedl syndrome 16'. I pasted the explanation below - I believe it is inferred this way because Bardet-Biedl syndrome 16 has basis in dysfunction in the gene SDCCAG8, and so does Bardet Biedl syndrome 1 (in addition to several other genes).

![image](https://user-images.githubusercontent.com/6722114/60295170-e6dacb80-98d7-11e9-8eec-a9e9f2ef67e8.png)

**Comment by nicolevasilevsky** [comment]
@pnrobinson looks like you can't see all the relationships in OLS, but you can see it in Protege.

**Comment by pnrobinson** [comment]
The mistake was in the mondo.obo file. Something weird is going on...I just downloaded the obo file.

**Comment by pnrobinson** [comment]
Also, some of the diseaseHasBasis in assertions are wrong. For instance, CCDC28B is a modifier, not a basis. Where do these assertions come from?

**Comment by nicolevasilevsky** [comment]
@cmungall will have to answer that question :)

Yes, I see in the OMIM record it says "The CCDC28B gene (610162) modifies the expression of BBS phenotypes in patients who have mutations in other genes."
https://www.omim.org/entry/209900

**Comment by nicolevasilevsky** [comment]
I think all of the gene-disease assertions were coming from Orphanet:
https://www.orpha.net/consor/cgi-bin/Disease_Genes_Simple.php?lng=EN&LnkId=3244&Typ=Pat&diseaseType=Gen&from=rightMenu

I revised this to reflect the OMIM page:
https://www.omim.org/entry/209900

I revised the logical def to be:
'Bardet-Biedl syndrome'
 and ('disease has basis in dysfunction of' some BBS1)
