### ISSUE TITLE
OMIM 105210 mapping in Mondo

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7598]
**Mondo term (ID and Label):**
MONDO:0100552 ATTRV30M amyloidosis
MONDO:0007100 familial amyloid neuropathy (current Equivalent mapping in Mondo)

**Xref that should be fixed (ID and label):**
OMIM 105210

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
I am not sure where this OMIM record belongs, but based on ORDO, http://www.orpha.net/ORDO/Orphanet_85447 is exact match to [OMIM:105210](https://omim.org/entry/105210).  the parent concept ([Orphanet:271861](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=271861) Hereditary ATTR amyloidosis == MONDO:0007100) points to the MIM record, but the ORDO data for this same Orphanet record does not say they are an exact match.
Or is the overall OMIM record a match to the parent concept and then the 'included' concepts are the specific variants (V30M, V220I in Orphanet) that affect different organ systems (LEPTOMENINGEAL, CARDIOMYOPATHY , per OMIM) ?

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi @kanems 

After further review of the issue, we found that "Hereditary Systemic Amyloidosis 1" results from defects in the TTR gene, while ATTRV30M and ATTRV122I result from specific variations in the TTR gene.
Therefore, we made Hereditary Systemic Amyloidosis 1 (MONDO:0971004) the parent class for
ATTRV30M (MONDO0100552), and ATTRV122I (MONDO:0019441).

We updated the cross-references accordingly:
While the 3 Orphanet terms (85451, 85447, 271861) point to the same OMIM:105210, our analysis indicate the following
- OMIM:105210 represents the version of the disease caused by a variation in the TTR gene and therefore represent the same concept as MONDO:0971004 - Hereditary Systemic Amyloidosis 1.
- ATTRV30M and ATTRV122I represent the more specific concepts of Orphanet 85451 and 85447. It seems like the mappings between these Orphanet x-refs and OMIM:105210 are therefore not exact (orphanet concepts are more specific than OMIM:105210).
- (3rd orphanet 271861): based on the definition, this concept seems to represent the hereditary version of the disease, regardless of the causing gene. Therefore this orphanet concept is the same as MONDO:0007100 (familial amyloid neuropathy), which is also represented by the OMIM phenotypic series OMIMPS:105210

Based on this analysis, it looks like MEDGEN:414031 represents the concept of  Hereditary Systemic Amyloidosis caused by a variation in the TTR gene, ie MONDO:0971004 (Hereditary Systemic Amyloidosis 1). If you agree, please make sure to update your mappings so it is reflected in the ontology. Thank you!

Please let us know if you agree/disagree with our analysis, and if you have any comments

**Comment by kanems** [comment]
I agree with this mapping/concept review. I will check our records to ensure we have correct/updated Mondo , OMIM and Orpha mappings to the best CUI in UMLS (if an appropriate one exists) for these concepts.
