### ISSUE TITLE
[NTR/ACD] ACD-related telomere biology disorder

### ISSUE THREAD

**Issue by awaddell01** [monarch-initiative/mondo#7605]
**Preferred gene-related syndrome label**
ACD-related telomere biology disorder

**Synonyms**
ACD-related telomeropathy

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0100137 (telomere syndrome)

**Definition**
A complex set of inherited conditions caused by a pathogenic variant(s) in the ACD gene that results in aberrant telomere biology. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 20301779

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
*ACD-related short telomere syndrome* (not currently existing. will also need a new term created-happy to submit a separate request if needed)
Definition: A spectrum of conditions, including dyskeratosis congenita, Hoyeraal-Hreidarsson syndrome, hereditary aplastic anemia, and pulmonary fibrosis, typically characterized by shortened telomeres due to a pathogenic variant(s) in ACD that results in impaired telomere maintenance.  
Child terms under this new term: MONDO:0014690 (Dyskeratosis congenita, autosomal dominant 6), MONDO:0800370 (dyskeratosis congenita, autosomal recessive 7), MONDO:0018045 (Hoyeraal Hreidarsson syndrome), MONDO:0001713 (hereditary isolated aplastic anemia)  

*ACD-related long telomere syndrome* (not currently existing. will also need a new term created-happy to submit a separate request if needed)
Definition: A telomere biology disorder typically characterized by increased telomere length due to a pathogenic variant in ACD 
Child terms under this new term: MONDO:0018961 (Familial melanoma)  

**Your nano-attribution (ORCID) or URL for a working group**
https://orcid.org/0009-0007-0138-2054

I've added a screenshot below of the proposed tree that the GCEP envisions. Please let me know if you are not able to see it. It's just showing up as text for me, so I'm happy to send over email if that would be helpful and works better. 

<img width="739" alt="Screen Shot 2024-04-18 at 12 14 36 PM" src="https://github.com/monarch-initiative/mondo/assets/132306268/e6c0f158-0852-45fc-a58d-5ef043a26029">

This request is being made on behalf of the ClinGen Interstitial Lung Disease GCEP.
@courtneythaxton
@nicolevasilevsky
@ahamosh

**Comment by nicolevasilevsky** [comment]
@awaddell01 I created the three new terms.

It doesn't make sense ontologically to classify MONDO:0018961 (Familial melanoma) as a child of ACD-related long telomere syndrome because this would be interpreted as ACD is the _only_ gene implicated in familial melanoma and that is not the case (there are 11 genes according to [Orphanet](https://www.orpha.net/en/disease/gene/list/618?mode=name).)

This is also the case with MONDO:0018045 (Hoyeraal Hreidarsson syndrome) and MONDO:0001713 (hereditary isolated aplastic anemia) as children of 'ACD-related short telomere syndrome'. There are other genes besides ACD that are implicated in these diseases.

I added MONDO:0014690 (Dyskeratosis congenita, autosomal dominant 6) and MONDO:0800370 (dyskeratosis congenita, autosomal recessive 7) as children of 'ACD-related short telomere syndrome'

Here is a screenshot of the hierarchy:

<img width="430" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/4d9fb450-ee22-4aca-bbe1-a08fdeeb6380">

I'm happy to have a call to discuss further if there are any questions.

**Comment by awaddell01** [comment]
@nicolevasilevsky That makes sense. Thanks so much for doing this! For ACD-related long telomere syndrome, could we possibly edit the definition to include familial melanoma since it can't be a child term? Something like "A telomere biology disorder typically characterized by increased telomere length due to a pathogenic variant in the ACD gene that may cause familial melanoma"

**Comment by nicolevasilevsky** [comment]
Hi @awaddell01 - sure thing, I will edit the definition.
