### ISSUE TITLE
[Revise subclass] of spinal muscular atrophy

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7636]
**Mondo term (ID and Label)**

peripheral neuropathy-myopathy-hoarseness-hearing loss syndrome
has the ancestor "spinal muscular atrophy"
does not seem to be a "spinal muscular atrophy"

I think the issue might be the intervening term
"neuronopathy, distal hereditary motor, autosomal dominant"

MN2B primarily affects the peripheral nerves, leading to weakness and wasting of muscles in the hands and feet, whereas SMA affects the spinal motor neurons, resulting in weakness and muscle wasting throughout the body.

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by sabrinatoro** [comment]
Hi @ValWood! I (we) am (are) finally able to get to this issue. Thank you for your patience. 

I have reviewed the disease description for "distal hereditary motor neuronopathy", and all sources agree that it is a "spinal muscular atrophy".
- from OMIM: Distal hereditary motor neuronopathy (dHMN or HMN) is a heterogeneous group of neuromuscular disorders **caused by anterior horn cell degeneration** and characterized by progressive distal motor weakness and muscular atrophy of the peripheral nervous system without sensory impairment.
- from the "spinal muscular atrophy" definition: "(...) resulting from progressive degeneration and irreversible loss of the anterior horn cells in the spinal cord (i.e., lower motor neurons) (...)"

Unless you have other sources which I have not reviewed, I think the "spinal muscular atrophy" parent for (both autosomal dominant and recessive form of) "distal hereditary motor neuronopathy".


That being said, I agree that there is no evidence for "peripheral neuropathy-myopathy-hoarseness-hearing loss syndrome" to be a child of "spinal muscular atrophy" or "distal hereditary motor neuronopathy". I will therefore exclude the subClass for this term.


Please let me know if you agree with this assessment and proposal. 
Thank you again for your patience!

**Comment by katiermullen** [comment]
Hi @ValWood and @sabrinatoro!

I believe that "distal hereditary motor neuronopathy" is a child of "spinal muscular atrophy" based on both being a result of progressive anterior horn cell degeneration, with the former causing specifically distal motor weakness (from OMIM). 

I agree that "peripheral neuropathy-myopathy-hoarseness-hearing loss syndrome" should not be a child of either "spinal muscular atrophy" or "distal hereditary motor neuronopathy".

Thank you!

**Comment by ValWood** [comment]
sounds good!
