### ISSUE TITLE
[NTR/gene] MTOR

### ISSUE THREAD

**Issue by abbe-Lai** [monarch-initiative/mondo#7717]
**Preferred gene-related syndrome label**
MTOR-related Overgrowth spectrum

**Synonyms**
MONDO:0100283

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0019716 overgrowth syndrome

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. 

Any malformations/disorders resulting from pathogenic gain-of-function variants in the MTOR gene. The variants can be germline or somatic

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 27860216; 33833411; 35163267

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
MONDO:0011818
MONDO:0014716

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://clinicalgenome.org/affiliation/50020/

**Comment by sagehrke** [comment]
Dear @abbe-Lai, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by nicolevasilevsky** [comment]
Hi @abbe-Lai I see you requested MONDO:0100283 as a synonym, but this is an existing class, so it does not make sense, ontologically, to add this as an exact synonym. We could add it as a related synonym? Does that work?

**Comment by nicolevasilevsky** [comment]
MONDO:0011818 'isolated focal cortical dysplasia type II' has mutations in 3 possible genes (according to [OMIM](https://omim.org/entry/607341)), so in this case as well, it doesn't make sense ontologically to add this as a child of MTOR-related overgrowth spectrum because that would mean every case of 'isolated focal cortical dysplasia type II' would have a mutation in MTOR, but according to OMIM, there may be variations in any of these three genes but not every case has an MTOR variation.

Also, I don't think it makes sense to classify MONDO:0014716 'macrocephaly-intellectual disability-neurodevelopmental disorder-small thorax syndrome' as a child of overgrowth syndrome, as overgrowth is just a feature of this disease.

Let me know if you have further questions about these, thanks!
