### ISSUE TITLE
Immune thrombocytopenia is a synonym fortwo terms

### ISSUE THREAD

**Issue by linikujp** [monarch-initiative/mondo#7791]
Immune thrombocytopenia is the synonym for two:
 http://purl.obolibrary.org/obo/MONDO_0008558, 	prefLabel: autoimmune thrombocytopenic purpura
 http://purl.obolibrary.org/obo/MONDO_0002048, 	prefLabel: thrombocytopenia due to immune destruction

Suggest to keep thrombocytopenia due to immune destruction, because the other one is narrower .

**Comment by twhetzel** [comment]
Hi Asiyah - I see you assigned this ticket to Nico. Is this follow-up to a previous conversation or do you mind if we re-assign this to one of the curators?

**Comment by twhetzel** [comment]
Hi @linikujp - thank you for pointing out that issue. I agree that 'immune thrombocytopenia' is an exact synonym to MONDO:0002048 'thrombocytopenia due to immune destruction' and that the concept MONDO:0008558 'autoimmune thrombocytopenic purpura' is more narrow. The synonym scopes will be adjusted to reflect this.

**Comment by linikujp** [comment]
Hi Trish, glad this ticket is resolved w/o me.
