### ISSUE TITLE
Request for new synonym gastric cancer

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#7828]
### Mondo term

gastric cancer (MONDO_0001056)

### Synonyms

GC

### Synonym type

exact

### Additional comments

Requesting on behalf of Open Targets, please see the discussion here: https://github.com/opentargets/issues/issues/3353

**Comment by sagehrke** [comment]
Dear @zoependlington, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by prashantuniyal02** [comment]
Hi @sagehrke,

Hope the team is doing well. Just wanted to check with you and your team, if you have had a discussion on this issue to consider `GC` as a synonym of `Gastric Cancer` (`MONDO_0001056`).

This issue affects us at Open Targets as many people in manuscripts occasionally refer to `gastric cancer` as `GC` due to which our pipeline grounds `GC` to `ghonorrea` which has a `GC` synonym. 
![image](https://github.com/user-attachments/assets/a28fc1bf-1012-40ab-b1d7-f96dad5b7fee)

If gastric cancer were to have a `GC` synonym, the disambiguation feature built into our pipeline would resolve this. Kindly see the discussion [here](https://github.com/opentargets/issues/issues/3353).

Looking forward to hear from you.

Best,
Prashant

**Comment by sabrinatoro** [comment]
Thank you @prashantuniyal02.
One of the Mondo team members is looking into this. We will reach out if we have questions and we will keep you updated.
Best, Sabrina
