### ISSUE TITLE
Williams-Campbell syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7854]
Hi!  I noticed that you list tracheobronchomalacia as a synonym of Williams-Campbell syndrome (MONDO:0008888) when they are, in fact, different conditions.  Tracheobronchomalacia  occurs when the walls of the airway (specifically the trachea and bronchi) are weak, and Williams-Campbell syndrome typically involving 4th to 6th order bronchi with preservation of the trachea and main bronchi.  
I believe that the synonym in MONDO comes from GARD.

For sources please see: 
https://www.orpha.net/en/disease/detail/411501
https://omim.org/entry/211450
https://www.ncbi.nlm.nih.gov/books/NBK553191/#article-30432.s4
https://pubmed.ncbi.nlm.nih.gov/34726534/ (no abstract but you may be able to see the full article)
https://erj.ersjournals.com/content/54/3/1900382.long

Thank you!

Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
_ Tracheobronchomalacia is listed as a related synonym of Williams-Campbell Syndrome, when it is in fact not:_

The definition of Williams-Campbell Syndrome (WCS): 'Rare congenital disorder, which leads to bronchiectasis affecting fourth to sixth order of bronchial divisions' (PMID:33614112). The manifestation of WCS, Bronchiectasis, is potentially caused by Bronchomalacia (PMID:28613561).

Given WCS refers specifically to the 4th to 6th divisions of the bronchi and not the trachea, WCS should only ever be defined as Bronchomalacia and not Tracheobronchomalacia.

Lastly, searching the GARD reference does not return anything. Therefore, **I agree with the collaborator to remove Tracheobronchomalacia as a related synonym.**
