### ISSUE TITLE
PI4KA-Related Disorder

### ISSUE THREAD

**Issue by madysoncbrown** [monarch-initiative/mondo#7858]
PI4KA-Related Disorder

Synonyms: None

Parent Terms: MONDO:0030831, MONDO:0020340, MONDO:0015150

Definition:
Per GeneReviews PI4KA-related disorder is a clinically variable disorder characterized primarily by neurologic dysfunction (limb spasticity, developmental delay, intellectual disability, seizures, ataxia, nystagmus), gastrointestinal manifestations (multiple intestinal atresia, inflammatory bowel disease), and combined immunodeficiency (leukopenia, variable immunoglobulin defects). Age of onset is typically antenatal or in early childhood; individuals can present with any combination of these features. Rare individuals present with later-onset hereditary spastic paraplegia. Brain MRI findings can include hypomyelinating leukodystrophy, cerebellar hypoplasia/atrophy, thin or dysplastic corpus callosum, and/or perisylvian polymicrogyria.

Definition source: https://www.ncbi.nlm.nih.gov/books/NBK583038/

Children terms: MONDO:0014679, MONDO:0030482, MONDO:0030669

Working Group: https://www.clinicalgenome.org/affiliation/40020/

@ErinRiggs @elizabeth-gavrilov

**Comment by sagehrke** [comment]
Dear @madysoncbrown,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@madysoncbrown in review of this term, PI4KA-related disorder, it was noted that it was incorrectly classified as a child of: 

- 'bilateral perisylvian polymicrogyria'
- 'complex hereditary spastic paraplegia'
- 'gastrointestinal defect and immunodeficiency syndrome'

In Mondo, PI4KA-related disorder should not be a subclass (child) of these disorders because it does not ALWAYS present with all of these disease characteristics.

PI4KA-related disorder is now correctly classified as a child of hereditary disease. The three child terms of PI4KA-related disorder remain:

<img width="529" height="72" alt="Image" src="https://github.com/user-attachments/assets/eaf53c6f-ac50-4976-a4f2-bca142bc56d0" />

Thank you so much and please let me know if you have any questions!
