### ISSUE TITLE
NTR: ataxic diplegia

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7921]
### Label

ataxic diplegia

### Synonyms

diplegic ataxia, ataxic diplegic, diplegic ataxic, spastic/ataxic diplegia, ataxic/spastic diplegia, ataxic-spastic diplegia, spastic-ataxic diplegia

### Synonym type

exact

### Definition

Ataxic diplegia has pathogenetic and clinical presentations, such as spastic diplegia, rather than simple ataxia. In ataxic diplegic children, all extremities are neurologically affected. There is more voluntary control in the upper extremities, spasticity and stiffness in the lower extremities that affect children’s ability to roll, sit, stand, and ambulate; as well as signs and symptoms of loss of balance and coordination.

PMID:10854109

### Parent term

MONDO:0000400 mixed cerebral palsy

### Additional comments

**XREF exact**
UMLS:C0393997

**Comment by sabrinatoro** [comment]
@peupeubangbang, thank you for your request. 

Could you please review the following updated definition, and let me know whether you agree with it?

"ataxic diplegic cerebral palsy": a mixed cerebral palsy that is characterized by pathogenetic and clinical presentations of both ataxic cerebral palsy and spastic diplegia.
In ataxic diplegic children, all extremities are neurologically affected. There is more voluntary control in the upper extremities, spasticity and stiffness in the lower extremities that affect children’s ability to roll, sit, stand, and ambulate; as well as signs and symptoms of loss of balance and coordination.


To your knowledge, are there other types of "mixed cerebral palsy"?

Thank you! 



Note to self: 
From PMID:10854109
These children all have ataxic cerebral palsy, but interestingly one of the four children also has lower limb spasticity and is classified as having ataxic diplegic cerebral palsy. (...)
We have identified a family that segregates both ataxic CP and ataxic diplegia and have mapped the genetic locus responsible in this family to chromosome 9p12–q12. The identification of gene(s) involved in the aetiology of CP will offer the possibility of prenatal/premarital testing to some families with children affected with the disorder and will greatly increase our understanding of the development of the control of motor function.

From PMID:35642697
One in four children with ataxic CP is classified as having ataxic diplegic CP[2]. Ataxic diplegia has pathogenetic and clinical presentations, such as spastic diplegia, rather than simple ataxia. In ataxic diplegic children, all extremities are neurologically affected. There is more voluntary control in the upper extremities, spasticity and stiffness in the lower extremities that affect children’s ability to roll, sit, stand, and ambulate; as well as signs and symptoms of loss of balance and coordination[1].

**Comment by katiermullen** [comment]
Hi @sabrinatoro and @peupeubangbang,

I agree with the classification of this new term, "ataxic diplegic cerebral palsy" as child of "mixed cerebral palsy." I was not able to find other examples of mixed cerebral palsy in a brief search. @peupeubangbang do you know if there are other terms that we should classify as children of "mixed cerebral palsy?"

Interestingly, the UMLS term UMLS:C0393997 "Cerebral palsy with spastic/ataxic diplegia" is classified as a child of "spastic cerebral palsy", but I am not sure this is correct based on the definition provided above.
