### ISSUE TITLE
SPATA5L1-related complex neurodevelopmental disorder with motor features and hearing loss

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#7975]
**Mondo term (ID and Label):**
SPATA5L1-related complex neurodevelopmental disorder with motor features and hearing loss

**Suggested new label:**
AFG2B-related complex neurodevelopmental disorder with motor features and hearing loss

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://www.clinicalgenome.org/affiliation/40113/ 

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
The SPATA5L1 gene name is now outdated, please update the term to AFG2B both in the term name and in the definition. 

Thank you!
@ErinRiggs

**Comment by twhetzel** [comment]
Thank you @icordovaG for this term relabel request. We will make that change and since '[SPATA5L1' was the previous gene symbol for AFG2B](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:28762) the current label will be maintained as a synonym.

TODO
- [ ] re-label MONDO:0100551 to 'AFG2B-related complex neurodevelopmental disorder with motor features and hearing loss'
- [ ] add 'SPATA5L1-related complex neurodevelopmental disorder with motor features and hearing loss' as an exact synonym with xref https://clinicalgenome.org/affiliation/40006/ (the original group that requested this term)
- [ ] update the definition to use the new gene label
- [ ] add term tracker property to reference this ticket
