### ISSUE TITLE
Revise subclass relationship of "hypertensive nephropathy"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#8010]
"hypertensive nephropathy" (MONDO:0024633)

This can be acquired. I would like to suggest removing the restriction to "inherited kidney disorder" (MONDO:0100191) and put it under "kidney disorder" (MONDO:0005240) or "chronic kidney disease" (MONDO:0005300) instead.

**Comment by twhetzel** [comment]
Thank you @nklsbckmnn for suggesting this change. We have reviewed this and will remove the parent class 'hereditary disease' since looking at the [OMIM page](https://omim.org/entry/608026) it is not clear that this is considered hereditary and will add the parent 'kidney disorder'. To document, [PMID:37793351 ](https://pubmed.ncbi.nlm.nih.gov/37793351/) does mention that "HN can be viewed as an "acquired error of metabolism.""
