### ISSUE TITLE
[Revise text def] MONDO:0001734 'tuberous sclerosis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#8074]
**Mondo term (ID and Label)**
MONDO:0001734 'tuberous sclerosis'

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

Upon review with Steve Roberds from the TSC Alliance, he noted that TSC is not always hereditary, as there can be de novo mutations. TSC is part of the phenotypic series from OMIM though. So I think we may need to create a triad that is:
neurocutaneous syndrome
-TSC (generic) (NEW)
--hereditary TSC (MONDO:0001734, equivalent to OMIMPS:191100)
---TSC1
---TSC2
--acquired TSC (NEW, note- a synonym of acquired is 'not genetically inherited', so I think acquired is the correct label. Or should it be non-genetic? that is the sibling class to hereditary but this isn't actually non-genetic because it is a de novo mutation, so I think acquired fits better) :

![image](https://github.com/user-attachments/assets/9b49835c-a502-4ea3-9316-df494aa098eb)

Proposed definitions:

**Tuberous sclerosis**
A hereditary or non genetically inherited disease characterized by seizures, intellectual disability, developmental delay, and skin and ocular lesions. Tumors may form in many different organs, primarily in the brain, eyes, heart, kidney, skin, and lungs. First signs usually occur during infancy or childhood but in rare cases, it may not be diagnosed until 2nd or 3rd decade.

**Inherited tuberous sclerosis**
An instance of tuberous sclerosis that is caused by an inherited genomic modification in an individual.

**Acquired tuberous sclerosis**
An instance of tuberous sclerosis that is caused by a de novo mutation during the lifetime of the individual.

- [x] **Note**: the current text def uses the term 'mental retardation' in the definition and this should be revised as a high priority.

Synonyms:
- [x] there are some duplicated synonyms that need to be cleaned up
- [x] capitalization of the synonyms need to be fixed 
- [x] adenoma sebaceum syndrom is a phenotype associated with TSC
- [x] cerebral sclerosis is currently a related synonym, this is from DO (https://www.ebi.ac.uk/ols4/ontologies/doid/classes?obo_id=DOID%3A13515), but I don't see any evidence that this is a synonym for tuberous sclerosis. I deprecated this synonym.

cc @sabrinatoro

**Comment by nicolevasilevsky** [comment]
Note - Steve Roberds told me:
The one complication is that MONDO:0008612 and MONDO:0013199 (TSC1 and TSC2, respectively) also occur under the new “acquired” tuberous sclerosis.  (I agree with your rationale for “acquired,” also. Non-genetic would not be accurate.)

**Comment by nicolevasilevsky** [comment]
Discussed on Mondo curation call on 2024-09-05

instead of the term acquired, we'll use congenital and make TSC1 and TSC2 children of hereditary TSC and congenital TSC

**Comment by nicolevasilevsky** [comment]
emailed Steve Roberds on 2024-09-06

**Comment by courtneythaxton** [comment]
@nicolevasilevsky I just wanted to leave a comment on this definition update. The ticket indiates an "acquired" form of TS due to de novo mutation. I just want to clarify that _de novo_ variation can still be considered a monogenic disease. While not directly inherited through a family, it would be the same mechanism. My understanding is the word acquired means you develop a disease or phenotypes from other causes beyond genetics. For example, you can develop hypertrophic cardiomyopathy from exercising too much, and these individuals would be shown not to have any pathogenic variants in genes know to cause a monogenic disorder. 

Acquired also indicates that the person was not born with the disease. Again, some monogenic disorders will result in observable features developing later in life, but technically if the person has a genetic mutation responsible for the disease, then they were born with it. 

I am also not sure, but one other way to develop cancers is through somatic mutation, which means that the individuals gained variants through life, and these were not inherited from parents.


It may be worth engaging @ahamosh or @pnrobinson for more details on this definition.


This could all be accurate, but I worry about indicating Acquired TSC is caused by _de novo_ mutations.

**Comment by pnrobinson** [comment]
I agree. Do not use "acquired" to refer to this. "acquired" is used to mean a non-genetic etiology!

**Comment by ahamosh** [comment]
Just make TSC1 and TSC2.  Once someone has a de novo TSC1 or TSC2 mutation, it will be hereditary.  This is the completely wrong use of acquired.  Tuberous Sclerosis is a genetic disease!

**Comment by nicolevasilevsky** [comment]
Thank you @courtneythaxton @pnrobinson and @ahamosh for your comments, this is super helpful!

We'll leave the hierarchy as it is, thanks!

**Comment by nicolevasilevsky** [comment]
closing this issue as no further action is required
