### ISSUE TITLE
Merge filarial elephantiasis (MONDO:0005761) and lymphatic filariasis (MONDO:0016076)

### ISSUE THREAD

**Issue by gtsueng** [monarch-initiative/mondo#842]
These items appear to be the same:
-filarial elephantiasis (MONDO:0005761)
-lymphatic filariasis (MONDO:0016076)

Both appear to be lymphatic infections of bancrofti, but filiarial elephantiasis mentions brugia malayi as an additional potential causative agent. [NCBI taxonomy search for brugia malayi](https://www.ncbi.nlm.nih.gov/taxonomy/?term=brugia+malayi) suggests it's a causative agent of lymphatic filariasis. Filarial elephantiasis also has statement 'AKA:  lymphatic filariasis' and lymphatic filariasis has statement 'AKA: elephantiasis'.

**Comment by nicolevasilevsky** [comment]
Does anyone have any objections? @gtsueng I will leave this open on the tracker for at least a couple weeks, so the community can comment.

The definition for lymphatic filariasis (MONDO:0016076) is cut off, it should be:

Lymphatic filariasis (LF) is a severe form of filariasis, caused by the parasitic worms Wuchereria bancrofti, Brugia malayi and Brugia timori, and the most common cause of acquired lymphedema worldwide. LF is endemic to tropical and subtropical regions. The vast majority of infected patients are asymptomatic but it can also cause a variety of clinical manifestations, including limb lymphedema, genital anomalies (hydrocele, chylocele), elephantiasis in later stages of the disease (frequently in the lower extremities), and tropical pulmonary eosinophilia (nocturnal paroxysmal cough and wheezing, weight loss, low-grade fever, adenopathy, and pronounced blood eosinophilia). Renal involvement (hematuria, proteinuria, nephritic syndrome, glomerulonephritis), and mono-arthritis of the knee or ankle joint have also been reported.

**Comment by gtsueng** [comment]
Sounds good. If the community decides these are two different entities, then I suggest changing the AKA statement in filarial elephantiasis from 'lymphatic filariasis' to 'late-stage lymphatic filariasis', just to make the distinction more clear.

**Comment by nicolevasilevsky** [comment]
Sounds good. Note, I created a pull request to fix the definition in MONDO:0016076

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@gtsueng 
EFO has EFO:0007272 'filarial elephantiasis' with synonym 'lymphatic filariasis' among others. The definitions we have are:

"Parasitic infestation of the human lymphatic system by wuchereria bancrofti or brugia malayi. It is also called lymphatic filariasis. [ MESH:D004605 ]"

and

"A filariasis that is characterized by the thickening of the skin and underlying tissues, especially in the legs, male genitals and female breasts, caused by thread-like parasitic worms Wuchereria bancrofti, Brugia malayi or Brugia timori, which inhabit the lymphatics. These nematodes are transmitted by mosquitoes. Acute symptoms include fever, lymphadenitis, lymphangitis, funiculitis, and epididymitis. Chronic symptoms include abscesses, hyperkeratosis, polyarthritis, hydroceles, lymphedema, and elephantiasis. [ http://www.ebi.ac.uk/ontology/webulous#OPPL_pattern ]" (which means it was likely submitted by one of our collaborators.)

The two terms seem the same to me.
I also note that EFO:0007272 'filarial elephantiasis' is
Subclass of:
    filariasis
    parasitic eyelid infestation
    elephantiasis
    disease has feature some elephantiasis
It appears that we inherited some of these relationships from MONDO. I'd retain the first one and the last one, but the two middle ones seem incorrect. 
Thanks for your work on this,
Paola

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia 
parasitic eyelid infestation is inferred to be a parent, I pasted the explanation below:
![image](https://user-images.githubusercontent.com/6722114/69588373-3adc0000-0f9d-11ea-97e9-fe772a9fb5b7.png)

If I remove elephantiasis as a parent, it is inferred to be a parent because of the equivalence axiom on 'filarial elephantiasis':

elephantiasis
 and ('disease has location' some eyelid)
