### ISSUE TITLE
issues with HIV-1 infection mapping

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#9]
EFO_0000180 HIV-1 infection is suggested to be a subclass of OMIM_609423, which seems incorrect.

Also the equivalence between OMIM_609423 and DOID_635 is questionable.

![image](https://user-images.githubusercontent.com/6722114/32242713-beae2022-be30-11e7-8736-8b6a669f1bae.png)

**Comment by jmcmurry** [comment]
This brings up an interesting point in terms of how infectious diseases get structured in MONDO. My two cents:

- **HIV-1 virus** needs to be an entity. Perhaps now, let's use https://www.wikidata.org/wiki/Q18907320 since virus classification and identification is [still] pretty terrible with no end in sight. The course-grained descriptions in Wikidata are probably adequate for our needs in MONDO.
- **"Infection with HIV-1"** needs to be an entity related to **HIV-1 virus**
- **"HIV-1 progression"** probably should be an entity too; not sure in what ontology or knowledgebase
- **"susceptibility to HIV-1"** -- if I'm allowed to be pedantic -- should have two child terms: 
  - **"susceptibility to HIV-1 infection"** (of course, related to the above "infection with HIV-1"). Note that susceptibility is the default; only in certain situations are people resistant. The best-characterized example of resistance is due to a rare "delta 32" variant in CCR5. 
  -  **"susceptibility to HIV-1 progression"** of people who get a productive infection, some progress to AIDS more rapidly than others. This can be the result of various interrelated factors, some host (eg. HLA), some pathogen (infectious dose, site of infection whether IV / mucosal), some course of treatment (eg specific drugs, adherence), some co-morbidity (eg. tuberculosis, age etc).

**Comment by cmungall** [comment]
We use NCBITaxonomy to axiomatize the infectious diseases by agent:

![image](https://user-images.githubusercontent.com/50745/32253039-09c22368-be56-11e7-810e-2152d3899edd.png)

Note many have 2 taxa which is not correct unless we are saying it is caused by both. Needs review. Maybe in some cases it would be easier to get a grouping class from wikidata but we should at least ask NCBI first.

For progression we have a small hierarchy under occurrent for stages of disease

I didn't know that about the difference in susceptibility. Is this likely to be common for other infectious diseases? If so we should encode this as a DP

**Comment by cmungall** [comment]
Note also we plan to implement general susceptibility DPs. For now susceptibility to X is a type of X which is a hack.

**Comment by nicolevasilevsky** [comment]
I think this can  be closed.
