### ISSUE TITLE
Failure to access previous MONDO owl versions using versionIRI

### ISSUE THREAD

**Issue by aschroed** [monarch-initiative/mondo#927]
Getting a 404 error when trying to access older versions of mondo.owl using the versionIRI.

Are the owl files not versioned and archived?  If they are why does the IRI not work?  It also does not work for the current version using the IRI from the file I previously downloaded.

Thanks for your assistance.
cheers,
Andy

$ wget http://purl.obolibrary.org/obo/hp/releases/2019-08-28/mondo.owl
--2019-11-07 12:36:41--  http://purl.obolibrary.org/obo/hp/releases/2019-08-28/mondo.owl
Resolving purl.obolibrary.org (purl.obolibrary.org)... 52.3.123.63
Connecting to purl.obolibrary.org (purl.obolibrary.org)|52.3.123.63|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2019-08-28/mondo.owl [following]
--2019-11-07 12:36:41--  https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2019-08-28/mondo.owl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.20.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.20.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-07 12:36:41 ERROR 404: Not Found.

**Comment by balhoff** [comment]
@aschroed I think there is a mistake in the version IRI you're checking—did that come from the ontology? Yours has 'hp' within the path.

But your point still stands; when I try the version IRI of the current release (`http://purl.obolibrary.org/obo/mondo/releases/2019-10-25/mondo.owl`) I get '404 Not Found'.

The problem is that the git tag has been created as `2019-10-25`, when it should have been `v2019-10-25`. The previous release, `http://purl.obolibrary.org/obo/mondo/releases/2019-09-30/mondo.owl` does resolve.

**Comment by aschroed** [comment]
@balhoff Thank you for your reply.  I apologize for including misleading information in my issue - as you noted I mistakenly included a typo in the versionIRI I posted   I appreciate that you were able to solve my issue and were able to identify the cause of my initial problem - the unexpected tag.  Thanks!

**Comment by balhoff** [comment]
No problem, some does still need to add the tag. I'll make an issue for that, since I don't have permission to make a release here.

**Comment by balhoff** [comment]
@aschroed your problem should now be fixed. `http://purl.obolibrary.org/obo/mondo/releases/2019-10-25/mondo.owl` can be downloaded from the version IRI.
