### ISSUE TITLE
[Revise logical def] MONDO:0013419 complement component C1s deficiency

### ISSUE THREAD

**Issue by bmeldal** [monarch-initiative/mondo#959]
**Mondo term (ID and Label)**
MONDO:0013419 complement component C1s deficiency

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

A rare defect resulting in C1 deficiency and impaired activation of the complement classical pathway. C1 deficiency generally leads to severe immune complex disease with features of systemic lupus erythematosus and glomerulonephritis. 

PMID:11390518

Taken from UniProt entry P09871 as there isn't a def on this entry.

The related synonyms should be exact synonyms and are duplicated.

Thanks,
Birgit

**Comment by paolaroncaglia** [comment]
@bmeldal 
A quick general note. In my opinion, acronyms, such as C1SD, should not be _exact_ synonyms, because an acronym can be ambiguous. We've had this discussion with Mondo and GO editors in time, sorry I didn't have a chance to bring it up when you opened your other ticket recently. I suggest to leave/have acronyms as related synonyms. Thanks!

**Comment by bmeldal** [comment]
@paolaroncaglia
Ok, that makes sense that acronyms are potentially ambiguous. Bane of my life with gene symbols!
